// Generated from Pokémon GO masterfile — group "breadMoveLevelSettings" templateIds.

package masterfile

type BreadMoveLevelSettingsTemplateID string

const (
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup1 BreadMoveLevelSettingsTemplateID = "BREAD_MOVE_LEVEL_SETTINGS_GROUP_1"
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup2 BreadMoveLevelSettingsTemplateID = "BREAD_MOVE_LEVEL_SETTINGS_GROUP_2"
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup3 BreadMoveLevelSettingsTemplateID = "BREAD_MOVE_LEVEL_SETTINGS_GROUP_3"
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup4 BreadMoveLevelSettingsTemplateID = "BREAD_MOVE_LEVEL_SETTINGS_GROUP_4"
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup7 BreadMoveLevelSettingsTemplateID = "BREAD_MOVE_LEVEL_SETTINGS_GROUP_7"
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup8 BreadMoveLevelSettingsTemplateID = "BREAD_MOVE_LEVEL_SETTINGS_GROUP_8"
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroupZ BreadMoveLevelSettingsTemplateID = "BREAD_MOVE_LEVEL_SETTINGS_GROUP_Z"
)

var BreadMoveLevelSettingsTemplateIDValues = []BreadMoveLevelSettingsTemplateID{
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup1,
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup2,
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup3,
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup4,
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup7,
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroup8,
	BreadMoveLevelSettingsTemplateIDBreadMoveLevelSettingsGroupZ,
}
