// Generated from Pokémon GO masterfile — group "combatRankingProtoSettings" templateIds.

package masterfile

type CombatRankingProtoSettingsTemplateID string

const (
	CombatRankingProtoSettingsTemplateIDCombatRankingSettings    CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS10 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S10"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS13 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S13"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS14 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S14"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS15 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S15"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS16 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S16"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS17 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S17"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS18 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S18"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS19 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S19"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS20 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S20"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS21 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S21"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS22 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S22"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS23 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S23"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS24 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S24"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS25 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S25"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS26 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S26"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS27 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S27"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS28 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S28"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS29 CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S29"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS8  CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S8"
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS9  CombatRankingProtoSettingsTemplateID = "COMBAT_RANKING_SETTINGS_S9"
)

var CombatRankingProtoSettingsTemplateIDValues = []CombatRankingProtoSettingsTemplateID{
	CombatRankingProtoSettingsTemplateIDCombatRankingSettings,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS10,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS13,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS14,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS15,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS16,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS17,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS18,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS19,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS20,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS21,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS22,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS23,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS24,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS25,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS26,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS27,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS28,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS29,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS8,
	CombatRankingProtoSettingsTemplateIDCombatRankingSettingsS9,
}
