// Generated from Pokémon GO masterfile — group "evolutionChainDisplaySettings" templateIds.

package masterfile

type EvolutionChainDisplaySettingsTemplateID string

const (
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0052PokemonMeowth       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0052_POKEMON_MEOWTH"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0083PokemonFarfetchd    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0083_POKEMON_FARFETCHD"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0122PokemonMrMime       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0122_POKEMON_MR_MIME"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0123PokemonScyther      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0123_POKEMON_SCYTHER"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0150PokemonMewtwo       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0150_POKEMON_MEWTWO"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0155PokemonCyndaquil    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0155_POKEMON_CYNDAQUIL"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0156PokemonQuilava      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0156_POKEMON_QUILAVA"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0157PokemonTyphlosion   EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0157_POKEMON_TYPHLOSION"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0194PokemonWooper       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0194_POKEMON_WOOPER"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0211PokemonQwilfish     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0211_POKEMON_QWILFISH"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0215PokemonSneasel      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0215_POKEMON_SNEASEL"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0222PokemonCorsola      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0222_POKEMON_CORSOLA"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0234PokemonStantler     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0234_POKEMON_STANTLER"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0263PokemonZigzagoon    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0263_POKEMON_ZIGZAGOON"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0264PokemonLinoone      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0264_POKEMON_LINOONE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0290PokemonNincada      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0290_POKEMON_NINCADA"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0412PokemonBurmy        EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0412_POKEMON_BURMY"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0413PokemonWormadam     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0413_POKEMON_WORMADAM"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0414PokemonMothim       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0414_POKEMON_MOTHIM"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0420PokemonCherubi      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0420_POKEMON_CHERUBI"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0421PokemonCherrim      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0421_POKEMON_CHERRIM"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0422PokemonShellos      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0422_POKEMON_SHELLOS"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0423PokemonGastrodon    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0423_POKEMON_GASTRODON"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0449PokemonHippopotas   EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0449_POKEMON_HIPPOPOTAS"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0450PokemonHippowdon    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0450_POKEMON_HIPPOWDON"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0501PokemonOshawott     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0501_POKEMON_OSHAWOTT"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0502PokemonDewott       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0502_POKEMON_DEWOTT"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0503PokemonSamurott     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0503_POKEMON_SAMUROTT"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0519PokemonPidove       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0519_POKEMON_PIDOVE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0520PokemonTranquill    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0520_POKEMON_TRANQUILL"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0521PokemonUnfezant     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0521_POKEMON_UNFEZANT"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0550PokemonBasculin     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0550_POKEMON_BASCULIN"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0554PokemonDarumaka     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0554_POKEMON_DARUMAKA"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0562PokemonYamask       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0562_POKEMON_YAMASK"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0585PokemonDeerling     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0585_POKEMON_DEERLING"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0586PokemonSawsbuck     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0586_POKEMON_SAWSBUCK"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0592PokemonFrillish     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0592_POKEMON_FRILLISH"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0593PokemonJellicent    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0593_POKEMON_JELLICENT"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0664PokemonScatterbug   EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0664_POKEMON_SCATTERBUG"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0665PokemonSpewpa       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0665_POKEMON_SPEWPA"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0666PokemonVivillon     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0666_POKEMON_VIVILLON"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0667PokemonLitleo       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0667_POKEMON_LITLEO"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0668PokemonPyroar       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0668_POKEMON_PYROAR"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0669PokemonFlabebe      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0669_POKEMON_FLABEBE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0670PokemonFloette      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0670_POKEMON_FLOETTE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0671PokemonFlorges      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0671_POKEMON_FLORGES"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0677PokemonEspurr       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0677_POKEMON_ESPURR"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0678PokemonMeowstic     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0678_POKEMON_MEOWSTIC"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0679PokemonHonedge      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0679_POKEMON_HONEDGE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0680PokemonDoublade     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0680_POKEMON_DOUBLADE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0681PokemonAegislash    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0681_POKEMON_AEGISLASH"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0710PokemonPumpkaboo    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0710_POKEMON_PUMPKABOO"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0711PokemonGourgeist    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0711_POKEMON_GOURGEIST"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0718PokemonZygarde      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0718_POKEMON_ZYGARDE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0722PokemonRowlet       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0722_POKEMON_ROWLET"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0723PokemonDartrix      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0723_POKEMON_DARTRIX"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0724PokemonDecidueye    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0724_POKEMON_DECIDUEYE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0744PokemonRockruff     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0744_POKEMON_ROCKRUFF"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0745PokemonLycanroc     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0745_POKEMON_LYCANROC"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0800PokemonNecrozma     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0800_POKEMON_NECROZMA"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0848PokemonToxel        EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0848_POKEMON_TOXEL"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0849PokemonToxtricity   EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0849_POKEMON_TOXTRICITY"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0862PokemonObstagoon    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0862_POKEMON_OBSTAGOON"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0863PokemonPerrserker   EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0863_POKEMON_PERRSERKER"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0864PokemonCursola      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0864_POKEMON_CURSOLA"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0865PokemonSirfetchd    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0865_POKEMON_SIRFETCHD"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0866PokemonMrRime       EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0866_POKEMON_MR_RIME"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0867PokemonRunerigus    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0867_POKEMON_RUNERIGUS"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0899PokemonWyrdeer      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0899_POKEMON_WYRDEER"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0900PokemonKleavor      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0900_POKEMON_KLEAVOR"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0903PokemonSneasler     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0903_POKEMON_SNEASLER"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0904PokemonOverqwil     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0904_POKEMON_OVERQWIL"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0915PokemonLechonk      EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0915_POKEMON_LECHONK"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0916PokemonOinkologne   EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0916_POKEMON_OINKOLOGNE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0924PokemonTandemaus    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0924_POKEMON_TANDEMAUS"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0925PokemonMaushold     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0925_POKEMON_MAUSHOLD"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0980PokemonClodsire     EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V0980_POKEMON_CLODSIRE"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV1012PokemonPoltchageist EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V1012_POKEMON_POLTCHAGEIST"
	EvolutionChainDisplaySettingsTemplateIDEvolutionV1013PokemonSinistcha    EvolutionChainDisplaySettingsTemplateID = "EVOLUTION_V1013_POKEMON_SINISTCHA"
)

var EvolutionChainDisplaySettingsTemplateIDValues = [...]EvolutionChainDisplaySettingsTemplateID{
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0052PokemonMeowth,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0083PokemonFarfetchd,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0122PokemonMrMime,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0123PokemonScyther,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0150PokemonMewtwo,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0155PokemonCyndaquil,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0156PokemonQuilava,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0157PokemonTyphlosion,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0194PokemonWooper,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0211PokemonQwilfish,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0215PokemonSneasel,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0222PokemonCorsola,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0234PokemonStantler,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0263PokemonZigzagoon,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0264PokemonLinoone,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0290PokemonNincada,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0412PokemonBurmy,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0413PokemonWormadam,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0414PokemonMothim,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0420PokemonCherubi,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0421PokemonCherrim,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0422PokemonShellos,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0423PokemonGastrodon,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0449PokemonHippopotas,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0450PokemonHippowdon,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0501PokemonOshawott,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0502PokemonDewott,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0503PokemonSamurott,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0519PokemonPidove,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0520PokemonTranquill,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0521PokemonUnfezant,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0550PokemonBasculin,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0554PokemonDarumaka,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0562PokemonYamask,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0585PokemonDeerling,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0586PokemonSawsbuck,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0592PokemonFrillish,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0593PokemonJellicent,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0664PokemonScatterbug,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0665PokemonSpewpa,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0666PokemonVivillon,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0667PokemonLitleo,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0668PokemonPyroar,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0669PokemonFlabebe,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0670PokemonFloette,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0671PokemonFlorges,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0677PokemonEspurr,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0678PokemonMeowstic,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0679PokemonHonedge,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0680PokemonDoublade,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0681PokemonAegislash,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0710PokemonPumpkaboo,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0711PokemonGourgeist,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0718PokemonZygarde,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0722PokemonRowlet,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0723PokemonDartrix,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0724PokemonDecidueye,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0744PokemonRockruff,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0745PokemonLycanroc,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0800PokemonNecrozma,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0848PokemonToxel,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0849PokemonToxtricity,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0862PokemonObstagoon,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0863PokemonPerrserker,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0864PokemonCursola,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0865PokemonSirfetchd,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0866PokemonMrRime,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0867PokemonRunerigus,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0899PokemonWyrdeer,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0900PokemonKleavor,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0903PokemonSneasler,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0904PokemonOverqwil,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0915PokemonLechonk,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0916PokemonOinkologne,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0924PokemonTandemaus,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0925PokemonMaushold,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV0980PokemonClodsire,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV1012PokemonPoltchageist,
	EvolutionChainDisplaySettingsTemplateIDEvolutionV1013PokemonSinistcha,
}
