// Generated from Pokémon GO masterfile — group "fortPowerUpLevelSettings" templateIds.

package masterfile

type FortPowerUpLevelSettingsTemplateID string

const (
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel0 FortPowerUpLevelSettingsTemplateID = "FORT_POWER_UP_LEVEL_0"
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel1 FortPowerUpLevelSettingsTemplateID = "FORT_POWER_UP_LEVEL_1"
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel2 FortPowerUpLevelSettingsTemplateID = "FORT_POWER_UP_LEVEL_2"
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel3 FortPowerUpLevelSettingsTemplateID = "FORT_POWER_UP_LEVEL_3"
)

var FortPowerUpLevelSettingsTemplateIDValues = [...]FortPowerUpLevelSettingsTemplateID{
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel0,
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel1,
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel2,
	FortPowerUpLevelSettingsTemplateIDFortPowerUpLevel3,
}
