// Generated from Pokémon GO masterfile — group "itemExpirationSettings" templateIds.

package masterfile

type ItemExpirationSettingsTemplateID string

const (
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoFest01     ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_GO_FEST_01"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoFest02     ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_GO_FEST_02"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoTour01     ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_GO_TOUR_01"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoTour02     ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_GO_TOUR_02"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoWildArea01 ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_GO_WILD_AREA_01"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps01    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_01"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps02    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_02"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps03    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_03"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps04    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_04"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps05    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_05"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps06    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_06"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps07    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_07"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps08    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_LIVE_OPS_08"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointMonthly01    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_MONTHLY_01"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointMonthly02    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_MONTHLY_02"
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointMonthly03    ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_EVENT_PASS_POINT_MONTHLY_03"
	ItemExpirationSettingsTemplateIDItemExpirationItemIncubatorTimed             ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_INCUBATOR_TIMED"
	ItemExpirationSettingsTemplateIDItemExpirationItemLuckyFriendApplicator      ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_LUCKY_FRIEND_APPLICATOR"
	ItemExpirationSettingsTemplateIDItemExpirationItemSingleStatIncrease         ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_SINGLE_STAT_INCREASE"
	ItemExpirationSettingsTemplateIDItemExpirationItemTripleStatIncrease         ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_TRIPLE_STAT_INCREASE"
	ItemExpirationSettingsTemplateIDItemExpirationItemWildBall                   ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_WILD_BALL"
	ItemExpirationSettingsTemplateIDItemExpirationItemWildBallPremier            ItemExpirationSettingsTemplateID = "ITEM_EXPIRATION_ITEM_WILD_BALL_PREMIER"
)

var ItemExpirationSettingsTemplateIDValues = [...]ItemExpirationSettingsTemplateID{
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoFest01,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoFest02,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoTour01,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoTour02,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointGoWildArea01,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps01,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps02,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps03,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps04,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps05,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps06,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps07,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointLiveOps08,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointMonthly01,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointMonthly02,
	ItemExpirationSettingsTemplateIDItemExpirationItemEventPassPointMonthly03,
	ItemExpirationSettingsTemplateIDItemExpirationItemIncubatorTimed,
	ItemExpirationSettingsTemplateIDItemExpirationItemLuckyFriendApplicator,
	ItemExpirationSettingsTemplateIDItemExpirationItemSingleStatIncrease,
	ItemExpirationSettingsTemplateIDItemExpirationItemTripleStatIncrease,
	ItemExpirationSettingsTemplateIDItemExpirationItemWildBall,
	ItemExpirationSettingsTemplateIDItemExpirationItemWildBallPremier,
}
