// Generated from Pokémon GO masterfile — group "nonCombatMoveSettings" templateIds.

package masterfile

type NonCombatMoveSettingsTemplateID string

const (
	NonCombatMoveSettingsTemplateIDNonCombatV0388MoveSpacialRend    NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0388_MOVE_SPACIAL_REND"
	NonCombatMoveSettingsTemplateIDNonCombatV0394MoveRoarOfTime     NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0394_MOVE_ROAR_OF_TIME"
	NonCombatMoveSettingsTemplateIDNonCombatV0404MoveSunsteelStrike NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0404_MOVE_SUNSTEEL_STRIKE"
	NonCombatMoveSettingsTemplateIDNonCombatV0405MoveMoongeistBeam  NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0405_MOVE_MOONGEIST_BEAM"
	NonCombatMoveSettingsTemplateIDNonCombatV0466MoveFreezeShock    NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0466_MOVE_FREEZE_SHOCK"
	NonCombatMoveSettingsTemplateIDNonCombatV0467MoveIceBurn        NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0467_MOVE_ICE_BURN"
	NonCombatMoveSettingsTemplateIDNonCombatV0469MoveBehemothBlade  NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0469_MOVE_BEHEMOTH_BLADE"
	NonCombatMoveSettingsTemplateIDNonCombatV0470MoveBehemothBash   NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0470_MOVE_BEHEMOTH_BASH"
	NonCombatMoveSettingsTemplateIDNonCombatV0482MoveDynamaxCannon  NonCombatMoveSettingsTemplateID = "NON_COMBAT_V0482_MOVE_DYNAMAX_CANNON"
)

var NonCombatMoveSettingsTemplateIDValues = [...]NonCombatMoveSettingsTemplateID{
	NonCombatMoveSettingsTemplateIDNonCombatV0388MoveSpacialRend,
	NonCombatMoveSettingsTemplateIDNonCombatV0394MoveRoarOfTime,
	NonCombatMoveSettingsTemplateIDNonCombatV0404MoveSunsteelStrike,
	NonCombatMoveSettingsTemplateIDNonCombatV0405MoveMoongeistBeam,
	NonCombatMoveSettingsTemplateIDNonCombatV0466MoveFreezeShock,
	NonCombatMoveSettingsTemplateIDNonCombatV0467MoveIceBurn,
	NonCombatMoveSettingsTemplateIDNonCombatV0469MoveBehemothBlade,
	NonCombatMoveSettingsTemplateIDNonCombatV0470MoveBehemothBash,
	NonCombatMoveSettingsTemplateIDNonCombatV0482MoveDynamaxCannon,
}
