// Generated from Pokémon GO masterfile — group "pokemonHomeFormReversions" templateIds.

package masterfile

type PokemonHomeFormReversionsTemplateID string

const (
	PokemonHomeFormReversionsTemplateIDV0351PokemonCastformHomeFormReversion   PokemonHomeFormReversionsTemplateID = "V0351_POKEMON_CASTFORM_HOME_FORM_REVERSION"
	PokemonHomeFormReversionsTemplateIDV0421CherrimHomeFormReversion           PokemonHomeFormReversionsTemplateID = "V0421_CHERRIM_HOME_FORM_REVERSION"
	PokemonHomeFormReversionsTemplateIDV0487PokemonGiratinaHomeReversion       PokemonHomeFormReversionsTemplateID = "V0487_POKEMON_GIRATINA_HOME_REVERSION"
	PokemonHomeFormReversionsTemplateIDV0555PokemonDarmanitanHomeFormReversion PokemonHomeFormReversionsTemplateID = "V0555_POKEMON_DARMANITAN_HOME_FORM_REVERSION"
	PokemonHomeFormReversionsTemplateIDV0647PokemonKeldeoHomeFormReversion     PokemonHomeFormReversionsTemplateID = "V0647_POKEMON_KELDEO_HOME_FORM_REVERSION"
	PokemonHomeFormReversionsTemplateIDV0648PokemonMeloettaHomeFormReversion   PokemonHomeFormReversionsTemplateID = "V0648_POKEMON_MELOETTA_HOME_FORM_REVERSION"
	PokemonHomeFormReversionsTemplateIDV0649PokemonGenesectHomeFormReversion   PokemonHomeFormReversionsTemplateID = "V0649_POKEMON_GENESECT_HOME_FORM_REVERSION"
)

var PokemonHomeFormReversionsTemplateIDValues = [...]PokemonHomeFormReversionsTemplateID{
	PokemonHomeFormReversionsTemplateIDV0351PokemonCastformHomeFormReversion,
	PokemonHomeFormReversionsTemplateIDV0421CherrimHomeFormReversion,
	PokemonHomeFormReversionsTemplateIDV0487PokemonGiratinaHomeReversion,
	PokemonHomeFormReversionsTemplateIDV0555PokemonDarmanitanHomeFormReversion,
	PokemonHomeFormReversionsTemplateIDV0647PokemonKeldeoHomeFormReversion,
	PokemonHomeFormReversionsTemplateIDV0648PokemonMeloettaHomeFormReversion,
	PokemonHomeFormReversionsTemplateIDV0649PokemonGenesectHomeFormReversion,
}
