// Generated from Pokémon GO masterfile — group "recommendedSearchSettings" templateIds.

package masterfile

type RecommendedSearchSettingsTemplateID string

const (
	RecommendedSearchSettingsTemplateIDRecommendedSearchAppraisalIvHigh          RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_APPRAISAL_IV_HIGH"
	RecommendedSearchSettingsTemplateIDRecommendedSearchAppraisalIvLow           RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_APPRAISAL_IV_LOW"
	RecommendedSearchSettingsTemplateIDRecommendedSearchAppraisalLabelEvolveMega RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_APPRAISAL_LABEL_EVOLVE_MEGA"
	RecommendedSearchSettingsTemplateIDRecommendedSearchBadgeKantoRegion         RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_BADGE_KANTO_REGION"
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelEvolvable     RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_FILTER_LABEL_EVOLVABLE"
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelHatched       RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_FILTER_LABEL_HATCHED"
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelLegendary     RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_FILTER_LABEL_LEGENDARY"
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelShiny         RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_FILTER_LABEL_SHINY"
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelTraded        RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_FILTER_LABEL_TRADED"
	RecommendedSearchSettingsTemplateIDRecommendedSearchPokemonTypeNormal        RecommendedSearchSettingsTemplateID = "RECOMMENDED_SEARCH_POKEMON_TYPE_NORMAL"
)

var RecommendedSearchSettingsTemplateIDValues = [...]RecommendedSearchSettingsTemplateID{
	RecommendedSearchSettingsTemplateIDRecommendedSearchAppraisalIvHigh,
	RecommendedSearchSettingsTemplateIDRecommendedSearchAppraisalIvLow,
	RecommendedSearchSettingsTemplateIDRecommendedSearchAppraisalLabelEvolveMega,
	RecommendedSearchSettingsTemplateIDRecommendedSearchBadgeKantoRegion,
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelEvolvable,
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelHatched,
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelLegendary,
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelShiny,
	RecommendedSearchSettingsTemplateIDRecommendedSearchFilterLabelTraded,
	RecommendedSearchSettingsTemplateIDRecommendedSearchPokemonTypeNormal,
}
