// Generated from Pokémon GO masterfile — group "temporaryEvolutionSettings" templateIds.

package masterfile

type TemporaryEvolutionSettingsTemplateID string

const (
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0003PokemonVenusaur   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0003_POKEMON_VENUSAUR"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0006PokemonCharizard  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0006_POKEMON_CHARIZARD"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0009PokemonBlastoise  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0009_POKEMON_BLASTOISE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0015PokemonBeedrill   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0015_POKEMON_BEEDRILL"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0018PokemonPidgeot    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0018_POKEMON_PIDGEOT"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0065PokemonAlakazam   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0065_POKEMON_ALAKAZAM"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0071PokemonVictreebel TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0071_POKEMON_VICTREEBEL"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0080PokemonSlowbro    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0080_POKEMON_SLOWBRO"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0094PokemonGengar     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0094_POKEMON_GENGAR"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0115PokemonKangaskhan TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0115_POKEMON_KANGASKHAN"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0127PokemonPinsir     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0127_POKEMON_PINSIR"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0130PokemonGyarados   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0130_POKEMON_GYARADOS"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0142PokemonAerodactyl TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0142_POKEMON_AERODACTYL"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0149PokemonDragonite  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0149_POKEMON_DRAGONITE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0181PokemonAmpharos   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0181_POKEMON_AMPHAROS"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0208PokemonSteelix    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0208_POKEMON_STEELIX"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0212PokemonScizor     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0212_POKEMON_SCIZOR"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0214PokemonHeracross  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0214_POKEMON_HERACROSS"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0229PokemonHoundoom   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0229_POKEMON_HOUNDOOM"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0248PokemonTyranitar  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0248_POKEMON_TYRANITAR"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0254PokemonSceptile   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0254_POKEMON_SCEPTILE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0257PokemonBlaziken   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0257_POKEMON_BLAZIKEN"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0260PokemonSwampert   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0260_POKEMON_SWAMPERT"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0282PokemonGardevoir  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0282_POKEMON_GARDEVOIR"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0302PokemonSableye    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0302_POKEMON_SABLEYE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0303PokemonMawile     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0303_POKEMON_MAWILE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0306PokemonAggron     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0306_POKEMON_AGGRON"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0308PokemonMedicham   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0308_POKEMON_MEDICHAM"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0310PokemonManectric  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0310_POKEMON_MANECTRIC"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0319PokemonSharpedo   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0319_POKEMON_SHARPEDO"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0323PokemonCamerupt   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0323_POKEMON_CAMERUPT"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0334PokemonAltaria    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0334_POKEMON_ALTARIA"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0354PokemonBanette    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0354_POKEMON_BANETTE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0359PokemonAbsol      TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0359_POKEMON_ABSOL"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0362PokemonGlalie     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0362_POKEMON_GLALIE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0373PokemonSalamence  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0373_POKEMON_SALAMENCE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0376PokemonMetagross  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0376_POKEMON_METAGROSS"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0380PokemonLatias     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0380_POKEMON_LATIAS"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0381PokemonLatios     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0381_POKEMON_LATIOS"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0382PokemonKyogre     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0382_POKEMON_KYOGRE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0383PokemonGroudon    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0383_POKEMON_GROUDON"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0384PokemonRayquaza   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0384_POKEMON_RAYQUAZA"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0428PokemonGarchomp   TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0428_POKEMON_GARCHOMP"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0428PokemonLopunny    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0428_POKEMON_LOPUNNY"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0448PokemonLucario    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0448_POKEMON_LUCARIO"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0460PokemonAbomasnow  TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0460_POKEMON_ABOMASNOW"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0475PokemonGallade    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0475_POKEMON_GALLADE"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0531PokemonAudino     TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0531_POKEMON_AUDINO"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0687PokemonMalamar    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0687_POKEMON_MALAMAR"
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0719PokemonDiancie    TemporaryEvolutionSettingsTemplateID = "TEMPORARY_EVOLUTION_V0719_POKEMON_DIANCIE"
)

var TemporaryEvolutionSettingsTemplateIDValues = [...]TemporaryEvolutionSettingsTemplateID{
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0003PokemonVenusaur,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0006PokemonCharizard,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0009PokemonBlastoise,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0015PokemonBeedrill,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0018PokemonPidgeot,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0065PokemonAlakazam,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0071PokemonVictreebel,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0080PokemonSlowbro,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0094PokemonGengar,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0115PokemonKangaskhan,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0127PokemonPinsir,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0130PokemonGyarados,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0142PokemonAerodactyl,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0149PokemonDragonite,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0181PokemonAmpharos,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0208PokemonSteelix,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0212PokemonScizor,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0214PokemonHeracross,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0229PokemonHoundoom,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0248PokemonTyranitar,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0254PokemonSceptile,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0257PokemonBlaziken,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0260PokemonSwampert,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0282PokemonGardevoir,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0302PokemonSableye,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0303PokemonMawile,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0306PokemonAggron,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0308PokemonMedicham,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0310PokemonManectric,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0319PokemonSharpedo,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0323PokemonCamerupt,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0334PokemonAltaria,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0354PokemonBanette,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0359PokemonAbsol,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0362PokemonGlalie,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0373PokemonSalamence,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0376PokemonMetagross,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0380PokemonLatias,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0381PokemonLatios,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0382PokemonKyogre,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0383PokemonGroudon,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0384PokemonRayquaza,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0428PokemonGarchomp,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0428PokemonLopunny,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0448PokemonLucario,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0460PokemonAbomasnow,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0475PokemonGallade,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0531PokemonAudino,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0687PokemonMalamar,
	TemporaryEvolutionSettingsTemplateIDTemporaryEvolutionV0719PokemonDiancie,
}
