// Generated from Pokémon GO masterfile — group "vsSeekerLoot" templateIds.

package masterfile

type VsSeekerLootTemplateID string

const (
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank10Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_10_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank10Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_10_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank11Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_11_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank11Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_11_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank12Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_12_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank12Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_12_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank13Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_13_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank13Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_13_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank14Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_14_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank14Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_14_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank15Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_15_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank15Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_15_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank16Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_16_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank16Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_16_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank17Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_17_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank17Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_17_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank18Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_18_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank18Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_18_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank19Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_19_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank19Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_19_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank1Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_1_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank1Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_1_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank20Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_20_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank20Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_20_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank21Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_21_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank21Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_21_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank22Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_22_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank22Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_22_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank23Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_23_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank23Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_23_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank24Free    VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_24_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank24Premium VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_24_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank2Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_2_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank2Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_2_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank3Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_3_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank3Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_3_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank4Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_4_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank4Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_4_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank5Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_5_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank5Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_5_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank6Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_6_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank6Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_6_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank7Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_7_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank7Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_7_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank8Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_8_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank8Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_8_PREMIUM"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank9Free     VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_9_FREE"
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank9Premium  VsSeekerLootTemplateID = "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_9_PREMIUM"
)

var VsSeekerLootTemplateIDValues = [...]VsSeekerLootTemplateID{
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank10Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank10Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank11Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank11Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank12Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank12Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank13Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank13Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank14Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank14Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank15Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank15Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank16Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank16Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank17Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank17Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank18Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank18Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank19Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank19Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank1Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank1Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank20Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank20Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank21Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank21Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank22Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank22Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank23Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank23Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank24Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank24Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank2Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank2Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank3Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank3Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank4Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank4Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank5Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank5Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank6Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank6Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank7Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank7Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank8Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank8Premium,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank9Free,
	VsSeekerLootTemplateIDVsSeekerLootPerWinSettingsRank9Premium,
}
