// Generated from Pokémon GO masterfile — group "eventPassTierSettings", 420 entries (structural types).

export type * from "./variants";

export interface EventPassTierSettings<TemplateID extends string = string, TData extends EventPassTierSettingsData = EventPassTierSettingsData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		eventPassTierSettings: TData;
	};
}

export interface EventPassTierSettingsData {
	activeBonusDisplaySettings?: {
		bonusBoxes: Array<{
			iconType: "GIFT" | "INCENSE" | "LUCKY_EGG" | "STARDUST";
			text: "dai_duration_double" | "gift_open_more_daily" | "gift_send_more_daily" | "gift_storage_more" | "hatch_stardust_double" | "hatch_xp_double";
		}>;
	};
	bonusSettings?: {
		bonusBoxes: Array<{
			iconType: "GIFT" | "INCENSE" | "LUCKY_EGG" | "STARDUST";
			text: "dai_duration_double" | "gift_open_more_daily" | "gift_send_more_daily" | "gift_storage_more" | "hatch_stardust_double" | "hatch_xp_double";
		}>;
		eventName: "season_pass_milestone_bonus_title_01" | "season_pass_milestone_bonus_title_02" | "season_pass_milestone_bonus_title_03";
	};
	minPointsRequired?: number;
	rank: number;
	rewards?: Array<{
		candy?: {
			amount: number;
			pokemonId:
				| "AXEW"
				| "BELDUM"
				| "BINACLE"
				| "BLIPBUG"
				| "COMBEE"
				| "DRUDDIGON"
				| "DUCKLETT"
				| "ENTEI"
				| "EXEGGCUTE"
				| "FOONGUS"
				| "GIRAFARIG"
				| "GROWLITHE"
				| "HATENNA"
				| "HOPPIP"
				| "PHANPY"
				| "POLTCHAGEIST"
				| "ROCKRUFF"
				| "ROGGENROLA"
				| "SINISTEA"
				| "SIZZLIPEDE"
				| "SKIDDO"
				| "SLOWPOKE"
				| "SNOM"
				| "TEPIG"
				| "WOOPER";
		};
		exp?: number;
		item?: {
			amount: number;
			item:
				| "ITEM_GOLDEN_PINAP_BERRY"
				| "ITEM_GOLDEN_RAZZ_BERRY"
				| "ITEM_GREAT_BALL"
				| "ITEM_INCENSE_ORDINARY"
				| "ITEM_INCUBATOR_BASIC"
				| "ITEM_INCUBATOR_SUPER"
				| "ITEM_LEADER_MAP_FRAGMENT"
				| "ITEM_LUCKY_EGG"
				| "ITEM_LUCKY_FRIEND_APPLICATOR"
				| "ITEM_MOVE_REROLL_FAST_ATTACK"
				| "ITEM_MOVE_REROLL_SPECIAL_ATTACK"
				| "ITEM_MP"
				| "ITEM_NANAB_BERRY"
				| "ITEM_PAID_RAID_TICKET"
				| "ITEM_POFFIN"
				| "ITEM_POKE_BALL"
				| "ITEM_RARE_CANDY"
				| "ITEM_RAZZ_BERRY"
				| "ITEM_STAR_PIECE"
				| "ITEM_TROY_DISK"
				| "ITEM_ULTRA_BALL"
				| "ITEM_XL_RARE_CANDY";
		};
		playerAttribute?: {
			durationMins: number;
			key: "april2026_season_pass_entitlement" | "april2026_season_pass_rank_01" | "april2026_season_pass_rank_02" | "april2026_season_pass_rank_03";
		};
		pokemonEncounter?: {
			isFeaturedPokemon: boolean;
			pokemonDisplay?: {
				breadModeEnum?: "BREAD_MODE";
				form:
					| "AMOONGUSS_NORMAL"
					| "BELDUM_NORMAL"
					| "BINACLE_NORMAL"
					| "BLIPBUG_NORMAL"
					| "COMBEE_NORMAL"
					| "DRUDDIGON_NORMAL"
					| "ENTEI_NORMAL"
					| "EXEGGUTOR_ALOLA"
					| "FRAXURE_NORMAL"
					| "GIRAFARIG_NORMAL"
					| "GROWLITHE_NORMAL"
					| "HATENNA_NORMAL"
					| "JUMPLUFF_NORMAL"
					| "PHANPY_NORMAL"
					| "ROCKRUFF_NORMAL"
					| "ROGGENROLA_NORMAL"
					| "SIZZLIPEDE_NORMAL"
					| "SKIDDO_NORMAL"
					| "SLOWPOKE_GALARIAN"
					| "SLOWPOKE_NORMAL"
					| "SNOM_NORMAL"
					| "SWANNA_NORMAL"
					| "TEPIG_NORMAL"
					| "WOOPER_NORMAL"
					| "WOOPER_PALDEA";
			};
			pokemonId:
				| "AMOONGUSS"
				| "BELDUM"
				| "BINACLE"
				| "BLIPBUG"
				| "COMBEE"
				| "DRUDDIGON"
				| "ENTEI"
				| "EXEGGUTOR"
				| "FRAXURE"
				| "GIRAFARIG"
				| "GROWLITHE"
				| "HATENNA"
				| "JUMPLUFF"
				| "PHANPY"
				| "POLTCHAGEIST"
				| "ROCKRUFF"
				| "ROGGENROLA"
				| "SINISTEA"
				| "SIZZLIPEDE"
				| "SKIDDO"
				| "SLOWPOKE"
				| "SNOM"
				| "SWANNA"
				| "TEPIG"
				| "WOOPER";
			statsLimitsOverride?: {
				maxPokemonLevel: number;
				minPokemonLevel: number;
			};
		};
		stardust?: number;
		type: "CANDY" | "EXPERIENCE" | "ITEM" | "PLAYER_ATTRIBUTE" | "POKEMON_ENCOUNTER" | "STARDUST" | "XL_CANDY";
		xlCandy?: {
			amount: number;
			pokemonId:
				| "AXEW"
				| "BELDUM"
				| "COMBEE"
				| "DUCKLETT"
				| "ENTEI"
				| "EXEGGCUTE"
				| "GIRAFARIG"
				| "GROWLITHE"
				| "HATENNA"
				| "PHANPY"
				| "ROGGENROLA"
				| "SINISTEA"
				| "SIZZLIPEDE"
				| "SKIDDO"
				| "SLOWPOKE"
				| "SNOM"
				| "TEPIG"
				| "WOOPER";
		};
	}>;
	track: "FREE" | "PREMIUM";
}

export type EventPassTierSettingsMasterfileEntry =
	| EventPassTierSettings100Free
	| EventPassTierSettings100Premium
	| EventPassTierSettings101Free
	| EventPassTierSettings101Premium
	| EventPassTierSettings102Free
	| EventPassTierSettings102Premium
	| EventPassTierSettings103Free
	| EventPassTierSettings103Premium
	| EventPassTierSettings104Free
	| EventPassTierSettings104Premium
	| EventPassTierSettings105Free
	| EventPassTierSettings105Premium
	| EventPassTierSettings106Free
	| EventPassTierSettings106Premium
	| EventPassTierSettings107Free
	| EventPassTierSettings107Premium
	| EventPassTierSettings108Free
	| EventPassTierSettings108Premium
	| EventPassTierSettings109Free
	| EventPassTierSettings109Premium
	| EventPassTierSettings10Free
	| EventPassTierSettings10Premium
	| EventPassTierSettings110Free
	| EventPassTierSettings110Premium
	| EventPassTierSettings111Free
	| EventPassTierSettings111Premium
	| EventPassTierSettings112Free
	| EventPassTierSettings112Premium
	| EventPassTierSettings113Free
	| EventPassTierSettings113Premium
	| EventPassTierSettings114Free
	| EventPassTierSettings114Premium
	| EventPassTierSettings115Free
	| EventPassTierSettings115Premium
	| EventPassTierSettings116Free
	| EventPassTierSettings116Premium
	| EventPassTierSettings117Free
	| EventPassTierSettings117Premium
	| EventPassTierSettings118Free
	| EventPassTierSettings118Premium
	| EventPassTierSettings119Free
	| EventPassTierSettings119Premium
	| EventPassTierSettings11Free
	| EventPassTierSettings11Premium
	| EventPassTierSettings120Free
	| EventPassTierSettings120Premium
	| EventPassTierSettings121Free
	| EventPassTierSettings121Premium
	| EventPassTierSettings122Free
	| EventPassTierSettings122Premium
	| EventPassTierSettings123Free
	| EventPassTierSettings123Premium
	| EventPassTierSettings124Free
	| EventPassTierSettings124Premium
	| EventPassTierSettings125Free
	| EventPassTierSettings125Premium
	| EventPassTierSettings126Free
	| EventPassTierSettings126Premium
	| EventPassTierSettings127Free
	| EventPassTierSettings127Premium
	| EventPassTierSettings128Free
	| EventPassTierSettings128Premium
	| EventPassTierSettings129Free
	| EventPassTierSettings129Premium
	| EventPassTierSettings12Free
	| EventPassTierSettings12Premium
	| EventPassTierSettings130Free
	| EventPassTierSettings130Premium
	| EventPassTierSettings131Free
	| EventPassTierSettings131Premium
	| EventPassTierSettings132Free
	| EventPassTierSettings132Premium
	| EventPassTierSettings133Free
	| EventPassTierSettings133Premium
	| EventPassTierSettings134Free
	| EventPassTierSettings134Premium
	| EventPassTierSettings135Free
	| EventPassTierSettings135Premium
	| EventPassTierSettings136Free
	| EventPassTierSettings136Premium
	| EventPassTierSettings137Free
	| EventPassTierSettings137Premium
	| EventPassTierSettings138Free
	| EventPassTierSettings138Premium
	| EventPassTierSettings139Free
	| EventPassTierSettings139Premium
	| EventPassTierSettings13Free
	| EventPassTierSettings13Premium
	| EventPassTierSettings140Free
	| EventPassTierSettings140Premium
	| EventPassTierSettings141Free
	| EventPassTierSettings141Premium
	| EventPassTierSettings142Free
	| EventPassTierSettings142Premium
	| EventPassTierSettings143Free
	| EventPassTierSettings143Premium
	| EventPassTierSettings144Free
	| EventPassTierSettings144Premium
	| EventPassTierSettings145Free
	| EventPassTierSettings145Premium
	| EventPassTierSettings146Free
	| EventPassTierSettings146Premium
	| EventPassTierSettings147Free
	| EventPassTierSettings147Premium
	| EventPassTierSettings148Free
	| EventPassTierSettings148Premium
	| EventPassTierSettings149Free
	| EventPassTierSettings149Premium
	| EventPassTierSettings14Free
	| EventPassTierSettings14Premium
	| EventPassTierSettings150Free
	| EventPassTierSettings150Premium
	| EventPassTierSettings151Free
	| EventPassTierSettings151Premium
	| EventPassTierSettings152Free
	| EventPassTierSettings152Premium
	| EventPassTierSettings153Free
	| EventPassTierSettings153Premium
	| EventPassTierSettings154Free
	| EventPassTierSettings154Premium
	| EventPassTierSettings155Free
	| EventPassTierSettings155Premium
	| EventPassTierSettings156Free
	| EventPassTierSettings156Premium
	| EventPassTierSettings157Free
	| EventPassTierSettings157Premium
	| EventPassTierSettings158Free
	| EventPassTierSettings158Premium
	| EventPassTierSettings159Free
	| EventPassTierSettings159Premium
	| EventPassTierSettings15Free
	| EventPassTierSettings15Premium
	| EventPassTierSettings160Free
	| EventPassTierSettings160Premium
	| EventPassTierSettings161Free
	| EventPassTierSettings161Premium
	| EventPassTierSettings162Free
	| EventPassTierSettings162Premium
	| EventPassTierSettings163Free
	| EventPassTierSettings163Premium
	| EventPassTierSettings164Free
	| EventPassTierSettings164Premium
	| EventPassTierSettings165Free
	| EventPassTierSettings165Premium
	| EventPassTierSettings166Free
	| EventPassTierSettings166Premium
	| EventPassTierSettings167Free
	| EventPassTierSettings167Premium
	| EventPassTierSettings168Free
	| EventPassTierSettings168Premium
	| EventPassTierSettings169Free
	| EventPassTierSettings169Premium
	| EventPassTierSettings16Free
	| EventPassTierSettings16Premium
	| EventPassTierSettings170Free
	| EventPassTierSettings170Premium
	| EventPassTierSettings171Free
	| EventPassTierSettings171Premium
	| EventPassTierSettings172Free
	| EventPassTierSettings172Premium
	| EventPassTierSettings173Free
	| EventPassTierSettings173Premium
	| EventPassTierSettings174Free
	| EventPassTierSettings174Premium
	| EventPassTierSettings175Free
	| EventPassTierSettings175Premium
	| EventPassTierSettings176Free
	| EventPassTierSettings176Premium
	| EventPassTierSettings177Free
	| EventPassTierSettings177Premium
	| EventPassTierSettings178Free
	| EventPassTierSettings178Premium
	| EventPassTierSettings179Free
	| EventPassTierSettings179Premium
	| EventPassTierSettings17Free
	| EventPassTierSettings17Premium
	| EventPassTierSettings180Free
	| EventPassTierSettings180Premium
	| EventPassTierSettings181Free
	| EventPassTierSettings181Premium
	| EventPassTierSettings182Free
	| EventPassTierSettings182Premium
	| EventPassTierSettings183Free
	| EventPassTierSettings183Premium
	| EventPassTierSettings184Free
	| EventPassTierSettings184Premium
	| EventPassTierSettings185Free
	| EventPassTierSettings185Premium
	| EventPassTierSettings186Free
	| EventPassTierSettings186Premium
	| EventPassTierSettings187Free
	| EventPassTierSettings187Premium
	| EventPassTierSettings188Free
	| EventPassTierSettings188Premium
	| EventPassTierSettings189Free
	| EventPassTierSettings189Premium
	| EventPassTierSettings18Free
	| EventPassTierSettings18Premium
	| EventPassTierSettings190Free
	| EventPassTierSettings190Premium
	| EventPassTierSettings191Free
	| EventPassTierSettings191Premium
	| EventPassTierSettings192Free
	| EventPassTierSettings192Premium
	| EventPassTierSettings193Free
	| EventPassTierSettings193Premium
	| EventPassTierSettings194Free
	| EventPassTierSettings194Premium
	| EventPassTierSettings195Free
	| EventPassTierSettings195Premium
	| EventPassTierSettings196Free
	| EventPassTierSettings196Premium
	| EventPassTierSettings197Free
	| EventPassTierSettings197Premium
	| EventPassTierSettings198Free
	| EventPassTierSettings198Premium
	| EventPassTierSettings199Free
	| EventPassTierSettings199Premium
	| EventPassTierSettings19Free
	| EventPassTierSettings19Premium
	| EventPassTierSettings1Free
	| EventPassTierSettings1Premium
	| EventPassTierSettings200Free
	| EventPassTierSettings200Premium
	| EventPassTierSettings201Free
	| EventPassTierSettings201Premium
	| EventPassTierSettings202Free
	| EventPassTierSettings202Premium
	| EventPassTierSettings203Free
	| EventPassTierSettings203Premium
	| EventPassTierSettings204Free
	| EventPassTierSettings204Premium
	| EventPassTierSettings205Free
	| EventPassTierSettings205Premium
	| EventPassTierSettings206Free
	| EventPassTierSettings206Premium
	| EventPassTierSettings207Free
	| EventPassTierSettings207Premium
	| EventPassTierSettings208Free
	| EventPassTierSettings208Premium
	| EventPassTierSettings209Free
	| EventPassTierSettings209Premium
	| EventPassTierSettings20Free
	| EventPassTierSettings20Premium
	| EventPassTierSettings210Free
	| EventPassTierSettings210Premium
	| EventPassTierSettings21Free
	| EventPassTierSettings21Premium
	| EventPassTierSettings22Free
	| EventPassTierSettings22Premium
	| EventPassTierSettings23Free
	| EventPassTierSettings23Premium
	| EventPassTierSettings24Free
	| EventPassTierSettings24Premium
	| EventPassTierSettings25Free
	| EventPassTierSettings25Premium
	| EventPassTierSettings26Free
	| EventPassTierSettings26Premium
	| EventPassTierSettings27Free
	| EventPassTierSettings27Premium
	| EventPassTierSettings28Free
	| EventPassTierSettings28Premium
	| EventPassTierSettings29Free
	| EventPassTierSettings29Premium
	| EventPassTierSettings2Free
	| EventPassTierSettings2Premium
	| EventPassTierSettings30Free
	| EventPassTierSettings30Premium
	| EventPassTierSettings31Free
	| EventPassTierSettings31Premium
	| EventPassTierSettings32Free
	| EventPassTierSettings32Premium
	| EventPassTierSettings33Free
	| EventPassTierSettings33Premium
	| EventPassTierSettings34Free
	| EventPassTierSettings34Premium
	| EventPassTierSettings35Free
	| EventPassTierSettings35Premium
	| EventPassTierSettings36Free
	| EventPassTierSettings36Premium
	| EventPassTierSettings37Free
	| EventPassTierSettings37Premium
	| EventPassTierSettings38Free
	| EventPassTierSettings38Premium
	| EventPassTierSettings39Free
	| EventPassTierSettings39Premium
	| EventPassTierSettings3Free
	| EventPassTierSettings3Premium
	| EventPassTierSettings40Free
	| EventPassTierSettings40Premium
	| EventPassTierSettings41Free
	| EventPassTierSettings41Premium
	| EventPassTierSettings42Free
	| EventPassTierSettings42Premium
	| EventPassTierSettings43Free
	| EventPassTierSettings43Premium
	| EventPassTierSettings44Free
	| EventPassTierSettings44Premium
	| EventPassTierSettings45Free
	| EventPassTierSettings45Premium
	| EventPassTierSettings46Free
	| EventPassTierSettings46Premium
	| EventPassTierSettings47Free
	| EventPassTierSettings47Premium
	| EventPassTierSettings48Free
	| EventPassTierSettings48Premium
	| EventPassTierSettings49Free
	| EventPassTierSettings49Premium
	| EventPassTierSettings4Free
	| EventPassTierSettings4Premium
	| EventPassTierSettings50Free
	| EventPassTierSettings50Premium
	| EventPassTierSettings51Free
	| EventPassTierSettings51Premium
	| EventPassTierSettings52Free
	| EventPassTierSettings52Premium
	| EventPassTierSettings53Free
	| EventPassTierSettings53Premium
	| EventPassTierSettings54Free
	| EventPassTierSettings54Premium
	| EventPassTierSettings55Free
	| EventPassTierSettings55Premium
	| EventPassTierSettings56Free
	| EventPassTierSettings56Premium
	| EventPassTierSettings57Free
	| EventPassTierSettings57Premium
	| EventPassTierSettings58Free
	| EventPassTierSettings58Premium
	| EventPassTierSettings59Free
	| EventPassTierSettings59Premium
	| EventPassTierSettings5Free
	| EventPassTierSettings5Premium
	| EventPassTierSettings60Free
	| EventPassTierSettings60Premium
	| EventPassTierSettings61Free
	| EventPassTierSettings61Premium
	| EventPassTierSettings62Free
	| EventPassTierSettings62Premium
	| EventPassTierSettings63Free
	| EventPassTierSettings63Premium
	| EventPassTierSettings64Free
	| EventPassTierSettings64Premium
	| EventPassTierSettings65Free
	| EventPassTierSettings65Premium
	| EventPassTierSettings66Free
	| EventPassTierSettings66Premium
	| EventPassTierSettings67Free
	| EventPassTierSettings67Premium
	| EventPassTierSettings68Free
	| EventPassTierSettings68Premium
	| EventPassTierSettings69Free
	| EventPassTierSettings69Premium
	| EventPassTierSettings6Free
	| EventPassTierSettings6Premium
	| EventPassTierSettings70Free
	| EventPassTierSettings70Premium
	| EventPassTierSettings71Free
	| EventPassTierSettings71Premium
	| EventPassTierSettings72Free
	| EventPassTierSettings72Premium
	| EventPassTierSettings73Free
	| EventPassTierSettings73Premium
	| EventPassTierSettings74Free
	| EventPassTierSettings74Premium
	| EventPassTierSettings75Free
	| EventPassTierSettings75Premium
	| EventPassTierSettings76Free
	| EventPassTierSettings76Premium
	| EventPassTierSettings77Free
	| EventPassTierSettings77Premium
	| EventPassTierSettings78Free
	| EventPassTierSettings78Premium
	| EventPassTierSettings79Free
	| EventPassTierSettings79Premium
	| EventPassTierSettings7Free
	| EventPassTierSettings7Premium
	| EventPassTierSettings80Free
	| EventPassTierSettings80Premium
	| EventPassTierSettings81Free
	| EventPassTierSettings81Premium
	| EventPassTierSettings82Free
	| EventPassTierSettings82Premium
	| EventPassTierSettings83Free
	| EventPassTierSettings83Premium
	| EventPassTierSettings84Free
	| EventPassTierSettings84Premium
	| EventPassTierSettings85Free
	| EventPassTierSettings85Premium
	| EventPassTierSettings86Free
	| EventPassTierSettings86Premium
	| EventPassTierSettings87Free
	| EventPassTierSettings87Premium
	| EventPassTierSettings88Free
	| EventPassTierSettings88Premium
	| EventPassTierSettings89Free
	| EventPassTierSettings89Premium
	| EventPassTierSettings8Free
	| EventPassTierSettings8Premium
	| EventPassTierSettings90Free
	| EventPassTierSettings90Premium
	| EventPassTierSettings91Free
	| EventPassTierSettings91Premium
	| EventPassTierSettings92Free
	| EventPassTierSettings92Premium
	| EventPassTierSettings93Free
	| EventPassTierSettings93Premium
	| EventPassTierSettings94Free
	| EventPassTierSettings94Premium
	| EventPassTierSettings95Free
	| EventPassTierSettings95Premium
	| EventPassTierSettings96Free
	| EventPassTierSettings96Premium
	| EventPassTierSettings97Free
	| EventPassTierSettings97Premium
	| EventPassTierSettings98Free
	| EventPassTierSettings98Premium
	| EventPassTierSettings99Free
	| EventPassTierSettings99Premium
	| EventPassTierSettings9Free
	| EventPassTierSettings9Premium;

export type EventPassTierSettingsTemplateID = EventPassTierSettingsMasterfileEntry["templateId"];
