// Generated from Pokémon GO masterfile — group "moveSequenceSettings", 331 entries (structural types).

export type * from "./variants";

export interface MoveSequenceSettings<TemplateID extends string = string, TData extends MoveSequenceSettingsData = MoveSequenceSettingsData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		moveSequenceSettings: TData;
	};
}

export interface MoveSequenceSettingsData {
	sequence: Array<string>;
}

export type MoveSequenceSettingsMasterfileEntry =
	| MoveSequenceSettingsAcidFast
	| MoveSequenceSettingsAcidSpray
	| MoveSequenceSettingsAcrobatics
	| MoveSequenceSettingsAerialAce
	| MoveSequenceSettingsAeroblast
	| MoveSequenceSettingsAirCutter
	| MoveSequenceSettingsAirSlashFast
	| MoveSequenceSettingsAncientPower
	| MoveSequenceSettingsAquaJet
	| MoveSequenceSettingsAquaStep
	| MoveSequenceSettingsAquaTail
	| MoveSequenceSettingsAstonishFast
	| MoveSequenceSettingsAuraSphere
	| MoveSequenceSettingsAuraWheelDark
	| MoveSequenceSettingsAuraWheelElectric
	| MoveSequenceSettingsAuroraBeam
	| MoveSequenceSettingsAvalanche
	| MoveSequenceSettingsBeakBlast
	| MoveSequenceSettingsBehemothBash
	| MoveSequenceSettingsBehemothBlade
	| MoveSequenceSettingsBiteFast
	| MoveSequenceSettingsBlastBurn
	| MoveSequenceSettingsBlazeKick
	| MoveSequenceSettingsBleakwindStorm
	| MoveSequenceSettingsBlizzard
	| MoveSequenceSettingsBodySlam
	| MoveSequenceSettingsBoneClub
	| MoveSequenceSettingsBoomburst
	| MoveSequenceSettingsBraveBird
	| MoveSequenceSettingsBreakingSwipe
	| MoveSequenceSettingsBrickBreak
	| MoveSequenceSettingsBrine
	| MoveSequenceSettingsBrutalSwing
	| MoveSequenceSettingsBubbleBeam
	| MoveSequenceSettingsBubbleFast
	| MoveSequenceSettingsBugBiteFast
	| MoveSequenceSettingsBugBuzz
	| MoveSequenceSettingsBulldoze
	| MoveSequenceSettingsBulletPunchFast
	| MoveSequenceSettingsBulletSeedFast
	| MoveSequenceSettingsChargeBeamFast
	| MoveSequenceSettingsCharmFast
	| MoveSequenceSettingsChillingWater
	| MoveSequenceSettingsClangingScales
	| MoveSequenceSettingsCloseCombat
	| MoveSequenceSettingsConfusionFast
	| MoveSequenceSettingsCounterFast
	| MoveSequenceSettingsCrabhammer
	| MoveSequenceSettingsCrossChop
	| MoveSequenceSettingsCrossPoison
	| MoveSequenceSettingsCrunch
	| MoveSequenceSettingsCrushClaw
	| MoveSequenceSettingsCrushGrip
	| MoveSequenceSettingsCutFast
	| MoveSequenceSettingsDarkPulse
	| MoveSequenceSettingsDarkestLariat
	| MoveSequenceSettingsDazzlingGleam
	| MoveSequenceSettingsDefault
	| MoveSequenceSettingsDig
	| MoveSequenceSettingsDisarmingVoice
	| MoveSequenceSettingsDischarge
	| MoveSequenceSettingsDoomDesire
	| MoveSequenceSettingsDoubleIronBash
	| MoveSequenceSettingsDoubleKickFast
	| MoveSequenceSettingsDracoMeteor
	| MoveSequenceSettingsDragonAscent
	| MoveSequenceSettingsDragonBreathFast
	| MoveSequenceSettingsDragonClaw
	| MoveSequenceSettingsDragonEnergy
	| MoveSequenceSettingsDragonPulse
	| MoveSequenceSettingsDragonTailFast
	| MoveSequenceSettingsDrainPunch
	| MoveSequenceSettingsDrainingKiss
	| MoveSequenceSettingsDrillPeck
	| MoveSequenceSettingsDrillRun
	| MoveSequenceSettingsDrumBeating
	| MoveSequenceSettingsDynamaxCannon
	| MoveSequenceSettingsDynamicPunch
	| MoveSequenceSettingsEarthPower
	| MoveSequenceSettingsEarthquake
	| MoveSequenceSettingsEmberFast
	| MoveSequenceSettingsEnergyBall
	| MoveSequenceSettingsExtrasensoryFast
	| MoveSequenceSettingsFairyWindFast
	| MoveSequenceSettingsFeatherDance
	| MoveSequenceSettingsFeintAttackFast
	| MoveSequenceSettingsFellStinger
	| MoveSequenceSettingsFireBlast
	| MoveSequenceSettingsFireFangFast
	| MoveSequenceSettingsFirePunch
	| MoveSequenceSettingsFireSpinFast
	| MoveSequenceSettingsFissure
	| MoveSequenceSettingsFlameBurst
	| MoveSequenceSettingsFlameCharge
	| MoveSequenceSettingsFlameWheel
	| MoveSequenceSettingsFlamethrower
	| MoveSequenceSettingsFlashCannon
	| MoveSequenceSettingsFlowerTrick
	| MoveSequenceSettingsFly
	| MoveSequenceSettingsFocusBlast
	| MoveSequenceSettingsForcePalmFast
	| MoveSequenceSettingsFoulPlay
	| MoveSequenceSettingsFreezeShock
	| MoveSequenceSettingsFrenzyPlant
	| MoveSequenceSettingsFrostBreathFast
	| MoveSequenceSettingsFrustration
	| MoveSequenceSettingsFuryCutterFast
	| MoveSequenceSettingsFusionBolt
	| MoveSequenceSettingsFusionFlare
	| MoveSequenceSettingsFuturesight
	| MoveSequenceSettingsGeomancyFast
	| MoveSequenceSettingsGigaDrain
	| MoveSequenceSettingsGigaImpact
	| MoveSequenceSettingsGigatonHammer
	| MoveSequenceSettingsGlaciate
	| MoveSequenceSettingsGrassKnot
	| MoveSequenceSettingsGunkShot
	| MoveSequenceSettingsGustFast
	| MoveSequenceSettingsGyroBall
	| MoveSequenceSettingsHeartStamp
	| MoveSequenceSettingsHeatWave
	| MoveSequenceSettingsHeavySlam
	| MoveSequenceSettingsHexFast
	| MoveSequenceSettingsHiddenPowerFast
	| MoveSequenceSettingsHighHorsepower
	| MoveSequenceSettingsHighJumpKick
	| MoveSequenceSettingsHornAttack
	| MoveSequenceSettingsHornDrill
	| MoveSequenceSettingsHurricane
	| MoveSequenceSettingsHydroCannon
	| MoveSequenceSettingsHydroPump
	| MoveSequenceSettingsHydroPumpBlastoise
	| MoveSequenceSettingsHyperBeam
	| MoveSequenceSettingsHyperFang
	| MoveSequenceSettingsIceBeam
	| MoveSequenceSettingsIceBurn
	| MoveSequenceSettingsIceFangFast
	| MoveSequenceSettingsIcePunch
	| MoveSequenceSettingsIceShardFast
	| MoveSequenceSettingsIcicleSpear
	| MoveSequenceSettingsIcyWind
	| MoveSequenceSettingsIncinerateFast
	| MoveSequenceSettingsInfestationFast
	| MoveSequenceSettingsIronHead
	| MoveSequenceSettingsIronTailFast
	| MoveSequenceSettingsKarateChopFast
	| MoveSequenceSettingsLastResort
	| MoveSequenceSettingsLeafBlade
	| MoveSequenceSettingsLeafStorm
	| MoveSequenceSettingsLeafTornado
	| MoveSequenceSettingsLeafageFast
	| MoveSequenceSettingsLeechLife
	| MoveSequenceSettingsLickFast
	| MoveSequenceSettingsLiquidation
	| MoveSequenceSettingsLockOnFast
	| MoveSequenceSettingsLowKickFast
	| MoveSequenceSettingsLowSweep
	| MoveSequenceSettingsLunge
	| MoveSequenceSettingsLusterPurge
	| MoveSequenceSettingsMagicalLeafFast
	| MoveSequenceSettingsMagmaStorm
	| MoveSequenceSettingsMagnetBomb
	| MoveSequenceSettingsMegaDrain
	| MoveSequenceSettingsMegahorn
	| MoveSequenceSettingsMetalClawFast
	| MoveSequenceSettingsMetalSound
	| MoveSequenceSettingsMeteorBeam
	| MoveSequenceSettingsMeteorMash
	| MoveSequenceSettingsMindBlown
	| MoveSequenceSettingsMirrorCoat
	| MoveSequenceSettingsMirrorShot
	| MoveSequenceSettingsMistBall
	| MoveSequenceSettingsMoonblast
	| MoveSequenceSettingsMoongeistBeam
	| MoveSequenceSettingsMudBomb
	| MoveSequenceSettingsMudShotFast
	| MoveSequenceSettingsMudSlapFast
	| MoveSequenceSettingsMuddyWater
	| MoveSequenceSettingsMystFire
	| MoveSequenceSettingsNaturesMadness
	| MoveSequenceSettingsNightShade
	| MoveSequenceSettingsNightSlash
	| MoveSequenceSettingsOblivionWing
	| MoveSequenceSettingsObstruct
	| MoveSequenceSettingsOctazooka
	| MoveSequenceSettingsOminousWind
	| MoveSequenceSettingsOriginPulse
	| MoveSequenceSettingsOutrage
	| MoveSequenceSettingsOverheat
	| MoveSequenceSettingsParabolicCharge
	| MoveSequenceSettingsPayback
	| MoveSequenceSettingsPeckFast
	| MoveSequenceSettingsPetalBlizzard
	| MoveSequenceSettingsPlayRough
	| MoveSequenceSettingsPoisonFang
	| MoveSequenceSettingsPoisonJabFast
	| MoveSequenceSettingsPoisonStingFast
	| MoveSequenceSettingsPoltergeist
	| MoveSequenceSettingsPoundFast
	| MoveSequenceSettingsPowderSnowFast
	| MoveSequenceSettingsPowerGem
	| MoveSequenceSettingsPowerUpPunch
	| MoveSequenceSettingsPowerWhip
	| MoveSequenceSettingsPrecipiceBlades
	| MoveSequenceSettingsPresentFast
	| MoveSequenceSettingsPsybeam
	| MoveSequenceSettingsPsychic
	| MoveSequenceSettingsPsychicFangs
	| MoveSequenceSettingsPsychoBoost
	| MoveSequenceSettingsPsychoCutFast
	| MoveSequenceSettingsPsyshock
	| MoveSequenceSettingsPsystrike
	| MoveSequenceSettingsPsywave
	| MoveSequenceSettingsPyroball
	| MoveSequenceSettingsQuickAttackFast
	| MoveSequenceSettingsRageFist
	| MoveSequenceSettingsRazorLeafFast
	| MoveSequenceSettingsRazorShell
	| MoveSequenceSettingsRest
	| MoveSequenceSettingsReturn
	| MoveSequenceSettingsRoarOfTime
	| MoveSequenceSettingsRockBlast
	| MoveSequenceSettingsRockSlide
	| MoveSequenceSettingsRockSmashFast
	| MoveSequenceSettingsRockThrowFast
	| MoveSequenceSettingsRockTomb
	| MoveSequenceSettingsRockWrecker
	| MoveSequenceSettingsRolloutFast
	| MoveSequenceSettingsSacredFire
	| MoveSequenceSettingsSacredSword
	| MoveSequenceSettingsSandAttack
	| MoveSequenceSettingsSandTomb
	| MoveSequenceSettingsSandsearStorm
	| MoveSequenceSettingsScald
	| MoveSequenceSettingsScaldBlastoise
	| MoveSequenceSettingsScorchingSands
	| MoveSequenceSettingsScratchFast
	| MoveSequenceSettingsSecretSword
	| MoveSequenceSettingsSeedBomb
	| MoveSequenceSettingsSeedFlare
	| MoveSequenceSettingsSeqCombatFaint
	| MoveSequenceSettingsSeqCombatFaintEnding
	| MoveSequenceSettingsSeqCombatReturn
	| MoveSequenceSettingsSeqDing
	| MoveSequenceSettingsSeqDramaticFaint
	| MoveSequenceSettingsSeqFaint
	| MoveSequenceSettingsSeqFortFaint
	| MoveSequenceSettingsSeqIntro
	| MoveSequenceSettingsSeqOutro
	| MoveSequenceSettingsSeqReturn
	| MoveSequenceSettingsSeqTransform
	| MoveSequenceSettingsSeqTransformDark
	| MoveSequenceSettingsSeqTransformFast
	| MoveSequenceSettingsShadowBall
	| MoveSequenceSettingsShadowBone
	| MoveSequenceSettingsShadowClawFast
	| MoveSequenceSettingsShadowForce
	| MoveSequenceSettingsShadowPunch
	| MoveSequenceSettingsShadowSneak
	| MoveSequenceSettingsSignalBeam
	| MoveSequenceSettingsSilverWind
	| MoveSequenceSettingsSkullBash
	| MoveSequenceSettingsSkyAttack
	| MoveSequenceSettingsSludge
	| MoveSequenceSettingsSludgeBomb
	| MoveSequenceSettingsSludgeWave
	| MoveSequenceSettingsSmackDown
	| MoveSequenceSettingsSmackDownFast
	| MoveSequenceSettingsSnarlFast
	| MoveSequenceSettingsSolarBeam
	| MoveSequenceSettingsSpacialRend
	| MoveSequenceSettingsSparkFast
	| MoveSequenceSettingsSparklingAria
	| MoveSequenceSettingsSpiritShackle
	| MoveSequenceSettingsSplashFast
	| MoveSequenceSettingsSteelWingFast
	| MoveSequenceSettingsStomp
	| MoveSequenceSettingsStoneEdge
	| MoveSequenceSettingsStruggle
	| MoveSequenceSettingsStruggleBugFast
	| MoveSequenceSettingsSubmission
	| MoveSequenceSettingsSuckerPunchFast
	| MoveSequenceSettingsSunsteelStrike
	| MoveSequenceSettingsSuperPower
	| MoveSequenceSettingsSurf
	| MoveSequenceSettingsSwift
	| MoveSequenceSettingsSynchronoise
	| MoveSequenceSettingsTackleFast
	| MoveSequenceSettingsTakeDownFast
	| MoveSequenceSettingsTechnoBlastBurn
	| MoveSequenceSettingsTechnoBlastChill
	| MoveSequenceSettingsTechnoBlastNormal
	| MoveSequenceSettingsTechnoBlastShock
	| MoveSequenceSettingsTechnoBlastWater
	| MoveSequenceSettingsThunder
	| MoveSequenceSettingsThunderCage
	| MoveSequenceSettingsThunderFangFast
	| MoveSequenceSettingsThunderPunch
	| MoveSequenceSettingsThunderShockFast
	| MoveSequenceSettingsThunderbolt
	| MoveSequenceSettingsTorchSong
	| MoveSequenceSettingsTrailblaze
	| MoveSequenceSettingsTriAttack
	| MoveSequenceSettingsTripleAxel
	| MoveSequenceSettingsTwister
	| MoveSequenceSettingsUpperHand
	| MoveSequenceSettingsVCreate
	| MoveSequenceSettingsViceGrip
	| MoveSequenceSettingsVineWhipFast
	| MoveSequenceSettingsVoltSwitchFast
	| MoveSequenceSettingsVoltTackle
	| MoveSequenceSettingsWaterGunFast
	| MoveSequenceSettingsWaterGunFastBlastoise
	| MoveSequenceSettingsWaterPulse
	| MoveSequenceSettingsWaterShurikenFast
	| MoveSequenceSettingsWaterfallFast
	| MoveSequenceSettingsWeatherBallFire
	| MoveSequenceSettingsWeatherBallIce
	| MoveSequenceSettingsWeatherBallNormal
	| MoveSequenceSettingsWeatherBallRock
	| MoveSequenceSettingsWeatherBallWater
	| MoveSequenceSettingsWildCharge
	| MoveSequenceSettingsWildboltStorm
	| MoveSequenceSettingsWingAttackFast
	| MoveSequenceSettingsWrap
	| MoveSequenceSettingsWrapGreen
	| MoveSequenceSettingsWrapPink
	| MoveSequenceSettingsXScissor
	| MoveSequenceSettingsYawnFast
	| MoveSequenceSettingsZapCannon
	| MoveSequenceSettingsZenHeadbuttFast;

export type MoveSequenceSettingsTemplateID = MoveSequenceSettingsMasterfileEntry["templateId"];
