// Generated from Pokémon GO masterfile — list of group discriminators.

export const GROUP_NAMES = [
	"avatarCustomization",
	"avatarGroupOrderSettings",
	"avatarItemDisplay",
	"badgeSettings",
	"breadMoveLevelSettings",
	"buddyActivityCategorySettings",
	"buddyEmotionLevelSettings",
	"buddyLevelSettings",
	"clientQuestTemplate",
	"codeGateProto",
	"combatLeague",
	"combatMove",
	"combatNpcPersonality",
	"combatNpcTrainer",
	"combatRankingProtoSettings",
	"combatType",
	"eventPassSettings",
	"eventPassTierSettings",
	"evolutionChainDisplaySettings",
	"evolutionQuestTemplate",
	"featureGate",
	"formSettings",
	"fortPowerUpLevelSettings",
	"friendshipMilestoneSettings",
	"genderSettings",
	"iapCategoryDisplay",
	"iapItemDisplay",
	"invasionNpcDisplaySettings",
	"itemExpirationSettings",
	"itemSettings",
	"languageSettings",
	"levelUpRewards",
	"limitedPurchaseSkuSettings",
	"locationCardSettings",
	"megaEvoLevelSettings",
	"moveSequenceSettings",
	"moveSettings",
	"nonCombatMoveSettings",
	"partyPlayGeneralSettings",
	"photoSetsSettingsProto",
	"pokemonExtendedSettings",
	"pokemonFamily",
	"pokemonHomeEnergyCosts",
	"pokemonHomeFormReversions",
	"pokemonScaleSettings",
	"pokemonSettings",
	"pokemonUpgrades",
	"pokestopInvasionAvailabilitySettings",
	"questSettings",
	"recommendedSearchSettings",
	"rollBack",
	"settingsOverrideRule",
	"singletons",
	"stickerMetadata",
	"tappableSettings",
	"temporaryEvolutionSettings",
	"typeEffective",
	"vsSeekerLoot",
	"vsSeekerPokemonRewards",
	"weatherAffinities",
] as const;

export type GroupName = (typeof GROUP_NAMES)[number];
