// Generated from Pokémon GO masterfile — group "evolutionChainDisplaySettings", 79 entries (structural types).

import type { W } from "../_utils";

export interface EvolutionChainDisplaySettings<
	TemplateID extends string = string,
	TData extends EvolutionChainDisplaySettingsData = EvolutionChainDisplaySettingsData,
> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		evolutionChainDisplaySettings: TData;
	};
}
export type EvolutionChainDisplaySettingsType = W<EvolutionChainDisplaySettings>;

export interface EvolutionChainDisplaySettingsData {
	evolutionChains?: Array<{
		evolutionInfos: Array<{
			form?: string;
			gender?: "FEMALE" | "GENDERLESS" | "MALE";
			pokemon: string;
		}>;
		headerMessage?:
			| "alola_pokedex_header"
			| "form_artisan"
			| "form_counterfeit"
			| "form_masterpiece"
			| "galarian_pokedex_header"
			| "gender_female"
			| "gender_male"
			| "hisuian_pokedex_header"
			| "paldean_pokedex_header";
	}>;
	pokemon: string;
}

export type Evolution =
	| "EVOLUTION_V0052_POKEMON_MEOWTH"
	| "EVOLUTION_V0083_POKEMON_FARFETCHD"
	| "EVOLUTION_V0122_POKEMON_MR_MIME"
	| "EVOLUTION_V0123_POKEMON_SCYTHER"
	| "EVOLUTION_V0150_POKEMON_MEWTWO"
	| "EVOLUTION_V0155_POKEMON_CYNDAQUIL"
	| "EVOLUTION_V0156_POKEMON_QUILAVA"
	| "EVOLUTION_V0157_POKEMON_TYPHLOSION"
	| "EVOLUTION_V0194_POKEMON_WOOPER"
	| "EVOLUTION_V0211_POKEMON_QWILFISH"
	| "EVOLUTION_V0215_POKEMON_SNEASEL"
	| "EVOLUTION_V0222_POKEMON_CORSOLA"
	| "EVOLUTION_V0234_POKEMON_STANTLER"
	| "EVOLUTION_V0263_POKEMON_ZIGZAGOON"
	| "EVOLUTION_V0264_POKEMON_LINOONE"
	| "EVOLUTION_V0290_POKEMON_NINCADA"
	| "EVOLUTION_V0412_POKEMON_BURMY"
	| "EVOLUTION_V0413_POKEMON_WORMADAM"
	| "EVOLUTION_V0414_POKEMON_MOTHIM"
	| "EVOLUTION_V0420_POKEMON_CHERUBI"
	| "EVOLUTION_V0421_POKEMON_CHERRIM"
	| "EVOLUTION_V0422_POKEMON_SHELLOS"
	| "EVOLUTION_V0423_POKEMON_GASTRODON"
	| "EVOLUTION_V0449_POKEMON_HIPPOPOTAS"
	| "EVOLUTION_V0450_POKEMON_HIPPOWDON"
	| "EVOLUTION_V0501_POKEMON_OSHAWOTT"
	| "EVOLUTION_V0502_POKEMON_DEWOTT"
	| "EVOLUTION_V0503_POKEMON_SAMUROTT"
	| "EVOLUTION_V0519_POKEMON_PIDOVE"
	| "EVOLUTION_V0520_POKEMON_TRANQUILL"
	| "EVOLUTION_V0521_POKEMON_UNFEZANT"
	| "EVOLUTION_V0550_POKEMON_BASCULIN"
	| "EVOLUTION_V0554_POKEMON_DARUMAKA"
	| "EVOLUTION_V0562_POKEMON_YAMASK"
	| "EVOLUTION_V0585_POKEMON_DEERLING"
	| "EVOLUTION_V0586_POKEMON_SAWSBUCK"
	| "EVOLUTION_V0592_POKEMON_FRILLISH"
	| "EVOLUTION_V0593_POKEMON_JELLICENT"
	| "EVOLUTION_V0664_POKEMON_SCATTERBUG"
	| "EVOLUTION_V0665_POKEMON_SPEWPA"
	| "EVOLUTION_V0666_POKEMON_VIVILLON"
	| "EVOLUTION_V0667_POKEMON_LITLEO"
	| "EVOLUTION_V0668_POKEMON_PYROAR"
	| "EVOLUTION_V0669_POKEMON_FLABEBE"
	| "EVOLUTION_V0670_POKEMON_FLOETTE"
	| "EVOLUTION_V0671_POKEMON_FLORGES"
	| "EVOLUTION_V0677_POKEMON_ESPURR"
	| "EVOLUTION_V0678_POKEMON_MEOWSTIC"
	| "EVOLUTION_V0679_POKEMON_HONEDGE"
	| "EVOLUTION_V0680_POKEMON_DOUBLADE"
	| "EVOLUTION_V0681_POKEMON_AEGISLASH"
	| "EVOLUTION_V0710_POKEMON_PUMPKABOO"
	| "EVOLUTION_V0711_POKEMON_GOURGEIST"
	| "EVOLUTION_V0718_POKEMON_ZYGARDE"
	| "EVOLUTION_V0722_POKEMON_ROWLET"
	| "EVOLUTION_V0723_POKEMON_DARTRIX"
	| "EVOLUTION_V0724_POKEMON_DECIDUEYE"
	| "EVOLUTION_V0744_POKEMON_ROCKRUFF"
	| "EVOLUTION_V0745_POKEMON_LYCANROC"
	| "EVOLUTION_V0800_POKEMON_NECROZMA"
	| "EVOLUTION_V0848_POKEMON_TOXEL"
	| "EVOLUTION_V0849_POKEMON_TOXTRICITY"
	| "EVOLUTION_V0862_POKEMON_OBSTAGOON"
	| "EVOLUTION_V0863_POKEMON_PERRSERKER"
	| "EVOLUTION_V0864_POKEMON_CURSOLA"
	| "EVOLUTION_V0865_POKEMON_SIRFETCHD"
	| "EVOLUTION_V0866_POKEMON_MR_RIME"
	| "EVOLUTION_V0867_POKEMON_RUNERIGUS"
	| "EVOLUTION_V0899_POKEMON_WYRDEER"
	| "EVOLUTION_V0900_POKEMON_KLEAVOR"
	| "EVOLUTION_V0903_POKEMON_SNEASLER"
	| "EVOLUTION_V0904_POKEMON_OVERQWIL"
	| "EVOLUTION_V0915_POKEMON_LECHONK"
	| "EVOLUTION_V0916_POKEMON_OINKOLOGNE"
	| "EVOLUTION_V0924_POKEMON_TANDEMAUS"
	| "EVOLUTION_V0925_POKEMON_MAUSHOLD"
	| "EVOLUTION_V0980_POKEMON_CLODSIRE"
	| "EVOLUTION_V1012_POKEMON_POLTCHAGEIST"
	| "EVOLUTION_V1013_POKEMON_SINISTCHA";
