// Generated from Pokémon GO masterfile — group "megaEvoLevelSettings", 103 entries (structural types).

import type { W } from "../_utils";

export interface MegaEvoLevelSettings<TemplateID extends string = string, TData extends MegaEvoLevelSettingsData = MegaEvoLevelSettingsData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		megaEvoLevelSettings: TData & {
			cooldown: {
				bypassCostRoundingValue: 1;
			};
			effects: {
				differentTypeAttackBoost: 1.1;
				sameTypeAttackBoost: 1.3;
			};
			progression: {
				pointsLimitPerPeriod: 1;
				pointsPerMegaEvoAction: 1;
			};
		};
	};
}
export type MegaEvoLevelSettingsType = W<MegaEvoLevelSettings>;

export interface MegaEvoLevelSettingsData {
	cooldown: {
		bypassCostInitial: number;
		durationMs: "1209600000" | "259200000" | "432000000" | "604800000" | "86400000";
	};
	effects: {
		sameTypeExtraCatchCandy: number;
		sameTypeExtraCatchCandyXlChance?: number;
		sameTypeExtraCatchXp?: number;
		selfCpBoostAdditionalLevel?: number;
	};
	ftueExpirationTimestamp?: "1775001600000";
	level?: number;
	megaEnergyCostToUnlock?: number;
	pokemonId?:
		| "ALTARIA"
		| "BANETTE"
		| "BEEDRILL"
		| "DIANCIE"
		| "DRAGONITE"
		| "GARCHOMP"
		| "GROUDON"
		| "GYARADOS"
		| "HOUNDOOM"
		| "KYOGRE"
		| "LATIAS"
		| "LATIOS"
		| "MALAMAR"
		| "MANECTRIC"
		| "MEDICHAM"
		| "METAGROSS"
		| "MEWTWO"
		| "PIDGEOT"
		| "RAYQUAZA"
		| "SABLEYE"
		| "SALAMENCE"
		| "SLOWBRO"
		| "TYRANITAR"
		| "VICTREEBEL";
	progression: {
		pointsRequired?: number;
	};
}

export type MegaEvolutionLevel =
	| "MEGA_EVOLUTION_LEVEL_0"
	| "MEGA_EVOLUTION_LEVEL_0_V0015_POKEMON_BEEDRILL"
	| "MEGA_EVOLUTION_LEVEL_0_V0018_POKEMON_PIDGEOT"
	| "MEGA_EVOLUTION_LEVEL_0_V0071_POKEMON_VICTREEBEL"
	| "MEGA_EVOLUTION_LEVEL_0_V0080_POKEMON_SLOWBRO"
	| "MEGA_EVOLUTION_LEVEL_0_V0130_POKEMON_GYARADOS"
	| "MEGA_EVOLUTION_LEVEL_0_V0149_POKEMON_DRAGONITE"
	| "MEGA_EVOLUTION_LEVEL_0_V0150_POKEMON_MEWTWO"
	| "MEGA_EVOLUTION_LEVEL_0_V0229_POKEMON_HOUNDOOM"
	| "MEGA_EVOLUTION_LEVEL_0_V0248_POKEMON_TYRANITAR"
	| "MEGA_EVOLUTION_LEVEL_0_V0302_POKEMON_SABLEYE"
	| "MEGA_EVOLUTION_LEVEL_0_V0308_POKEMON_MEDICHAM"
	| "MEGA_EVOLUTION_LEVEL_0_V0310_POKEMON_MANECTRIC"
	| "MEGA_EVOLUTION_LEVEL_0_V0334_POKEMON_ALTARIA"
	| "MEGA_EVOLUTION_LEVEL_0_V0354_POKEMON_BANETTE"
	| "MEGA_EVOLUTION_LEVEL_0_V0373_POKEMON_SALAMENCE"
	| "MEGA_EVOLUTION_LEVEL_0_V0376_POKEMON_METAGROSS"
	| "MEGA_EVOLUTION_LEVEL_0_V0380_POKEMON_LATIAS"
	| "MEGA_EVOLUTION_LEVEL_0_V0381_POKEMON_LATIOS"
	| "MEGA_EVOLUTION_LEVEL_0_V0382_POKEMON_KYOGRE"
	| "MEGA_EVOLUTION_LEVEL_0_V0383_POKEMON_GROUDON"
	| "MEGA_EVOLUTION_LEVEL_0_V0384_POKEMON_RAYQUAZA"
	| "MEGA_EVOLUTION_LEVEL_0_V0445_POKEMON_GARCHOMP"
	| "MEGA_EVOLUTION_LEVEL_0_V0687_POKEMON_MALAMAR"
	| "MEGA_EVOLUTION_LEVEL_0_V0719_POKEMON_DIANCIE"
	| "MEGA_EVOLUTION_LEVEL_1"
	| "MEGA_EVOLUTION_LEVEL_1_V0015_POKEMON_BEEDRILL"
	| "MEGA_EVOLUTION_LEVEL_1_V0018_POKEMON_PIDGEOT"
	| "MEGA_EVOLUTION_LEVEL_1_V0071_POKEMON_VICTREEBEL"
	| "MEGA_EVOLUTION_LEVEL_1_V0080_POKEMON_SLOWBRO"
	| "MEGA_EVOLUTION_LEVEL_1_V0130_POKEMON_GYARADOS"
	| "MEGA_EVOLUTION_LEVEL_1_V0149_POKEMON_DRAGONITE"
	| "MEGA_EVOLUTION_LEVEL_1_V0150_POKEMON_MEWTWO"
	| "MEGA_EVOLUTION_LEVEL_1_V0229_POKEMON_HOUNDOOM"
	| "MEGA_EVOLUTION_LEVEL_1_V0248_POKEMON_TYRANITAR"
	| "MEGA_EVOLUTION_LEVEL_1_V0302_POKEMON_SABLEYE"
	| "MEGA_EVOLUTION_LEVEL_1_V0308_POKEMON_MEDICHAM"
	| "MEGA_EVOLUTION_LEVEL_1_V0310_POKEMON_MANECTRIC"
	| "MEGA_EVOLUTION_LEVEL_1_V0334_POKEMON_ALTARIA"
	| "MEGA_EVOLUTION_LEVEL_1_V0354_POKEMON_BANETTE"
	| "MEGA_EVOLUTION_LEVEL_1_V0373_POKEMON_SALAMENCE"
	| "MEGA_EVOLUTION_LEVEL_1_V0376_POKEMON_METAGROSS"
	| "MEGA_EVOLUTION_LEVEL_1_V0380_POKEMON_LATIAS"
	| "MEGA_EVOLUTION_LEVEL_1_V0381_POKEMON_LATIOS"
	| "MEGA_EVOLUTION_LEVEL_1_V0382_POKEMON_KYOGRE"
	| "MEGA_EVOLUTION_LEVEL_1_V0383_POKEMON_GROUDON"
	| "MEGA_EVOLUTION_LEVEL_1_V0384_POKEMON_RAYQUAZA"
	| "MEGA_EVOLUTION_LEVEL_1_V0445_POKEMON_GARCHOMP"
	| "MEGA_EVOLUTION_LEVEL_1_V0687_POKEMON_MALAMAR"
	| "MEGA_EVOLUTION_LEVEL_1_V0719_POKEMON_DIANCIE"
	| "MEGA_EVOLUTION_LEVEL_2"
	| "MEGA_EVOLUTION_LEVEL_2_V0015_POKEMON_BEEDRILL"
	| "MEGA_EVOLUTION_LEVEL_2_V0018_POKEMON_PIDGEOT"
	| "MEGA_EVOLUTION_LEVEL_2_V0071_POKEMON_VICTREEBEL"
	| "MEGA_EVOLUTION_LEVEL_2_V0080_POKEMON_SLOWBRO"
	| "MEGA_EVOLUTION_LEVEL_2_V0130_POKEMON_GYARADOS"
	| "MEGA_EVOLUTION_LEVEL_2_V0149_POKEMON_DRAGONITE"
	| "MEGA_EVOLUTION_LEVEL_2_V0150_POKEMON_MEWTWO"
	| "MEGA_EVOLUTION_LEVEL_2_V0229_POKEMON_HOUNDOOM"
	| "MEGA_EVOLUTION_LEVEL_2_V0248_POKEMON_TYRANITAR"
	| "MEGA_EVOLUTION_LEVEL_2_V0302_POKEMON_SABLEYE"
	| "MEGA_EVOLUTION_LEVEL_2_V0308_POKEMON_MEDICHAM"
	| "MEGA_EVOLUTION_LEVEL_2_V0310_POKEMON_MANECTRIC"
	| "MEGA_EVOLUTION_LEVEL_2_V0334_POKEMON_ALTARIA"
	| "MEGA_EVOLUTION_LEVEL_2_V0354_POKEMON_BANETTE"
	| "MEGA_EVOLUTION_LEVEL_2_V0373_POKEMON_SALAMENCE"
	| "MEGA_EVOLUTION_LEVEL_2_V0376_POKEMON_METAGROSS"
	| "MEGA_EVOLUTION_LEVEL_2_V0380_POKEMON_LATIAS"
	| "MEGA_EVOLUTION_LEVEL_2_V0381_POKEMON_LATIOS"
	| "MEGA_EVOLUTION_LEVEL_2_V0382_POKEMON_KYOGRE"
	| "MEGA_EVOLUTION_LEVEL_2_V0383_POKEMON_GROUDON"
	| "MEGA_EVOLUTION_LEVEL_2_V0384_POKEMON_RAYQUAZA"
	| "MEGA_EVOLUTION_LEVEL_2_V0445_POKEMON_GARCHOMP"
	| "MEGA_EVOLUTION_LEVEL_2_V0687_POKEMON_MALAMAR"
	| "MEGA_EVOLUTION_LEVEL_2_V0719_POKEMON_DIANCIE"
	| "MEGA_EVOLUTION_LEVEL_3"
	| "MEGA_EVOLUTION_LEVEL_3_V0015_POKEMON_BEEDRILL"
	| "MEGA_EVOLUTION_LEVEL_3_V0018_POKEMON_PIDGEOT"
	| "MEGA_EVOLUTION_LEVEL_3_V0071_POKEMON_VICTREEBEL"
	| "MEGA_EVOLUTION_LEVEL_3_V0080_POKEMON_SLOWBRO"
	| "MEGA_EVOLUTION_LEVEL_3_V0130_POKEMON_GYARADOS"
	| "MEGA_EVOLUTION_LEVEL_3_V0149_POKEMON_DRAGONITE"
	| "MEGA_EVOLUTION_LEVEL_3_V0150_POKEMON_MEWTWO"
	| "MEGA_EVOLUTION_LEVEL_3_V0229_POKEMON_HOUNDOOM"
	| "MEGA_EVOLUTION_LEVEL_3_V0248_POKEMON_TYRANITAR"
	| "MEGA_EVOLUTION_LEVEL_3_V0302_POKEMON_SABLEYE"
	| "MEGA_EVOLUTION_LEVEL_3_V0308_POKEMON_MEDICHAM"
	| "MEGA_EVOLUTION_LEVEL_3_V0310_POKEMON_MANECTRIC"
	| "MEGA_EVOLUTION_LEVEL_3_V0334_POKEMON_ALTARIA"
	| "MEGA_EVOLUTION_LEVEL_3_V0354_POKEMON_BANETTE"
	| "MEGA_EVOLUTION_LEVEL_3_V0373_POKEMON_SALAMENCE"
	| "MEGA_EVOLUTION_LEVEL_3_V0376_POKEMON_METAGROSS"
	| "MEGA_EVOLUTION_LEVEL_3_V0380_POKEMON_LATIAS"
	| "MEGA_EVOLUTION_LEVEL_3_V0381_POKEMON_LATIOS"
	| "MEGA_EVOLUTION_LEVEL_3_V0382_POKEMON_KYOGRE"
	| "MEGA_EVOLUTION_LEVEL_3_V0383_POKEMON_GROUDON"
	| "MEGA_EVOLUTION_LEVEL_3_V0384_POKEMON_RAYQUAZA"
	| "MEGA_EVOLUTION_LEVEL_3_V0445_POKEMON_GARCHOMP"
	| "MEGA_EVOLUTION_LEVEL_3_V0687_POKEMON_MALAMAR"
	| "MEGA_EVOLUTION_LEVEL_3_V0719_POKEMON_DIANCIE"
	| "MEGA_EVOLUTION_LEVEL_4_V0071_POKEMON_VICTREEBEL"
	| "MEGA_EVOLUTION_LEVEL_4_V0149_POKEMON_DRAGONITE"
	| "MEGA_EVOLUTION_LEVEL_4_V0687_POKEMON_MALAMAR";
