export interface EvolutionChainDisplaySettings<T extends string> {
	templateId: T;
	data: EvolutionChainDisplaySettingsData<T>;
}

export interface EvolutionChainDisplaySettingsData<T extends string> {
	templateId: T;
	evolutionChainDisplaySettings: unknown;
}

export type EvolutionChainDisplaySettingsV0052PokemonMeowth = EvolutionChainDisplaySettings<"EVOLUTION_V0052_POKEMON_MEOWTH">;
export type EvolutionChainDisplaySettingsV0083PokemonFarfetchd = EvolutionChainDisplaySettings<"EVOLUTION_V0083_POKEMON_FARFETCHD">;
export type EvolutionChainDisplaySettingsV0122PokemonMrMime = EvolutionChainDisplaySettings<"EVOLUTION_V0122_POKEMON_MR_MIME">;
export type EvolutionChainDisplaySettingsV0123PokemonScyther = EvolutionChainDisplaySettings<"EVOLUTION_V0123_POKEMON_SCYTHER">;
export type EvolutionChainDisplaySettingsV0150PokemonMewtwo = EvolutionChainDisplaySettings<"EVOLUTION_V0150_POKEMON_MEWTWO">;
export type EvolutionChainDisplaySettingsV0155PokemonCyndaquil = EvolutionChainDisplaySettings<"EVOLUTION_V0155_POKEMON_CYNDAQUIL">;
export type EvolutionChainDisplaySettingsV0156PokemonQuilava = EvolutionChainDisplaySettings<"EVOLUTION_V0156_POKEMON_QUILAVA">;
export type EvolutionChainDisplaySettingsV0157PokemonTyphlosion = EvolutionChainDisplaySettings<"EVOLUTION_V0157_POKEMON_TYPHLOSION">;
export type EvolutionChainDisplaySettingsV0194PokemonWooper = EvolutionChainDisplaySettings<"EVOLUTION_V0194_POKEMON_WOOPER">;
export type EvolutionChainDisplaySettingsV0211PokemonQwilfish = EvolutionChainDisplaySettings<"EVOLUTION_V0211_POKEMON_QWILFISH">;
export type EvolutionChainDisplaySettingsV0215PokemonSneasel = EvolutionChainDisplaySettings<"EVOLUTION_V0215_POKEMON_SNEASEL">;
export type EvolutionChainDisplaySettingsV0222PokemonCorsola = EvolutionChainDisplaySettings<"EVOLUTION_V0222_POKEMON_CORSOLA">;
export type EvolutionChainDisplaySettingsV0234PokemonStantler = EvolutionChainDisplaySettings<"EVOLUTION_V0234_POKEMON_STANTLER">;
export type EvolutionChainDisplaySettingsV0263PokemonZigzagoon = EvolutionChainDisplaySettings<"EVOLUTION_V0263_POKEMON_ZIGZAGOON">;
export type EvolutionChainDisplaySettingsV0264PokemonLinoone = EvolutionChainDisplaySettings<"EVOLUTION_V0264_POKEMON_LINOONE">;
export type EvolutionChainDisplaySettingsV0290PokemonNincada = EvolutionChainDisplaySettings<"EVOLUTION_V0290_POKEMON_NINCADA">;
export type EvolutionChainDisplaySettingsV0412PokemonBurmy = EvolutionChainDisplaySettings<"EVOLUTION_V0412_POKEMON_BURMY">;
export type EvolutionChainDisplaySettingsV0413PokemonWormadam = EvolutionChainDisplaySettings<"EVOLUTION_V0413_POKEMON_WORMADAM">;
export type EvolutionChainDisplaySettingsV0414PokemonMothim = EvolutionChainDisplaySettings<"EVOLUTION_V0414_POKEMON_MOTHIM">;
export type EvolutionChainDisplaySettingsV0420PokemonCherubi = EvolutionChainDisplaySettings<"EVOLUTION_V0420_POKEMON_CHERUBI">;
export type EvolutionChainDisplaySettingsV0421PokemonCherrim = EvolutionChainDisplaySettings<"EVOLUTION_V0421_POKEMON_CHERRIM">;
export type EvolutionChainDisplaySettingsV0422PokemonShellos = EvolutionChainDisplaySettings<"EVOLUTION_V0422_POKEMON_SHELLOS">;
export type EvolutionChainDisplaySettingsV0423PokemonGastrodon = EvolutionChainDisplaySettings<"EVOLUTION_V0423_POKEMON_GASTRODON">;
export type EvolutionChainDisplaySettingsV0449PokemonHippopotas = EvolutionChainDisplaySettings<"EVOLUTION_V0449_POKEMON_HIPPOPOTAS">;
export type EvolutionChainDisplaySettingsV0450PokemonHippowdon = EvolutionChainDisplaySettings<"EVOLUTION_V0450_POKEMON_HIPPOWDON">;
export type EvolutionChainDisplaySettingsV0501PokemonOshawott = EvolutionChainDisplaySettings<"EVOLUTION_V0501_POKEMON_OSHAWOTT">;
export type EvolutionChainDisplaySettingsV0502PokemonDewott = EvolutionChainDisplaySettings<"EVOLUTION_V0502_POKEMON_DEWOTT">;
export type EvolutionChainDisplaySettingsV0503PokemonSamurott = EvolutionChainDisplaySettings<"EVOLUTION_V0503_POKEMON_SAMUROTT">;
export type EvolutionChainDisplaySettingsV0519PokemonPidove = EvolutionChainDisplaySettings<"EVOLUTION_V0519_POKEMON_PIDOVE">;
export type EvolutionChainDisplaySettingsV0520PokemonTranquill = EvolutionChainDisplaySettings<"EVOLUTION_V0520_POKEMON_TRANQUILL">;
export type EvolutionChainDisplaySettingsV0521PokemonUnfezant = EvolutionChainDisplaySettings<"EVOLUTION_V0521_POKEMON_UNFEZANT">;
export type EvolutionChainDisplaySettingsV0550PokemonBasculin = EvolutionChainDisplaySettings<"EVOLUTION_V0550_POKEMON_BASCULIN">;
export type EvolutionChainDisplaySettingsV0554PokemonDarumaka = EvolutionChainDisplaySettings<"EVOLUTION_V0554_POKEMON_DARUMAKA">;
export type EvolutionChainDisplaySettingsV0562PokemonYamask = EvolutionChainDisplaySettings<"EVOLUTION_V0562_POKEMON_YAMASK">;
export type EvolutionChainDisplaySettingsV0585PokemonDeerling = EvolutionChainDisplaySettings<"EVOLUTION_V0585_POKEMON_DEERLING">;
export type EvolutionChainDisplaySettingsV0586PokemonSawsbuck = EvolutionChainDisplaySettings<"EVOLUTION_V0586_POKEMON_SAWSBUCK">;
export type EvolutionChainDisplaySettingsV0592PokemonFrillish = EvolutionChainDisplaySettings<"EVOLUTION_V0592_POKEMON_FRILLISH">;
export type EvolutionChainDisplaySettingsV0593PokemonJellicent = EvolutionChainDisplaySettings<"EVOLUTION_V0593_POKEMON_JELLICENT">;
export type EvolutionChainDisplaySettingsV0664PokemonScatterbug = EvolutionChainDisplaySettings<"EVOLUTION_V0664_POKEMON_SCATTERBUG">;
export type EvolutionChainDisplaySettingsV0665PokemonSpewpa = EvolutionChainDisplaySettings<"EVOLUTION_V0665_POKEMON_SPEWPA">;
export type EvolutionChainDisplaySettingsV0666PokemonVivillon = EvolutionChainDisplaySettings<"EVOLUTION_V0666_POKEMON_VIVILLON">;
export type EvolutionChainDisplaySettingsV0667PokemonLitleo = EvolutionChainDisplaySettings<"EVOLUTION_V0667_POKEMON_LITLEO">;
export type EvolutionChainDisplaySettingsV0668PokemonPyroar = EvolutionChainDisplaySettings<"EVOLUTION_V0668_POKEMON_PYROAR">;
export type EvolutionChainDisplaySettingsV0669PokemonFlabebe = EvolutionChainDisplaySettings<"EVOLUTION_V0669_POKEMON_FLABEBE">;
export type EvolutionChainDisplaySettingsV0670PokemonFloette = EvolutionChainDisplaySettings<"EVOLUTION_V0670_POKEMON_FLOETTE">;
export type EvolutionChainDisplaySettingsV0671PokemonFlorges = EvolutionChainDisplaySettings<"EVOLUTION_V0671_POKEMON_FLORGES">;
export type EvolutionChainDisplaySettingsV0677PokemonEspurr = EvolutionChainDisplaySettings<"EVOLUTION_V0677_POKEMON_ESPURR">;
export type EvolutionChainDisplaySettingsV0678PokemonMeowstic = EvolutionChainDisplaySettings<"EVOLUTION_V0678_POKEMON_MEOWSTIC">;
export type EvolutionChainDisplaySettingsV0679PokemonHonedge = EvolutionChainDisplaySettings<"EVOLUTION_V0679_POKEMON_HONEDGE">;
export type EvolutionChainDisplaySettingsV0680PokemonDoublade = EvolutionChainDisplaySettings<"EVOLUTION_V0680_POKEMON_DOUBLADE">;
export type EvolutionChainDisplaySettingsV0681PokemonAegislash = EvolutionChainDisplaySettings<"EVOLUTION_V0681_POKEMON_AEGISLASH">;
export type EvolutionChainDisplaySettingsV0710PokemonPumpkaboo = EvolutionChainDisplaySettings<"EVOLUTION_V0710_POKEMON_PUMPKABOO">;
export type EvolutionChainDisplaySettingsV0711PokemonGourgeist = EvolutionChainDisplaySettings<"EVOLUTION_V0711_POKEMON_GOURGEIST">;
export type EvolutionChainDisplaySettingsV0718PokemonZygarde = EvolutionChainDisplaySettings<"EVOLUTION_V0718_POKEMON_ZYGARDE">;
export type EvolutionChainDisplaySettingsV0722PokemonRowlet = EvolutionChainDisplaySettings<"EVOLUTION_V0722_POKEMON_ROWLET">;
export type EvolutionChainDisplaySettingsV0723PokemonDartrix = EvolutionChainDisplaySettings<"EVOLUTION_V0723_POKEMON_DARTRIX">;
export type EvolutionChainDisplaySettingsV0724PokemonDecidueye = EvolutionChainDisplaySettings<"EVOLUTION_V0724_POKEMON_DECIDUEYE">;
export type EvolutionChainDisplaySettingsV0744PokemonRockruff = EvolutionChainDisplaySettings<"EVOLUTION_V0744_POKEMON_ROCKRUFF">;
export type EvolutionChainDisplaySettingsV0745PokemonLycanroc = EvolutionChainDisplaySettings<"EVOLUTION_V0745_POKEMON_LYCANROC">;
export type EvolutionChainDisplaySettingsV0800PokemonNecrozma = EvolutionChainDisplaySettings<"EVOLUTION_V0800_POKEMON_NECROZMA">;
export type EvolutionChainDisplaySettingsV0848PokemonToxel = EvolutionChainDisplaySettings<"EVOLUTION_V0848_POKEMON_TOXEL">;
export type EvolutionChainDisplaySettingsV0849PokemonToxtricity = EvolutionChainDisplaySettings<"EVOLUTION_V0849_POKEMON_TOXTRICITY">;
export type EvolutionChainDisplaySettingsV0862PokemonObstagoon = EvolutionChainDisplaySettings<"EVOLUTION_V0862_POKEMON_OBSTAGOON">;
export type EvolutionChainDisplaySettingsV0863PokemonPerrserker = EvolutionChainDisplaySettings<"EVOLUTION_V0863_POKEMON_PERRSERKER">;
export type EvolutionChainDisplaySettingsV0864PokemonCursola = EvolutionChainDisplaySettings<"EVOLUTION_V0864_POKEMON_CURSOLA">;
export type EvolutionChainDisplaySettingsV0865PokemonSirfetchd = EvolutionChainDisplaySettings<"EVOLUTION_V0865_POKEMON_SIRFETCHD">;
export type EvolutionChainDisplaySettingsV0866PokemonMrRime = EvolutionChainDisplaySettings<"EVOLUTION_V0866_POKEMON_MR_RIME">;
export type EvolutionChainDisplaySettingsV0867PokemonRunerigus = EvolutionChainDisplaySettings<"EVOLUTION_V0867_POKEMON_RUNERIGUS">;
export type EvolutionChainDisplaySettingsV0899PokemonWyrdeer = EvolutionChainDisplaySettings<"EVOLUTION_V0899_POKEMON_WYRDEER">;
export type EvolutionChainDisplaySettingsV0900PokemonKleavor = EvolutionChainDisplaySettings<"EVOLUTION_V0900_POKEMON_KLEAVOR">;
export type EvolutionChainDisplaySettingsV0903PokemonSneasler = EvolutionChainDisplaySettings<"EVOLUTION_V0903_POKEMON_SNEASLER">;
export type EvolutionChainDisplaySettingsV0904PokemonOverqwil = EvolutionChainDisplaySettings<"EVOLUTION_V0904_POKEMON_OVERQWIL">;
export type EvolutionChainDisplaySettingsV0915PokemonLechonk = EvolutionChainDisplaySettings<"EVOLUTION_V0915_POKEMON_LECHONK">;
export type EvolutionChainDisplaySettingsV0916PokemonOinkologne = EvolutionChainDisplaySettings<"EVOLUTION_V0916_POKEMON_OINKOLOGNE">;
export type EvolutionChainDisplaySettingsV0924PokemonTandemaus = EvolutionChainDisplaySettings<"EVOLUTION_V0924_POKEMON_TANDEMAUS">;
export type EvolutionChainDisplaySettingsV0925PokemonMaushold = EvolutionChainDisplaySettings<"EVOLUTION_V0925_POKEMON_MAUSHOLD">;
export type EvolutionChainDisplaySettingsV0980PokemonClodsire = EvolutionChainDisplaySettings<"EVOLUTION_V0980_POKEMON_CLODSIRE">;
export type EvolutionChainDisplaySettingsV1012PokemonPoltchageist = EvolutionChainDisplaySettings<"EVOLUTION_V1012_POKEMON_POLTCHAGEIST">;
export type EvolutionChainDisplaySettingsV1013PokemonSinistcha = EvolutionChainDisplaySettings<"EVOLUTION_V1013_POKEMON_SINISTCHA">;

export type EvolutionChainDisplaySettingsMasterfileEntry =
	| EvolutionChainDisplaySettingsV0052PokemonMeowth
	| EvolutionChainDisplaySettingsV0083PokemonFarfetchd
	| EvolutionChainDisplaySettingsV0122PokemonMrMime
	| EvolutionChainDisplaySettingsV0123PokemonScyther
	| EvolutionChainDisplaySettingsV0150PokemonMewtwo
	| EvolutionChainDisplaySettingsV0155PokemonCyndaquil
	| EvolutionChainDisplaySettingsV0156PokemonQuilava
	| EvolutionChainDisplaySettingsV0157PokemonTyphlosion
	| EvolutionChainDisplaySettingsV0194PokemonWooper
	| EvolutionChainDisplaySettingsV0211PokemonQwilfish
	| EvolutionChainDisplaySettingsV0215PokemonSneasel
	| EvolutionChainDisplaySettingsV0222PokemonCorsola
	| EvolutionChainDisplaySettingsV0234PokemonStantler
	| EvolutionChainDisplaySettingsV0263PokemonZigzagoon
	| EvolutionChainDisplaySettingsV0264PokemonLinoone
	| EvolutionChainDisplaySettingsV0290PokemonNincada
	| EvolutionChainDisplaySettingsV0412PokemonBurmy
	| EvolutionChainDisplaySettingsV0413PokemonWormadam
	| EvolutionChainDisplaySettingsV0414PokemonMothim
	| EvolutionChainDisplaySettingsV0420PokemonCherubi
	| EvolutionChainDisplaySettingsV0421PokemonCherrim
	| EvolutionChainDisplaySettingsV0422PokemonShellos
	| EvolutionChainDisplaySettingsV0423PokemonGastrodon
	| EvolutionChainDisplaySettingsV0449PokemonHippopotas
	| EvolutionChainDisplaySettingsV0450PokemonHippowdon
	| EvolutionChainDisplaySettingsV0501PokemonOshawott
	| EvolutionChainDisplaySettingsV0502PokemonDewott
	| EvolutionChainDisplaySettingsV0503PokemonSamurott
	| EvolutionChainDisplaySettingsV0519PokemonPidove
	| EvolutionChainDisplaySettingsV0520PokemonTranquill
	| EvolutionChainDisplaySettingsV0521PokemonUnfezant
	| EvolutionChainDisplaySettingsV0550PokemonBasculin
	| EvolutionChainDisplaySettingsV0554PokemonDarumaka
	| EvolutionChainDisplaySettingsV0562PokemonYamask
	| EvolutionChainDisplaySettingsV0585PokemonDeerling
	| EvolutionChainDisplaySettingsV0586PokemonSawsbuck
	| EvolutionChainDisplaySettingsV0592PokemonFrillish
	| EvolutionChainDisplaySettingsV0593PokemonJellicent
	| EvolutionChainDisplaySettingsV0664PokemonScatterbug
	| EvolutionChainDisplaySettingsV0665PokemonSpewpa
	| EvolutionChainDisplaySettingsV0666PokemonVivillon
	| EvolutionChainDisplaySettingsV0667PokemonLitleo
	| EvolutionChainDisplaySettingsV0668PokemonPyroar
	| EvolutionChainDisplaySettingsV0669PokemonFlabebe
	| EvolutionChainDisplaySettingsV0670PokemonFloette
	| EvolutionChainDisplaySettingsV0671PokemonFlorges
	| EvolutionChainDisplaySettingsV0677PokemonEspurr
	| EvolutionChainDisplaySettingsV0678PokemonMeowstic
	| EvolutionChainDisplaySettingsV0679PokemonHonedge
	| EvolutionChainDisplaySettingsV0680PokemonDoublade
	| EvolutionChainDisplaySettingsV0681PokemonAegislash
	| EvolutionChainDisplaySettingsV0710PokemonPumpkaboo
	| EvolutionChainDisplaySettingsV0711PokemonGourgeist
	| EvolutionChainDisplaySettingsV0718PokemonZygarde
	| EvolutionChainDisplaySettingsV0722PokemonRowlet
	| EvolutionChainDisplaySettingsV0723PokemonDartrix
	| EvolutionChainDisplaySettingsV0724PokemonDecidueye
	| EvolutionChainDisplaySettingsV0744PokemonRockruff
	| EvolutionChainDisplaySettingsV0745PokemonLycanroc
	| EvolutionChainDisplaySettingsV0800PokemonNecrozma
	| EvolutionChainDisplaySettingsV0848PokemonToxel
	| EvolutionChainDisplaySettingsV0849PokemonToxtricity
	| EvolutionChainDisplaySettingsV0862PokemonObstagoon
	| EvolutionChainDisplaySettingsV0863PokemonPerrserker
	| EvolutionChainDisplaySettingsV0864PokemonCursola
	| EvolutionChainDisplaySettingsV0865PokemonSirfetchd
	| EvolutionChainDisplaySettingsV0866PokemonMrRime
	| EvolutionChainDisplaySettingsV0867PokemonRunerigus
	| EvolutionChainDisplaySettingsV0899PokemonWyrdeer
	| EvolutionChainDisplaySettingsV0900PokemonKleavor
	| EvolutionChainDisplaySettingsV0903PokemonSneasler
	| EvolutionChainDisplaySettingsV0904PokemonOverqwil
	| EvolutionChainDisplaySettingsV0915PokemonLechonk
	| EvolutionChainDisplaySettingsV0916PokemonOinkologne
	| EvolutionChainDisplaySettingsV0924PokemonTandemaus
	| EvolutionChainDisplaySettingsV0925PokemonMaushold
	| EvolutionChainDisplaySettingsV0980PokemonClodsire
	| EvolutionChainDisplaySettingsV1012PokemonPoltchageist
	| EvolutionChainDisplaySettingsV1013PokemonSinistcha;

export type EvolutionChainDisplaySettingsTemplateID = EvolutionChainDisplaySettingsMasterfileEntry["templateId"];
