export interface PokestopInvasionAvailabilitySettings<T extends string> {
	templateId: T;
	data: PokestopInvasionAvailabilitySettingsData<T>;
}

export interface PokestopInvasionAvailabilitySettingsData<T extends string> {
	templateId: T;
	pokestopInvasionAvailabilitySettings: unknown;
}

export type PokestopInvasionAvailabilitySettingsFriday = PokestopInvasionAvailabilitySettings<"INVASION_AVAILABILITY_SETTINGS_FRIDAY">;
export type PokestopInvasionAvailabilitySettingsMonday = PokestopInvasionAvailabilitySettings<"INVASION_AVAILABILITY_SETTINGS_MONDAY">;
export type PokestopInvasionAvailabilitySettingsSaturday = PokestopInvasionAvailabilitySettings<"INVASION_AVAILABILITY_SETTINGS_SATURDAY">;
export type PokestopInvasionAvailabilitySettingsSunday = PokestopInvasionAvailabilitySettings<"INVASION_AVAILABILITY_SETTINGS_SUNDAY">;
export type PokestopInvasionAvailabilitySettingsThursday = PokestopInvasionAvailabilitySettings<"INVASION_AVAILABILITY_SETTINGS_THURSDAY">;
export type PokestopInvasionAvailabilitySettingsTuesday = PokestopInvasionAvailabilitySettings<"INVASION_AVAILABILITY_SETTINGS_TUESDAY">;
export type PokestopInvasionAvailabilitySettingsWednesday = PokestopInvasionAvailabilitySettings<"INVASION_AVAILABILITY_SETTINGS_WEDNESDAY">;

export type PokestopInvasionAvailabilitySettingsMasterfileEntry =
	| PokestopInvasionAvailabilitySettingsFriday
	| PokestopInvasionAvailabilitySettingsMonday
	| PokestopInvasionAvailabilitySettingsSaturday
	| PokestopInvasionAvailabilitySettingsSunday
	| PokestopInvasionAvailabilitySettingsThursday
	| PokestopInvasionAvailabilitySettingsTuesday
	| PokestopInvasionAvailabilitySettingsWednesday;

export type PokestopInvasionAvailabilitySettingsTemplateID = PokestopInvasionAvailabilitySettingsMasterfileEntry["templateId"];
