// Generated from Pokémon GO masterfile — group "avatarCustomization", 1757 entries (structural types).

export type * from "./variants";

export interface AvatarCustomization<TemplateID extends string = string, TData extends AvatarCustomizationData = AvatarCustomizationData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		avatarCustomization: TData;
	};
}

export interface AvatarCustomizationData {
	assetName: string;
	avatarType?: "PLAYER_AVATAR_FEMALE";
	bundleName?: string;
	enabled?: boolean;
	groupName:
		| "group_backpack"
		| "group_belt"
		| "group_eyes"
		| "group_face"
		| "group_glasses"
		| "group_gloves"
		| "group_hair"
		| "group_hat"
		| "group_necklace"
		| "group_pants"
		| "group_poses"
		| "group_seasonal"
		| "group_shirt"
		| "group_shoes"
		| "group_skin"
		| "group_socks"
		| "group_sponsor";
	iapSku?: string;
	iconName?: string;
	setNames?: Array<string>;
	setPrimeItem?: boolean;
	slot: ["BACKPACK" | "BELT" | "EYES" | "FACE" | "GLASSES" | "GLOVES" | "HAIR" | "HAT" | "NECKLACE" | "PANTS" | "POSE" | "SHIRT" | "SHOES" | "SKIN" | "SOCKS"];
	sortOrder: number;
	unlockBadgeLevel?: number;
	unlockBadgeType?:
		| "BADGE_BATTLE_ATTACK_WON"
		| "BADGE_BATTLE_TRAINING_WON"
		| "BADGE_BIG_MAGIKARP"
		| "BADGE_GREAT_LEAGUE"
		| "BADGE_HOURS_DEFENDED"
		| "BADGE_MASTER_LEAGUE"
		| "BADGE_MAX_SIZE_FIRST_PLACE_WIN"
		| "BADGE_PIKACHU"
		| "BADGE_POKEDEX_ENTRIES"
		| "BADGE_POKEDEX_ENTRIES_GEN2"
		| "BADGE_ROCKET_GIOVANNI_DEFEATED"
		| "BADGE_TRAVEL_KM"
		| "BADGE_ULTRA_LEAGUE";
	unlockPlayerLevel?: number;
	unlockType: "DEFAULT" | "IAP_CLOTHING" | "LEVEL_REWARD" | "MEDAL_REWARD";
}

export type AvatarCustomizationMasterfileEntry =
	| AvatarCustomizationFBackpackAlolaitemslittenbp
	| AvatarCustomizationFBackpackAlolaitemspoppliobp
	| AvatarCustomizationFBackpackAlolaitemsrowletbp
	| AvatarCustomizationFBackpackAnimegou
	| AvatarCustomizationFBackpackBackpacker
	| AvatarCustomizationFBackpackCombeebackpack
	| AvatarCustomizationFBackpackCombeebackpack01
	| AvatarCustomizationFBackpackCute0
	| AvatarCustomizationFBackpackDedenneitems
	| AvatarCustomizationFBackpackDefault0
	| AvatarCustomizationFBackpackDefault1
	| AvatarCustomizationFBackpackDefault2
	| AvatarCustomizationFBackpackDefault3
	| AvatarCustomizationFBackpackEggIncubator
	| AvatarCustomizationFBackpackEggbackpack0
	| AvatarCustomizationFBackpackEggbackpack1
	| AvatarCustomizationFBackpackEggbackpack2
	| AvatarCustomizationFBackpackEmpty
	| AvatarCustomizationFBackpackFrlg0
	| AvatarCustomizationFBackpackGenesecteventitem
	| AvatarCustomizationFBackpackGengar0
	| AvatarCustomizationFBackpackGiratinaitems
	| AvatarCustomizationFBackpackGuccibackpack
	| AvatarCustomizationFBackpackGuitarcasebackpack
	| AvatarCustomizationFBackpackHgss0
	| AvatarCustomizationFBackpackHououbackpack
	| AvatarCustomizationFBackpackKakureonpouch
	| AvatarCustomizationFBackpackKomala
	| AvatarCustomizationFBackpackLongchampbp
	| AvatarCustomizationFBackpackLunalaitems
	| AvatarCustomizationFBackpackLunarnewyr
	| AvatarCustomizationFBackpackMimikyubp
	| AvatarCustomizationFBackpackMovie2020
	| AvatarCustomizationFBackpackNaganadelawings
	| AvatarCustomizationFBackpackNike2021
	| AvatarCustomizationFBackpackPamobackpack
	| AvatarCustomizationFBackpackPkmnhoodie001
	| AvatarCustomizationFBackpackPkmnhoodie004
	| AvatarCustomizationFBackpackPkmnhoodie007
	| AvatarCustomizationFBackpackRuinmaniac
	| AvatarCustomizationFBackpackSnapcamera
	| AvatarCustomizationFBackpackSs
	| AvatarCustomizationFBackpackSvcostumescarletschool
	| AvatarCustomizationFBackpackSvcostumevioletschool
	| AvatarCustomizationFBackpackSvdlc1
	| AvatarCustomizationFBackpackSvdlc2spring
	| AvatarCustomizationFBackpackSwshdlc2costume
	| AvatarCustomizationFBackpackSwshdlccostume
	| AvatarCustomizationFBackpackTogepibackpack
	| AvatarCustomizationFBackpackUltra0
	| AvatarCustomizationFBackpackVerizon2021
	| AvatarCustomizationFBackpackZubatbp
	| AvatarCustomizationFBeltAcetrainerbw
	| AvatarCustomizationFBeltDefault0
	| AvatarCustomizationFBeltDefault1
	| AvatarCustomizationFBeltDefault2
	| AvatarCustomizationFBeltDefault3
	| AvatarCustomizationFBeltDefault4
	| AvatarCustomizationFBeltDefault5
	| AvatarCustomizationFBeltDefault6
	| AvatarCustomizationFBeltDefault7
	| AvatarCustomizationFBeltDefault8
	| AvatarCustomizationFBeltEmpty
	| AvatarCustomizationFBeltSimple0
	| AvatarCustomizationFBeltSimple1
	| AvatarCustomizationFBeltSimple2
	| AvatarCustomizationFBeltSimple3
	| AvatarCustomizationFBeltTeamrocket0
	| AvatarCustomizationFBeltTeamrocket1
	| AvatarCustomizationFEyes0
	| AvatarCustomizationFEyes1
	| AvatarCustomizationFEyes2
	| AvatarCustomizationFEyes3
	| AvatarCustomizationFEyes4
	| AvatarCustomizationFFace3dmask00
	| AvatarCustomizationFFace3dmask01
	| AvatarCustomizationFFace3dmask02
	| AvatarCustomizationFFaceBanettemask
	| AvatarCustomizationFFaceDayofthedead
	| AvatarCustomizationFFaceDefaultmask
	| AvatarCustomizationFFaceEmpty
	| AvatarCustomizationFFaceFacestickerghostpika
	| AvatarCustomizationFFaceFacestickerpikachu
	| AvatarCustomizationFFaceFacestickerpokeball
	| AvatarCustomizationFFaceFestofcolors00
	| AvatarCustomizationFFaceFestofcolors01
	| AvatarCustomizationFFaceFestofcolors02
	| AvatarCustomizationFFaceGracidea
	| AvatarCustomizationFFaceHoliday2022santacostumes
	| AvatarCustomizationFFacePikachumask
	| AvatarCustomizationFFaceSableyemask
	| AvatarCustomizationFFaceTeamskull
	| AvatarCustomizationFFaceToxelmask
	| AvatarCustomizationFFaceVerizon2020mask
	| AvatarCustomizationFGlasses3d
	| AvatarCustomizationFGlassesCutieflysleepmask
	| AvatarCustomizationFGlassesDivingsuit
	| AvatarCustomizationFGlassesDrpikachu
	| AvatarCustomizationFGlassesEmpty
	| AvatarCustomizationFGlassesFrillishglasses
	| AvatarCustomizationFGlassesFw2022
	| AvatarCustomizationFGlassesGimmighoulitems
	| AvatarCustomizationFGlassesGoteamrocketarlo
	| AvatarCustomizationFGlassesGrandoakglasses
	| AvatarCustomizationFGlassesLugiaglasses
	| AvatarCustomizationFGlassesLv40glasses
	| AvatarCustomizationFGlassesMask0
	| AvatarCustomizationFGlassesMask1
	| AvatarCustomizationFGlassesNewyear2022
	| AvatarCustomizationFGlassesNewyearglasses2020
	| AvatarCustomizationFGlassesNewyearglasses2021
	| AvatarCustomizationFGlassesObstagoonitems
	| AvatarCustomizationFGlassesRoundsunglasses
	| AvatarCustomizationFGlassesTeardrop0
	| AvatarCustomizationFGlassesThick0
	| AvatarCustomizationFGlassesThick1
	| AvatarCustomizationFGlassesThick2
	| AvatarCustomizationFGlassesThick3
	| AvatarCustomizationFGlassesThick4
	| AvatarCustomizationFGlovesAcetrainersm
	| AvatarCustomizationFGlovesBattlegirl0
	| AvatarCustomizationFGlovesBea
	| AvatarCustomizationFGlovesBwn
	| AvatarCustomizationFGlovesDefault0
	| AvatarCustomizationFGlovesDefault1
	| AvatarCustomizationFGlovesDefault2
	| AvatarCustomizationFGlovesDefault3
	| AvatarCustomizationFGlovesDelibird
	| AvatarCustomizationFGlovesDynamaxswsh
	| AvatarCustomizationFGlovesEmpty
	| AvatarCustomizationFGlovesFrlg0
	| AvatarCustomizationFGlovesGeeta
	| AvatarCustomizationFGlovesGiovanni
	| AvatarCustomizationFGlovesGuzma
	| AvatarCustomizationFGlovesGymleader0
	| AvatarCustomizationFGlovesHoopabangle
	| AvatarCustomizationFGlovesKorrina
	| AvatarCustomizationFGlovesLysandre
	| AvatarCustomizationFGlovesMegabangle
	| AvatarCustomizationFGlovesMegabangleblack
	| AvatarCustomizationFGlovesMegabangleblue
	| AvatarCustomizationFGlovesMegabanglered
	| AvatarCustomizationFGlovesMegabangleyellow
	| AvatarCustomizationFGlovesObstagoonitems
	| AvatarCustomizationFGlovesPalmer
	| AvatarCustomizationFGlovesProfwillowoutfit
	| AvatarCustomizationFGlovesStevenfirst
	| AvatarCustomizationFGlovesSvdlc2spring
	| AvatarCustomizationFGlovesSwshdlc2costume
	| AvatarCustomizationFGlovesSwshdlccostume
	| AvatarCustomizationFGlovesSwshuniformchampion
	| AvatarCustomizationFGlovesSwshuniformdark
	| AvatarCustomizationFGlovesSwshuniformdefault
	| AvatarCustomizationFGlovesSwshuniformdragon
	| AvatarCustomizationFGlovesTeamaqua
	| AvatarCustomizationFGlovesTeammagma
	| AvatarCustomizationFGlovesTeamrocket0
	| AvatarCustomizationFGlovesTeamspark
	| AvatarCustomizationFGlovesWintergloves2023
	| AvatarCustomizationFGofestPikachuvisor
	| AvatarCustomizationFHairDefault0
	| AvatarCustomizationFHairDefault1
	| AvatarCustomizationFHairDefault10
	| AvatarCustomizationFHairDefault11
	| AvatarCustomizationFHairDefault12
	| AvatarCustomizationFHairDefault13
	| AvatarCustomizationFHairDefault14
	| AvatarCustomizationFHairDefault15
	| AvatarCustomizationFHairDefault16
	| AvatarCustomizationFHairDefault17
	| AvatarCustomizationFHairDefault18
	| AvatarCustomizationFHairDefault19
	| AvatarCustomizationFHairDefault2
	| AvatarCustomizationFHairDefault3
	| AvatarCustomizationFHairDefault4
	| AvatarCustomizationFHairDefault5
	| AvatarCustomizationFHairDefault6
	| AvatarCustomizationFHairDefault7
	| AvatarCustomizationFHairDefault8
	| AvatarCustomizationFHairDefault9
	| AvatarCustomizationFHat6thanniversary
	| AvatarCustomizationFHatAcetrainersm
	| AvatarCustomizationFHatAdventure0
	| AvatarCustomizationFHatAseries
	| AvatarCustomizationFHatBea
	| AvatarCustomizationFHatBidoofhat
	| AvatarCustomizationFHatBounsweetitems
	| AvatarCustomizationFHatBurmyearrings11
	| AvatarCustomizationFHatBurmyearrings12
	| AvatarCustomizationFHatBurmyearrings13
	| AvatarCustomizationFHatBwn
	| AvatarCustomizationFHatCasket0
	| AvatarCustomizationFHatCetoddlehat
	| AvatarCustomizationFHatClay
	| AvatarCustomizationFHatCofagrigusitems
	| AvatarCustomizationFHatCosmog
	| AvatarCustomizationFHatCrownmoon
	| AvatarCustomizationFHatCrownsun
	| AvatarCustomizationFHatCubonehat
	| AvatarCustomizationFHatDarumakahat
	| AvatarCustomizationFHatDedenneitems
	| AvatarCustomizationFHatDefaultA0
	| AvatarCustomizationFHatDefaultA1
	| AvatarCustomizationFHatDefaultA2
	| AvatarCustomizationFHatDefaultA3
	| AvatarCustomizationFHatDefaultA4
	| AvatarCustomizationFHatDefaultA5
	| AvatarCustomizationFHatDefaultB0
	| AvatarCustomizationFHatDefaultB1
	| AvatarCustomizationFHatDeino
	| AvatarCustomizationFHatDelibird
	| AvatarCustomizationFHatDetectivepikachu
	| AvatarCustomizationFHatDiancie
	| AvatarCustomizationFHatDp
	| AvatarCustomizationFHatDrifloon0
	| AvatarCustomizationFHatDrpikachu
	| AvatarCustomizationFHatDusclopsmummy
	| AvatarCustomizationFHatEeveecap
	| AvatarCustomizationFHatElesa
	| AvatarCustomizationFHatEmpty
	| AvatarCustomizationFHatFedora0
	| AvatarCustomizationFHatFedora1
	| AvatarCustomizationFHatFlabebepack
	| AvatarCustomizationFHatFragment0
	| AvatarCustomizationFHatFrlg0
	| AvatarCustomizationFHatFurfrouwig
	| AvatarCustomizationFHatFw2022
	| AvatarCustomizationFHatGalarfarfetchditems
	| AvatarCustomizationFHatGenesecteventitem
	| AvatarCustomizationFHatGengar0
	| AvatarCustomizationFHatGimmighoulitems
	| AvatarCustomizationFHatGiratinaitems
	| AvatarCustomizationFHatGladion
	| AvatarCustomizationFHatGoomy
	| AvatarCustomizationFHatGreavardwig
	| AvatarCustomizationFHatGreencoat
	| AvatarCustomizationFHatGrowlithehelmet
	| AvatarCustomizationFHatGtr2024eeveefanmask
	| AvatarCustomizationFHatGtr2024pikachufanmask
	| AvatarCustomizationFHatGuccihat
	| AvatarCustomizationFHatGuzma
	| AvatarCustomizationFHatGyaradoscap
	| AvatarCustomizationFHatHgss0
	| AvatarCustomizationFHatHoliday2022santacostumes
	| AvatarCustomizationFHatHolidaybeanie
	| AvatarCustomizationFHatHoopaearmuffs
	| AvatarCustomizationFHatIngo
	| AvatarCustomizationFHatKantotourcapgreen
	| AvatarCustomizationFHatKantotourcapred
	| AvatarCustomizationFHatKnitted0
	| AvatarCustomizationFHatKnitted1
	| AvatarCustomizationFHatKorrina
	| AvatarCustomizationFHatLana
	| AvatarCustomizationFHatLaprasbandana
	| AvatarCustomizationFHatLasecuritycorps
	| AvatarCustomizationFHatLegendofarceus
	| AvatarCustomizationFHatLitwickhat
	| AvatarCustomizationFHatLoneearrings
	| AvatarCustomizationFHatLvl50cap
	| AvatarCustomizationFHatMagikarp
	| AvatarCustomizationFHatMareaniehat
	| AvatarCustomizationFHatMegalopunnyitems
	| AvatarCustomizationFHatMegarayquaza
	| AvatarCustomizationFHatMeltan
	| AvatarCustomizationFHatMeltanearrings
	| AvatarCustomizationFHatMewtwo
	| AvatarCustomizationFHatMimikyu0
	| AvatarCustomizationFHatMismagius0
	| AvatarCustomizationFHatMovie2020
	| AvatarCustomizationFHatMunnapack0
	| AvatarCustomizationFHatMunnapack1
	| AvatarCustomizationFHatNewyear2022
	| AvatarCustomizationFHatNewyearhat2021
	| AvatarCustomizationFHatNewyearhat2023
	| AvatarCustomizationFHatNihilegoitems
	| AvatarCustomizationFHatNoibat
	| AvatarCustomizationFHatObstagoonitems
	| AvatarCustomizationFHatOras
	| AvatarCustomizationFHatOricoriopink
	| AvatarCustomizationFHatOricoriopurple
	| AvatarCustomizationFHatOricoriored
	| AvatarCustomizationFHatOricorioyellow
	| AvatarCustomizationFHatPartneritemsjan2024hat
	| AvatarCustomizationFHatPhantump
	| AvatarCustomizationFHatPikachucap
	| AvatarCustomizationFHatPikachufan0
	| AvatarCustomizationFHatPikachulibre
	| AvatarCustomizationFHatPikachupumpkinhead
	| AvatarCustomizationFHatPkmncap0
	| AvatarCustomizationFHatPkmncap1
	| AvatarCustomizationFHatPkmncap2
	| AvatarCustomizationFHatPoipole
	| AvatarCustomizationFHatProfwillowoutfit
	| AvatarCustomizationFHatRegiicejersies
	| AvatarCustomizationFHatRegirockjersies
	| AvatarCustomizationFHatRegisteeljersies
	| AvatarCustomizationFHatRuinmaniac
	| AvatarCustomizationFHatSableyegoggles
	| AvatarCustomizationFHatSamsungsummer2020
	| AvatarCustomizationFHatSandygasthat
	| AvatarCustomizationFHatShayminhat
	| AvatarCustomizationFHatSlowpoketailshirts
	| AvatarCustomizationFHatSnorlaxnightcap
	| AvatarCustomizationFHatSolgaleoitems
	| AvatarCustomizationFHatSs
	| AvatarCustomizationFHatStantlerheadband
	| AvatarCustomizationFHatStrawhat
	| AvatarCustomizationFHatSummer2023
	| AvatarCustomizationFHatSvcostumescarletschool
	| AvatarCustomizationFHatSvcostumevioletschool
	| AvatarCustomizationFHatSwshdlc2costume
	| AvatarCustomizationFHatSwshuniformchampion
	| AvatarCustomizationFHatSylveonitems
	| AvatarCustomizationFHatTcgcollabtshirtandcap
	| AvatarCustomizationFHatTeamaqua
	| AvatarCustomizationFHatTeamleadercap0
	| AvatarCustomizationFHatTeamleadercap1
	| AvatarCustomizationFHatTeamleadercap2
	| AvatarCustomizationFHatTeamrocket0
	| AvatarCustomizationFHatTeamrocketcap
	| AvatarCustomizationFHatTeamskull
	| AvatarCustomizationFHatTophat0
	| AvatarCustomizationFHatUltrareconsquad
	| AvatarCustomizationFHatUltrareconsquadb
	| AvatarCustomizationFHatUltra0
	| AvatarCustomizationFHatVerizon2021
	| AvatarCustomizationFHatWcs2022winnersitems
	| AvatarCustomizationFHatWhimsicottearmuff
	| AvatarCustomizationFHatWillowglasses
	| AvatarCustomizationFHatWoobatearrings
	| AvatarCustomizationFHatYamaskhat
	| AvatarCustomizationFHatYamaskmask
	| AvatarCustomizationFHatZubathat
	| AvatarCustomizationFJacketNewyear2022
	| AvatarCustomizationFNecklaceDefault0
	| AvatarCustomizationFNecklaceDefault1
	| AvatarCustomizationFNecklaceEmpty
	| AvatarCustomizationFNecklaceHeart0
	| AvatarCustomizationFNecklaceStar0
	| AvatarCustomizationFPants6thanniversary
	| AvatarCustomizationFPants7thanniversary
	| AvatarCustomizationFPantsAcetrainerbw
	| AvatarCustomizationFPantsAnimegou
	| AvatarCustomizationFPantsBackpacker
	| AvatarCustomizationFPantsBattlegirl0
	| AvatarCustomizationFPantsBounsweetitems
	| AvatarCustomizationFPantsBwn
	| AvatarCustomizationFPantsCasual0
	| AvatarCustomizationFPantsCasual1
	| AvatarCustomizationFPantsClay
	| AvatarCustomizationFPantsDefault0
	| AvatarCustomizationFPantsDefault1
	| AvatarCustomizationFPantsDefault2
	| AvatarCustomizationFPantsDefault3
	| AvatarCustomizationFPantsDefault4
	| AvatarCustomizationFPantsDefault5
	| AvatarCustomizationFPantsDenimfashionweek2023
	| AvatarCustomizationFPantsDp
	| AvatarCustomizationFPantsFashionweek2022
	| AvatarCustomizationFPantsFlabebepack
	| AvatarCustomizationFPantsFrlg0
	| AvatarCustomizationFPantsFw2022
	| AvatarCustomizationFPantsGeeta
	| AvatarCustomizationFPantsGenderlessskirt
	| AvatarCustomizationFPantsGiovanni
	| AvatarCustomizationFPantsGladion
	| AvatarCustomizationFPantsGothitelleitems
	| AvatarCustomizationFPantsGreen
	| AvatarCustomizationFPantsGreencoat
	| AvatarCustomizationFPantsGuzma
	| AvatarCustomizationFPantsGymleader0
	| AvatarCustomizationFPantsGymleader1
	| AvatarCustomizationFPantsGymleader2
	| AvatarCustomizationFPantsHala
	| AvatarCustomizationFPantsHgss0
	| AvatarCustomizationFPantsIngo
	| AvatarCustomizationFPantsLoosepants
	| AvatarCustomizationFPantsLunalaitems
	| AvatarCustomizationFPantsLuvdiscpack
	| AvatarCustomizationFPantsLysandre
	| AvatarCustomizationFPantsMewtwo
	| AvatarCustomizationFPantsMiniskirt0
	| AvatarCustomizationFPantsMiniskirt1
	| AvatarCustomizationFPantsMiniskirt2
	| AvatarCustomizationFPantsMiniskirt3
	| AvatarCustomizationFPantsMiniskirtWave0
	| AvatarCustomizationFPantsMiniskirtWave1
	| AvatarCustomizationFPantsMiniskirtWave2
	| AvatarCustomizationFPantsMisty
	| AvatarCustomizationFPantsMunnapack
	| AvatarCustomizationFPantsNeonSolid0
	| AvatarCustomizationFPantsNeonSolid1
	| AvatarCustomizationFPantsNeonSolid2
	| AvatarCustomizationFPantsNeonStripes0
	| AvatarCustomizationFPantsNeonStripes1
	| AvatarCustomizationFPantsNewyear2022
	| AvatarCustomizationFPantsOras
	| AvatarCustomizationFPantsPajamas20220
	| AvatarCustomizationFPantsPajamas20221
	| AvatarCustomizationFPantsPalmer
	| AvatarCustomizationFPantsPikachufan0
	| AvatarCustomizationFPantsPikachulibre
	| AvatarCustomizationFPantsProfwillowoutfit
	| AvatarCustomizationFPantsPumpkabooitems
	| AvatarCustomizationFPantsRegiicejersies
	| AvatarCustomizationFPantsRegirockjersies
	| AvatarCustomizationFPantsRegisteeljersies
	| AvatarCustomizationFPantsShorts0
	| AvatarCustomizationFPantsShorts1
	| AvatarCustomizationFPantsShorts2
	| AvatarCustomizationFPantsShorts3
	| AvatarCustomizationFPantsSkinnyjeans0
	| AvatarCustomizationFPantsSteven
	| AvatarCustomizationFPantsStevenfirst
	| AvatarCustomizationFPantsSwshdlc2costume
	| AvatarCustomizationFPantsSwshuniformchampion
	| AvatarCustomizationFPantsSwshuniformdark
	| AvatarCustomizationFPantsSwshuniformdefault
	| AvatarCustomizationFPantsSwshuniformdragon
	| AvatarCustomizationFPantsTeamaqua
	| AvatarCustomizationFPantsTeamblanche
	| AvatarCustomizationFPantsTeamcandela
	| AvatarCustomizationFPantsTeammagma
	| AvatarCustomizationFPantsTeamrocket0
	| AvatarCustomizationFPantsTeamskull
	| AvatarCustomizationFPantsTeamspark
	| AvatarCustomizationFPantsTurbine0
	| AvatarCustomizationFPantsTurbine1
	| AvatarCustomizationFPantsTurbine2
	| AvatarCustomizationFPantsUltra0
	| AvatarCustomizationFPantsVeterantrainerxy
	| AvatarCustomizationFPantsWcs2022winnersitems
	| AvatarCustomizationFPose01
	| AvatarCustomizationFPose02
	| AvatarCustomizationFPose03
	| AvatarCustomizationFPose04
	| AvatarCustomizationFPose05
	| AvatarCustomizationFPose06
	| AvatarCustomizationFPose07
	| AvatarCustomizationFPose08
	| AvatarCustomizationFPose09
	| AvatarCustomizationFPose10
	| AvatarCustomizationFPose11
	| AvatarCustomizationFPose12
	| AvatarCustomizationFPose13
	| AvatarCustomizationFPose14
	| AvatarCustomizationFPose15
	| AvatarCustomizationFPose16
	| AvatarCustomizationFPose17
	| AvatarCustomizationFPose18
	| AvatarCustomizationFPose19
	| AvatarCustomizationFPose20
	| AvatarCustomizationFPose21
	| AvatarCustomizationFPose22
	| AvatarCustomizationFPose23
	| AvatarCustomizationFPose24
	| AvatarCustomizationFPose25
	| AvatarCustomizationFPose26
	| AvatarCustomizationFPose27
	| AvatarCustomizationFPose28
	| AvatarCustomizationFPose29
	| AvatarCustomizationFPose30
	| AvatarCustomizationFPose31
	| AvatarCustomizationFPose32
	| AvatarCustomizationFPose33
	| AvatarCustomizationFPose34
	| AvatarCustomizationFPose35
	| AvatarCustomizationFPose36
	| AvatarCustomizationFPose37
	| AvatarCustomizationFPose38
	| AvatarCustomizationFPose39
	| AvatarCustomizationFPose40
	| AvatarCustomizationFPose41
	| AvatarCustomizationFPose43
	| AvatarCustomizationFPose44
	| AvatarCustomizationFPose45
	| AvatarCustomizationFPose46
	| AvatarCustomizationFPose47
	| AvatarCustomizationFPose48
	| AvatarCustomizationFPose49
	| AvatarCustomizationFPose50
	| AvatarCustomizationFPose51
	| AvatarCustomizationFPose52
	| AvatarCustomizationFPose53
	| AvatarCustomizationFPose54
	| AvatarCustomizationFPose55
	| AvatarCustomizationFPose56
	| AvatarCustomizationFPose57
	| AvatarCustomizationFPose58
	| AvatarCustomizationFPose59
	| AvatarCustomizationFPose60
	| AvatarCustomizationFPose61
	| AvatarCustomizationFPose62
	| AvatarCustomizationFPose63
	| AvatarCustomizationFPose64
	| AvatarCustomizationFPoseEmpty
	| AvatarCustomizationFShirt6thanniversary
	| AvatarCustomizationFShirt7thanniversary
	| AvatarCustomizationFShirtAcetrainerbw
	| AvatarCustomizationFShirtAcetrainersm
	| AvatarCustomizationFShirtAlolacomfey
	| AvatarCustomizationFShirtAnimegou
	| AvatarCustomizationFShirtAseries
	| AvatarCustomizationFShirtBackpacker
	| AvatarCustomizationFShirtBallguy
	| AvatarCustomizationFShirtBattlegirl0
	| AvatarCustomizationFShirtBea
	| AvatarCustomizationFShirtBounsweetitems
	| AvatarCustomizationFShirtButtondown0
	| AvatarCustomizationFShirtBuzzwoleitems
	| AvatarCustomizationFShirtBwn
	| AvatarCustomizationFShirtCasual0
	| AvatarCustomizationFShirtCasual1
	| AvatarCustomizationFShirtCasual2
	| AvatarCustomizationFShirtCasual3
	| AvatarCustomizationFShirtCelebi0
	| AvatarCustomizationFShirtChimcharonesie
	| AvatarCustomizationFShirtClay
	| AvatarCustomizationFShirtCofagrigusitems
	| AvatarCustomizationFShirtCosmog
	| AvatarCustomizationFShirtCowichansweater
	| AvatarCustomizationFShirtDayofdead
	| AvatarCustomizationFShirtDefault0
	| AvatarCustomizationFShirtDefault1
	| AvatarCustomizationFShirtDefault2
	| AvatarCustomizationFShirtDefault3
	| AvatarCustomizationFShirtDefault4
	| AvatarCustomizationFShirtDefault5
	| AvatarCustomizationFShirtDefault6
	| AvatarCustomizationFShirtDefault7
	| AvatarCustomizationFShirtDefault8
	| AvatarCustomizationFShirtDelibird
	| AvatarCustomizationFShirtDelibirdonesie
	| AvatarCustomizationFShirtDenimfashionweek2023
	| AvatarCustomizationFShirtDenimjacket
	| AvatarCustomizationFShirtDetectivepikachu
	| AvatarCustomizationFShirtDiancie
	| AvatarCustomizationFShirtDivingsuit
	| AvatarCustomizationFShirtDiwali2021
	| AvatarCustomizationFShirtDp
	| AvatarCustomizationFShirtDrifblim0
	| AvatarCustomizationFShirtDusclopsmummy
	| AvatarCustomizationFShirtEarthday2018
	| AvatarCustomizationFShirtEeveestshirt00
	| AvatarCustomizationFShirtEeveestshirt01
	| AvatarCustomizationFShirtEeveestshirt02
	| AvatarCustomizationFShirtEeveestshirt03
	| AvatarCustomizationFShirtEeveestshirt04
	| AvatarCustomizationFShirtEeveestshirt05
	| AvatarCustomizationFShirtEeveestshirt06
	| AvatarCustomizationFShirtEeveestshirt07
	| AvatarCustomizationFShirtEeveestshirt08
	| AvatarCustomizationFShirtElesa
	| AvatarCustomizationFShirtFashionweek2022
	| AvatarCustomizationFShirtFestivaloflights00
	| AvatarCustomizationFShirtFestivaloflights01
	| AvatarCustomizationFShirtFlabebepack
	| AvatarCustomizationFShirtFragment0
	| AvatarCustomizationFShirtFrlg0
	| AvatarCustomizationFShirtFw2022
	| AvatarCustomizationFShirtGalarfarfetchditems
	| AvatarCustomizationFShirtGalaxyoutfit
	| AvatarCustomizationFShirtGeeta
	| AvatarCustomizationFShirtGenderlessskirt
	| AvatarCustomizationFShirtGengar0
	| AvatarCustomizationFShirtGengaronesie
	| AvatarCustomizationFShirtGiovanni
	| AvatarCustomizationFShirtGiratinaitems
	| AvatarCustomizationFShirtGladion
	| AvatarCustomizationFShirtGofest2022
	| AvatarCustomizationFShirtGofest2023
	| AvatarCustomizationFShirtGofest2024darkgray
	| AvatarCustomizationFShirtGofest2024gray
	| AvatarCustomizationFShirtGofest2024purple
	| AvatarCustomizationFShirtGofest2019
	| AvatarCustomizationFShirtGofest2020
	| AvatarCustomizationFShirtGofest2021
	| AvatarCustomizationFShirtGofestglobal2023
	| AvatarCustomizationFShirtGoteamrocketarlo
	| AvatarCustomizationFShirtGoteamrocketcliff
	| AvatarCustomizationFShirtGoteamrocketsierra
	| AvatarCustomizationFShirtGothitelleitems
	| AvatarCustomizationFShirtGotour2023
	| AvatarCustomizationFShirtGotour2024
	| AvatarCustomizationFShirtGreedentsweater
	| AvatarCustomizationFShirtGreen
	| AvatarCustomizationFShirtGreencoat
	| AvatarCustomizationFShirtGtrtshirt202200
	| AvatarCustomizationFShirtGtrtshirt202201
	| AvatarCustomizationFShirtGuccitshirts
	| AvatarCustomizationFShirtGuzma
	| AvatarCustomizationFShirtGymleader0
	| AvatarCustomizationFShirtGymleader1
	| AvatarCustomizationFShirtGymleader2
	| AvatarCustomizationFShirtHala
	| AvatarCustomizationFShirtHappi
	| AvatarCustomizationFShirtHappi1
	| AvatarCustomizationFShirtHappi2
	| AvatarCustomizationFShirtHgss0
	| AvatarCustomizationFShirtHoliday2022santacostumes
	| AvatarCustomizationFShirtHolifestival2021black
	| AvatarCustomizationFShirtHolifestival2021white
	| AvatarCustomizationFShirtHoopaunboundtshirt
	| AvatarCustomizationFShirtIngo
	| AvatarCustomizationFShirtIngress0
	| AvatarCustomizationFShirtIngressE0
	| AvatarCustomizationFShirtIngressR0
	| AvatarCustomizationFShirtJessie
	| AvatarCustomizationFShirtJirachi
	| AvatarCustomizationFShirtKeldeotshirt
	| AvatarCustomizationFShirtKorrina
	| AvatarCustomizationFShirtLadiamondoutfit
	| AvatarCustomizationFShirtLana
	| AvatarCustomizationFShirtLapearloutfit
	| AvatarCustomizationFShirtLasecuritycorps
	| AvatarCustomizationFShirtLatiasLatios0
	| AvatarCustomizationFShirtLegendofarceus
	| AvatarCustomizationFShirtLuvdiscpack
	| AvatarCustomizationFShirtLvl50
	| AvatarCustomizationFShirtLvl501
	| AvatarCustomizationFShirtLysandre
	| AvatarCustomizationFShirtMarshadowtshirt
	| AvatarCustomizationFShirtMegalopunnyitems
	| AvatarCustomizationFShirtMegarayquaza
	| AvatarCustomizationFShirtMelmetaljacket
	| AvatarCustomizationFShirtMelmetalvest
	| AvatarCustomizationFShirtMeloettatshirt
	| AvatarCustomizationFShirtMeltan
	| AvatarCustomizationFShirtMew0
	| AvatarCustomizationFShirtMewtwo
	| AvatarCustomizationFShirtMisty
	| AvatarCustomizationFShirtMovie2020jessiejames
	| AvatarCustomizationFShirtMunnapack
	| AvatarCustomizationFShirtNike2021
	| AvatarCustomizationFShirtOcshirt045
	| AvatarCustomizationFShirtOcshirt108
	| AvatarCustomizationFShirtOcshirt129
	| AvatarCustomizationFShirtOcshirt143
	| AvatarCustomizationFShirtOras
	| AvatarCustomizationFShirtPajamas20220
	| AvatarCustomizationFShirtPajamas20221
	| AvatarCustomizationFShirtPalmer
	| AvatarCustomizationFShirtPartneritemsjan2024hoodie
	| AvatarCustomizationFShirtPartneritemsjan2024tshirt
	| AvatarCustomizationFShirtPikachufan0
	| AvatarCustomizationFShirtPikachulibre
	| AvatarCustomizationFShirtPikachuonesie
	| AvatarCustomizationFShirtPinpukuhoodie
	| AvatarCustomizationFShirtPipluponesie
	| AvatarCustomizationFShirtPkmnhoodie001
	| AvatarCustomizationFShirtPkmnhoodie004
	| AvatarCustomizationFShirtPkmnhoodie007
	| AvatarCustomizationFShirtPkmnshirts202100
	| AvatarCustomizationFShirtPkmnshirts202101
	| AvatarCustomizationFShirtPkmnshirts202102
	| AvatarCustomizationFShirtPkmnshirts165
	| AvatarCustomizationFShirtPkmnshirts188
	| AvatarCustomizationFShirtPkmnshirts201
	| AvatarCustomizationFShirtPkmnshirts238
	| AvatarCustomizationFShirtPoloshirt
	| AvatarCustomizationFShirtPoloshirt1
	| AvatarCustomizationFShirtPoloshirt2
	| AvatarCustomizationFShirtProfwillowoutfit
	| AvatarCustomizationFShirtProjectguitar
	| AvatarCustomizationFShirtPumpkabooitems
	| AvatarCustomizationFShirtRegiicejersies
	| AvatarCustomizationFShirtRegirockjersies
	| AvatarCustomizationFShirtRegisteeljersies
	| AvatarCustomizationFShirtReuniclusitems
	| AvatarCustomizationFShirtRuinmaniac
	| AvatarCustomizationFShirtSafarizone2020
	| AvatarCustomizationFShirtSamsungsummer2020
	| AvatarCustomizationFShirtShayminlandtshirt
	| AvatarCustomizationFShirtShayminskytshirt
	| AvatarCustomizationFShirtShinymewtshirts
	| AvatarCustomizationFShirtSlowpokeshirts
	| AvatarCustomizationFShirtSlowpoketailshirts
	| AvatarCustomizationFShirtSnorlaxonesie
	| AvatarCustomizationFShirtSpiritomb0
	| AvatarCustomizationFShirtSpring2021gulpin
	| AvatarCustomizationFShirtSpring2021plusle
	| AvatarCustomizationFShirtSs
	| AvatarCustomizationFShirtSteven
	| AvatarCustomizationFShirtStevenfirst
	| AvatarCustomizationFShirtSukajanblastoise
	| AvatarCustomizationFShirtSukajancharizard
	| AvatarCustomizationFShirtSukajanhouou
	| AvatarCustomizationFShirtSukajanlugia
	| AvatarCustomizationFShirtSukajanvenusaur
	| AvatarCustomizationFShirtSummer2023
	| AvatarCustomizationFShirtSustainability2021
	| AvatarCustomizationFShirtSvcostumescarletschool
	| AvatarCustomizationFShirtSvcostumevioletschool
	| AvatarCustomizationFShirtSvdlc1
	| AvatarCustomizationFShirtSvdlc2fall
	| AvatarCustomizationFShirtSvdlc2spring
	| AvatarCustomizationFShirtSweater300
	| AvatarCustomizationFShirtSweater301
	| AvatarCustomizationFShirtSweater302
	| AvatarCustomizationFShirtSweaterInstinct
	| AvatarCustomizationFShirtSweaterMystic
	| AvatarCustomizationFShirtSweaterValor
	| AvatarCustomizationFShirtSwshdlc2costume
	| AvatarCustomizationFShirtSwshdlccostume
	| AvatarCustomizationFShirtSwshuniformchampion
	| AvatarCustomizationFShirtSwshuniformdark
	| AvatarCustomizationFShirtSwshuniformdefault
	| AvatarCustomizationFShirtSwshuniformdragon
	| AvatarCustomizationFShirtSylveonitems
	| AvatarCustomizationFShirtTanktop0
	| AvatarCustomizationFShirtTanktop1
	| AvatarCustomizationFShirtTanktop2
	| AvatarCustomizationFShirtTanktopCharizard0
	| AvatarCustomizationFShirtTanktopCharizard1
	| AvatarCustomizationFShirtTanktopCharizard2
	| AvatarCustomizationFShirtTanktopPikachu0
	| AvatarCustomizationFShirtTanktopPikachu1
	| AvatarCustomizationFShirtTanktopPikachu2
	| AvatarCustomizationFShirtTcgcollabtshirtandcap
	| AvatarCustomizationFShirtTeamaqua
	| AvatarCustomizationFShirtTeamblanche
	| AvatarCustomizationFShirtTeamcandela
	| AvatarCustomizationFShirtTeammagma
	| AvatarCustomizationFShirtTeamrocket0
	| AvatarCustomizationFShirtTeamrocket1
	| AvatarCustomizationFShirtTeamskull
	| AvatarCustomizationFShirtTeamspark
	| AvatarCustomizationFShirtTogepihoodie
	| AvatarCustomizationFShirtTracksuitsgroudon
	| AvatarCustomizationFShirtTracksuitskyogre
	| AvatarCustomizationFShirtTshirtCycling0
	| AvatarCustomizationFShirtTshirtCycling1
	| AvatarCustomizationFShirtTshirtCycling2
	| AvatarCustomizationFShirtTshirtCycling3
	| AvatarCustomizationFShirtTshirtFestChicago2017
	| AvatarCustomizationFShirtTshirtFestChicago2018
	| AvatarCustomizationFShirtTshirtGlobalGoals2017
	| AvatarCustomizationFShirtTshirtPikachu0
	| AvatarCustomizationFShirtTshirtPikachu1
	| AvatarCustomizationFShirtTshirtPikachu2
	| AvatarCustomizationFShirtTshirtPikachu3
	| AvatarCustomizationFShirtTshirtPikachu4
	| AvatarCustomizationFShirtTshirtPikachu5
	| AvatarCustomizationFShirtTshirtPikachu6
	| AvatarCustomizationFShirtTurtwigonesie
	| AvatarCustomizationFShirtUltrareconsquad
	| AvatarCustomizationFShirtUltra0
	| AvatarCustomizationFShirtUniqlotshirts0
	| AvatarCustomizationFShirtUniqlotshirts1
	| AvatarCustomizationFShirtUniqlotshirts2
	| AvatarCustomizationFShirtUnwto
	| AvatarCustomizationFShirtValentine2023
	| AvatarCustomizationFShirtVerizon2020
	| AvatarCustomizationFShirtVeterantrainerxy
	| AvatarCustomizationFShirtVictinitshirts
	| AvatarCustomizationFShirtWcs2022
	| AvatarCustomizationFShirtWcs2022tshirtbulu
	| AvatarCustomizationFShirtWcs2022tshirtred
	| AvatarCustomizationFShirtWcs2022winnersitems
	| AvatarCustomizationFShirtWcs2023
	| AvatarCustomizationFShirtWcs2023promotshirt
	| AvatarCustomizationFShirtWcs2023promotshirt01
	| AvatarCustomizationFShirtWcs2023sukajan
	| AvatarCustomizationFShirtWcs2023winnersitems
	| AvatarCustomizationFShirtWcs2024
	| AvatarCustomizationFShirtWcs2024championshipshirtBlue
	| AvatarCustomizationFShirtWcs2024championshipshirtWhite
	| AvatarCustomizationFShirtWcsyokohama
	| AvatarCustomizationFShirtWhitecoat
	| AvatarCustomizationFShirtWintersweater2023
	| AvatarCustomizationFShirtZoruaonesie
	| AvatarCustomizationFShoes6thanniversary
	| AvatarCustomizationFShoesAcetrainerbw
	| AvatarCustomizationFShoesAcetrainersm
	| AvatarCustomizationFShoesAnimegou
	| AvatarCustomizationFShoesBackpacker
	| AvatarCustomizationFShoesBattlegirl0
	| AvatarCustomizationFShoesBwn
	| AvatarCustomizationFShoesCarbink
	| AvatarCustomizationFShoesClay
	| AvatarCustomizationFShoesCoolboots
	| AvatarCustomizationFShoesDedenneitems
	| AvatarCustomizationFShoesDefault0
	| AvatarCustomizationFShoesDefault1
	| AvatarCustomizationFShoesDefault2
	| AvatarCustomizationFShoesDefault3
	| AvatarCustomizationFShoesDefault4
	| AvatarCustomizationFShoesDefault5
	| AvatarCustomizationFShoesDefault6
	| AvatarCustomizationFShoesDelibird
	| AvatarCustomizationFShoesDp
	| AvatarCustomizationFShoesElesa
	| AvatarCustomizationFShoesEmpty
	| AvatarCustomizationFShoesFashionweek2022
	| AvatarCustomizationFShoesFrlg0
	| AvatarCustomizationFShoesFw2022
	| AvatarCustomizationFShoesGeeta
	| AvatarCustomizationFShoesGiovanni
	| AvatarCustomizationFShoesGladion
	| AvatarCustomizationFShoesGothitelleitems
	| AvatarCustomizationFShoesGreen
	| AvatarCustomizationFShoesGymleader0
	| AvatarCustomizationFShoesGymleader1
	| AvatarCustomizationFShoesGymleader2
	| AvatarCustomizationFShoesHala
	| AvatarCustomizationFShoesHgss0
	| AvatarCustomizationFShoesIngo
	| AvatarCustomizationFShoesKorrina
	| AvatarCustomizationFShoesLadiamondoutfit
	| AvatarCustomizationFShoesLana
	| AvatarCustomizationFShoesLapearloutfit
	| AvatarCustomizationFShoesLegendofarceus
	| AvatarCustomizationFShoesLoosepants
	| AvatarCustomizationFShoesLoosepants1
	| AvatarCustomizationFShoesLoosepants2
	| AvatarCustomizationFShoesLoosepants3
	| AvatarCustomizationFShoesLuvdiscpack
	| AvatarCustomizationFShoesLysandre
	| AvatarCustomizationFShoesMegalopunnyitems
	| AvatarCustomizationFShoesMelmetalshoes
	| AvatarCustomizationFShoesMewtwo
	| AvatarCustomizationFShoesMisty
	| AvatarCustomizationFShoesNewyear2022
	| AvatarCustomizationFShoesNike2021
	| AvatarCustomizationFShoesOras
	| AvatarCustomizationFShoesPajamas20220
	| AvatarCustomizationFShoesPajamas20221
	| AvatarCustomizationFShoesPalmer
	| AvatarCustomizationFShoesPikachufan0
	| AvatarCustomizationFShoesPikachulibre
	| AvatarCustomizationFShoesProfwillowoutfit
	| AvatarCustomizationFShoesRegiicejersies
	| AvatarCustomizationFShoesRegirockjersies
	| AvatarCustomizationFShoesRegisteeljersies
	| AvatarCustomizationFShoesReuniclusitems
	| AvatarCustomizationFShoesRuinmaniac
	| AvatarCustomizationFShoesSandals
	| AvatarCustomizationFShoesSandals1
	| AvatarCustomizationFShoesSandals2
	| AvatarCustomizationFShoesSolgaleoitems
	| AvatarCustomizationFShoesSs
	| AvatarCustomizationFShoesSteven
	| AvatarCustomizationFShoesStevenfirst
	| AvatarCustomizationFShoesSvcostumescarletschool
	| AvatarCustomizationFShoesSvcostumevioletschool
	| AvatarCustomizationFShoesSvdlc1
	| AvatarCustomizationFShoesSvdlc2spring
	| AvatarCustomizationFShoesSwshdlc2costume
	| AvatarCustomizationFShoesSwshdlccostume
	| AvatarCustomizationFShoesSwshuniformdark
	| AvatarCustomizationFShoesSwshuniformdefault
	| AvatarCustomizationFShoesSwshuniformdragon
	| AvatarCustomizationFShoesSylveonitems
	| AvatarCustomizationFShoesTeamaqua
	| AvatarCustomizationFShoesTeamblanche
	| AvatarCustomizationFShoesTeamcandela
	| AvatarCustomizationFShoesTeammagma
	| AvatarCustomizationFShoesTeamrocket0
	| AvatarCustomizationFShoesTeamrocket1
	| AvatarCustomizationFShoesTeamskull
	| AvatarCustomizationFShoesTeamspark
	| AvatarCustomizationFShoesUltrareconsquad
	| AvatarCustomizationFShoesUltra0
	| AvatarCustomizationFShoesVeterantrainerxy
	| AvatarCustomizationFShoesWcs2022winnersitems
	| AvatarCustomizationFShoesWcs2023winnersitems
	| AvatarCustomizationFShoesWinterboots2023
	| AvatarCustomizationFShoesWinterboots0
	| AvatarCustomizationFShoesWinterboots1
	| AvatarCustomizationFShoesWinterboots2
	| AvatarCustomizationFShoesWinterboots3
	| AvatarCustomizationFSkin0
	| AvatarCustomizationFSkin1
	| AvatarCustomizationFSkin10
	| AvatarCustomizationFSkin11
	| AvatarCustomizationFSkin2
	| AvatarCustomizationFSkin3
	| AvatarCustomizationFSkin4
	| AvatarCustomizationFSkin5
	| AvatarCustomizationFSkin6
	| AvatarCustomizationFSkin7
	| AvatarCustomizationFSkin8
	| AvatarCustomizationFSkin9
	| AvatarCustomizationFSocksDefault0
	| AvatarCustomizationFSocksDefault1
	| AvatarCustomizationFSocksDefault2
	| AvatarCustomizationFSocksEmpty
	| AvatarCustomizationFSocksFw2022
	| AvatarCustomizationFSocksHgss0
	| AvatarCustomizationFSocksSneakersocks0
	| AvatarCustomizationFSocksSneakersocks1
	| AvatarCustomizationFSocksSollunaitems
	| AvatarCustomizationFSocksSwshuniformdefault
	| AvatarCustomizationFSocksSwshuniformdragon
	| AvatarCustomizationFSocksTeamaqua
	| AvatarCustomizationFSocksThighhighs0
	| AvatarCustomizationMBackpackAlolaitemslittenbp
	| AvatarCustomizationMBackpackAlolaitemspoppliobp
	| AvatarCustomizationMBackpackAlolaitemsrowletbp
	| AvatarCustomizationMBackpackAnimegou
	| AvatarCustomizationMBackpackBackpacker
	| AvatarCustomizationMBackpackCombeebackpack
	| AvatarCustomizationMBackpackCombeebackpack01
	| AvatarCustomizationMBackpackDedenneitems
	| AvatarCustomizationMBackpackDefault0
	| AvatarCustomizationMBackpackDefault1
	| AvatarCustomizationMBackpackDefault2
	| AvatarCustomizationMBackpackDefault3
	| AvatarCustomizationMBackpackDefault4
	| AvatarCustomizationMBackpackDefault5
	| AvatarCustomizationMBackpackDp
	| AvatarCustomizationMBackpackEggIncubator
	| AvatarCustomizationMBackpackEggbackpack0
	| AvatarCustomizationMBackpackEggbackpack1
	| AvatarCustomizationMBackpackEggbackpack2
	| AvatarCustomizationMBackpackEmpty
	| AvatarCustomizationMBackpackFrlg0
	| AvatarCustomizationMBackpackGenesecteventitem
	| AvatarCustomizationMBackpackGengar0
	| AvatarCustomizationMBackpackGiratinaitems
	| AvatarCustomizationMBackpackGuccibackpack
	| AvatarCustomizationMBackpackGuitarcasebackpack
	| AvatarCustomizationMBackpackHgss0
	| AvatarCustomizationMBackpackHououbackpack
	| AvatarCustomizationMBackpackKakureonpouch
	| AvatarCustomizationMBackpackKomala
	| AvatarCustomizationMBackpackLongchampbp
	| AvatarCustomizationMBackpackLunalaitems
	| AvatarCustomizationMBackpackLunarnewyr
	| AvatarCustomizationMBackpackMimikyubp
	| AvatarCustomizationMBackpackMovie2020
	| AvatarCustomizationMBackpackNaganadelawings
	| AvatarCustomizationMBackpackNike2021
	| AvatarCustomizationMBackpackPamobackpack
	| AvatarCustomizationMBackpackPkmnhoodie001
	| AvatarCustomizationMBackpackPkmnhoodie004
	| AvatarCustomizationMBackpackPkmnhoodie007
	| AvatarCustomizationMBackpackRuinmaniac
	| AvatarCustomizationMBackpackSnapcamera
	| AvatarCustomizationMBackpackSs
	| AvatarCustomizationMBackpackSvcostumescarletschool
	| AvatarCustomizationMBackpackSvcostumevioletschool
	| AvatarCustomizationMBackpackSvdlc1
	| AvatarCustomizationMBackpackSvdlc2spring
	| AvatarCustomizationMBackpackSwshdlc2costume
	| AvatarCustomizationMBackpackSwshdlccostume
	| AvatarCustomizationMBackpackTogepibackpack
	| AvatarCustomizationMBackpackUltra0
	| AvatarCustomizationMBackpackVerizon2021
	| AvatarCustomizationMBackpackZubatbp
	| AvatarCustomizationMEyes0
	| AvatarCustomizationMEyes1
	| AvatarCustomizationMEyes2
	| AvatarCustomizationMEyes3
	| AvatarCustomizationMEyes4
	| AvatarCustomizationMFace3dmask00
	| AvatarCustomizationMFace3dmask01
	| AvatarCustomizationMFace3dmask02
	| AvatarCustomizationMFaceBanettemask
	| AvatarCustomizationMFaceDayofthedead
	| AvatarCustomizationMFaceDefaultmask
	| AvatarCustomizationMFaceEmpty
	| AvatarCustomizationMFaceFacestickerghostpika
	| AvatarCustomizationMFaceFacestickerpikachu
	| AvatarCustomizationMFaceFacestickerpokeball
	| AvatarCustomizationMFaceFestofcolors00
	| AvatarCustomizationMFaceFestofcolors01
	| AvatarCustomizationMFaceFestofcolors02
	| AvatarCustomizationMFaceGracidea
	| AvatarCustomizationMFaceHoliday2022santacostumes
	| AvatarCustomizationMFacePikachumask
	| AvatarCustomizationMFaceSableyemask
	| AvatarCustomizationMFaceTeamskull
	| AvatarCustomizationMFaceToxelmask
	| AvatarCustomizationMFaceVerizon2020mask
	| AvatarCustomizationMGlasses3d
	| AvatarCustomizationMGlassesCutieflysleepmask
	| AvatarCustomizationMGlassesDivingsuit
	| AvatarCustomizationMGlassesDrpikachu
	| AvatarCustomizationMGlassesEmpty
	| AvatarCustomizationMGlassesFrillishglasses
	| AvatarCustomizationMGlassesFw2022
	| AvatarCustomizationMGlassesGimmighoulitems
	| AvatarCustomizationMGlassesGoteamrocketarlo
	| AvatarCustomizationMGlassesGrandoakglasses
	| AvatarCustomizationMGlassesJogger0
	| AvatarCustomizationMGlassesLugiaglasses
	| AvatarCustomizationMGlassesLv40glasses
	| AvatarCustomizationMGlassesMask0
	| AvatarCustomizationMGlassesMask1
	| AvatarCustomizationMGlassesNewyear2022
	| AvatarCustomizationMGlassesNewyearglasses2020
	| AvatarCustomizationMGlassesNewyearglasses2021
	| AvatarCustomizationMGlassesObstagoonitems
	| AvatarCustomizationMGlassesRoundsunglasses
	| AvatarCustomizationMGlassesTeardrop0
	| AvatarCustomizationMGlassesThick0
	| AvatarCustomizationMGlassesThick1
	| AvatarCustomizationMGlassesThick2
	| AvatarCustomizationMGlassesThick3
	| AvatarCustomizationMGlassesThick4
	| AvatarCustomizationMGlovesAcetrainersm
	| AvatarCustomizationMGlovesBea
	| AvatarCustomizationMGlovesBwn
	| AvatarCustomizationMGlovesDefault0
	| AvatarCustomizationMGlovesDefault1
	| AvatarCustomizationMGlovesDefault2
	| AvatarCustomizationMGlovesDefault3
	| AvatarCustomizationMGlovesDelibird
	| AvatarCustomizationMGlovesDynamaxswsh
	| AvatarCustomizationMGlovesEmpty
	| AvatarCustomizationMGlovesFrlg0
	| AvatarCustomizationMGlovesGeeta
	| AvatarCustomizationMGlovesGiovanni
	| AvatarCustomizationMGlovesGuzma
	| AvatarCustomizationMGlovesGymleader0
	| AvatarCustomizationMGlovesHoopabangle
	| AvatarCustomizationMGlovesJogger0
	| AvatarCustomizationMGlovesKorrina
	| AvatarCustomizationMGlovesLysandre
	| AvatarCustomizationMGlovesMegabangle
	| AvatarCustomizationMGlovesMegabangleblack
	| AvatarCustomizationMGlovesMegabangleblue
	| AvatarCustomizationMGlovesMegabanglered
	| AvatarCustomizationMGlovesMegabangleyellow
	| AvatarCustomizationMGlovesObstagoonitems
	| AvatarCustomizationMGlovesPalmer
	| AvatarCustomizationMGlovesProfwillowoutfit
	| AvatarCustomizationMGlovesStevenfirst
	| AvatarCustomizationMGlovesSvdlc2spring
	| AvatarCustomizationMGlovesSwshdlc2costume
	| AvatarCustomizationMGlovesSwshdlccostume
	| AvatarCustomizationMGlovesSwshuniformchampion
	| AvatarCustomizationMGlovesSwshuniformdark
	| AvatarCustomizationMGlovesSwshuniformdefault
	| AvatarCustomizationMGlovesSwshuniformdragon
	| AvatarCustomizationMGlovesTeamaqua
	| AvatarCustomizationMGlovesTeammagma
	| AvatarCustomizationMGlovesTeamrocket0
	| AvatarCustomizationMGlovesTeamspark
	| AvatarCustomizationMGlovesWintergloves2023
	| AvatarCustomizationMGofestPikachuvisor
	| AvatarCustomizationMHairDefault0
	| AvatarCustomizationMHairDefault1
	| AvatarCustomizationMHairDefault10
	| AvatarCustomizationMHairDefault11
	| AvatarCustomizationMHairDefault12
	| AvatarCustomizationMHairDefault13
	| AvatarCustomizationMHairDefault14
	| AvatarCustomizationMHairDefault15
	| AvatarCustomizationMHairDefault16
	| AvatarCustomizationMHairDefault17
	| AvatarCustomizationMHairDefault18
	| AvatarCustomizationMHairDefault19
	| AvatarCustomizationMHairDefault2
	| AvatarCustomizationMHairDefault3
	| AvatarCustomizationMHairDefault4
	| AvatarCustomizationMHairDefault5
	| AvatarCustomizationMHairDefault6
	| AvatarCustomizationMHairDefault7
	| AvatarCustomizationMHairDefault8
	| AvatarCustomizationMHairDefault9
	| AvatarCustomizationMHat6thanniversary
	| AvatarCustomizationMHatAcetrainersm
	| AvatarCustomizationMHatAdventure0
	| AvatarCustomizationMHatAseries
	| AvatarCustomizationMHatBea
	| AvatarCustomizationMHatBidoofhat
	| AvatarCustomizationMHatBounsweetitems
	| AvatarCustomizationMHatBurmyearrings11
	| AvatarCustomizationMHatBurmyearrings12
	| AvatarCustomizationMHatBurmyearrings13
	| AvatarCustomizationMHatBwn
	| AvatarCustomizationMHatCasket0
	| AvatarCustomizationMHatCetoddlehat
	| AvatarCustomizationMHatClay
	| AvatarCustomizationMHatCofagrigusitems
	| AvatarCustomizationMHatCosmog
	| AvatarCustomizationMHatCrownmoon
	| AvatarCustomizationMHatCrownsun
	| AvatarCustomizationMHatCubonehat
	| AvatarCustomizationMHatDarumakahat
	| AvatarCustomizationMHatDedenneitems
	| AvatarCustomizationMHatDefault0
	| AvatarCustomizationMHatDefault1
	| AvatarCustomizationMHatDefault2
	| AvatarCustomizationMHatDefault3
	| AvatarCustomizationMHatDefault4
	| AvatarCustomizationMHatDefault5
	| AvatarCustomizationMHatDeino
	| AvatarCustomizationMHatDelibird
	| AvatarCustomizationMHatDetectivepikachu
	| AvatarCustomizationMHatDiancie
	| AvatarCustomizationMHatDp
	| AvatarCustomizationMHatDrifloon0
	| AvatarCustomizationMHatDrpikachu
	| AvatarCustomizationMHatDusclopsmummy
	| AvatarCustomizationMHatEeveecap
	| AvatarCustomizationMHatElesa
	| AvatarCustomizationMHatEmpty
	| AvatarCustomizationMHatFedora0
	| AvatarCustomizationMHatFedora1
	| AvatarCustomizationMHatFisher0
	| AvatarCustomizationMHatFlabebepack
	| AvatarCustomizationMHatFragment0
	| AvatarCustomizationMHatFrlg0
	| AvatarCustomizationMHatFurfrouwig
	| AvatarCustomizationMHatFw2022
	| AvatarCustomizationMHatGalarfarfetchditems
	| AvatarCustomizationMHatGenesecteventitem
	| AvatarCustomizationMHatGengar0
	| AvatarCustomizationMHatGimmighoulitems
	| AvatarCustomizationMHatGiratinaitems
	| AvatarCustomizationMHatGladion
	| AvatarCustomizationMHatGoomy
	| AvatarCustomizationMHatGreavardwig
	| AvatarCustomizationMHatGreencoat
	| AvatarCustomizationMHatGrowlithehelmet
	| AvatarCustomizationMHatGtr2024eeveefanmask
	| AvatarCustomizationMHatGtr2024pikachufanmask
	| AvatarCustomizationMHatGuccihat
	| AvatarCustomizationMHatGuzma
	| AvatarCustomizationMHatGyaradoscap
	| AvatarCustomizationMHatHgss0
	| AvatarCustomizationMHatHoliday2022santacostumes
	| AvatarCustomizationMHatHolidaybeanie
	| AvatarCustomizationMHatHoopaearmuffs
	| AvatarCustomizationMHatIngo
	| AvatarCustomizationMHatJogger0
	| AvatarCustomizationMHatKantotourcapgreen
	| AvatarCustomizationMHatKantotourcapred
	| AvatarCustomizationMHatKorrina
	| AvatarCustomizationMHatLana
	| AvatarCustomizationMHatLaprasbandana
	| AvatarCustomizationMHatLasecuritycorps
	| AvatarCustomizationMHatLegendofarceus
	| AvatarCustomizationMHatLitwickhat
	| AvatarCustomizationMHatLoneearrings
	| AvatarCustomizationMHatLvl50cap
	| AvatarCustomizationMHatMagikarp
	| AvatarCustomizationMHatMareaniehat
	| AvatarCustomizationMHatMegalopunnyitems
	| AvatarCustomizationMHatMegarayquaza
	| AvatarCustomizationMHatMeltan
	| AvatarCustomizationMHatMewtwo
	| AvatarCustomizationMHatMimikyu0
	| AvatarCustomizationMHatMismagius0
	| AvatarCustomizationMHatMovie2020
	| AvatarCustomizationMHatMunnapack0
	| AvatarCustomizationMHatMunnapack1
	| AvatarCustomizationMHatNewyear2022
	| AvatarCustomizationMHatNewyearhat2021
	| AvatarCustomizationMHatNewyearhat2023
	| AvatarCustomizationMHatNihilegoitems
	| AvatarCustomizationMHatNoibat
	| AvatarCustomizationMHatObstagoonitems
	| AvatarCustomizationMHatOras
	| AvatarCustomizationMHatOricoriopink
	| AvatarCustomizationMHatOricoriopurple
	| AvatarCustomizationMHatOricoriored
	| AvatarCustomizationMHatOricorioyellow
	| AvatarCustomizationMHatPartneritemsjan2024hat
	| AvatarCustomizationMHatPhantump
	| AvatarCustomizationMHatPikachucap
	| AvatarCustomizationMHatPikachufan0
	| AvatarCustomizationMHatPikachulibre
	| AvatarCustomizationMHatPikachupumpkinhead
	| AvatarCustomizationMHatPkmncap0
	| AvatarCustomizationMHatPkmncap1
	| AvatarCustomizationMHatPkmncap2
	| AvatarCustomizationMHatPoipole
	| AvatarCustomizationMHatProfwillowoutfit
	| AvatarCustomizationMHatRegiicejersies
	| AvatarCustomizationMHatRegirockjersies
	| AvatarCustomizationMHatRegisteeljersies
	| AvatarCustomizationMHatRuinmaniac
	| AvatarCustomizationMHatSableyegoggles
	| AvatarCustomizationMHatSamsungsummer2020
	| AvatarCustomizationMHatSandygasthat
	| AvatarCustomizationMHatShayminhat
	| AvatarCustomizationMHatSlowpoketailshirts
	| AvatarCustomizationMHatSnorlaxnightcap
	| AvatarCustomizationMHatSolgaleoitems
	| AvatarCustomizationMHatSs
	| AvatarCustomizationMHatStantlerheadband
	| AvatarCustomizationMHatStrawhat
	| AvatarCustomizationMHatSummer2023
	| AvatarCustomizationMHatSvcostumescarletschool
	| AvatarCustomizationMHatSvcostumevioletschool
	| AvatarCustomizationMHatSwshdlc2costume
	| AvatarCustomizationMHatSwshuniformchampion
	| AvatarCustomizationMHatSylveonitems
	| AvatarCustomizationMHatTcgcollabtshirtandcap
	| AvatarCustomizationMHatTeamaqua
	| AvatarCustomizationMHatTeamleadercap0
	| AvatarCustomizationMHatTeamleadercap1
	| AvatarCustomizationMHatTeamleadercap2
	| AvatarCustomizationMHatTeamrocket0
	| AvatarCustomizationMHatTeamrocketcap
	| AvatarCustomizationMHatTeamskull
	| AvatarCustomizationMHatTophat0
	| AvatarCustomizationMHatUltrareconsquad
	| AvatarCustomizationMHatUltrareconsquadb
	| AvatarCustomizationMHatUltra0
	| AvatarCustomizationMHatVerizon2021
	| AvatarCustomizationMHatWcs2022winnersitems
	| AvatarCustomizationMHatWhimsicottearmuff
	| AvatarCustomizationMHatWillowglasses
	| AvatarCustomizationMHatWoobatearrings
	| AvatarCustomizationMHatYamaskhat
	| AvatarCustomizationMHatYamaskmask
	| AvatarCustomizationMHatZubathat
	| AvatarCustomizationMJacketNewyear2022
	| AvatarCustomizationMPants6thanniversary
	| AvatarCustomizationMPants7thanniversary
	| AvatarCustomizationMPantsAcetrainerbw
	| AvatarCustomizationMPantsAcetrainersm
	| AvatarCustomizationMPantsAnimegou
	| AvatarCustomizationMPantsBackpacker
	| AvatarCustomizationMPantsBounsweetitems
	| AvatarCustomizationMPantsBrock
	| AvatarCustomizationMPantsBwn
	| AvatarCustomizationMPantsCasual0
	| AvatarCustomizationMPantsCasual1
	| AvatarCustomizationMPantsClay
	| AvatarCustomizationMPantsDefault0
	| AvatarCustomizationMPantsDenimfashionweek2023
	| AvatarCustomizationMPantsDp
	| AvatarCustomizationMPantsElesa
	| AvatarCustomizationMPantsFashionweek2022
	| AvatarCustomizationMPantsFisher0
	| AvatarCustomizationMPantsFlabebepack
	| AvatarCustomizationMPantsFrlg0
	| AvatarCustomizationMPantsFw2022
	| AvatarCustomizationMPantsGeeta
	| AvatarCustomizationMPantsGenderlessskirt
	| AvatarCustomizationMPantsGiovanni
	| AvatarCustomizationMPantsGladion
	| AvatarCustomizationMPantsGothitelleitems
	| AvatarCustomizationMPantsGreen
	| AvatarCustomizationMPantsGreencoat
	| AvatarCustomizationMPantsGuzma
	| AvatarCustomizationMPantsGymleader0
	| AvatarCustomizationMPantsGymleader1
	| AvatarCustomizationMPantsGymleader2
	| AvatarCustomizationMPantsHala
	| AvatarCustomizationMPantsHgss0
	| AvatarCustomizationMPantsIngo
	| AvatarCustomizationMPantsJogger0
	| AvatarCustomizationMPantsKorrina
	| AvatarCustomizationMPantsLoosepants
	| AvatarCustomizationMPantsLunalaitems
	| AvatarCustomizationMPantsLuvdiscpack
	| AvatarCustomizationMPantsLysandre
	| AvatarCustomizationMPantsMewtwo
	| AvatarCustomizationMPantsMunnapack
	| AvatarCustomizationMPantsNewyear2022
	| AvatarCustomizationMPantsOras
	| AvatarCustomizationMPantsPajamas20220
	| AvatarCustomizationMPantsPajamas20221
	| AvatarCustomizationMPantsPalmer
	| AvatarCustomizationMPantsPikachufan0
	| AvatarCustomizationMPantsPikachulibre
	| AvatarCustomizationMPantsProfwillowoutfit
	| AvatarCustomizationMPantsPumpkabooitems
	| AvatarCustomizationMPantsRegiicejersies
	| AvatarCustomizationMPantsRegirockjersies
	| AvatarCustomizationMPantsRegisteeljersies
	| AvatarCustomizationMPantsSkinnyjeans0
	| AvatarCustomizationMPantsSkinnyjeans1
	| AvatarCustomizationMPantsSkinnyjeans2
	| AvatarCustomizationMPantsSs
	| AvatarCustomizationMPantsSteven
	| AvatarCustomizationMPantsStevenfirst
	| AvatarCustomizationMPantsSweats0
	| AvatarCustomizationMPantsSweats1
	| AvatarCustomizationMPantsSweats2
	| AvatarCustomizationMPantsSweats3
	| AvatarCustomizationMPantsSweats4
	| AvatarCustomizationMPantsSwshdlc2costume
	| AvatarCustomizationMPantsSwshuniformchampion
	| AvatarCustomizationMPantsSwshuniformdark
	| AvatarCustomizationMPantsSwshuniformdefault
	| AvatarCustomizationMPantsSwshuniformdragon
	| AvatarCustomizationMPantsTeamaqua
	| AvatarCustomizationMPantsTeamblanche
	| AvatarCustomizationMPantsTeamcandela
	| AvatarCustomizationMPantsTeammagma
	| AvatarCustomizationMPantsTeamrocket0
	| AvatarCustomizationMPantsTeamskull
	| AvatarCustomizationMPantsTeamspark
	| AvatarCustomizationMPantsUltra0
	| AvatarCustomizationMPantsVeterantrainerxy
	| AvatarCustomizationMPantsWcs2022winnersitems
	| AvatarCustomizationMPose01
	| AvatarCustomizationMPose02
	| AvatarCustomizationMPose03
	| AvatarCustomizationMPose04
	| AvatarCustomizationMPose05
	| AvatarCustomizationMPose06
	| AvatarCustomizationMPose07
	| AvatarCustomizationMPose08
	| AvatarCustomizationMPose09
	| AvatarCustomizationMPose10
	| AvatarCustomizationMPose11
	| AvatarCustomizationMPose12
	| AvatarCustomizationMPose13
	| AvatarCustomizationMPose14
	| AvatarCustomizationMPose15
	| AvatarCustomizationMPose16
	| AvatarCustomizationMPose17
	| AvatarCustomizationMPose18
	| AvatarCustomizationMPose19
	| AvatarCustomizationMPose20
	| AvatarCustomizationMPose21
	| AvatarCustomizationMPose22
	| AvatarCustomizationMPose23
	| AvatarCustomizationMPose24
	| AvatarCustomizationMPose25
	| AvatarCustomizationMPose26
	| AvatarCustomizationMPose27
	| AvatarCustomizationMPose28
	| AvatarCustomizationMPose29
	| AvatarCustomizationMPose30
	| AvatarCustomizationMPose31
	| AvatarCustomizationMPose32
	| AvatarCustomizationMPose33
	| AvatarCustomizationMPose34
	| AvatarCustomizationMPose35
	| AvatarCustomizationMPose36
	| AvatarCustomizationMPose37
	| AvatarCustomizationMPose38
	| AvatarCustomizationMPose39
	| AvatarCustomizationMPose40
	| AvatarCustomizationMPose41
	| AvatarCustomizationMPose43
	| AvatarCustomizationMPose44
	| AvatarCustomizationMPose45
	| AvatarCustomizationMPose46
	| AvatarCustomizationMPose47
	| AvatarCustomizationMPose48
	| AvatarCustomizationMPose49
	| AvatarCustomizationMPose50
	| AvatarCustomizationMPose51
	| AvatarCustomizationMPose52
	| AvatarCustomizationMPose53
	| AvatarCustomizationMPose54
	| AvatarCustomizationMPose55
	| AvatarCustomizationMPose56
	| AvatarCustomizationMPose57
	| AvatarCustomizationMPose58
	| AvatarCustomizationMPose59
	| AvatarCustomizationMPose60
	| AvatarCustomizationMPose61
	| AvatarCustomizationMPose62
	| AvatarCustomizationMPose63
	| AvatarCustomizationMPose64
	| AvatarCustomizationMPoseEmpty
	| AvatarCustomizationMShirt6thanniversary
	| AvatarCustomizationMShirt7thanniversary
	| AvatarCustomizationMShirtAcetrainerbw
	| AvatarCustomizationMShirtAcetrainersm
	| AvatarCustomizationMShirtAlolacomfey
	| AvatarCustomizationMShirtAnimegou
	| AvatarCustomizationMShirtAseries
	| AvatarCustomizationMShirtBackpacker
	| AvatarCustomizationMShirtBallguy
	| AvatarCustomizationMShirtBea
	| AvatarCustomizationMShirtBlazer0
	| AvatarCustomizationMShirtBounsweetitems
	| AvatarCustomizationMShirtBrock
	| AvatarCustomizationMShirtBuzzwoleitems
	| AvatarCustomizationMShirtBwn
	| AvatarCustomizationMShirtCasual0
	| AvatarCustomizationMShirtCasual1
	| AvatarCustomizationMShirtCasual2
	| AvatarCustomizationMShirtCasual3
	| AvatarCustomizationMShirtCelebi0
	| AvatarCustomizationMShirtChimcharonesie
	| AvatarCustomizationMShirtClay
	| AvatarCustomizationMShirtCofagrigusitems
	| AvatarCustomizationMShirtCosmog
	| AvatarCustomizationMShirtCowichansweater
	| AvatarCustomizationMShirtDayofdead
	| AvatarCustomizationMShirtDefault0
	| AvatarCustomizationMShirtDefault1
	| AvatarCustomizationMShirtDefault2
	| AvatarCustomizationMShirtDefault2b
	| AvatarCustomizationMShirtDefault3
	| AvatarCustomizationMShirtDefault4
	| AvatarCustomizationMShirtDefault5
	| AvatarCustomizationMShirtDefault6
	| AvatarCustomizationMShirtDefault7
	| AvatarCustomizationMShirtDelibird
	| AvatarCustomizationMShirtDelibirdonesie
	| AvatarCustomizationMShirtDenimfashionweek2023
	| AvatarCustomizationMShirtDenimjacket
	| AvatarCustomizationMShirtDetectivepikachu
	| AvatarCustomizationMShirtDiancie
	| AvatarCustomizationMShirtDivingsuit
	| AvatarCustomizationMShirtDiwali2021
	| AvatarCustomizationMShirtDp
	| AvatarCustomizationMShirtDrifblim0
	| AvatarCustomizationMShirtDusclopsmummy
	| AvatarCustomizationMShirtEarthday2018
	| AvatarCustomizationMShirtEeveestshirt00
	| AvatarCustomizationMShirtEeveestshirt01
	| AvatarCustomizationMShirtEeveestshirt02
	| AvatarCustomizationMShirtEeveestshirt03
	| AvatarCustomizationMShirtEeveestshirt04
	| AvatarCustomizationMShirtEeveestshirt05
	| AvatarCustomizationMShirtEeveestshirt06
	| AvatarCustomizationMShirtEeveestshirt07
	| AvatarCustomizationMShirtEeveestshirt08
	| AvatarCustomizationMShirtElesa
	| AvatarCustomizationMShirtFashionweek2022
	| AvatarCustomizationMShirtFestivaloflights00
	| AvatarCustomizationMShirtFestivaloflights01
	| AvatarCustomizationMShirtFisher0
	| AvatarCustomizationMShirtFlabebepack
	| AvatarCustomizationMShirtFragment0
	| AvatarCustomizationMShirtFrlg0
	| AvatarCustomizationMShirtFw2022
	| AvatarCustomizationMShirtGalarfarfetchditems
	| AvatarCustomizationMShirtGalaxyoutfit
	| AvatarCustomizationMShirtGeeta
	| AvatarCustomizationMShirtGenderlessskirt
	| AvatarCustomizationMShirtGengar0
	| AvatarCustomizationMShirtGengaronesie
	| AvatarCustomizationMShirtGiovanni
	| AvatarCustomizationMShirtGiratinaitems
	| AvatarCustomizationMShirtGladion
	| AvatarCustomizationMShirtGofest2022
	| AvatarCustomizationMShirtGofest2023
	| AvatarCustomizationMShirtGofest2024darkgray
	| AvatarCustomizationMShirtGofest2024gray
	| AvatarCustomizationMShirtGofest2024purple
	| AvatarCustomizationMShirtGofest2019
	| AvatarCustomizationMShirtGofest2020
	| AvatarCustomizationMShirtGofest2021
	| AvatarCustomizationMShirtGofestglobal2023
	| AvatarCustomizationMShirtGoteamrocketarlo
	| AvatarCustomizationMShirtGoteamrocketcliff
	| AvatarCustomizationMShirtGoteamrocketsierra
	| AvatarCustomizationMShirtGothitelleitems
	| AvatarCustomizationMShirtGotour2023
	| AvatarCustomizationMShirtGotour2024
	| AvatarCustomizationMShirtGreedentsweater
	| AvatarCustomizationMShirtGreen
	| AvatarCustomizationMShirtGreencoat
	| AvatarCustomizationMShirtGtrtshirt202200
	| AvatarCustomizationMShirtGtrtshirt202201
	| AvatarCustomizationMShirtGuccitshirts
	| AvatarCustomizationMShirtGuzma
	| AvatarCustomizationMShirtGymleader0
	| AvatarCustomizationMShirtGymleader1
	| AvatarCustomizationMShirtGymleader2
	| AvatarCustomizationMShirtHala
	| AvatarCustomizationMShirtHappi
	| AvatarCustomizationMShirtHappi1
	| AvatarCustomizationMShirtHappi2
	| AvatarCustomizationMShirtHgss0
	| AvatarCustomizationMShirtHoliday2022santacostumes
	| AvatarCustomizationMShirtHolifestival2021black
	| AvatarCustomizationMShirtHolifestival2021white
	| AvatarCustomizationMShirtHoopaunboundtshirt
	| AvatarCustomizationMShirtIngo
	| AvatarCustomizationMShirtIngress0
	| AvatarCustomizationMShirtIngressE0
	| AvatarCustomizationMShirtIngressR0
	| AvatarCustomizationMShirtJames
	| AvatarCustomizationMShirtJirachi
	| AvatarCustomizationMShirtJogger0
	| AvatarCustomizationMShirtKeldeotshirt
	| AvatarCustomizationMShirtKorrina
	| AvatarCustomizationMShirtLadiamondoutfit
	| AvatarCustomizationMShirtLana
	| AvatarCustomizationMShirtLapearloutfit
	| AvatarCustomizationMShirtLasecuritycorps
	| AvatarCustomizationMShirtLatiasLatios0
	| AvatarCustomizationMShirtLegendofarceus
	| AvatarCustomizationMShirtLongsleevesCharizard0
	| AvatarCustomizationMShirtLongsleevesCharizard1
	| AvatarCustomizationMShirtLongsleevesCharizard2
	| AvatarCustomizationMShirtLongsleevesPikachu0
	| AvatarCustomizationMShirtLongsleevesPikachu1
	| AvatarCustomizationMShirtLongsleevesPikachu2
	| AvatarCustomizationMShirtLuvdiscpack
	| AvatarCustomizationMShirtLvl50
	| AvatarCustomizationMShirtLvl501
	| AvatarCustomizationMShirtLysandre
	| AvatarCustomizationMShirtMarshadowtshirt
	| AvatarCustomizationMShirtMegalopunnyitems
	| AvatarCustomizationMShirtMegarayquaza
	| AvatarCustomizationMShirtMelmetaljacket
	| AvatarCustomizationMShirtMelmetalvest
	| AvatarCustomizationMShirtMeloettatshirt
	| AvatarCustomizationMShirtMeltan
	| AvatarCustomizationMShirtMew0
	| AvatarCustomizationMShirtMewtwo
	| AvatarCustomizationMShirtMovie2020jessiejames
	| AvatarCustomizationMShirtMunnapack
	| AvatarCustomizationMShirtNike2021
	| AvatarCustomizationMShirtOcshirt045
	| AvatarCustomizationMShirtOcshirt108
	| AvatarCustomizationMShirtOcshirt129
	| AvatarCustomizationMShirtOcshirt143
	| AvatarCustomizationMShirtOras
	| AvatarCustomizationMShirtPajamas20220
	| AvatarCustomizationMShirtPajamas20221
	| AvatarCustomizationMShirtPalmer
	| AvatarCustomizationMShirtPartneritemsjan2024hoodie
	| AvatarCustomizationMShirtPartneritemsjan2024tshirt
	| AvatarCustomizationMShirtPikachufan0
	| AvatarCustomizationMShirtPikachulibre
	| AvatarCustomizationMShirtPikachuonesie
	| AvatarCustomizationMShirtPinpukuhoodie
	| AvatarCustomizationMShirtPipluponesie
	| AvatarCustomizationMShirtPkmnhoodie001
	| AvatarCustomizationMShirtPkmnhoodie004
	| AvatarCustomizationMShirtPkmnhoodie007
	| AvatarCustomizationMShirtPkmnshirts202100
	| AvatarCustomizationMShirtPkmnshirts202101
	| AvatarCustomizationMShirtPkmnshirts202102
	| AvatarCustomizationMShirtPkmnshirts165
	| AvatarCustomizationMShirtPkmnshirts188
	| AvatarCustomizationMShirtPkmnshirts201
	| AvatarCustomizationMShirtPkmnshirts238
	| AvatarCustomizationMShirtPoloshirt
	| AvatarCustomizationMShirtPoloshirt1
	| AvatarCustomizationMShirtPoloshirt2
	| AvatarCustomizationMShirtProfwillowoutfit
	| AvatarCustomizationMShirtProjectguitar
	| AvatarCustomizationMShirtPumpkabooitems
	| AvatarCustomizationMShirtRegiicejersies
	| AvatarCustomizationMShirtRegirockjersies
	| AvatarCustomizationMShirtRegisteeljersies
	| AvatarCustomizationMShirtReuniclusitems
	| AvatarCustomizationMShirtRuinmaniac
	| AvatarCustomizationMShirtSafarizone2020
	| AvatarCustomizationMShirtSamsungsummer2020
	| AvatarCustomizationMShirtShayminlandtshirt
	| AvatarCustomizationMShirtShayminskytshirt
	| AvatarCustomizationMShirtShinymewtshirts
	| AvatarCustomizationMShirtSlowpokeshirts
	| AvatarCustomizationMShirtSlowpoketailshirts
	| AvatarCustomizationMShirtSnorlaxonesie
	| AvatarCustomizationMShirtSpiritomb0
	| AvatarCustomizationMShirtSpring2021gulpin
	| AvatarCustomizationMShirtSpring2021plusle
	| AvatarCustomizationMShirtSs
	| AvatarCustomizationMShirtSteven
	| AvatarCustomizationMShirtStevenfirst
	| AvatarCustomizationMShirtSukajanblastoise
	| AvatarCustomizationMShirtSukajancharizard
	| AvatarCustomizationMShirtSukajanhouou
	| AvatarCustomizationMShirtSukajanlugia
	| AvatarCustomizationMShirtSukajanvenusaur
	| AvatarCustomizationMShirtSummer2023
	| AvatarCustomizationMShirtSustainability2021
	| AvatarCustomizationMShirtSvcostumescarletschool
	| AvatarCustomizationMShirtSvcostumevioletschool
	| AvatarCustomizationMShirtSvdlc1
	| AvatarCustomizationMShirtSvdlc2fall
	| AvatarCustomizationMShirtSvdlc2spring
	| AvatarCustomizationMShirtSweatshirtSporty0
	| AvatarCustomizationMShirtSweatshirtSporty1
	| AvatarCustomizationMShirtSweatshirtSporty2
	| AvatarCustomizationMShirtSweatshirtSporty3
	| AvatarCustomizationMShirtSweatshirtStreak0
	| AvatarCustomizationMShirtSweatshirtStreak1
	| AvatarCustomizationMShirtSweatshirtStreak2
	| AvatarCustomizationMShirtSweatshirtStreak3
	| AvatarCustomizationMShirtSweatshirtStreak4
	| AvatarCustomizationMShirtSwshdlc2costume
	| AvatarCustomizationMShirtSwshdlccostume
	| AvatarCustomizationMShirtSwshuniformchampion
	| AvatarCustomizationMShirtSwshuniformdark
	| AvatarCustomizationMShirtSwshuniformdefault
	| AvatarCustomizationMShirtSwshuniformdragon
	| AvatarCustomizationMShirtSylveonitems
	| AvatarCustomizationMShirtTcgcollabtshirtandcap
	| AvatarCustomizationMShirtTeamaqua
	| AvatarCustomizationMShirtTeamblanche
	| AvatarCustomizationMShirtTeamcandela
	| AvatarCustomizationMShirtTeammagma
	| AvatarCustomizationMShirtTeamrocket0
	| AvatarCustomizationMShirtTeamrocket1
	| AvatarCustomizationMShirtTeamskull
	| AvatarCustomizationMShirtTeamspark
	| AvatarCustomizationMShirtTogepihoodie
	| AvatarCustomizationMShirtTracksuitsgroudon
	| AvatarCustomizationMShirtTracksuitskyogre
	| AvatarCustomizationMShirtTshirtFestChicago2017
	| AvatarCustomizationMShirtTshirtFestChicago2018
	| AvatarCustomizationMShirtTshirtGeometric0
	| AvatarCustomizationMShirtTshirtGeometric1
	| AvatarCustomizationMShirtTshirtGeometric2
	| AvatarCustomizationMShirtTshirtGlobalGoals2017
	| AvatarCustomizationMShirtTshirtInstinct
	| AvatarCustomizationMShirtTshirtMystic
	| AvatarCustomizationMShirtTshirtValor
	| AvatarCustomizationMShirtTurtleneck300
	| AvatarCustomizationMShirtTurtleneck301
	| AvatarCustomizationMShirtTurtleneck302
	| AvatarCustomizationMShirtTurtleneck303
	| AvatarCustomizationMShirtTurtwigonesie
	| AvatarCustomizationMShirtUltrareconsquad
	| AvatarCustomizationMShirtUltra0
	| AvatarCustomizationMShirtUniqlotshirts0
	| AvatarCustomizationMShirtUniqlotshirts1
	| AvatarCustomizationMShirtUniqlotshirts2
	| AvatarCustomizationMShirtUnwto
	| AvatarCustomizationMShirtValentine2023
	| AvatarCustomizationMShirtVerizon2020
	| AvatarCustomizationMShirtVeterantrainerxy
	| AvatarCustomizationMShirtVictinitshirts
	| AvatarCustomizationMShirtWcs2022
	| AvatarCustomizationMShirtWcs2022tshirtbulu
	| AvatarCustomizationMShirtWcs2022tshirtred
	| AvatarCustomizationMShirtWcs2022winnersitems
	| AvatarCustomizationMShirtWcs2023
	| AvatarCustomizationMShirtWcs2023promotshirt
	| AvatarCustomizationMShirtWcs2023promotshirt01
	| AvatarCustomizationMShirtWcs2023sukajan
	| AvatarCustomizationMShirtWcs2023winnersitems
	| AvatarCustomizationMShirtWcs2024
	| AvatarCustomizationMShirtWcs2024championshipshirtBlue
	| AvatarCustomizationMShirtWcs2024championshipshirtWhite
	| AvatarCustomizationMShirtWcsyokohama
	| AvatarCustomizationMShirtWhitecoat
	| AvatarCustomizationMShirtWintersweater2023
	| AvatarCustomizationMShirtZoruaonesie
	| AvatarCustomizationMShoes6thanniversary
	| AvatarCustomizationMShoesAcetrainerbw
	| AvatarCustomizationMShoesAcetrainersm
	| AvatarCustomizationMShoesAnimegou
	| AvatarCustomizationMShoesBackpacker
	| AvatarCustomizationMShoesBrock
	| AvatarCustomizationMShoesBwn
	| AvatarCustomizationMShoesCarbink
	| AvatarCustomizationMShoesClay
	| AvatarCustomizationMShoesCoolboots
	| AvatarCustomizationMShoesDedenneitems
	| AvatarCustomizationMShoesDefault0
	| AvatarCustomizationMShoesDefault1
	| AvatarCustomizationMShoesDefault2
	| AvatarCustomizationMShoesDefault3
	| AvatarCustomizationMShoesDefault4
	| AvatarCustomizationMShoesDefault5
	| AvatarCustomizationMShoesDefault6
	| AvatarCustomizationMShoesDelibird
	| AvatarCustomizationMShoesDp
	| AvatarCustomizationMShoesElesa
	| AvatarCustomizationMShoesEmpty
	| AvatarCustomizationMShoesFashionweek2022
	| AvatarCustomizationMShoesFisher0
	| AvatarCustomizationMShoesFrlg0
	| AvatarCustomizationMShoesFw2022
	| AvatarCustomizationMShoesGeeta
	| AvatarCustomizationMShoesGiovanni
	| AvatarCustomizationMShoesGladion
	| AvatarCustomizationMShoesGothitelleitems
	| AvatarCustomizationMShoesGreen
	| AvatarCustomizationMShoesGymleader0
	| AvatarCustomizationMShoesGymleader1
	| AvatarCustomizationMShoesGymleader2
	| AvatarCustomizationMShoesHala
	| AvatarCustomizationMShoesHgss0
	| AvatarCustomizationMShoesIngo
	| AvatarCustomizationMShoesJogger0
	| AvatarCustomizationMShoesKorrina
	| AvatarCustomizationMShoesLadiamondoutfit
	| AvatarCustomizationMShoesLana
	| AvatarCustomizationMShoesLapearloutfit
	| AvatarCustomizationMShoesLegendofarceus
	| AvatarCustomizationMShoesLoosepants
	| AvatarCustomizationMShoesLoosepants1
	| AvatarCustomizationMShoesLoosepants2
	| AvatarCustomizationMShoesLoosepants3
	| AvatarCustomizationMShoesLuvdiscpack
	| AvatarCustomizationMShoesLysandre
	| AvatarCustomizationMShoesMegalopunnyitems
	| AvatarCustomizationMShoesMelmetalshoes
	| AvatarCustomizationMShoesMewtwo
	| AvatarCustomizationMShoesNewyear2022
	| AvatarCustomizationMShoesNike2021
	| AvatarCustomizationMShoesOras
	| AvatarCustomizationMShoesPajamas20220
	| AvatarCustomizationMShoesPajamas20221
	| AvatarCustomizationMShoesPalmer
	| AvatarCustomizationMShoesPikachufan0
	| AvatarCustomizationMShoesPikachulibre
	| AvatarCustomizationMShoesProfwillowoutfit
	| AvatarCustomizationMShoesRegiicejersies
	| AvatarCustomizationMShoesRegirockjersies
	| AvatarCustomizationMShoesRegisteeljersies
	| AvatarCustomizationMShoesReuniclusitems
	| AvatarCustomizationMShoesRuinmaniac
	| AvatarCustomizationMShoesSandals
	| AvatarCustomizationMShoesSandals1
	| AvatarCustomizationMShoesSandals2
	| AvatarCustomizationMShoesSolgaleoitems
	| AvatarCustomizationMShoesSs
	| AvatarCustomizationMShoesSteven
	| AvatarCustomizationMShoesStevenfirst
	| AvatarCustomizationMShoesSvcostumescarletschool
	| AvatarCustomizationMShoesSvcostumevioletschool
	| AvatarCustomizationMShoesSvdlc1
	| AvatarCustomizationMShoesSvdlc2spring
	| AvatarCustomizationMShoesSwshdlc2costume
	| AvatarCustomizationMShoesSwshdlccostume
	| AvatarCustomizationMShoesSwshuniformdark
	| AvatarCustomizationMShoesSwshuniformdefault
	| AvatarCustomizationMShoesSwshuniformdragon
	| AvatarCustomizationMShoesSylveonitems
	| AvatarCustomizationMShoesTeamaqua
	| AvatarCustomizationMShoesTeamblanche
	| AvatarCustomizationMShoesTeamcandela
	| AvatarCustomizationMShoesTeammagma
	| AvatarCustomizationMShoesTeamrocket0
	| AvatarCustomizationMShoesTeamrocket1
	| AvatarCustomizationMShoesTeamskull
	| AvatarCustomizationMShoesTeamspark
	| AvatarCustomizationMShoesUltrareconsquad
	| AvatarCustomizationMShoesUltra0
	| AvatarCustomizationMShoesVeterantrainerxy
	| AvatarCustomizationMShoesWcs2022winnersitems
	| AvatarCustomizationMShoesWcs2023winnersitems
	| AvatarCustomizationMShoesWinterboots2023
	| AvatarCustomizationMShoesWinterboots0
	| AvatarCustomizationMShoesWinterboots1
	| AvatarCustomizationMShoesWinterboots2
	| AvatarCustomizationMShoesWinterboots3
	| AvatarCustomizationMSkin0
	| AvatarCustomizationMSkin1
	| AvatarCustomizationMSkin10
	| AvatarCustomizationMSkin11
	| AvatarCustomizationMSkin2
	| AvatarCustomizationMSkin3
	| AvatarCustomizationMSkin4
	| AvatarCustomizationMSkin5
	| AvatarCustomizationMSkin6
	| AvatarCustomizationMSkin7
	| AvatarCustomizationMSkin8
	| AvatarCustomizationMSkin9
	| AvatarCustomizationMSocksDefault0
	| AvatarCustomizationMSocksDefault1
	| AvatarCustomizationMSocksDefault2
	| AvatarCustomizationMSocksDefault3
	| AvatarCustomizationMSocksEmpty
	| AvatarCustomizationMSocksFw2022
	| AvatarCustomizationMSocksSneakersocks0
	| AvatarCustomizationMSocksSneakersocks1
	| AvatarCustomizationMSocksSollunaitems
	| AvatarCustomizationMSocksSwshuniformdefault
	| AvatarCustomizationMSocksSwshuniformdragon;

export type AvatarCustomizationTemplateID = AvatarCustomizationMasterfileEntry["templateId"];
