// Generated from Pokémon GO masterfile — group "avatarItemDisplay", 1636 entries (structural types).

export type * from "./variants";

export interface AvatarItemDisplay<TemplateID extends string = string, TData extends AvatarItemDisplayData = AvatarItemDisplayData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		avatarItemDisplay: TData;
	};
}

export interface AvatarItemDisplayData {
	displayStringId?: string;
	iconAddress: string;
}

export type AvatarItemDisplayMasterfileEntry =
	| AvatarItemDisplayMBackpackEggbackpack0
	| AvatarItemDisplayMBackpackEggbackpack1
	| AvatarItemDisplayMBackpackEggbackpack2
	| AvatarItemDisplayNBackpackAlolaitemslittenbp0
	| AvatarItemDisplayNBackpackAlolaitemspoppliobp0
	| AvatarItemDisplayNBackpackAlolaitemsrowletbp0
	| AvatarItemDisplayNBackpackAnimegou0
	| AvatarItemDisplayNBackpackBackpacker0
	| AvatarItemDisplayNBackpackBlackkyuremitem0
	| AvatarItemDisplayNBackpackCharjabug0
	| AvatarItemDisplayNBackpackClemont0
	| AvatarItemDisplayNBackpackCombeebackpack0
	| AvatarItemDisplayNBackpackCombeebackpack1
	| AvatarItemDisplayNBackpackCute0
	| AvatarItemDisplayNBackpackDedenneitems0
	| AvatarItemDisplayNBackpackDefaultNew0
	| AvatarItemDisplayNBackpackDefaultA0
	| AvatarItemDisplayNBackpackDefaultA1
	| AvatarItemDisplayNBackpackDefaultA2
	| AvatarItemDisplayNBackpackDefaultA3
	| AvatarItemDisplayNBackpackDefaultB0
	| AvatarItemDisplayNBackpackDefaultB1
	| AvatarItemDisplayNBackpackDefaultB2
	| AvatarItemDisplayNBackpackDefaultB3
	| AvatarItemDisplayNBackpackDefaultB4
	| AvatarItemDisplayNBackpackDefaultB5
	| AvatarItemDisplayNBackpackDp0
	| AvatarItemDisplayNBackpackEggIncubator0
	| AvatarItemDisplayNBackpackEggbackpack0
	| AvatarItemDisplayNBackpackEggbackpack1
	| AvatarItemDisplayNBackpackEggbackpack2
	| AvatarItemDisplayNBackpackFrlgA0
	| AvatarItemDisplayNBackpackFrlgB0
	| AvatarItemDisplayNBackpackGenesecteventitem0
	| AvatarItemDisplayNBackpackGengar0
	| AvatarItemDisplayNBackpackGiratinaitems0
	| AvatarItemDisplayNBackpackGoruckgengar0
	| AvatarItemDisplayNBackpackGoruckpikachu0
	| AvatarItemDisplayNBackpackGoruckwobbuffet0
	| AvatarItemDisplayNBackpackGreenpikavee0
	| AvatarItemDisplayNBackpackGuccibackpack0
	| AvatarItemDisplayNBackpackGuitarcasebackpack0
	| AvatarItemDisplayNBackpackHgssA0
	| AvatarItemDisplayNBackpackHgssB0
	| AvatarItemDisplayNBackpackHououbackpack0
	| AvatarItemDisplayNBackpackKakureonpouch0
	| AvatarItemDisplayNBackpackKomala0
	| AvatarItemDisplayNBackpackLongchampbp0
	| AvatarItemDisplayNBackpackLunalaitems0
	| AvatarItemDisplayNBackpackLunarnewyr0
	| AvatarItemDisplayNBackpackMimikyubp0
	| AvatarItemDisplayNBackpackMovie20200
	| AvatarItemDisplayNBackpackNaganadelwings0
	| AvatarItemDisplayNBackpackNike20210
	| AvatarItemDisplayNBackpackPamobackpack0
	| AvatarItemDisplayNBackpackPinap0
	| AvatarItemDisplayNBackpackPkmnhoodie0010
	| AvatarItemDisplayNBackpackPkmnhoodie0040
	| AvatarItemDisplayNBackpackPkmnhoodie0070
	| AvatarItemDisplayNBackpackRuinmaniac0
	| AvatarItemDisplayNBackpackSnapcamera0
	| AvatarItemDisplayNBackpackSsA0
	| AvatarItemDisplayNBackpackSsB0
	| AvatarItemDisplayNBackpackSvcostumescarletschool0
	| AvatarItemDisplayNBackpackSvcostumevioletschool0
	| AvatarItemDisplayNBackpackSvdlc10
	| AvatarItemDisplayNBackpackSvdlc2spring0
	| AvatarItemDisplayNBackpackSwshdlc2costumeA0
	| AvatarItemDisplayNBackpackSwshdlc2costumeB0
	| AvatarItemDisplayNBackpackSwshdlccostumeA0
	| AvatarItemDisplayNBackpackSwshdlccostumeB0
	| AvatarItemDisplayNBackpackTatsugiribackpackCurly0
	| AvatarItemDisplayNBackpackTatsugiribackpackDroopy0
	| AvatarItemDisplayNBackpackTatsugiribackpackStretchy0
	| AvatarItemDisplayNBackpackTogepibackpack0
	| AvatarItemDisplayNBackpackUltraA0
	| AvatarItemDisplayNBackpackUltraB0
	| AvatarItemDisplayNBackpackUnequip0
	| AvatarItemDisplayNBackpackVerizon20210
	| AvatarItemDisplayNBackpackWhitekyuremitem0
	| AvatarItemDisplayNBackpackZubatbp0
	| AvatarItemDisplayNBeltAcetrainerbw0
	| AvatarItemDisplayNBeltDefaultA0
	| AvatarItemDisplayNBeltDefaultA1
	| AvatarItemDisplayNBeltDefaultA2
	| AvatarItemDisplayNBeltDefaultA3
	| AvatarItemDisplayNBeltDefaultA4
	| AvatarItemDisplayNBeltDefaultA5
	| AvatarItemDisplayNBeltDefaultA6
	| AvatarItemDisplayNBeltDefaultA7
	| AvatarItemDisplayNBeltDefaultA8
	| AvatarItemDisplayNBeltSimple0
	| AvatarItemDisplayNBeltSimple1
	| AvatarItemDisplayNBeltSimple2
	| AvatarItemDisplayNBeltSimple3
	| AvatarItemDisplayNBeltTeamrocket0
	| AvatarItemDisplayNBeltTeamrocket1
	| AvatarItemDisplayNBeltUnequip0
	| AvatarItemDisplayNFace3dmask0
	| AvatarItemDisplayNFace3dmask1
	| AvatarItemDisplayNFace3dmask2
	| AvatarItemDisplayNFaceAllister0
	| AvatarItemDisplayNFaceBanettemask0
	| AvatarItemDisplayNFaceDayofthedead0
	| AvatarItemDisplayNFaceDefaultmask0
	| AvatarItemDisplayNFaceFacestickerghostpika0
	| AvatarItemDisplayNFaceFacestickerpikachu0
	| AvatarItemDisplayNFaceFacestickerpokeball0
	| AvatarItemDisplayNFaceFestofcolors0
	| AvatarItemDisplayNFaceFestofcolors1
	| AvatarItemDisplayNFaceFestofcolors2
	| AvatarItemDisplayNFaceGracidea0
	| AvatarItemDisplayNFaceHoliday2022santacostumes0
	| AvatarItemDisplayNFacePikachumask0
	| AvatarItemDisplayNFaceSableyemask0
	| AvatarItemDisplayNFaceTeamskull0
	| AvatarItemDisplayNFaceToxelmask0
	| AvatarItemDisplayNFaceUnequip0
	| AvatarItemDisplayNFaceVerizon2020mask0
	| AvatarItemDisplayNGlasses3d0
	| AvatarItemDisplayNGlassesClemont0
	| AvatarItemDisplayNGlassesCutieflysleepmask0
	| AvatarItemDisplayNGlassesDittoeyewear0
	| AvatarItemDisplayNGlassesDivingsuit0
	| AvatarItemDisplayNGlassesDrpikachu0
	| AvatarItemDisplayNGlassesFrillishglasses0
	| AvatarItemDisplayNGlassesFw20220
	| AvatarItemDisplayNGlassesGimmighoulitems0
	| AvatarItemDisplayNGlassesGoteamrocketarlo0
	| AvatarItemDisplayNGlassesGrandoakglasses0
	| AvatarItemDisplayNGlassesJogger0
	| AvatarItemDisplayNGlassesLugiaglasses0
	| AvatarItemDisplayNGlassesLv40glasses0
	| AvatarItemDisplayNGlassesLvl73Visorspecs0
	| AvatarItemDisplayNGlassesMask0
	| AvatarItemDisplayNGlassesMask1
	| AvatarItemDisplayNGlassesNecrozmaitems0
	| AvatarItemDisplayNGlassesNewyear20220
	| AvatarItemDisplayNGlassesNewyearglasses20200
	| AvatarItemDisplayNGlassesNewyearglasses20210
	| AvatarItemDisplayNGlassesObstagoonitems0
	| AvatarItemDisplayNGlassesRoundsunglasses0
	| AvatarItemDisplayNGlassesTeardrop0
	| AvatarItemDisplayNGlassesThick0
	| AvatarItemDisplayNGlassesThick1
	| AvatarItemDisplayNGlassesThick2
	| AvatarItemDisplayNGlassesThick3
	| AvatarItemDisplayNGlassesThick4
	| AvatarItemDisplayNGlassesUnequip0
	| AvatarItemDisplayNGlassesWcs2024winnersitems0
	| AvatarItemDisplayNGlovesAcetrainersm0
	| AvatarItemDisplayNGlovesAllister0
	| AvatarItemDisplayNGlovesBattlegirl0
	| AvatarItemDisplayNGlovesBea0
	| AvatarItemDisplayNGlovesBwn0
	| AvatarItemDisplayNGlovesDefaultNew0
	| AvatarItemDisplayNGlovesDefaultA0
	| AvatarItemDisplayNGlovesDefaultA1
	| AvatarItemDisplayNGlovesDefaultA2
	| AvatarItemDisplayNGlovesDefaultA3
	| AvatarItemDisplayNGlovesDefaultB0
	| AvatarItemDisplayNGlovesDefaultB1
	| AvatarItemDisplayNGlovesDefaultB2
	| AvatarItemDisplayNGlovesDefaultB3
	| AvatarItemDisplayNGlovesDelibird0
	| AvatarItemDisplayNGlovesDynamaxswsh0
	| AvatarItemDisplayNGlovesFrlgA0
	| AvatarItemDisplayNGlovesFrlgB0
	| AvatarItemDisplayNGlovesGeeta0
	| AvatarItemDisplayNGlovesGiovanni0
	| AvatarItemDisplayNGlovesGuzma0
	| AvatarItemDisplayNGlovesGymleaderA0
	| AvatarItemDisplayNGlovesGymleaderB0
	| AvatarItemDisplayNGlovesHoopabangle0
	| AvatarItemDisplayNGlovesJogger0
	| AvatarItemDisplayNGlovesKorrina0
	| AvatarItemDisplayNGlovesLysandre0
	| AvatarItemDisplayNGlovesMegabangle0
	| AvatarItemDisplayNGlovesMegabangle1
	| AvatarItemDisplayNGlovesMegabangle2
	| AvatarItemDisplayNGlovesMegabangle3
	| AvatarItemDisplayNGlovesMegabangle4
	| AvatarItemDisplayNGlovesObstagoonitems0
	| AvatarItemDisplayNGlovesPalmer0
	| AvatarItemDisplayNGlovesProfwillowoutfit0
	| AvatarItemDisplayNGlovesStevenfirst0
	| AvatarItemDisplayNGlovesSvdlc2spring0
	| AvatarItemDisplayNGlovesSwshdlc2costume0
	| AvatarItemDisplayNGlovesSwshdlccostume0
	| AvatarItemDisplayNGlovesSwshuniformchampion0
	| AvatarItemDisplayNGlovesSwshuniformdark0
	| AvatarItemDisplayNGlovesSwshuniformdefault0
	| AvatarItemDisplayNGlovesSwshuniformdragon0
	| AvatarItemDisplayNGlovesTeamaquaA0
	| AvatarItemDisplayNGlovesTeamaquaB0
	| AvatarItemDisplayNGlovesTeammagma0
	| AvatarItemDisplayNGlovesTeamrocket0
	| AvatarItemDisplayNGlovesTeamsparkA0
	| AvatarItemDisplayNGlovesTeamsparkB0
	| AvatarItemDisplayNGlovesTeamwristband0
	| AvatarItemDisplayNGlovesTeamwristband1
	| AvatarItemDisplayNGlovesTeamwristband2
	| AvatarItemDisplayNGlovesTeamwristband3
	| AvatarItemDisplayNGlovesTeamyellgrunts0
	| AvatarItemDisplayNGlovesUnequip0
	| AvatarItemDisplayNGlovesWintergloves20230
	| AvatarItemDisplayNGradientEye0
	| AvatarItemDisplayNGradientEye1
	| AvatarItemDisplayNGradientEye10
	| AvatarItemDisplayNGradientEye11
	| AvatarItemDisplayNGradientEye12
	| AvatarItemDisplayNGradientEye13
	| AvatarItemDisplayNGradientEye14
	| AvatarItemDisplayNGradientEye15
	| AvatarItemDisplayNGradientEye16
	| AvatarItemDisplayNGradientEye17
	| AvatarItemDisplayNGradientEye18
	| AvatarItemDisplayNGradientEye19
	| AvatarItemDisplayNGradientEye2
	| AvatarItemDisplayNGradientEye3
	| AvatarItemDisplayNGradientEye4
	| AvatarItemDisplayNGradientEye5
	| AvatarItemDisplayNGradientEye6
	| AvatarItemDisplayNGradientEye7
	| AvatarItemDisplayNGradientEye8
	| AvatarItemDisplayNGradientEye9
	| AvatarItemDisplayNGradientHair0
	| AvatarItemDisplayNGradientHair1
	| AvatarItemDisplayNGradientHair10
	| AvatarItemDisplayNGradientHair11
	| AvatarItemDisplayNGradientHair12
	| AvatarItemDisplayNGradientHair13
	| AvatarItemDisplayNGradientHair14
	| AvatarItemDisplayNGradientHair15
	| AvatarItemDisplayNGradientHair16
	| AvatarItemDisplayNGradientHair17
	| AvatarItemDisplayNGradientHair18
	| AvatarItemDisplayNGradientHair19
	| AvatarItemDisplayNGradientHair2
	| AvatarItemDisplayNGradientHair20
	| AvatarItemDisplayNGradientHair21
	| AvatarItemDisplayNGradientHair22
	| AvatarItemDisplayNGradientHair23
	| AvatarItemDisplayNGradientHair24
	| AvatarItemDisplayNGradientHair25
	| AvatarItemDisplayNGradientHair26
	| AvatarItemDisplayNGradientHair27
	| AvatarItemDisplayNGradientHair28
	| AvatarItemDisplayNGradientHair29
	| AvatarItemDisplayNGradientHair3
	| AvatarItemDisplayNGradientHair30
	| AvatarItemDisplayNGradientHair31
	| AvatarItemDisplayNGradientHair4
	| AvatarItemDisplayNGradientHair5
	| AvatarItemDisplayNGradientHair6
	| AvatarItemDisplayNGradientHair7
	| AvatarItemDisplayNGradientHair8
	| AvatarItemDisplayNGradientHair9
	| AvatarItemDisplayNGradientTesteye0
	| AvatarItemDisplayNGradientTesteye1
	| AvatarItemDisplayNGradientTesthair0
	| AvatarItemDisplayNGradientTesthair1
	| AvatarItemDisplayNHairCoilyshort0
	| AvatarItemDisplayNHairCurlymedium0
	| AvatarItemDisplayNHairDefaultA0
	| AvatarItemDisplayNHairDefaultB0
	| AvatarItemDisplayNHairGrimmsnarl0
	| AvatarItemDisplayNHairKinkymedium0
	| AvatarItemDisplayNHairKinkyshort0
	| AvatarItemDisplayNHairLvl79Synthfade0
	| AvatarItemDisplayNHairLvl79Urbanphantom0
	| AvatarItemDisplayNHairMohawk00
	| AvatarItemDisplayNHairMohawk10
	| AvatarItemDisplayNHairMorgrem0
	| AvatarItemDisplayNHairStraightlong0
	| AvatarItemDisplayNHairStraightmedium0
	| AvatarItemDisplayNHairStraightshort0
	| AvatarItemDisplayNHairTesthair00
	| AvatarItemDisplayNHairTesthair10
	| AvatarItemDisplayNHairWavylong0
	| AvatarItemDisplayNHairWavymedium0
	| AvatarItemDisplayNHairWavyshort0
	| AvatarItemDisplayNHairZacian0
	| AvatarItemDisplayNHairZamazenta0
	| AvatarItemDisplayNHat6thanniversaryA0
	| AvatarItemDisplayNHat6thanniversaryB0
	| AvatarItemDisplayNHatAcetrainersmA0
	| AvatarItemDisplayNHatAcetrainersmB0
	| AvatarItemDisplayNHatAdventure0
	| AvatarItemDisplayNHatAlolanexeggutorhat0
	| AvatarItemDisplayNHatApplinitems0
	| AvatarItemDisplayNHatAseries0
	| AvatarItemDisplayNHatBeaA0
	| AvatarItemDisplayNHatBeaB0
	| AvatarItemDisplayNHatBidoofhat0
	| AvatarItemDisplayNHatBounsweetitems0
	| AvatarItemDisplayNHatBwn0
	| AvatarItemDisplayNHatCaptainpikachu0
	| AvatarItemDisplayNHatCasket0
	| AvatarItemDisplayNHatCetoddlehat0
	| AvatarItemDisplayNHatClay0
	| AvatarItemDisplayNHatCofagrigusitems0
	| AvatarItemDisplayNHatCommunityambassador0
	| AvatarItemDisplayNHatCosmog0
	| AvatarItemDisplayNHatCrownmoon0
	| AvatarItemDisplayNHatCrownsun0
	| AvatarItemDisplayNHatCubonehat0
	| AvatarItemDisplayNHatDarumakahat0
	| AvatarItemDisplayNHatDedenneitems0
	| AvatarItemDisplayNHatDefaultA0
	| AvatarItemDisplayNHatDefaultA1
	| AvatarItemDisplayNHatDefaultA2
	| AvatarItemDisplayNHatDefaultA3
	| AvatarItemDisplayNHatDefaultA4
	| AvatarItemDisplayNHatDefaultA5
	| AvatarItemDisplayNHatDefaultA6
	| AvatarItemDisplayNHatDefaultA7
	| AvatarItemDisplayNHatDefaultB0
	| AvatarItemDisplayNHatDefaultB1
	| AvatarItemDisplayNHatDefaultB2
	| AvatarItemDisplayNHatDefaultB3
	| AvatarItemDisplayNHatDefaultB4
	| AvatarItemDisplayNHatDefaultB5
	| AvatarItemDisplayNHatDeino0
	| AvatarItemDisplayNHatDelibird0
	| AvatarItemDisplayNHatDetectivepikachu0
	| AvatarItemDisplayNHatDiancie0
	| AvatarItemDisplayNHatDpA0
	| AvatarItemDisplayNHatDpB0
	| AvatarItemDisplayNHatDrifloon0
	| AvatarItemDisplayNHatDrpikachu0
	| AvatarItemDisplayNHatDusclopsmummy0
	| AvatarItemDisplayNHatEarringsburmyplant0
	| AvatarItemDisplayNHatEarringsburmysandy0
	| AvatarItemDisplayNHatEarringsburmytrash0
	| AvatarItemDisplayNHatEeveecap0
	| AvatarItemDisplayNHatElesa0
	| AvatarItemDisplayNHatEternatussuit0
	| AvatarItemDisplayNHatFedora0
	| AvatarItemDisplayNHatFedora1
	| AvatarItemDisplayNHatFisher0
	| AvatarItemDisplayNHatFlabebepack0
	| AvatarItemDisplayNHatFlowercrown0
	| AvatarItemDisplayNHatFragment0
	| AvatarItemDisplayNHatFrlgA0
	| AvatarItemDisplayNHatFrlgB0
	| AvatarItemDisplayNHatFurfrouwig0
	| AvatarItemDisplayNHatFw20220
	| AvatarItemDisplayNHatGalarfarfetchditems0
	| AvatarItemDisplayNHatGenesecteventitem0
	| AvatarItemDisplayNHatGengar0
	| AvatarItemDisplayNHatGimmighoulitems0
	| AvatarItemDisplayNHatGiratinaitems0
	| AvatarItemDisplayNHatGladion0
	| AvatarItemDisplayNHatGofestPikachuvisor0
	| AvatarItemDisplayNHatGoomy0
	| AvatarItemDisplayNHatGreavardwig0
	| AvatarItemDisplayNHatGreencoat0
	| AvatarItemDisplayNHatGrowlithehelmet0
	| AvatarItemDisplayNHatGtr2024eeveefanmask0
	| AvatarItemDisplayNHatGtr2024pikachufanmask0
	| AvatarItemDisplayNHatGuccihat0
	| AvatarItemDisplayNHatGuzma0
	| AvatarItemDisplayNHatGyaradoscap0
	| AvatarItemDisplayNHatHalloween20240
	| AvatarItemDisplayNHatHgssA0
	| AvatarItemDisplayNHatHgssB0
	| AvatarItemDisplayNHatHoliday2022santacostumes0
	| AvatarItemDisplayNHatHolidaybeanie0
	| AvatarItemDisplayNHatHoopaearmuffs0
	| AvatarItemDisplayNHatIngo0
	| AvatarItemDisplayNHatJogger0
	| AvatarItemDisplayNHatKantotourcapgreen0
	| AvatarItemDisplayNHatKantotourcapred0
	| AvatarItemDisplayNHatKnitted0
	| AvatarItemDisplayNHatKnitted1
	| AvatarItemDisplayNHatKorrina0
	| AvatarItemDisplayNHatKyuremhat0
	| AvatarItemDisplayNHatLana0
	| AvatarItemDisplayNHatLaprasbandanaA0
	| AvatarItemDisplayNHatLaprasbandanaB0
	| AvatarItemDisplayNHatLasecuritycorps0
	| AvatarItemDisplayNHatLegendofarceusA0
	| AvatarItemDisplayNHatLegendofarceusB0
	| AvatarItemDisplayNHatLitwickhat0
	| AvatarItemDisplayNHatLoneearrings0
	| AvatarItemDisplayNHatLucariomask0
	| AvatarItemDisplayNHatLvl50cap0
	| AvatarItemDisplayNHatMagikarp0
	| AvatarItemDisplayNHatMareaniehat0
	| AvatarItemDisplayNHatMegalopunnyitems0
	| AvatarItemDisplayNHatMegarayquaza0
	| AvatarItemDisplayNHatMeltan0
	| AvatarItemDisplayNHatMeltanearrings0
	| AvatarItemDisplayNHatMewtwoA0
	| AvatarItemDisplayNHatMewtwoB0
	| AvatarItemDisplayNHatMimikyu0
	| AvatarItemDisplayNHatMismagius0
	| AvatarItemDisplayNHatMlbBrewers0
	| AvatarItemDisplayNHatMlbDiamondbacks0
	| AvatarItemDisplayNHatMlbGiants0
	| AvatarItemDisplayNHatMlbGuardians0
	| AvatarItemDisplayNHatMlbMariners0
	| AvatarItemDisplayNHatMlbMarlins0
	| AvatarItemDisplayNHatMlbMets0
	| AvatarItemDisplayNHatMlbNationals0
	| AvatarItemDisplayNHatMlbOrioles0
	| AvatarItemDisplayNHatMlbPadres0
	| AvatarItemDisplayNHatMlbRangers0
	| AvatarItemDisplayNHatMlbRays0
	| AvatarItemDisplayNHatMlbRedsox0
	| AvatarItemDisplayNHatMlbTwins0
	| AvatarItemDisplayNHatMlbWhitesox0
	| AvatarItemDisplayNHatMlb0
	| AvatarItemDisplayNHatMovie20200
	| AvatarItemDisplayNHatMunnapack0
	| AvatarItemDisplayNHatMunnapack1
	| AvatarItemDisplayNHatMustard0
	| AvatarItemDisplayNHatNewyear20220
	| AvatarItemDisplayNHatNewyearhat20210
	| AvatarItemDisplayNHatNewyearhat20230
	| AvatarItemDisplayNHatNihilegoitems0
	| AvatarItemDisplayNHatNoibat0
	| AvatarItemDisplayNHatObstagoonitems0
	| AvatarItemDisplayNHatOrasA0
	| AvatarItemDisplayNHatOrasB0
	| AvatarItemDisplayNHatOricoriopink0
	| AvatarItemDisplayNHatOricoriopurple0
	| AvatarItemDisplayNHatOricoriored0
	| AvatarItemDisplayNHatOricorioyellow0
	| AvatarItemDisplayNHatPartneritemsjan2024hat0
	| AvatarItemDisplayNHatPartyhat0
	| AvatarItemDisplayNHatPhantump0
	| AvatarItemDisplayNHatPikachubutlerBlue0
	| AvatarItemDisplayNHatPikachubutlerRed0
	| AvatarItemDisplayNHatPikachubutlerYellow0
	| AvatarItemDisplayNHatPikachucap0
	| AvatarItemDisplayNHatPikachufan0
	| AvatarItemDisplayNHatPikachulibre0
	| AvatarItemDisplayNHatPikachupumpkinhead0
	| AvatarItemDisplayNHatPkmncap0
	| AvatarItemDisplayNHatPkmncap1
	| AvatarItemDisplayNHatPkmncap2
	| AvatarItemDisplayNHatPoipole0
	| AvatarItemDisplayNHatPokeballitemsBasic0
	| AvatarItemDisplayNHatPokeballitemsGreat0
	| AvatarItemDisplayNHatPokeballitemsUltra0
	| AvatarItemDisplayNHatPolteageisthat0
	| AvatarItemDisplayNHatProfwillowoutfit0
	| AvatarItemDisplayNHatRegiicejersies0
	| AvatarItemDisplayNHatRegirockjersies0
	| AvatarItemDisplayNHatRegisteeljersies0
	| AvatarItemDisplayNHatRuinmaniacA0
	| AvatarItemDisplayNHatRuinmaniacB0
	| AvatarItemDisplayNHatSableyegoggles0
	| AvatarItemDisplayNHatSamsungsummer20200
	| AvatarItemDisplayNHatSandygasthat0
	| AvatarItemDisplayNHatShayminhat0
	| AvatarItemDisplayNHatSlowpoketailshirts0
	| AvatarItemDisplayNHatSnombeanie0
	| AvatarItemDisplayNHatSnorlaxnightcap0
	| AvatarItemDisplayNHatSolgaleoitems0
	| AvatarItemDisplayNHatSsA0
	| AvatarItemDisplayNHatSsB0
	| AvatarItemDisplayNHatStantlerheadband0
	| AvatarItemDisplayNHatStrawhat0
	| AvatarItemDisplayNHatSummer20230
	| AvatarItemDisplayNHatSvcostumescarletschool0
	| AvatarItemDisplayNHatSvcostumevioletschool0
	| AvatarItemDisplayNHatSwshdlc2costume0
	| AvatarItemDisplayNHatSwshuniformchampion0
	| AvatarItemDisplayNHatSylveonitemsA0
	| AvatarItemDisplayNHatSylveonitemsB0
	| AvatarItemDisplayNHatTcgcollabtshirtandcap0
	| AvatarItemDisplayNHatTeamaqua0
	| AvatarItemDisplayNHatTeamleadercap0
	| AvatarItemDisplayNHatTeamleadercap1
	| AvatarItemDisplayNHatTeamleadercap2
	| AvatarItemDisplayNHatTeamrocket0
	| AvatarItemDisplayNHatTeamrocketcap0
	| AvatarItemDisplayNHatTeamskull0
	| AvatarItemDisplayNHatTophat0
	| AvatarItemDisplayNHatUltraA0
	| AvatarItemDisplayNHatUltraB0
	| AvatarItemDisplayNHatUltrareconsquad0
	| AvatarItemDisplayNHatUltrareconsquadb0
	| AvatarItemDisplayNHatUnequip0
	| AvatarItemDisplayNHatVerizon20210
	| AvatarItemDisplayNHatWcs2022winnersitems0
	| AvatarItemDisplayNHatWcs2024paiditems0
	| AvatarItemDisplayNHatWcs20250
	| AvatarItemDisplayNHatWcs2025winnersitems0
	| AvatarItemDisplayNHatWhimsicottearmuff0
	| AvatarItemDisplayNHatWillowglasses0
	| AvatarItemDisplayNHatWoobatearrings0
	| AvatarItemDisplayNHatXerneasitems0
	| AvatarItemDisplayNHatYamaskhat0
	| AvatarItemDisplayNHatYamaskmask0
	| AvatarItemDisplayNHatZacianmask0
	| AvatarItemDisplayNHatZacostumeA0
	| AvatarItemDisplayNHatZacostumeB0
	| AvatarItemDisplayNHatZamazentamask0
	| AvatarItemDisplayNHatZubathat0
	| AvatarItemDisplayNIdle01
	| AvatarItemDisplayNNecklaceDefault0
	| AvatarItemDisplayNNecklaceDefault1
	| AvatarItemDisplayNNecklaceHeart0
	| AvatarItemDisplayNNecklaceStar0
	| AvatarItemDisplayNNecklaceUnequip0
	| AvatarItemDisplayNPants6thanniversary0
	| AvatarItemDisplayNPants7thanniversary0
	| AvatarItemDisplayNPantsAcetrainerbwA0
	| AvatarItemDisplayNPantsAcetrainerbwB0
	| AvatarItemDisplayNPantsAcetrainersm0
	| AvatarItemDisplayNPantsAnimegou0
	| AvatarItemDisplayNPantsBackpackerA0
	| AvatarItemDisplayNPantsBackpackerB0
	| AvatarItemDisplayNPantsBattlegirl0
	| AvatarItemDisplayNPantsBlackwhite0
	| AvatarItemDisplayNPantsBounsweetitems0
	| AvatarItemDisplayNPantsBrock0
	| AvatarItemDisplayNPantsBwn0
	| AvatarItemDisplayNPantsCasualA0
	| AvatarItemDisplayNPantsCasualA1
	| AvatarItemDisplayNPantsCasualB0
	| AvatarItemDisplayNPantsCasualB1
	| AvatarItemDisplayNPantsClay0
	| AvatarItemDisplayNPantsDefaultNew0
	| AvatarItemDisplayNPantsDefaultA0
	| AvatarItemDisplayNPantsDefaultA1
	| AvatarItemDisplayNPantsDefaultA2
	| AvatarItemDisplayNPantsDefaultA3
	| AvatarItemDisplayNPantsDefaultA4
	| AvatarItemDisplayNPantsDefaultA5
	| AvatarItemDisplayNPantsDefaultB0
	| AvatarItemDisplayNPantsDenimfashionweek20230
	| AvatarItemDisplayNPantsDpA0
	| AvatarItemDisplayNPantsDpB0
	| AvatarItemDisplayNPantsElesa0
	| AvatarItemDisplayNPantsEternatussuit0
	| AvatarItemDisplayNPantsFashionweek20220
	| AvatarItemDisplayNPantsFashionweek20250
	| AvatarItemDisplayNPantsFisher0
	| AvatarItemDisplayNPantsFlabebepack0
	| AvatarItemDisplayNPantsFrlgA0
	| AvatarItemDisplayNPantsFrlgB0
	| AvatarItemDisplayNPantsFw2022A0
	| AvatarItemDisplayNPantsFw2022B0
	| AvatarItemDisplayNPantsGeeta0
	| AvatarItemDisplayNPantsGenderlessskirt0
	| AvatarItemDisplayNPantsGiovanni0
	| AvatarItemDisplayNPantsGladion0
	| AvatarItemDisplayNPantsGothitelleitems0
	| AvatarItemDisplayNPantsGreenA0
	| AvatarItemDisplayNPantsGreenB0
	| AvatarItemDisplayNPantsGreencoat0
	| AvatarItemDisplayNPantsGreenpikavee0
	| AvatarItemDisplayNPantsGrimsley0
	| AvatarItemDisplayNPantsGrusha0
	| AvatarItemDisplayNPantsGuzma0
	| AvatarItemDisplayNPantsGymleaderA0
	| AvatarItemDisplayNPantsGymleaderA1
	| AvatarItemDisplayNPantsGymleaderA2
	| AvatarItemDisplayNPantsGymleaderB0
	| AvatarItemDisplayNPantsGymleaderB1
	| AvatarItemDisplayNPantsGymleaderB2
	| AvatarItemDisplayNPantsHala0
	| AvatarItemDisplayNPantsHgssA0
	| AvatarItemDisplayNPantsHgssB0
	| AvatarItemDisplayNPantsIngo0
	| AvatarItemDisplayNPantsJogger0
	| AvatarItemDisplayNPantsKorrina0
	| AvatarItemDisplayNPantsLooseFitting0
	| AvatarItemDisplayNPantsLoosepants0
	| AvatarItemDisplayNPantsLunalaitems0
	| AvatarItemDisplayNPantsLuvdiscpackA0
	| AvatarItemDisplayNPantsLuvdiscpackB0
	| AvatarItemDisplayNPantsLvl75Techtrousers0
	| AvatarItemDisplayNPantsLysandre0
	| AvatarItemDisplayNPantsMewtwoA0
	| AvatarItemDisplayNPantsMewtwoB0
	| AvatarItemDisplayNPantsMiniskirtWave0
	| AvatarItemDisplayNPantsMiniskirtWave1
	| AvatarItemDisplayNPantsMiniskirtWave2
	| AvatarItemDisplayNPantsMiniskirt0
	| AvatarItemDisplayNPantsMiniskirt1
	| AvatarItemDisplayNPantsMiniskirt2
	| AvatarItemDisplayNPantsMiniskirt3
	| AvatarItemDisplayNPantsMisty0
	| AvatarItemDisplayNPantsMunnapack0
	| AvatarItemDisplayNPantsMustard0
	| AvatarItemDisplayNPantsNaganadelaitems0
	| AvatarItemDisplayNPantsNecrozmaitems0
	| AvatarItemDisplayNPantsNeonSolid0
	| AvatarItemDisplayNPantsNeonSolid1
	| AvatarItemDisplayNPantsNeonSolid2
	| AvatarItemDisplayNPantsNeonStripes0
	| AvatarItemDisplayNPantsNeonStripes1
	| AvatarItemDisplayNPantsNewyear20220
	| AvatarItemDisplayNPantsOrasA0
	| AvatarItemDisplayNPantsOrasB0
	| AvatarItemDisplayNPantsPajamas20220
	| AvatarItemDisplayNPantsPajamas20221
	| AvatarItemDisplayNPantsPalmer0
	| AvatarItemDisplayNPantsPikachubutler0
	| AvatarItemDisplayNPantsPikachufanA0
	| AvatarItemDisplayNPantsPikachufanB0
	| AvatarItemDisplayNPantsPikachulibreA0
	| AvatarItemDisplayNPantsPikachulibreB0
	| AvatarItemDisplayNPantsProfwillowoutfit0
	| AvatarItemDisplayNPantsPumpkabooitems0
	| AvatarItemDisplayNPantsRegiicejersies0
	| AvatarItemDisplayNPantsRegirockjersies0
	| AvatarItemDisplayNPantsRegisteeljersies0
	| AvatarItemDisplayNPantsS19gbl0
	| AvatarItemDisplayNPantsShorts0
	| AvatarItemDisplayNPantsShorts1
	| AvatarItemDisplayNPantsShorts2
	| AvatarItemDisplayNPantsShorts3
	| AvatarItemDisplayNPantsSkinnyjeansA0
	| AvatarItemDisplayNPantsSkinnyjeansB0
	| AvatarItemDisplayNPantsSkinnyjeansB1
	| AvatarItemDisplayNPantsSkinnyjeansB2
	| AvatarItemDisplayNPantsSs0
	| AvatarItemDisplayNPantsSteven0
	| AvatarItemDisplayNPantsStevenfirst0
	| AvatarItemDisplayNPantsSweats0
	| AvatarItemDisplayNPantsSweats1
	| AvatarItemDisplayNPantsSweats2
	| AvatarItemDisplayNPantsSweats3
	| AvatarItemDisplayNPantsSweats4
	| AvatarItemDisplayNPantsSwshuniformchampion0
	| AvatarItemDisplayNPantsSwshuniformdarkA0
	| AvatarItemDisplayNPantsSwshuniformdarkB0
	| AvatarItemDisplayNPantsSwshuniformdefaultA0
	| AvatarItemDisplayNPantsSwshuniformdefaultB0
	| AvatarItemDisplayNPantsSwshuniformdragonA0
	| AvatarItemDisplayNPantsSwshuniformdragonB0
	| AvatarItemDisplayNPantsTeamaquaA0
	| AvatarItemDisplayNPantsTeamaquaB0
	| AvatarItemDisplayNPantsTeamblancheA0
	| AvatarItemDisplayNPantsTeamblancheB0
	| AvatarItemDisplayNPantsTeamcandelaA0
	| AvatarItemDisplayNPantsTeamcandelaB0
	| AvatarItemDisplayNPantsTeammagmaA0
	| AvatarItemDisplayNPantsTeammagmaB0
	| AvatarItemDisplayNPantsTeamrocketA0
	| AvatarItemDisplayNPantsTeamrocketB0
	| AvatarItemDisplayNPantsTeamskullA0
	| AvatarItemDisplayNPantsTeamskullB0
	| AvatarItemDisplayNPantsTeamsparkA0
	| AvatarItemDisplayNPantsTeamsparkB0
	| AvatarItemDisplayNPantsTeamyellgruntsPants0
	| AvatarItemDisplayNPantsTeamyellgruntsSkirt0
	| AvatarItemDisplayNPantsTurbine0
	| AvatarItemDisplayNPantsTurbine1
	| AvatarItemDisplayNPantsTurbine2
	| AvatarItemDisplayNPantsUltraA0
	| AvatarItemDisplayNPantsUltraB0
	| AvatarItemDisplayNPantsVeterantrainerxyA0
	| AvatarItemDisplayNPantsVeterantrainerxyB0
	| AvatarItemDisplayNPantsWcs2022winnersitems0
	| AvatarItemDisplayNPantsWcs2024winnersitems0
	| AvatarItemDisplayNPantsWcs2025winnersitems0
	| AvatarItemDisplayNPose001
	| AvatarItemDisplayNPose002
	| AvatarItemDisplayNPose003
	| AvatarItemDisplayNPose004
	| AvatarItemDisplayNPose005
	| AvatarItemDisplayNPose006
	| AvatarItemDisplayNPose007
	| AvatarItemDisplayNPose008
	| AvatarItemDisplayNPose009
	| AvatarItemDisplayNPose010
	| AvatarItemDisplayNPose011
	| AvatarItemDisplayNPose012
	| AvatarItemDisplayNPose013
	| AvatarItemDisplayNPose014
	| AvatarItemDisplayNPose015
	| AvatarItemDisplayNPose016
	| AvatarItemDisplayNPose017
	| AvatarItemDisplayNPose018
	| AvatarItemDisplayNPose019
	| AvatarItemDisplayNPose020
	| AvatarItemDisplayNPose021
	| AvatarItemDisplayNPose022
	| AvatarItemDisplayNPose023
	| AvatarItemDisplayNPose024
	| AvatarItemDisplayNPose025
	| AvatarItemDisplayNPose026
	| AvatarItemDisplayNPose027
	| AvatarItemDisplayNPose028
	| AvatarItemDisplayNPose029
	| AvatarItemDisplayNPose030
	| AvatarItemDisplayNPose031
	| AvatarItemDisplayNPose032
	| AvatarItemDisplayNPose032A
	| AvatarItemDisplayNPose033
	| AvatarItemDisplayNPose034
	| AvatarItemDisplayNPose035
	| AvatarItemDisplayNPose036
	| AvatarItemDisplayNPose037
	| AvatarItemDisplayNPose038
	| AvatarItemDisplayNPose039
	| AvatarItemDisplayNPose040
	| AvatarItemDisplayNPose041
	| AvatarItemDisplayNPose042
	| AvatarItemDisplayNPose043
	| AvatarItemDisplayNPose044
	| AvatarItemDisplayNPose045
	| AvatarItemDisplayNPose046
	| AvatarItemDisplayNPose047
	| AvatarItemDisplayNPose048
	| AvatarItemDisplayNPose049
	| AvatarItemDisplayNPose050
	| AvatarItemDisplayNPose051
	| AvatarItemDisplayNPose052
	| AvatarItemDisplayNPose053
	| AvatarItemDisplayNPose054
	| AvatarItemDisplayNPose055
	| AvatarItemDisplayNPose056
	| AvatarItemDisplayNPose057
	| AvatarItemDisplayNPose058
	| AvatarItemDisplayNPose059
	| AvatarItemDisplayNPose060
	| AvatarItemDisplayNPose061
	| AvatarItemDisplayNPose062
	| AvatarItemDisplayNPose063
	| AvatarItemDisplayNPose064
	| AvatarItemDisplayNPose065
	| AvatarItemDisplayNPose066
	| AvatarItemDisplayNPose067
	| AvatarItemDisplayNPose068
	| AvatarItemDisplayNPoseBuddypokeball
	| AvatarItemDisplayNPoseCarnival
	| AvatarItemDisplayNPoseCommunityambassador
	| AvatarItemDisplayNPoseConcierge
	| AvatarItemDisplayNPoseEmpty
	| AvatarItemDisplayNPoseFashionweek2025
	| AvatarItemDisplayNPoseGofest2025
	| AvatarItemDisplayNPoseGrowingup
	| AvatarItemDisplayNPoseGrusha
	| AvatarItemDisplayNPoseHeart
	| AvatarItemDisplayNPoseIdle
	| AvatarItemDisplayNPoseIdleA
	| AvatarItemDisplayNPoseIdleB
	| AvatarItemDisplayNPoseLegacy50
	| AvatarItemDisplayNPoseLvl77
	| AvatarItemDisplayNPoseMustard
	| AvatarItemDisplayNPosePenpal
	| AvatarItemDisplayNPoseS16finale
	| AvatarItemDisplayNPoseS19gbl
	| AvatarItemDisplayNPoseS20gbl
	| AvatarItemDisplayNPoseS22gbl
	| AvatarItemDisplayNPoseSustainability
	| AvatarItemDisplayNPoseTeapot
	| AvatarItemDisplayNPoseTinkatonhammer
	| AvatarItemDisplayNPoseUrshifurapidstrike
	| AvatarItemDisplayNPoseUrshifusinglestrike
	| AvatarItemDisplayNPoseWaterfestival
	| AvatarItemDisplayNShirt6thanniversaryA0
	| AvatarItemDisplayNShirt6thanniversaryB0
	| AvatarItemDisplayNShirt7thanniversary0
	| AvatarItemDisplayNShirtAcetrainerbwA0
	| AvatarItemDisplayNShirtAcetrainerbwB0
	| AvatarItemDisplayNShirtAcetrainersmA0
	| AvatarItemDisplayNShirtAcetrainersmB0
	| AvatarItemDisplayNShirtAllister0
	| AvatarItemDisplayNShirtAlolacomfey0
	| AvatarItemDisplayNShirtAnimegou0
	| AvatarItemDisplayNShirtApplinitems0
	| AvatarItemDisplayNShirtAseries0
	| AvatarItemDisplayNShirtBackpackerA0
	| AvatarItemDisplayNShirtBackpackerB0
	| AvatarItemDisplayNShirtBallguy0
	| AvatarItemDisplayNShirtBattlegirl0
	| AvatarItemDisplayNShirtBeaA0
	| AvatarItemDisplayNShirtBeaB0
	| AvatarItemDisplayNShirtBewearcostume0
	| AvatarItemDisplayNShirtBlackwhite0
	| AvatarItemDisplayNShirtBlazer0
	| AvatarItemDisplayNShirtBounsweetitemsA0
	| AvatarItemDisplayNShirtBounsweetitemsB0
	| AvatarItemDisplayNShirtBrock0
	| AvatarItemDisplayNShirtButtondown0
	| AvatarItemDisplayNShirtBuzzwoleitems0
	| AvatarItemDisplayNShirtBwn0
	| AvatarItemDisplayNShirtCasualA0
	| AvatarItemDisplayNShirtCasualA1
	| AvatarItemDisplayNShirtCasualA2
	| AvatarItemDisplayNShirtCasualA3
	| AvatarItemDisplayNShirtCasualB0
	| AvatarItemDisplayNShirtCasualB1
	| AvatarItemDisplayNShirtCasualB2
	| AvatarItemDisplayNShirtCasualB3
	| AvatarItemDisplayNShirtCelebi0
	| AvatarItemDisplayNShirtChimcharonesie0
	| AvatarItemDisplayNShirtClay0
	| AvatarItemDisplayNShirtClemont0
	| AvatarItemDisplayNShirtCofagrigusitems0
	| AvatarItemDisplayNShirtConcierge0
	| AvatarItemDisplayNShirtCosmog0
	| AvatarItemDisplayNShirtCowichansweater0
	| AvatarItemDisplayNShirtDayofdead0
	| AvatarItemDisplayNShirtDefaultNew0
	| AvatarItemDisplayNShirtDefaultA0
	| AvatarItemDisplayNShirtDefaultA1
	| AvatarItemDisplayNShirtDefaultA2
	| AvatarItemDisplayNShirtDefaultA3
	| AvatarItemDisplayNShirtDefaultA4
	| AvatarItemDisplayNShirtDefaultA5
	| AvatarItemDisplayNShirtDefaultA6
	| AvatarItemDisplayNShirtDefaultA7
	| AvatarItemDisplayNShirtDefaultA8
	| AvatarItemDisplayNShirtDefaultB0
	| AvatarItemDisplayNShirtDefaultB1
	| AvatarItemDisplayNShirtDefaultB2
	| AvatarItemDisplayNShirtDefaultB3
	| AvatarItemDisplayNShirtDefaultB4
	| AvatarItemDisplayNShirtDefaultB5
	| AvatarItemDisplayNShirtDefaultB6
	| AvatarItemDisplayNShirtDefaultB7
	| AvatarItemDisplayNShirtDefaultB8
	| AvatarItemDisplayNShirtDelibird0
	| AvatarItemDisplayNShirtDelibirdonesie0
	| AvatarItemDisplayNShirtDenimfashionweek20230
	| AvatarItemDisplayNShirtDenimjacket0
	| AvatarItemDisplayNShirtDetectivepikachu0
	| AvatarItemDisplayNShirtDiancie0
	| AvatarItemDisplayNShirtDisguiseHoodoff0
	| AvatarItemDisplayNShirtDisguiseHoodon0
	| AvatarItemDisplayNShirtDivingsuit0
	| AvatarItemDisplayNShirtDiwali20210
	| AvatarItemDisplayNShirtDpA0
	| AvatarItemDisplayNShirtDpB0
	| AvatarItemDisplayNShirtDrifblim0
	| AvatarItemDisplayNShirtDudunsparceitem0
	| AvatarItemDisplayNShirtDusclopsmummy0
	| AvatarItemDisplayNShirtEarthday20180
	| AvatarItemDisplayNShirtEeveestshirt000
	| AvatarItemDisplayNShirtEeveestshirt010
	| AvatarItemDisplayNShirtEeveestshirt020
	| AvatarItemDisplayNShirtEeveestshirt030
	| AvatarItemDisplayNShirtEeveestshirt040
	| AvatarItemDisplayNShirtEeveestshirt050
	| AvatarItemDisplayNShirtEeveestshirt060
	| AvatarItemDisplayNShirtEeveestshirt070
	| AvatarItemDisplayNShirtEeveestshirt080
	| AvatarItemDisplayNShirtElesaA0
	| AvatarItemDisplayNShirtElesaB0
	| AvatarItemDisplayNShirtEternatussuit0
	| AvatarItemDisplayNShirtFashionweek20220
	| AvatarItemDisplayNShirtFashionweek20250
	| AvatarItemDisplayNShirtFestivaloflights000
	| AvatarItemDisplayNShirtFestivaloflights010
	| AvatarItemDisplayNShirtFisher0
	| AvatarItemDisplayNShirtFlabebepack0
	| AvatarItemDisplayNShirtFragment0
	| AvatarItemDisplayNShirtFrlgA0
	| AvatarItemDisplayNShirtFrlgB0
	| AvatarItemDisplayNShirtFw2022A0
	| AvatarItemDisplayNShirtFw2022B0
	| AvatarItemDisplayNShirtGalarfarfetchditems0
	| AvatarItemDisplayNShirtGalaxyoutfitA0
	| AvatarItemDisplayNShirtGalaxyoutfitB0
	| AvatarItemDisplayNShirtGeeta0
	| AvatarItemDisplayNShirtGenderlessskirt0
	| AvatarItemDisplayNShirtGengar0
	| AvatarItemDisplayNShirtGengaronesie0
	| AvatarItemDisplayNShirtGiovanniA0
	| AvatarItemDisplayNShirtGiovanniB0
	| AvatarItemDisplayNShirtGiratinaitems0
	| AvatarItemDisplayNShirtGladion0
	| AvatarItemDisplayNShirtGofest20190
	| AvatarItemDisplayNShirtGofest20200
	| AvatarItemDisplayNShirtGofest20210
	| AvatarItemDisplayNShirtGofest20220
	| AvatarItemDisplayNShirtGofest20230
	| AvatarItemDisplayNShirtGofest2024darkgray0
	| AvatarItemDisplayNShirtGofest2024gray0
	| AvatarItemDisplayNShirtGofest2024purple0
	| AvatarItemDisplayNShirtGofest20250
	| AvatarItemDisplayNShirtGofest2025cream0
	| AvatarItemDisplayNShirtGofestglobal20230
	| AvatarItemDisplayNShirtGoteamrocketarloA0
	| AvatarItemDisplayNShirtGoteamrocketarloB0
	| AvatarItemDisplayNShirtGoteamrocketcliffA0
	| AvatarItemDisplayNShirtGoteamrocketcliffB0
	| AvatarItemDisplayNShirtGoteamrocketsierraA0
	| AvatarItemDisplayNShirtGoteamrocketsierraB0
	| AvatarItemDisplayNShirtGothitelleitems0
	| AvatarItemDisplayNShirtGotour20230
	| AvatarItemDisplayNShirtGotour20240
	| AvatarItemDisplayNShirtGotour20250
	| AvatarItemDisplayNShirtGotour20251
	| AvatarItemDisplayNShirtGotour20252
	| AvatarItemDisplayNShirtGotour2026Black0
	| AvatarItemDisplayNShirtGotour2026Gray0
	| AvatarItemDisplayNShirtGowa20240
	| AvatarItemDisplayNShirtGowa20250
	| AvatarItemDisplayNShirtGowa20251
	| AvatarItemDisplayNShirtGreedentsweater0
	| AvatarItemDisplayNShirtGreen0
	| AvatarItemDisplayNShirtGreencoat0
	| AvatarItemDisplayNShirtGreenpikavee0
	| AvatarItemDisplayNShirtGrimsley0
	| AvatarItemDisplayNShirtGrusha0
	| AvatarItemDisplayNShirtGtrtshirt20220
	| AvatarItemDisplayNShirtGtrtshirt20221
	| AvatarItemDisplayNShirtGuccitshirts0
	| AvatarItemDisplayNShirtGuzma0
	| AvatarItemDisplayNShirtGymleaderA0
	| AvatarItemDisplayNShirtGymleaderA1
	| AvatarItemDisplayNShirtGymleaderA2
	| AvatarItemDisplayNShirtGymleaderB0
	| AvatarItemDisplayNShirtGymleaderB1
	| AvatarItemDisplayNShirtGymleaderB2
	| AvatarItemDisplayNShirtHala0
	| AvatarItemDisplayNShirtHalloween20240
	| AvatarItemDisplayNShirtHappi0
	| AvatarItemDisplayNShirtHappi1
	| AvatarItemDisplayNShirtHappi2
	| AvatarItemDisplayNShirtHgssA0
	| AvatarItemDisplayNShirtHgssB0
	| AvatarItemDisplayNShirtHoliday2022santacostumes0
	| AvatarItemDisplayNShirtHoliday2024Marshtompsweater0
	| AvatarItemDisplayNShirtHoliday2024Staryusweater0
	| AvatarItemDisplayNShirtHoliday2024Wooloojacket0
	| AvatarItemDisplayNShirtHolifestival2021black0
	| AvatarItemDisplayNShirtHolifestival2021white0
	| AvatarItemDisplayNShirtHoopaunboundtshirt0
	| AvatarItemDisplayNShirtIngo0
	| AvatarItemDisplayNShirtIngressE0
	| AvatarItemDisplayNShirtIngressR0
	| AvatarItemDisplayNShirtIngress0
	| AvatarItemDisplayNShirtJacketNewyear20220
	| AvatarItemDisplayNShirtJames0
	| AvatarItemDisplayNShirtJessie0
	| AvatarItemDisplayNShirtJirachi0
	| AvatarItemDisplayNShirtJogger0
	| AvatarItemDisplayNShirtKeldeotshirt0
	| AvatarItemDisplayNShirtKorrinaA0
	| AvatarItemDisplayNShirtKorrinaB0
	| AvatarItemDisplayNShirtLadiamondoutfitA0
	| AvatarItemDisplayNShirtLadiamondoutfitB0
	| AvatarItemDisplayNShirtLana0
	| AvatarItemDisplayNShirtLapearloutfitA0
	| AvatarItemDisplayNShirtLapearloutfitB0
	| AvatarItemDisplayNShirtLasecuritycorpsA0
	| AvatarItemDisplayNShirtLasecuritycorpsB0
	| AvatarItemDisplayNShirtLatiasLatios0
	| AvatarItemDisplayNShirtLegendofarceusA0
	| AvatarItemDisplayNShirtLegendofarceusB0
	| AvatarItemDisplayNShirtLongsleevesCharizard0
	| AvatarItemDisplayNShirtLongsleevesCharizard1
	| AvatarItemDisplayNShirtLongsleevesCharizard2
	| AvatarItemDisplayNShirtLongsleevesPikachu0
	| AvatarItemDisplayNShirtLongsleevesPikachu1
	| AvatarItemDisplayNShirtLongsleevesPikachu2
	| AvatarItemDisplayNShirtLooseFitting0
	| AvatarItemDisplayNShirtLooseFitting1
	| AvatarItemDisplayNShirtLuvdiscpackA0
	| AvatarItemDisplayNShirtLuvdiscpackB0
	| AvatarItemDisplayNShirtLvl500
	| AvatarItemDisplayNShirtLvl501
	| AvatarItemDisplayNShirtLvl80Circuitjacket0
	| AvatarItemDisplayNShirtLysandre0
	| AvatarItemDisplayNShirtMarshadowtshirt0
	| AvatarItemDisplayNShirtMegalopunnyitems0
	| AvatarItemDisplayNShirtMegarayquaza0
	| AvatarItemDisplayNShirtMelmetaljacket0
	| AvatarItemDisplayNShirtMelmetalvest0
	| AvatarItemDisplayNShirtMeloettatshirt0
	| AvatarItemDisplayNShirtMeltan0
	| AvatarItemDisplayNShirtMew0
	| AvatarItemDisplayNShirtMewtwoA0
	| AvatarItemDisplayNShirtMewtwoB0
	| AvatarItemDisplayNShirtMisty0
	| AvatarItemDisplayNShirtMorpekofullonesie0
	| AvatarItemDisplayNShirtMorpekohangryonesie0
	| AvatarItemDisplayNShirtMovie2020jessiejamesA0
	| AvatarItemDisplayNShirtMovie2020jessiejamesB0
	| AvatarItemDisplayNShirtMunnapackA0
	| AvatarItemDisplayNShirtMunnapackB0
	| AvatarItemDisplayNShirtMustard0
	| AvatarItemDisplayNShirtNaganadelaitems0
	| AvatarItemDisplayNShirtNecrozmaitems0
	| AvatarItemDisplayNShirtNike20210
	| AvatarItemDisplayNShirtOcshirt045A0
	| AvatarItemDisplayNShirtOcshirt045B0
	| AvatarItemDisplayNShirtOcshirt108A0
	| AvatarItemDisplayNShirtOcshirt108B0
	| AvatarItemDisplayNShirtOcshirt129A0
	| AvatarItemDisplayNShirtOcshirt129B0
	| AvatarItemDisplayNShirtOcshirt143A0
	| AvatarItemDisplayNShirtOcshirt143B0
	| AvatarItemDisplayNShirtOrasA0
	| AvatarItemDisplayNShirtOrasB0
	| AvatarItemDisplayNShirtPajamas20220
	| AvatarItemDisplayNShirtPajamas20221
	| AvatarItemDisplayNShirtPalmer0
	| AvatarItemDisplayNShirtPartneritemsjan2024hoodie0
	| AvatarItemDisplayNShirtPartneritemsjan2024tshirt0
	| AvatarItemDisplayNShirtPikachubutlerBlue0
	| AvatarItemDisplayNShirtPikachubutlerRed0
	| AvatarItemDisplayNShirtPikachubutlerYellow0
	| AvatarItemDisplayNShirtPikachufanA0
	| AvatarItemDisplayNShirtPikachufanB0
	| AvatarItemDisplayNShirtPikachulibreA0
	| AvatarItemDisplayNShirtPikachulibreB0
	| AvatarItemDisplayNShirtPikachuonesie0
	| AvatarItemDisplayNShirtPinpukuhoodie0
	| AvatarItemDisplayNShirtPipluponesie0
	| AvatarItemDisplayNShirtPkmnhoodie0010
	| AvatarItemDisplayNShirtPkmnhoodie0040
	| AvatarItemDisplayNShirtPkmnhoodie0070
	| AvatarItemDisplayNShirtPkmnshirts1650
	| AvatarItemDisplayNShirtPkmnshirts1880
	| AvatarItemDisplayNShirtPkmnshirts2010
	| AvatarItemDisplayNShirtPkmnshirts2380
	| AvatarItemDisplayNShirtPkmnshirts20210
	| AvatarItemDisplayNShirtPkmnshirts20211
	| AvatarItemDisplayNShirtPkmnshirts20212
	| AvatarItemDisplayNShirtPokeballitemsBasic0
	| AvatarItemDisplayNShirtPokeballitemsGreat0
	| AvatarItemDisplayNShirtPokeballitemsUltra0
	| AvatarItemDisplayNShirtPoloshirt0
	| AvatarItemDisplayNShirtPoloshirt1
	| AvatarItemDisplayNShirtPoloshirt2
	| AvatarItemDisplayNShirtProfwillowoutfit0
	| AvatarItemDisplayNShirtProjectguitar0
	| AvatarItemDisplayNShirtPumpkabooitems0
	| AvatarItemDisplayNShirtRegiicejersies0
	| AvatarItemDisplayNShirtRegirockjersies0
	| AvatarItemDisplayNShirtRegisteeljersies0
	| AvatarItemDisplayNShirtReuniclusitems0
	| AvatarItemDisplayNShirtRuinmaniacA0
	| AvatarItemDisplayNShirtRuinmaniacB0
	| AvatarItemDisplayNShirtS19gbl0
	| AvatarItemDisplayNShirtSafarizone2020A0
	| AvatarItemDisplayNShirtSafarizone2020B0
	| AvatarItemDisplayNShirtSamsungsummer20200
	| AvatarItemDisplayNShirtScolipede0
	| AvatarItemDisplayNShirtShayminlandtshirt0
	| AvatarItemDisplayNShirtShayminskytshirt0
	| AvatarItemDisplayNShirtShinydiancie
	| AvatarItemDisplayNShirtShinykeldeoshirt0
	| AvatarItemDisplayNShirtShinymeloettatshirt0
	| AvatarItemDisplayNShirtShinymewtshirts0
	| AvatarItemDisplayNShirtSlowpokeshirts0
	| AvatarItemDisplayNShirtSlowpoketailshirts0
	| AvatarItemDisplayNShirtSnorlaxonesie0
	| AvatarItemDisplayNShirtSpiritomb0
	| AvatarItemDisplayNShirtSpring2021gulpinA0
	| AvatarItemDisplayNShirtSpring2021gulpinB0
	| AvatarItemDisplayNShirtSpring2021plusleA0
	| AvatarItemDisplayNShirtSpring2021plusleB0
	| AvatarItemDisplayNShirtSsA0
	| AvatarItemDisplayNShirtSsB0
	| AvatarItemDisplayNShirtSteven0
	| AvatarItemDisplayNShirtStevenfirst0
	| AvatarItemDisplayNShirtSukajanblastoise0
	| AvatarItemDisplayNShirtSukajancharizard0
	| AvatarItemDisplayNShirtSukajanhouou0
	| AvatarItemDisplayNShirtSukajanlugia0
	| AvatarItemDisplayNShirtSukajanvenusaur0
	| AvatarItemDisplayNShirtSummer20230
	| AvatarItemDisplayNShirtSustainability2021A0
	| AvatarItemDisplayNShirtSustainability2021B0
	| AvatarItemDisplayNShirtSvcostumescarletschool0
	| AvatarItemDisplayNShirtSvcostumevioletschool0
	| AvatarItemDisplayNShirtSvdlc10
	| AvatarItemDisplayNShirtSvdlc2fall0
	| AvatarItemDisplayNShirtSvdlc2spring0
	| AvatarItemDisplayNShirtSweater300
	| AvatarItemDisplayNShirtSweater301
	| AvatarItemDisplayNShirtSweater302
	| AvatarItemDisplayNShirtSweaterInstinct0
	| AvatarItemDisplayNShirtSweaterMystic0
	| AvatarItemDisplayNShirtSweaterValor0
	| AvatarItemDisplayNShirtSweatshirtSporty0
	| AvatarItemDisplayNShirtSweatshirtSporty1
	| AvatarItemDisplayNShirtSweatshirtSporty2
	| AvatarItemDisplayNShirtSweatshirtSporty3
	| AvatarItemDisplayNShirtSweatshirtStreak0
	| AvatarItemDisplayNShirtSweatshirtStreak1
	| AvatarItemDisplayNShirtSweatshirtStreak2
	| AvatarItemDisplayNShirtSweatshirtStreak3
	| AvatarItemDisplayNShirtSweatshirtStreak4
	| AvatarItemDisplayNShirtSwshdlc2costume0
	| AvatarItemDisplayNShirtSwshdlccostumeA0
	| AvatarItemDisplayNShirtSwshdlccostumeB0
	| AvatarItemDisplayNShirtSwshuniformchampion0
	| AvatarItemDisplayNShirtSwshuniformdarkA0
	| AvatarItemDisplayNShirtSwshuniformdarkB0
	| AvatarItemDisplayNShirtSwshuniformdefault0
	| AvatarItemDisplayNShirtSwshuniformdragon0
	| AvatarItemDisplayNShirtSylveonitems0
	| AvatarItemDisplayNShirtTandemausitems0
	| AvatarItemDisplayNShirtTanktopCharizard0
	| AvatarItemDisplayNShirtTanktopCharizard1
	| AvatarItemDisplayNShirtTanktopCharizard2
	| AvatarItemDisplayNShirtTanktopPikachu0
	| AvatarItemDisplayNShirtTanktopPikachu1
	| AvatarItemDisplayNShirtTanktopPikachu2
	| AvatarItemDisplayNShirtTanktop0
	| AvatarItemDisplayNShirtTanktop1
	| AvatarItemDisplayNShirtTanktop2
	| AvatarItemDisplayNShirtTcgcollabtshirtandcap0
	| AvatarItemDisplayNShirtTeamaquaA0
	| AvatarItemDisplayNShirtTeamaquaB0
	| AvatarItemDisplayNShirtTeamblancheA0
	| AvatarItemDisplayNShirtTeamblancheB0
	| AvatarItemDisplayNShirtTeamcandelaA0
	| AvatarItemDisplayNShirtTeamcandelaB0
	| AvatarItemDisplayNShirtTeammagmaA0
	| AvatarItemDisplayNShirtTeammagmaB0
	| AvatarItemDisplayNShirtTeamrocketA0
	| AvatarItemDisplayNShirtTeamrocketA1
	| AvatarItemDisplayNShirtTeamrocketB0
	| AvatarItemDisplayNShirtTeamrocketB1
	| AvatarItemDisplayNShirtTeamskull0
	| AvatarItemDisplayNShirtTeamsparkA0
	| AvatarItemDisplayNShirtTeamsparkB0
	| AvatarItemDisplayNShirtTeamyellgruntsCropped0
	| AvatarItemDisplayNShirtTeamyellgruntsLong0
	| AvatarItemDisplayNShirtTogepihoodie0
	| AvatarItemDisplayNShirtTracksuitsgroudon0
	| AvatarItemDisplayNShirtTracksuitskyogre0
	| AvatarItemDisplayNShirtTshirtCycling0
	| AvatarItemDisplayNShirtTshirtCycling1
	| AvatarItemDisplayNShirtTshirtCycling2
	| AvatarItemDisplayNShirtTshirtCycling3
	| AvatarItemDisplayNShirtTshirtFestChicago20170
	| AvatarItemDisplayNShirtTshirtFestChicago20180
	| AvatarItemDisplayNShirtTshirtGeometric0
	| AvatarItemDisplayNShirtTshirtGeometric1
	| AvatarItemDisplayNShirtTshirtGeometric2
	| AvatarItemDisplayNShirtTshirtGlobalGoals20170
	| AvatarItemDisplayNShirtTshirtInstinct0
	| AvatarItemDisplayNShirtTshirtMystic0
	| AvatarItemDisplayNShirtTshirtPikachu0
	| AvatarItemDisplayNShirtTshirtPikachu1
	| AvatarItemDisplayNShirtTshirtPikachu2
	| AvatarItemDisplayNShirtTshirtPikachu3
	| AvatarItemDisplayNShirtTshirtPikachu4
	| AvatarItemDisplayNShirtTshirtPikachu5
	| AvatarItemDisplayNShirtTshirtPikachu6
	| AvatarItemDisplayNShirtTshirtValor0
	| AvatarItemDisplayNShirtTurtleneck300
	| AvatarItemDisplayNShirtTurtleneck301
	| AvatarItemDisplayNShirtTurtleneck302
	| AvatarItemDisplayNShirtTurtleneck303
	| AvatarItemDisplayNShirtTurtwigonesie0
	| AvatarItemDisplayNShirtUglysweatersudowoodo0
	| AvatarItemDisplayNShirtUltraA0
	| AvatarItemDisplayNShirtUltraB0
	| AvatarItemDisplayNShirtUltrareconsquad0
	| AvatarItemDisplayNShirtUniqlotshirts0
	| AvatarItemDisplayNShirtUniqlotshirts1
	| AvatarItemDisplayNShirtUniqlotshirts2
	| AvatarItemDisplayNShirtUnwto0
	| AvatarItemDisplayNShirtValentine20230
	| AvatarItemDisplayNShirtVerizon20200
	| AvatarItemDisplayNShirtVeterantrainerxyA0
	| AvatarItemDisplayNShirtVeterantrainerxyB0
	| AvatarItemDisplayNShirtVictinitshirts0
	| AvatarItemDisplayNShirtVolcaniontshirt0
	| AvatarItemDisplayNShirtWcs20220
	| AvatarItemDisplayNShirtWcs2022tshirtbulu0
	| AvatarItemDisplayNShirtWcs2022tshirtred0
	| AvatarItemDisplayNShirtWcs2022winnersitems0
	| AvatarItemDisplayNShirtWcs20230
	| AvatarItemDisplayNShirtWcs2023promotshirt00
	| AvatarItemDisplayNShirtWcs2023promotshirt10
	| AvatarItemDisplayNShirtWcs2023sukajan0
	| AvatarItemDisplayNShirtWcs2023winnersitems0
	| AvatarItemDisplayNShirtWcs20240
	| AvatarItemDisplayNShirtWcs2024championshipshirtBlue0
	| AvatarItemDisplayNShirtWcs2024championshipshirtWhite0
	| AvatarItemDisplayNShirtWcs2024paiditems0
	| AvatarItemDisplayNShirtWcs2024winnersitems0
	| AvatarItemDisplayNShirtWcs20250
	| AvatarItemDisplayNShirtWcs2025anaheimWhite0
	| AvatarItemDisplayNShirtWcs2025anaheimYellow0
	| AvatarItemDisplayNShirtWcs2025paiditems0
	| AvatarItemDisplayNShirtWcs2025winnersitems0
	| AvatarItemDisplayNShirtWcsyokohama0
	| AvatarItemDisplayNShirtWhitecoat0
	| AvatarItemDisplayNShirtWintersweater20230
	| AvatarItemDisplayNShirtYveltaljacket
	| AvatarItemDisplayNShirtZacostumeA0
	| AvatarItemDisplayNShirtZacostumeB0
	| AvatarItemDisplayNShirtZoruaonesie0
	| AvatarItemDisplayNShirtZygarde100items0
	| AvatarItemDisplayNShoes6thanniversaryA0
	| AvatarItemDisplayNShoes6thanniversaryB0
	| AvatarItemDisplayNShoesAcetrainerbwA0
	| AvatarItemDisplayNShoesAcetrainerbwB0
	| AvatarItemDisplayNShoesAcetrainersmA0
	| AvatarItemDisplayNShoesAcetrainersmB0
	| AvatarItemDisplayNShoesAllister0
	| AvatarItemDisplayNShoesAnimegou0
	| AvatarItemDisplayNShoesBackpackerA0
	| AvatarItemDisplayNShoesBackpackerB0
	| AvatarItemDisplayNShoesBattlegirl0
	| AvatarItemDisplayNShoesBlacephalon0
	| AvatarItemDisplayNShoesBrock0
	| AvatarItemDisplayNShoesBwn0
	| AvatarItemDisplayNShoesCarbink0
	| AvatarItemDisplayNShoesClay0
	| AvatarItemDisplayNShoesClemont0
	| AvatarItemDisplayNShoesCoolboots0
	| AvatarItemDisplayNShoesDedenneitems0
	| AvatarItemDisplayNShoesDefaultNew0
	| AvatarItemDisplayNShoesDefaultA0
	| AvatarItemDisplayNShoesDefaultA1
	| AvatarItemDisplayNShoesDefaultA2
	| AvatarItemDisplayNShoesDefaultA3
	| AvatarItemDisplayNShoesDefaultA4
	| AvatarItemDisplayNShoesDefaultA5
	| AvatarItemDisplayNShoesDefaultA6
	| AvatarItemDisplayNShoesDefaultB0
	| AvatarItemDisplayNShoesDefaultB1
	| AvatarItemDisplayNShoesDefaultB2
	| AvatarItemDisplayNShoesDefaultB3
	| AvatarItemDisplayNShoesDefaultB4
	| AvatarItemDisplayNShoesDefaultB5
	| AvatarItemDisplayNShoesDefaultB6
	| AvatarItemDisplayNShoesDelibird0
	| AvatarItemDisplayNShoesDpA0
	| AvatarItemDisplayNShoesDpB0
	| AvatarItemDisplayNShoesElesaA0
	| AvatarItemDisplayNShoesElesaB0
	| AvatarItemDisplayNShoesEternatussuit0
	| AvatarItemDisplayNShoesFashionweek20220
	| AvatarItemDisplayNShoesFisher0
	| AvatarItemDisplayNShoesFrlgA0
	| AvatarItemDisplayNShoesFrlgB0
	| AvatarItemDisplayNShoesFw20220
	| AvatarItemDisplayNShoesGeeta0
	| AvatarItemDisplayNShoesGiovanniA0
	| AvatarItemDisplayNShoesGiovanniB0
	| AvatarItemDisplayNShoesGladion0
	| AvatarItemDisplayNShoesGothitelleitems0
	| AvatarItemDisplayNShoesGreenA0
	| AvatarItemDisplayNShoesGreenB0
	| AvatarItemDisplayNShoesGreenpikavee0
	| AvatarItemDisplayNShoesGrimsley0
	| AvatarItemDisplayNShoesGrusha0
	| AvatarItemDisplayNShoesGymleader0
	| AvatarItemDisplayNShoesGymleader1
	| AvatarItemDisplayNShoesGymleader2
	| AvatarItemDisplayNShoesHala0
	| AvatarItemDisplayNShoesHgssA0
	| AvatarItemDisplayNShoesHgssB0
	| AvatarItemDisplayNShoesIngo0
	| AvatarItemDisplayNShoesJogger0
	| AvatarItemDisplayNShoesKorrina0
	| AvatarItemDisplayNShoesLadiamondoutfitA0
	| AvatarItemDisplayNShoesLadiamondoutfitB0
	| AvatarItemDisplayNShoesLana0
	| AvatarItemDisplayNShoesLapearloutfitA0
	| AvatarItemDisplayNShoesLapearloutfitB0
	| AvatarItemDisplayNShoesLegendofarceusA0
	| AvatarItemDisplayNShoesLegendofarceusB0
	| AvatarItemDisplayNShoesLoosepants0
	| AvatarItemDisplayNShoesLoosepants1
	| AvatarItemDisplayNShoesLoosepants2
	| AvatarItemDisplayNShoesLoosepants3
	| AvatarItemDisplayNShoesLuvdiscpack0
	| AvatarItemDisplayNShoesLvl71Cyberkicks0
	| AvatarItemDisplayNShoesLysandre0
	| AvatarItemDisplayNShoesMegalopunnyitems0
	| AvatarItemDisplayNShoesMelmetalshoes0
	| AvatarItemDisplayNShoesMewtwo0
	| AvatarItemDisplayNShoesMisty0
	| AvatarItemDisplayNShoesMustard0
	| AvatarItemDisplayNShoesNecrozmaitems0
	| AvatarItemDisplayNShoesNewyear20220
	| AvatarItemDisplayNShoesNike20210
	| AvatarItemDisplayNShoesOrasA0
	| AvatarItemDisplayNShoesOrasB0
	| AvatarItemDisplayNShoesPajamas20220
	| AvatarItemDisplayNShoesPajamas20221
	| AvatarItemDisplayNShoesPalmer0
	| AvatarItemDisplayNShoesPikachuathletic
	| AvatarItemDisplayNShoesPikachufan0
	| AvatarItemDisplayNShoesPikachulibre0
	| AvatarItemDisplayNShoesPokeballitemsBasic0
	| AvatarItemDisplayNShoesPokeballitemsGreat0
	| AvatarItemDisplayNShoesPokeballitemsUltra0
	| AvatarItemDisplayNShoesProfwillowoutfit0
	| AvatarItemDisplayNShoesRegiicejersies0
	| AvatarItemDisplayNShoesRegirockjersies0
	| AvatarItemDisplayNShoesRegisteeljersies0
	| AvatarItemDisplayNShoesReuniclusitems0
	| AvatarItemDisplayNShoesRuinmaniacA0
	| AvatarItemDisplayNShoesRuinmaniacB0
	| AvatarItemDisplayNShoesS19gbl0
	| AvatarItemDisplayNShoesSandals0
	| AvatarItemDisplayNShoesSandals1
	| AvatarItemDisplayNShoesSandals2
	| AvatarItemDisplayNShoesSizzlipedeboots0
	| AvatarItemDisplayNShoesSolgaleoitems0
	| AvatarItemDisplayNShoesSsA0
	| AvatarItemDisplayNShoesSsB0
	| AvatarItemDisplayNShoesSteven0
	| AvatarItemDisplayNShoesStevenfirst0
	| AvatarItemDisplayNShoesSvcostumescarletschool0
	| AvatarItemDisplayNShoesSvcostumevioletschool0
	| AvatarItemDisplayNShoesSvdlc10
	| AvatarItemDisplayNShoesSvdlc2spring0
	| AvatarItemDisplayNShoesSwshdlc2costume0
	| AvatarItemDisplayNShoesSwshdlccostume0
	| AvatarItemDisplayNShoesSwshuniformdark0
	| AvatarItemDisplayNShoesSwshuniformdefault0
	| AvatarItemDisplayNShoesSwshuniformdragon0
	| AvatarItemDisplayNShoesSylveonitems0
	| AvatarItemDisplayNShoesTandemausitems0
	| AvatarItemDisplayNShoesTeamaqua0
	| AvatarItemDisplayNShoesTeamblancheA0
	| AvatarItemDisplayNShoesTeamblancheB0
	| AvatarItemDisplayNShoesTeamcandelaA0
	| AvatarItemDisplayNShoesTeamcandelaB0
	| AvatarItemDisplayNShoesTeammagmaA0
	| AvatarItemDisplayNShoesTeammagmaB0
	| AvatarItemDisplayNShoesTeamrocketA0
	| AvatarItemDisplayNShoesTeamrocketA1
	| AvatarItemDisplayNShoesTeamrocketB0
	| AvatarItemDisplayNShoesTeamrocketB1
	| AvatarItemDisplayNShoesTeamskull0
	| AvatarItemDisplayNShoesTeamskullB0
	| AvatarItemDisplayNShoesTeamsparkA0
	| AvatarItemDisplayNShoesTeamsparkB0
	| AvatarItemDisplayNShoesTeamyellgrunts0
	| AvatarItemDisplayNShoesUltraA0
	| AvatarItemDisplayNShoesUltraB0
	| AvatarItemDisplayNShoesUltrareconsquad0
	| AvatarItemDisplayNShoesUnequip0
	| AvatarItemDisplayNShoesVeterantrainerxyA0
	| AvatarItemDisplayNShoesVeterantrainerxyB0
	| AvatarItemDisplayNShoesWcs2022winnersitems0
	| AvatarItemDisplayNShoesWcs2023winnersitems0
	| AvatarItemDisplayNShoesWcs2024winnersitems0
	| AvatarItemDisplayNShoesWinterboots20230
	| AvatarItemDisplayNShoesWinterboots0
	| AvatarItemDisplayNShoesWinterboots1
	| AvatarItemDisplayNShoesWinterboots2
	| AvatarItemDisplayNShoesWinterboots3
	| AvatarItemDisplayNShoesZacostumeA0
	| AvatarItemDisplayNShoesZacostumeB0
	| AvatarItemDisplayNSocksDefaultA0
	| AvatarItemDisplayNSocksDefaultA1
	| AvatarItemDisplayNSocksDefaultA2
	| AvatarItemDisplayNSocksDefaultB0
	| AvatarItemDisplayNSocksDefaultB1
	| AvatarItemDisplayNSocksDefaultB2
	| AvatarItemDisplayNSocksDefaultB3
	| AvatarItemDisplayNSocksFw2022A0
	| AvatarItemDisplayNSocksFw2022B0
	| AvatarItemDisplayNSocksHgss0
	| AvatarItemDisplayNSocksSneakersocks0
	| AvatarItemDisplayNSocksSneakersocks1
	| AvatarItemDisplayNSocksSollunaitems0
	| AvatarItemDisplayNSocksSwshuniformdefault0
	| AvatarItemDisplayNSocksSwshuniformdragon0
	| AvatarItemDisplayNSocksTeamaqua0
	| AvatarItemDisplayNSocksThighhighs0
	| AvatarItemDisplayNSocksUnequip0
	| AvatarItemDisplaySet6thanniversaryF
	| AvatarItemDisplaySet6thanniversaryM
	| AvatarItemDisplaySet7thanniversaryF
	| AvatarItemDisplaySet7thanniversaryM
	| AvatarItemDisplaySetAcetrainerbwF
	| AvatarItemDisplaySetAcetrainerbwM
	| AvatarItemDisplaySetAcetrainersmF
	| AvatarItemDisplaySetAcetrainersmM
	| AvatarItemDisplaySetAllister0
	| AvatarItemDisplaySetAnimegouF
	| AvatarItemDisplaySetAnimegouM
	| AvatarItemDisplaySetApplinitems
	| AvatarItemDisplaySetBackpackerF
	| AvatarItemDisplaySetBackpackerM
	| AvatarItemDisplaySetBattlegirl0F
	| AvatarItemDisplaySetBeaF
	| AvatarItemDisplaySetBeaM
	| AvatarItemDisplaySetBounsweetitemsF
	| AvatarItemDisplaySetBounsweetitemsM
	| AvatarItemDisplaySetBoxingoutfitF
	| AvatarItemDisplaySetBoxingoutfitM
	| AvatarItemDisplaySetBrockM
	| AvatarItemDisplaySetBwnF
	| AvatarItemDisplaySetBwnM
	| AvatarItemDisplaySetCasual0F
	| AvatarItemDisplaySetCasual0M
	| AvatarItemDisplaySetCasual1F
	| AvatarItemDisplaySetCasual1M
	| AvatarItemDisplaySetClayF
	| AvatarItemDisplaySetClayM
	| AvatarItemDisplaySetClemont
	| AvatarItemDisplaySetCofagrigusF
	| AvatarItemDisplaySetCofagrigusM
	| AvatarItemDisplaySetCosmogF
	| AvatarItemDisplaySetCosmogM
	| AvatarItemDisplaySetDayofthedeadF
	| AvatarItemDisplaySetDayofthedeadM
	| AvatarItemDisplaySetDedenneitemsF
	| AvatarItemDisplaySetDedenneitemsM
	| AvatarItemDisplaySetDelibirdF
	| AvatarItemDisplaySetDelibirdM
	| AvatarItemDisplaySetDetectivepikachuF
	| AvatarItemDisplaySetDetectivepikachuM
	| AvatarItemDisplaySetDivingsuitF
	| AvatarItemDisplaySetDivingsuitM
	| AvatarItemDisplaySetDpF
	| AvatarItemDisplaySetDpM
	| AvatarItemDisplaySetDusclopsmummyF
	| AvatarItemDisplaySetDusclopsmummyM
	| AvatarItemDisplaySetElesaF
	| AvatarItemDisplaySetElesaM
	| AvatarItemDisplaySetEternatussuit0
	| AvatarItemDisplaySetFashionweek2022F
	| AvatarItemDisplaySetFashionweek2022M
	| AvatarItemDisplaySetFashionweek20250
	| AvatarItemDisplaySetFisher0M
	| AvatarItemDisplaySetFlabebepackF
	| AvatarItemDisplaySetFlabebepackM
	| AvatarItemDisplaySetFragment0F
	| AvatarItemDisplaySetFragment0M
	| AvatarItemDisplaySetFrlg0F
	| AvatarItemDisplaySetFrlg0M
	| AvatarItemDisplaySetFw2022F
	| AvatarItemDisplaySetFw2022M
	| AvatarItemDisplaySetGalarfarfetchditemsF
	| AvatarItemDisplaySetGalarfarfetchditemsM
	| AvatarItemDisplaySetGeetaF
	| AvatarItemDisplaySetGeetaM
	| AvatarItemDisplaySetGenderlessskirtF
	| AvatarItemDisplaySetGenderlessskirtM
	| AvatarItemDisplaySetGenesecteventitemF
	| AvatarItemDisplaySetGenesecteventitemM
	| AvatarItemDisplaySetGengar0F
	| AvatarItemDisplaySetGengar0M
	| AvatarItemDisplaySetGimmighoulitemsF
	| AvatarItemDisplaySetGimmighoulitemsM
	| AvatarItemDisplaySetGiovanniF
	| AvatarItemDisplaySetGiovanniM
	| AvatarItemDisplaySetGiratinaitems
	| AvatarItemDisplaySetGladionF
	| AvatarItemDisplaySetGladionM
	| AvatarItemDisplaySetGoteamrocketarloF
	| AvatarItemDisplaySetGoteamrocketarloM
	| AvatarItemDisplaySetGreenF
	| AvatarItemDisplaySetGreenM
	| AvatarItemDisplaySetGreencoatF
	| AvatarItemDisplaySetGreencoatM
	| AvatarItemDisplaySetGrimsley0
	| AvatarItemDisplaySetGrusha
	| AvatarItemDisplaySetGuzmaF
	| AvatarItemDisplaySetGuzmaM
	| AvatarItemDisplaySetGymleader0F
	| AvatarItemDisplaySetGymleader0M
	| AvatarItemDisplaySetGymleader1F
	| AvatarItemDisplaySetGymleader1M
	| AvatarItemDisplaySetGymleader2F
	| AvatarItemDisplaySetGymleader2M
	| AvatarItemDisplaySetHala
	| AvatarItemDisplaySetHalloween20240
	| AvatarItemDisplaySetHgss0F
	| AvatarItemDisplaySetHgss0M
	| AvatarItemDisplaySetHoliday2022santacostumesF
	| AvatarItemDisplaySetHoliday2022santacostumesM
	| AvatarItemDisplaySetHoopaF
	| AvatarItemDisplaySetHoopaM
	| AvatarItemDisplaySetIngo
	| AvatarItemDisplaySetJogger0M
	| AvatarItemDisplaySetKorrinaF
	| AvatarItemDisplaySetKorrinaM
	| AvatarItemDisplaySetLadiamondoutfitF
	| AvatarItemDisplaySetLadiamondoutfitM
	| AvatarItemDisplaySetLana0
	| AvatarItemDisplaySetLapearloutfitF
	| AvatarItemDisplaySetLapearloutfitM
	| AvatarItemDisplaySetLasecuritycorpsF
	| AvatarItemDisplaySetLasecuritycorpsM
	| AvatarItemDisplaySetLegendofarceusF
	| AvatarItemDisplaySetLegendofarceusM
	| AvatarItemDisplaySetLooseFitting0
	| AvatarItemDisplaySetLooseFitting1
	| AvatarItemDisplaySetLunalaitemsF
	| AvatarItemDisplaySetLunalaitemsM
	| AvatarItemDisplaySetLuvdiscpackF
	| AvatarItemDisplaySetLuvdiscpackM
	| AvatarItemDisplaySetLvl500F
	| AvatarItemDisplaySetLvl500M
	| AvatarItemDisplaySetLvl501F
	| AvatarItemDisplaySetLvl501M
	| AvatarItemDisplaySetLysandreF
	| AvatarItemDisplaySetLysandreM
	| AvatarItemDisplaySetMegalopunnyitemsF
	| AvatarItemDisplaySetMegalopunnyitemsM
	| AvatarItemDisplaySetMegarayquazaF
	| AvatarItemDisplaySetMegarayquazaM
	| AvatarItemDisplaySetMelmetalJacketF
	| AvatarItemDisplaySetMelmetalJacketM
	| AvatarItemDisplaySetMelmetalVestF
	| AvatarItemDisplaySetMelmetalVestM
	| AvatarItemDisplaySetMeltanF
	| AvatarItemDisplaySetMeltanM
	| AvatarItemDisplaySetMewtwoF
	| AvatarItemDisplaySetMewtwoM
	| AvatarItemDisplaySetMimikyuF
	| AvatarItemDisplaySetMimikyuM
	| AvatarItemDisplaySetMistyF
	| AvatarItemDisplaySetMovie2020F
	| AvatarItemDisplaySetMovie2020M
	| AvatarItemDisplaySetMunnapack0F
	| AvatarItemDisplaySetMunnapack0M
	| AvatarItemDisplaySetMunnapack1F
	| AvatarItemDisplaySetMunnapack1M
	| AvatarItemDisplaySetMustard0
	| AvatarItemDisplaySetNDefaultNew
	| AvatarItemDisplaySetNDenimfashionweek2023
	| AvatarItemDisplaySetNGothitelleitems
	| AvatarItemDisplaySetNReuniclusitems
	| AvatarItemDisplaySetNaganadelaitems
	| AvatarItemDisplaySetNecrozmaitems0
	| AvatarItemDisplaySetNewyearF
	| AvatarItemDisplaySetNewyearM
	| AvatarItemDisplaySetObstagoonitemsF
	| AvatarItemDisplaySetObstagoonitemsM
	| AvatarItemDisplaySetOrasF
	| AvatarItemDisplaySetOrasM
	| AvatarItemDisplaySetPajamas20220F
	| AvatarItemDisplaySetPajamas20220M
	| AvatarItemDisplaySetPajamas20221F
	| AvatarItemDisplaySetPajamas20221M
	| AvatarItemDisplaySetPalmerF
	| AvatarItemDisplaySetPalmerM
	| AvatarItemDisplaySetPikachufan0F
	| AvatarItemDisplaySetPikachufan0M
	| AvatarItemDisplaySetPikachulibreF
	| AvatarItemDisplaySetPikachulibreM
	| AvatarItemDisplaySetPkmnhoodie001F
	| AvatarItemDisplaySetPkmnhoodie001M
	| AvatarItemDisplaySetPkmnhoodie004F
	| AvatarItemDisplaySetPkmnhoodie004M
	| AvatarItemDisplaySetPkmnhoodie007F
	| AvatarItemDisplaySetPkmnhoodie007M
	| AvatarItemDisplaySetProfwillowoutfitF
	| AvatarItemDisplaySetProfwillowoutfitM
	| AvatarItemDisplaySetPumpkabooitemsF
	| AvatarItemDisplaySetPumpkabooitemsM
	| AvatarItemDisplaySetRegiicejersiesF
	| AvatarItemDisplaySetRegiicejersiesM
	| AvatarItemDisplaySetRegirockjersiesF
	| AvatarItemDisplaySetRegirockjersiesM
	| AvatarItemDisplaySetRegisteeljersiesF
	| AvatarItemDisplaySetRegisteeljersiesM
	| AvatarItemDisplaySetRuinmaniacF
	| AvatarItemDisplaySetRuinmaniacM
	| AvatarItemDisplaySetS19gbl0
	| AvatarItemDisplaySetS22gbl0
	| AvatarItemDisplaySetShayminLandF
	| AvatarItemDisplaySetShayminLandM
	| AvatarItemDisplaySetShayminSkyF
	| AvatarItemDisplaySetShayminSkyM
	| AvatarItemDisplaySetSlowpoketailshirtsF
	| AvatarItemDisplaySetSlowpoketailshirtsM
	| AvatarItemDisplaySetSolgaleoitemsF
	| AvatarItemDisplaySetSolgaleoitemsM
	| AvatarItemDisplaySetSsF
	| AvatarItemDisplaySetSsM
	| AvatarItemDisplaySetStevenF
	| AvatarItemDisplaySetStevenM
	| AvatarItemDisplaySetStevenfirstF
	| AvatarItemDisplaySetStevenfirstM
	| AvatarItemDisplaySetSvcostumescarletschoolF
	| AvatarItemDisplaySetSvcostumescarletschoolM
	| AvatarItemDisplaySetSvcostumevioletschoolF
	| AvatarItemDisplaySetSvcostumevioletschoolM
	| AvatarItemDisplaySetSvdlc2fall0
	| AvatarItemDisplaySetSvdlc2spring0
	| AvatarItemDisplaySetSvdlcF
	| AvatarItemDisplaySetSvdlcM
	| AvatarItemDisplaySetSwshdlc2costumeF
	| AvatarItemDisplaySetSwshdlc2costumeM
	| AvatarItemDisplaySetSwshdlccostumeF
	| AvatarItemDisplaySetSwshdlccostumeM
	| AvatarItemDisplaySetSwshuniformchampionF
	| AvatarItemDisplaySetSwshuniformchampionM
	| AvatarItemDisplaySetSwshuniformdarkF
	| AvatarItemDisplaySetSwshuniformdarkM
	| AvatarItemDisplaySetSwshuniformdefaultF
	| AvatarItemDisplaySetSwshuniformdefaultM
	| AvatarItemDisplaySetSwshuniformdragonF
	| AvatarItemDisplaySetSwshuniformdragonM
	| AvatarItemDisplaySetSylveonitemsF
	| AvatarItemDisplaySetSylveonitemsM
	| AvatarItemDisplaySetTandemausitems0
	| AvatarItemDisplaySetTcgcollabtshirtandcapF
	| AvatarItemDisplaySetTcgcollabtshirtandcapM
	| AvatarItemDisplaySetTeamaquaF
	| AvatarItemDisplaySetTeamaquaM
	| AvatarItemDisplaySetTeamblancheF
	| AvatarItemDisplaySetTeamblancheM
	| AvatarItemDisplaySetTeamcandelaF
	| AvatarItemDisplaySetTeamcandelaM
	| AvatarItemDisplaySetTeammagmaF
	| AvatarItemDisplaySetTeammagmaM
	| AvatarItemDisplaySetTeamrocket0F
	| AvatarItemDisplaySetTeamrocket0M
	| AvatarItemDisplaySetTeamrocket1F
	| AvatarItemDisplaySetTeamrocket1M
	| AvatarItemDisplaySetTeamskullF
	| AvatarItemDisplaySetTeamskullM
	| AvatarItemDisplaySetTeamsparkF
	| AvatarItemDisplaySetTeamsparkM
	| AvatarItemDisplaySetTeamyellgruntsA0
	| AvatarItemDisplaySetTeamyellgruntsB0
	| AvatarItemDisplaySetUltra0F
	| AvatarItemDisplaySetUltra0M
	| AvatarItemDisplaySetUltrareconsquadF
	| AvatarItemDisplaySetUltrareconsquadM
	| AvatarItemDisplaySetUltrareconsquadbF
	| AvatarItemDisplaySetVeterantrainerxyF
	| AvatarItemDisplaySetVeterantrainerxyM
	| AvatarItemDisplaySetWcs2022winnersitemsF
	| AvatarItemDisplaySetWcs2022winnersitemsM
	| AvatarItemDisplaySetWcs2024paiditems0
	| AvatarItemDisplaySetWcs2024winnersitems0
	| AvatarItemDisplaySetWcs2025winnersitems0
	| AvatarItemDisplaySetWinter2023
	| AvatarItemDisplaySetZacostumeA
	| AvatarItemDisplaySetZacostumeB;

export type AvatarItemDisplayTemplateID = AvatarItemDisplayMasterfileEntry["templateId"];
