// Generated from Pokémon GO masterfile — group "locationCardSettings", 181 entries (structural types).

export type * from "./variants";

export interface LocationCardSettings<TemplateID extends string = string, TData extends LocationCardSettingsData = LocationCardSettingsData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		locationCardSettings: TData;
	};
}

export interface LocationCardSettingsData {
	cardType?: "LOCATION_CARD" | "SPECIAL_BACKGROUND";
	imageUrl: string;
	locationCard: number | string;
	vfxAddress?:
		| "bgfx_9thAnni"
		| "bgfx_Black"
		| "bgfx_CommunityDay_2026"
		| "bgfx_DelightfulDays"
		| "bgfx_Diamond"
		| "bgfx_Fusion"
		| "bgfx_goFest_2025_eternatus"
		| "bgfx_goFest_2025_rock_001"
		| "bgfx_goFest_2025_rock_002"
		| "bgfx_goFest_2025_rock_003"
		| "bgfx_goFest_2025_rock_004"
		| "bgfx_goFest_2025_rock_005"
		| "bgfx_goFest_2025_rock_006"
		| "bgfx_goFest_2025_shield"
		| "bgfx_goFest_2025_shield_c"
		| "bgfx_goFest_2025_sword"
		| "bgfx_goFest_2025_sword_c"
		| "bgfx_Gold"
		| "bgfx_gowa"
		| "bgfx_holi_2026"
		| "bgfx_Mega"
		| "bgfx_MightAndMastery"
		| "bgfx_Moon"
		| "bgfx_N"
		| "bgfx_Pearl"
		| "bgfx_Ruby"
		| "bgfx_Sapphire"
		| "bgfx_Silver"
		| "bgfx_Sun"
		| "bgfx_TalesOfTransformation"
		| "bgfx_TeamLeader_blue"
		| "bgfx_TeamLeader_red"
		| "bgfx_TeamLeader_yellow"
		| "bgfx_UltraWormhole"
		| "bgfx_White"
		| "bgfx_X"
		| "bgfx_Y";
}

export type LocationCardSettingsMasterfileEntry =
	| LocationCardSettings2023BarcelonaCitysafari001
	| LocationCardSettings2023JejuAiradventures001
	| LocationCardSettings2023LasvegasGotour001
	| LocationCardSettings2023LondonGofest001
	| LocationCardSettings2023MexicocityCitysafari001
	| LocationCardSettings2023NycGofest001
	| LocationCardSettings2023OsakaGofest001
	| LocationCardSettings2023SeoulCitysafari001
	| LocationCardSettings2024BaliAiradventures001
	| LocationCardSettings2024FukuokaGowa001
	| LocationCardSettings2024HongkongCitysafari001
	| LocationCardSettings2024HonoluluWorldChampionships001
	| LocationCardSettings2024IncheonSafariZone001
	| LocationCardSettings2024JakartaAiradventures001
	| LocationCardSettings2024LosangelesGotour001
	| LocationCardSettings2024MadridGofest001
	| LocationCardSettings2024MilanCitysafari001
	| LocationCardSettings2024Mlb001
	| LocationCardSettings2024Mlb002
	| LocationCardSettings2024Mlb003
	| LocationCardSettings2024Mlb004
	| LocationCardSettings2024Mlb005
	| LocationCardSettings2024Mlb006
	| LocationCardSettings2024Mlb007
	| LocationCardSettings2024Mlb008
	| LocationCardSettings2024Mlb009
	| LocationCardSettings2024Mlb010
	| LocationCardSettings2024Mlb011
	| LocationCardSettings2024Mlb012
	| LocationCardSettings2024Mlb013
	| LocationCardSettings2024Mlb014
	| LocationCardSettings2024MumbaiCitysafari001
	| LocationCardSettings2024NycGofest001
	| LocationCardSettings2024SantiagoCitysafari001
	| LocationCardSettings2024SaopauloCitysafari001
	| LocationCardSettings2024SendaiGofest001
	| LocationCardSettings2024SingaporeCitysafari001
	| LocationCardSettings2024SurabayaAiradventures001
	| LocationCardSettings2024TainanCitysafari001
	| LocationCardSettings2024YogyakartaAiradventures001
	| LocationCardSettings2025AmsterdamCitysafari001
	| LocationCardSettings2025AnaheimWorldChampionships001
	| LocationCardSettings2025BangkokCitysafari001
	| LocationCardSettings2025BerlinRoadtrip001
	| LocationCardSettings2025CancunCitysafari001
	| LocationCardSettings2025CherryBlossomFestival
	| LocationCardSettings2025CologneRoadtrip001
	| LocationCardSettings2025GowaNagasaki
	| LocationCardSettings2025HagueRoadtrip001
	| LocationCardSettings2025JangheungSummerFestival
	| LocationCardSettings2025JerseycityGofest001
	| LocationCardSettings2025KrPyeongchangWinterFestival
	| LocationCardSettings2025LondonRoadtrip001
	| LocationCardSettings2025LosangelesGotour001
	| LocationCardSettings2025ManchesterRoadtrip001
	| LocationCardSettings2025NewtaipeicityGotour001
	| LocationCardSettings2025Nfl001
	| LocationCardSettings2025OsakaEvent001
	| LocationCardSettings2025OsakaEvent002
	| LocationCardSettings2025OsakaEvent003
	| LocationCardSettings2025OsakaGofest001
	| LocationCardSettings2025Paris001
	| LocationCardSettings2025Paris002
	| LocationCardSettings2025ParisGofest001
	| LocationCardSettings2025ParisRoadtrip001
	| LocationCardSettings2025TaipeicityAmusementPark
	| LocationCardSettings2025ValenciaCitysafari001
	| LocationCardSettings2025ValenciaRoadtrip001
	| LocationCardSettings2025VancouverCitysafari001
	| LocationCardSettings2026CologneCarnival001
	| LocationCardSettings2026LosangelesGotour001
	| LocationCardSettings2026Npb001
	| LocationCardSettings2026Npb002
	| LocationCardSettings2026Npb003
	| LocationCardSettings2026Npb004
	| LocationCardSettings2026Npb005
	| LocationCardSettings2026Npb006
	| LocationCardSettings2026Npb007
	| LocationCardSettings2026Npb008
	| LocationCardSettings2026Npb009
	| LocationCardSettings2026Npb010
	| LocationCardSettings2026Npb011
	| LocationCardSettings2026Npb012
	| LocationCardSettings2026Npb013
	| LocationCardSettings2026Ppk001
	| LocationCardSettings2026RiodejaneiroCarnival001
	| LocationCardSettings2026TainanGotour001
	| LocationCardSettingsCitysafari2025Buenosaires
	| LocationCardSettingsCitysafari2025Miami
	| LocationCardSettingsCitysafari2025Sydney
	| LocationCardSettingsIdCarFreeDay
	| LocationCardSettingsJejuStampRally
	| LocationCardSettingsPokelidAichi
	| LocationCardSettingsPokelidAkita
	| LocationCardSettingsPokelidAomori
	| LocationCardSettingsPokelidChiba
	| LocationCardSettingsPokelidEhime
	| LocationCardSettingsPokelidFukui
	| LocationCardSettingsPokelidFukuoka
	| LocationCardSettingsPokelidFukushima
	| LocationCardSettingsPokelidGifu
	| LocationCardSettingsPokelidHokkaido
	| LocationCardSettingsPokelidHyogo
	| LocationCardSettingsPokelidIbaraki
	| LocationCardSettingsPokelidIshikawa
	| LocationCardSettingsPokelidIwate
	| LocationCardSettingsPokelidKagawa
	| LocationCardSettingsPokelidKagoshima
	| LocationCardSettingsPokelidKanagawa
	| LocationCardSettingsPokelidKochi
	| LocationCardSettingsPokelidKyoto
	| LocationCardSettingsPokelidMie
	| LocationCardSettingsPokelidMiyagi
	| LocationCardSettingsPokelidMiyazaki
	| LocationCardSettingsPokelidNagasaki
	| LocationCardSettingsPokelidNara
	| LocationCardSettingsPokelidNiigata
	| LocationCardSettingsPokelidOkayama
	| LocationCardSettingsPokelidOkinawa
	| LocationCardSettingsPokelidOsaka
	| LocationCardSettingsPokelidSaga
	| LocationCardSettingsPokelidSaitama
	| LocationCardSettingsPokelidShiga
	| LocationCardSettingsPokelidShimane
	| LocationCardSettingsPokelidShizuoka
	| LocationCardSettingsPokelidTochigi
	| LocationCardSettingsPokelidTokushima
	| LocationCardSettingsPokelidTokyo
	| LocationCardSettingsPokelidTottori
	| LocationCardSettingsPokelidToyama
	| LocationCardSettingsPokelidWakayama
	| LocationCardSettingsPokelidYamagata
	| LocationCardSettingsPokelidYamaguchi
	| LocationCardSettingsSpecialbackground2024Decembercdrecap
	| LocationCardSettingsSpecialbackground2024GlobalGofestRadiance001
	| LocationCardSettingsSpecialbackground2024GlobalGofestUmbra001
	| LocationCardSettingsSpecialbackground2024GlobalGowa001
	| LocationCardSettingsSpecialbackground20259thanniversary
	| LocationCardSettingsSpecialbackground2025GlobalEnigma001
	| LocationCardSettingsSpecialbackground2025GlobalGofestDd001
	| LocationCardSettingsSpecialbackground2025GlobalGofestRegi001
	| LocationCardSettingsSpecialbackground2025GlobalGofestRegi002
	| LocationCardSettingsSpecialbackground2025GlobalGofestRegi003
	| LocationCardSettingsSpecialbackground2025GlobalGofestRegi004
	| LocationCardSettingsSpecialbackground2025GlobalGofestRegi005
	| LocationCardSettingsSpecialbackground2025GlobalGofestRegi006
	| LocationCardSettingsSpecialbackground2025GlobalGofestShield001
	| LocationCardSettingsSpecialbackground2025GlobalGofestShieldCrowned001
	| LocationCardSettingsSpecialbackground2025GlobalGofestSword001
	| LocationCardSettingsSpecialbackground2025GlobalGofestSwordCrowned001
	| LocationCardSettingsSpecialbackground2025GlobalGotourBlack001
	| LocationCardSettingsSpecialbackground2025GlobalGotourBlackWhite001
	| LocationCardSettingsSpecialbackground2025GlobalGotourWhite001
	| LocationCardSettingsSpecialbackground2025GowaGlobal
	| LocationCardSettingsSpecialbackground2025S18
	| LocationCardSettingsSpecialbackground2025Season17
	| LocationCardSettingsSpecialbackground2025Season19
	| LocationCardSettingsSpecialbackground2025Season20
	| LocationCardSettingsSpecialbackground2026Communityday
	| LocationCardSettingsSpecialbackground2026GlobalDiamond001
	| LocationCardSettingsSpecialbackground2026GlobalGofest001
	| LocationCardSettingsSpecialbackground2026GlobalGold001
	| LocationCardSettingsSpecialbackground2026GlobalMega001
	| LocationCardSettingsSpecialbackground2026GlobalPearl001
	| LocationCardSettingsSpecialbackground2026GlobalRuby001
	| LocationCardSettingsSpecialbackground2026GlobalSapphire001
	| LocationCardSettingsSpecialbackground2026GlobalSilver001
	| LocationCardSettingsSpecialbackground2026GlobalX001
	| LocationCardSettingsSpecialbackground2026GlobalY001
	| LocationCardSettingsSpecialbackgroundCon2025
	| LocationCardSettingsSpecialbackgroundExtra202501
	| LocationCardSettingsSpecialbackgroundExtra202502
	| LocationCardSettingsSpecialbackgroundKr2025Lotte01
	| LocationCardSettingsSpecialbackgroundObservatoryExhibitionTour
	| LocationCardSettingsSpecialbackgroundPok2026
	| LocationCardSettingsSpecialbackgroundTeamBlue
	| LocationCardSettingsSpecialbackgroundTeamRed
	| LocationCardSettingsSpecialbackgroundTeamYellow
	| LocationCardSettingsSpecialBackground2024GlobalGofestMoonUltraWormhole001
	| LocationCardSettingsSpecialBackground2024GlobalGofestSunUltraWormhole001
	| LocationCardSettingsSpecialBackground2024GlobalGofestUltraWormhole001;

export type LocationCardSettingsTemplateID = LocationCardSettingsMasterfileEntry["templateId"];
