// Generated from Pokémon GO masterfile — "codeGateProto" lookup table.

import type {
	CodeGateProtoBattleAccessibilityCodeGate,
	CodeGateProtoBattleRewardsCodeGate,
	CodeGateProtoCombatVnextCodeGate,
	CodeGateProtoIbfcLwsCodeGate,
	CodeGateProtoInputTrackerCodeGate,
	CodeGateProtoIsSkuAvailableNoAppIdCodeGate,
	CodeGateProtoMapThemeLowPerfCodeGate,
	CodeGateProtoPredictChargeMoveOnSubmitRollBackCodeGate,
	CodeGateProtoPushGatewayMultiActionCodeGate,
	CodeGateProtoStampCollectionSnapshotEnabledCodeGate,
	CodeGateProtoTodayViewV3CodeGate,
	CodeGateProtoUseExtendedSettingsForMaxScaleCodeGate,
	CodeGateProtoUseGmtSkuDataCodeGate,
} from "pogo-masterfile-types/entries";

export interface CodeGateProtoLookup {
	BATTLE_ACCESSIBILITY_CODE_GATE: CodeGateProtoBattleAccessibilityCodeGate;
	BATTLE_REWARDS_CODE_GATE: CodeGateProtoBattleRewardsCodeGate;
	COMBAT_VNEXT_CODE_GATE: CodeGateProtoCombatVnextCodeGate;
	IBFC_LWS_CODE_GATE: CodeGateProtoIbfcLwsCodeGate;
	INPUT_TRACKER_CODE_GATE: CodeGateProtoInputTrackerCodeGate;
	IS_SKU_AVAILABLE_NO_APP_ID_CODE_GATE: CodeGateProtoIsSkuAvailableNoAppIdCodeGate;
	MAP_THEME_LOW_PERF_CODE_GATE: CodeGateProtoMapThemeLowPerfCodeGate;
	PREDICT_CHARGE_MOVE_ON_SUBMIT_ROLL_BACK_CODE_GATE: CodeGateProtoPredictChargeMoveOnSubmitRollBackCodeGate;
	PUSH_GATEWAY_MULTI_ACTION_CODE_GATE: CodeGateProtoPushGatewayMultiActionCodeGate;
	STAMP_COLLECTION_SNAPSHOT_ENABLED_CODE_GATE: CodeGateProtoStampCollectionSnapshotEnabledCodeGate;
	TODAY_VIEW_V3_CODE_GATE: CodeGateProtoTodayViewV3CodeGate;
	USE_EXTENDED_SETTINGS_FOR_MAX_SCALE_CODE_GATE: CodeGateProtoUseExtendedSettingsForMaxScaleCodeGate;
	USE_GMT_SKU_DATA_CODE_GATE: CodeGateProtoUseGmtSkuDataCodeGate;
}
