// Generated from Pokémon GO masterfile — "evolutionQuestTemplate" lookup table.

import type {
	EvolutionQuestTemplateAnnihilapeCdEvolutionQuest,
	EvolutionQuestTemplateAnnihilapeEvolutionQuest,
	EvolutionQuestTemplateBisharpKingambitEvolutionQuest,
	EvolutionQuestTemplateChanseyEvolutionQuest,
	EvolutionQuestTemplateCharcadetArmarougeEvolutionQuest,
	EvolutionQuestTemplateCharcadetCeruledgeEvolutionQuest,
	EvolutionQuestTemplateDipplinEvolutionQuest,
	EvolutionQuestTemplateEspeonCdEvolutionQuest,
	EvolutionQuestTemplateEspeonEvolutionQuest,
	EvolutionQuestTemplateFlorgesCdEvolutionQuest,
	EvolutionQuestTemplateFlorgesEvolutionQuest,
	EvolutionQuestTemplateKubfuRapidStrikeEvolutionQuest,
	EvolutionQuestTemplateKubfuSingleStrikeEvolutionQuest,
	EvolutionQuestTemplateMiloticEvolutionQuest,
	EvolutionQuestTemplateMrMimeEvolutionQuest,
	EvolutionQuestTemplateNaganadelEvolutionQuest,
	EvolutionQuestTemplateOverqwilEvolutionQuest,
	EvolutionQuestTemplatePanchamBuddyEventEvolutionQuest,
	EvolutionQuestTemplatePanchamEvolutionQuest,
	EvolutionQuestTemplatePawmotBuddyEventEvolutionQuest,
	EvolutionQuestTemplatePawmotCdEvolutionQuest,
	EvolutionQuestTemplatePawmotEvolutionQuest,
	EvolutionQuestTemplateRunerigusEvolutionQuest,
	EvolutionQuestTemplateSirfetchdEvolutionQuest,
	EvolutionQuestTemplateSlowbroGEvolutionQuest,
	EvolutionQuestTemplateSlowkingGEvolutionQuest,
	EvolutionQuestTemplateSneaslerEvolutionQuest,
	EvolutionQuestTemplateSnomFrosmothEvolutionQuest,
	EvolutionQuestTemplateSpritzeeEvolutionQuest,
	EvolutionQuestTemplateSudowoodoEvolutionQuest,
	EvolutionQuestTemplateSwirlixEvolutionQuest,
	EvolutionQuestTemplateSwoobatEvolutionQuest,
	EvolutionQuestTemplateSylveonBuddyEventEvolutionQuest,
	EvolutionQuestTemplateSylveonCdEvolutionQuest,
	EvolutionQuestTemplateSylveonEvolutionQuest,
	EvolutionQuestTemplateUmbreonCdEvolutionQuest,
	EvolutionQuestTemplateUmbreonEvolutionQuest,
} from "pogo-masterfile-types/entries";

export interface EvolutionQuestTemplateLookup {
	ANNIHILAPE_CD_EVOLUTION_QUEST: EvolutionQuestTemplateAnnihilapeCdEvolutionQuest;
	ANNIHILAPE_EVOLUTION_QUEST: EvolutionQuestTemplateAnnihilapeEvolutionQuest;
	BISHARP_KINGAMBIT_EVOLUTION_QUEST: EvolutionQuestTemplateBisharpKingambitEvolutionQuest;
	CHANSEY_EVOLUTION_QUEST: EvolutionQuestTemplateChanseyEvolutionQuest;
	CHARCADET_ARMAROUGE_EVOLUTION_QUEST: EvolutionQuestTemplateCharcadetArmarougeEvolutionQuest;
	CHARCADET_CERULEDGE_EVOLUTION_QUEST: EvolutionQuestTemplateCharcadetCeruledgeEvolutionQuest;
	DIPPLIN_EVOLUTION_QUEST: EvolutionQuestTemplateDipplinEvolutionQuest;
	ESPEON_CD_EVOLUTION_QUEST: EvolutionQuestTemplateEspeonCdEvolutionQuest;
	ESPEON_EVOLUTION_QUEST: EvolutionQuestTemplateEspeonEvolutionQuest;
	FLORGES_CD_EVOLUTION_QUEST: EvolutionQuestTemplateFlorgesCdEvolutionQuest;
	FLORGES_EVOLUTION_QUEST: EvolutionQuestTemplateFlorgesEvolutionQuest;
	KUBFU_RAPID_STRIKE_EVOLUTION_QUEST: EvolutionQuestTemplateKubfuRapidStrikeEvolutionQuest;
	KUBFU_SINGLE_STRIKE_EVOLUTION_QUEST: EvolutionQuestTemplateKubfuSingleStrikeEvolutionQuest;
	MILOTIC_EVOLUTION_QUEST: EvolutionQuestTemplateMiloticEvolutionQuest;
	MR_MIME_EVOLUTION_QUEST: EvolutionQuestTemplateMrMimeEvolutionQuest;
	NAGANADEL_EVOLUTION_QUEST: EvolutionQuestTemplateNaganadelEvolutionQuest;
	OVERQWIL_EVOLUTION_QUEST: EvolutionQuestTemplateOverqwilEvolutionQuest;
	PANCHAM_BUDDY_EVENT_EVOLUTION_QUEST: EvolutionQuestTemplatePanchamBuddyEventEvolutionQuest;
	PANCHAM_EVOLUTION_QUEST: EvolutionQuestTemplatePanchamEvolutionQuest;
	PAWMOT_BUDDY_EVENT_EVOLUTION_QUEST: EvolutionQuestTemplatePawmotBuddyEventEvolutionQuest;
	PAWMOT_CD_EVOLUTION_QUEST: EvolutionQuestTemplatePawmotCdEvolutionQuest;
	PAWMOT_EVOLUTION_QUEST: EvolutionQuestTemplatePawmotEvolutionQuest;
	RUNERIGUS_EVOLUTION_QUEST: EvolutionQuestTemplateRunerigusEvolutionQuest;
	SIRFETCHD_EVOLUTION_QUEST: EvolutionQuestTemplateSirfetchdEvolutionQuest;
	SLOWBRO_G_EVOLUTION_QUEST: EvolutionQuestTemplateSlowbroGEvolutionQuest;
	SLOWKING_G_EVOLUTION_QUEST: EvolutionQuestTemplateSlowkingGEvolutionQuest;
	SNEASLER_EVOLUTION_QUEST: EvolutionQuestTemplateSneaslerEvolutionQuest;
	SNOM_FROSMOTH_EVOLUTION_QUEST: EvolutionQuestTemplateSnomFrosmothEvolutionQuest;
	SPRITZEE_EVOLUTION_QUEST: EvolutionQuestTemplateSpritzeeEvolutionQuest;
	SUDOWOODO_EVOLUTION_QUEST: EvolutionQuestTemplateSudowoodoEvolutionQuest;
	SWIRLIX_EVOLUTION_QUEST: EvolutionQuestTemplateSwirlixEvolutionQuest;
	SWOOBAT_EVOLUTION_QUEST: EvolutionQuestTemplateSwoobatEvolutionQuest;
	SYLVEON_BUDDY_EVENT_EVOLUTION_QUEST: EvolutionQuestTemplateSylveonBuddyEventEvolutionQuest;
	SYLVEON_CD_EVOLUTION_QUEST: EvolutionQuestTemplateSylveonCdEvolutionQuest;
	SYLVEON_EVOLUTION_QUEST: EvolutionQuestTemplateSylveonEvolutionQuest;
	UMBREON_CD_EVOLUTION_QUEST: EvolutionQuestTemplateUmbreonCdEvolutionQuest;
	UMBREON_EVOLUTION_QUEST: EvolutionQuestTemplateUmbreonEvolutionQuest;
}
