// Generated from Pokémon GO masterfile — "invasionNpcDisplaySettings" lookup table.

import type {
	InvasionNpcDisplaySettingsBlanche,
	InvasionNpcDisplaySettingsBugGruntFemale,
	InvasionNpcDisplaySettingsBugGruntMale,
	InvasionNpcDisplaySettingsCandela,
	InvasionNpcDisplaySettingsDarkGruntFemale,
	InvasionNpcDisplaySettingsDarkGruntMale,
	InvasionNpcDisplaySettingsDecoyGruntFemale,
	InvasionNpcDisplaySettingsDecoyGruntMale,
	InvasionNpcDisplaySettingsDragonGruntFemale,
	InvasionNpcDisplaySettingsDragonGruntMale,
	InvasionNpcDisplaySettingsElectricGruntFemale,
	InvasionNpcDisplaySettingsElectricGruntMale,
	InvasionNpcDisplaySettingsEventArloUnticketed,
	InvasionNpcDisplaySettingsEventCliffUnticketed,
	InvasionNpcDisplaySettingsEventGiovanniUnticketed,
	InvasionNpcDisplaySettingsEventNpc0,
	InvasionNpcDisplaySettingsEventNpc1,
	InvasionNpcDisplaySettingsEventNpc10,
	InvasionNpcDisplaySettingsEventNpc2,
	InvasionNpcDisplaySettingsEventNpc3,
	InvasionNpcDisplaySettingsEventNpc4,
	InvasionNpcDisplaySettingsEventNpc5,
	InvasionNpcDisplaySettingsEventNpc6,
	InvasionNpcDisplaySettingsEventNpc7,
	InvasionNpcDisplaySettingsEventNpc8,
	InvasionNpcDisplaySettingsEventNpc9,
	InvasionNpcDisplaySettingsEventSierraUnticketed,
	InvasionNpcDisplaySettingsExecutiveArlo,
	InvasionNpcDisplaySettingsExecutiveCliff,
	InvasionNpcDisplaySettingsExecutiveSierra,
	InvasionNpcDisplaySettingsExplorer,
	InvasionNpcDisplaySettingsFairyGruntFemale,
	InvasionNpcDisplaySettingsFairyGruntMale,
	InvasionNpcDisplaySettingsFightingGruntFemale,
	InvasionNpcDisplaySettingsFightingGruntMale,
	InvasionNpcDisplaySettingsFireGruntFemale,
	InvasionNpcDisplaySettingsFireGruntMale,
	InvasionNpcDisplaySettingsFlyingGruntFemale,
	InvasionNpcDisplaySettingsFlyingGruntMale,
	InvasionNpcDisplaySettingsGhostGruntFemale,
	InvasionNpcDisplaySettingsGhostGruntMale,
	InvasionNpcDisplaySettingsGiovanni,
	InvasionNpcDisplaySettingsGrassGruntFemale,
	InvasionNpcDisplaySettingsGrassGruntMale,
	InvasionNpcDisplaySettingsGroundGruntFemale,
	InvasionNpcDisplaySettingsGroundGruntMale,
	InvasionNpcDisplaySettingsGruntFemale,
	InvasionNpcDisplaySettingsGruntMale,
	InvasionNpcDisplaySettingsGruntbFemale,
	InvasionNpcDisplaySettingsGruntbMale,
	InvasionNpcDisplaySettingsIceGruntFemale,
	InvasionNpcDisplaySettingsIceGruntMale,
	InvasionNpcDisplaySettingsMetalGruntFemale,
	InvasionNpcDisplaySettingsMetalGruntMale,
	InvasionNpcDisplaySettingsNormalGruntFemale,
	InvasionNpcDisplaySettingsNormalGruntMale,
	InvasionNpcDisplaySettingsPoisonGruntFemale,
	InvasionNpcDisplaySettingsPoisonGruntMale,
	InvasionNpcDisplaySettingsPsychicGruntFemale,
	InvasionNpcDisplaySettingsPsychicGruntMale,
	InvasionNpcDisplaySettingsRockGruntFemale,
	InvasionNpcDisplaySettingsRockGruntMale,
	InvasionNpcDisplaySettingsSpark,
	InvasionNpcDisplaySettingsWaterGruntFemale,
	InvasionNpcDisplaySettingsWaterGruntMale,
	InvasionNpcDisplaySettingsWillow,
	InvasionNpcDisplaySettingsWillowb,
} from "pogo-masterfile-types/entries";

export interface InvasionNpcDisplaySettingsLookup {
	CHARACTER_BLANCHE: InvasionNpcDisplaySettingsBlanche;
	CHARACTER_BUG_GRUNT_FEMALE: InvasionNpcDisplaySettingsBugGruntFemale;
	CHARACTER_BUG_GRUNT_MALE: InvasionNpcDisplaySettingsBugGruntMale;
	CHARACTER_CANDELA: InvasionNpcDisplaySettingsCandela;
	CHARACTER_DARK_GRUNT_FEMALE: InvasionNpcDisplaySettingsDarkGruntFemale;
	CHARACTER_DARK_GRUNT_MALE: InvasionNpcDisplaySettingsDarkGruntMale;
	CHARACTER_DECOY_GRUNT_FEMALE: InvasionNpcDisplaySettingsDecoyGruntFemale;
	CHARACTER_DECOY_GRUNT_MALE: InvasionNpcDisplaySettingsDecoyGruntMale;
	CHARACTER_DRAGON_GRUNT_FEMALE: InvasionNpcDisplaySettingsDragonGruntFemale;
	CHARACTER_DRAGON_GRUNT_MALE: InvasionNpcDisplaySettingsDragonGruntMale;
	CHARACTER_ELECTRIC_GRUNT_FEMALE: InvasionNpcDisplaySettingsElectricGruntFemale;
	CHARACTER_ELECTRIC_GRUNT_MALE: InvasionNpcDisplaySettingsElectricGruntMale;
	CHARACTER_EVENT_ARLO_UNTICKETED: InvasionNpcDisplaySettingsEventArloUnticketed;
	CHARACTER_EVENT_CLIFF_UNTICKETED: InvasionNpcDisplaySettingsEventCliffUnticketed;
	CHARACTER_EVENT_GIOVANNI_UNTICKETED: InvasionNpcDisplaySettingsEventGiovanniUnticketed;
	CHARACTER_EVENT_NPC_0: InvasionNpcDisplaySettingsEventNpc0;
	CHARACTER_EVENT_NPC_1: InvasionNpcDisplaySettingsEventNpc1;
	CHARACTER_EVENT_NPC_10: InvasionNpcDisplaySettingsEventNpc10;
	CHARACTER_EVENT_NPC_2: InvasionNpcDisplaySettingsEventNpc2;
	CHARACTER_EVENT_NPC_3: InvasionNpcDisplaySettingsEventNpc3;
	CHARACTER_EVENT_NPC_4: InvasionNpcDisplaySettingsEventNpc4;
	CHARACTER_EVENT_NPC_5: InvasionNpcDisplaySettingsEventNpc5;
	CHARACTER_EVENT_NPC_6: InvasionNpcDisplaySettingsEventNpc6;
	CHARACTER_EVENT_NPC_7: InvasionNpcDisplaySettingsEventNpc7;
	CHARACTER_EVENT_NPC_8: InvasionNpcDisplaySettingsEventNpc8;
	CHARACTER_EVENT_NPC_9: InvasionNpcDisplaySettingsEventNpc9;
	CHARACTER_EVENT_SIERRA_UNTICKETED: InvasionNpcDisplaySettingsEventSierraUnticketed;
	CHARACTER_EXECUTIVE_ARLO: InvasionNpcDisplaySettingsExecutiveArlo;
	CHARACTER_EXECUTIVE_CLIFF: InvasionNpcDisplaySettingsExecutiveCliff;
	CHARACTER_EXECUTIVE_SIERRA: InvasionNpcDisplaySettingsExecutiveSierra;
	CHARACTER_EXPLORER: InvasionNpcDisplaySettingsExplorer;
	CHARACTER_FAIRY_GRUNT_FEMALE: InvasionNpcDisplaySettingsFairyGruntFemale;
	CHARACTER_FAIRY_GRUNT_MALE: InvasionNpcDisplaySettingsFairyGruntMale;
	CHARACTER_FIGHTING_GRUNT_FEMALE: InvasionNpcDisplaySettingsFightingGruntFemale;
	CHARACTER_FIGHTING_GRUNT_MALE: InvasionNpcDisplaySettingsFightingGruntMale;
	CHARACTER_FIRE_GRUNT_FEMALE: InvasionNpcDisplaySettingsFireGruntFemale;
	CHARACTER_FIRE_GRUNT_MALE: InvasionNpcDisplaySettingsFireGruntMale;
	CHARACTER_FLYING_GRUNT_FEMALE: InvasionNpcDisplaySettingsFlyingGruntFemale;
	CHARACTER_FLYING_GRUNT_MALE: InvasionNpcDisplaySettingsFlyingGruntMale;
	CHARACTER_GHOST_GRUNT_FEMALE: InvasionNpcDisplaySettingsGhostGruntFemale;
	CHARACTER_GHOST_GRUNT_MALE: InvasionNpcDisplaySettingsGhostGruntMale;
	CHARACTER_GIOVANNI: InvasionNpcDisplaySettingsGiovanni;
	CHARACTER_GRASS_GRUNT_FEMALE: InvasionNpcDisplaySettingsGrassGruntFemale;
	CHARACTER_GRASS_GRUNT_MALE: InvasionNpcDisplaySettingsGrassGruntMale;
	CHARACTER_GROUND_GRUNT_FEMALE: InvasionNpcDisplaySettingsGroundGruntFemale;
	CHARACTER_GROUND_GRUNT_MALE: InvasionNpcDisplaySettingsGroundGruntMale;
	CHARACTER_GRUNT_FEMALE: InvasionNpcDisplaySettingsGruntFemale;
	CHARACTER_GRUNT_MALE: InvasionNpcDisplaySettingsGruntMale;
	CHARACTER_GRUNTB_FEMALE: InvasionNpcDisplaySettingsGruntbFemale;
	CHARACTER_GRUNTB_MALE: InvasionNpcDisplaySettingsGruntbMale;
	CHARACTER_ICE_GRUNT_FEMALE: InvasionNpcDisplaySettingsIceGruntFemale;
	CHARACTER_ICE_GRUNT_MALE: InvasionNpcDisplaySettingsIceGruntMale;
	CHARACTER_METAL_GRUNT_FEMALE: InvasionNpcDisplaySettingsMetalGruntFemale;
	CHARACTER_METAL_GRUNT_MALE: InvasionNpcDisplaySettingsMetalGruntMale;
	CHARACTER_NORMAL_GRUNT_FEMALE: InvasionNpcDisplaySettingsNormalGruntFemale;
	CHARACTER_NORMAL_GRUNT_MALE: InvasionNpcDisplaySettingsNormalGruntMale;
	CHARACTER_POISON_GRUNT_FEMALE: InvasionNpcDisplaySettingsPoisonGruntFemale;
	CHARACTER_POISON_GRUNT_MALE: InvasionNpcDisplaySettingsPoisonGruntMale;
	CHARACTER_PSYCHIC_GRUNT_FEMALE: InvasionNpcDisplaySettingsPsychicGruntFemale;
	CHARACTER_PSYCHIC_GRUNT_MALE: InvasionNpcDisplaySettingsPsychicGruntMale;
	CHARACTER_ROCK_GRUNT_FEMALE: InvasionNpcDisplaySettingsRockGruntFemale;
	CHARACTER_ROCK_GRUNT_MALE: InvasionNpcDisplaySettingsRockGruntMale;
	CHARACTER_SPARK: InvasionNpcDisplaySettingsSpark;
	CHARACTER_WATER_GRUNT_FEMALE: InvasionNpcDisplaySettingsWaterGruntFemale;
	CHARACTER_WATER_GRUNT_MALE: InvasionNpcDisplaySettingsWaterGruntMale;
	CHARACTER_WILLOW: InvasionNpcDisplaySettingsWillow;
	CHARACTER_WILLOWB: InvasionNpcDisplaySettingsWillowb;
}
