// Generated from Pokémon GO masterfile — "moveSequenceSettings" lookup table.

import type {
	MoveSequenceSettingsAcidFast,
	MoveSequenceSettingsAcidSpray,
	MoveSequenceSettingsAcrobatics,
	MoveSequenceSettingsAerialAce,
	MoveSequenceSettingsAeroblast,
	MoveSequenceSettingsAirCutter,
	MoveSequenceSettingsAirSlashFast,
	MoveSequenceSettingsAncientPower,
	MoveSequenceSettingsAquaJet,
	MoveSequenceSettingsAquaStep,
	MoveSequenceSettingsAquaTail,
	MoveSequenceSettingsAstonishFast,
	MoveSequenceSettingsAuraSphere,
	MoveSequenceSettingsAuraWheelDark,
	MoveSequenceSettingsAuraWheelElectric,
	MoveSequenceSettingsAuroraBeam,
	MoveSequenceSettingsAvalanche,
	MoveSequenceSettingsBeakBlast,
	MoveSequenceSettingsBehemothBash,
	MoveSequenceSettingsBehemothBlade,
	MoveSequenceSettingsBiteFast,
	MoveSequenceSettingsBlastBurn,
	MoveSequenceSettingsBlazeKick,
	MoveSequenceSettingsBleakwindStorm,
	MoveSequenceSettingsBlizzard,
	MoveSequenceSettingsBodySlam,
	MoveSequenceSettingsBoneClub,
	MoveSequenceSettingsBoomburst,
	MoveSequenceSettingsBraveBird,
	MoveSequenceSettingsBreakingSwipe,
	MoveSequenceSettingsBrickBreak,
	MoveSequenceSettingsBrine,
	MoveSequenceSettingsBrutalSwing,
	MoveSequenceSettingsBubbleBeam,
	MoveSequenceSettingsBubbleFast,
	MoveSequenceSettingsBugBiteFast,
	MoveSequenceSettingsBugBuzz,
	MoveSequenceSettingsBulldoze,
	MoveSequenceSettingsBulletPunchFast,
	MoveSequenceSettingsBulletSeedFast,
	MoveSequenceSettingsChargeBeamFast,
	MoveSequenceSettingsCharmFast,
	MoveSequenceSettingsChillingWater,
	MoveSequenceSettingsClangingScales,
	MoveSequenceSettingsCloseCombat,
	MoveSequenceSettingsConfusionFast,
	MoveSequenceSettingsCounterFast,
	MoveSequenceSettingsCrabhammer,
	MoveSequenceSettingsCrossChop,
	MoveSequenceSettingsCrossPoison,
	MoveSequenceSettingsCrunch,
	MoveSequenceSettingsCrushClaw,
	MoveSequenceSettingsCrushGrip,
	MoveSequenceSettingsCutFast,
	MoveSequenceSettingsDarkPulse,
	MoveSequenceSettingsDarkestLariat,
	MoveSequenceSettingsDazzlingGleam,
	MoveSequenceSettingsDefault,
	MoveSequenceSettingsDig,
	MoveSequenceSettingsDisarmingVoice,
	MoveSequenceSettingsDischarge,
	MoveSequenceSettingsDoomDesire,
	MoveSequenceSettingsDoubleIronBash,
	MoveSequenceSettingsDoubleKickFast,
	MoveSequenceSettingsDracoMeteor,
	MoveSequenceSettingsDragonAscent,
	MoveSequenceSettingsDragonBreathFast,
	MoveSequenceSettingsDragonClaw,
	MoveSequenceSettingsDragonEnergy,
	MoveSequenceSettingsDragonPulse,
	MoveSequenceSettingsDragonTailFast,
	MoveSequenceSettingsDrainPunch,
	MoveSequenceSettingsDrainingKiss,
	MoveSequenceSettingsDrillPeck,
	MoveSequenceSettingsDrillRun,
	MoveSequenceSettingsDrumBeating,
	MoveSequenceSettingsDynamaxCannon,
	MoveSequenceSettingsDynamicPunch,
	MoveSequenceSettingsEarthPower,
	MoveSequenceSettingsEarthquake,
	MoveSequenceSettingsEmberFast,
	MoveSequenceSettingsEnergyBall,
	MoveSequenceSettingsExtrasensoryFast,
	MoveSequenceSettingsFairyWindFast,
	MoveSequenceSettingsFeatherDance,
	MoveSequenceSettingsFeintAttackFast,
	MoveSequenceSettingsFellStinger,
	MoveSequenceSettingsFireBlast,
	MoveSequenceSettingsFireFangFast,
	MoveSequenceSettingsFirePunch,
	MoveSequenceSettingsFireSpinFast,
	MoveSequenceSettingsFissure,
	MoveSequenceSettingsFlameBurst,
	MoveSequenceSettingsFlameCharge,
	MoveSequenceSettingsFlameWheel,
	MoveSequenceSettingsFlamethrower,
	MoveSequenceSettingsFlashCannon,
	MoveSequenceSettingsFlowerTrick,
	MoveSequenceSettingsFly,
	MoveSequenceSettingsFocusBlast,
	MoveSequenceSettingsForcePalmFast,
	MoveSequenceSettingsFoulPlay,
	MoveSequenceSettingsFreezeShock,
	MoveSequenceSettingsFrenzyPlant,
	MoveSequenceSettingsFrostBreathFast,
	MoveSequenceSettingsFrustration,
	MoveSequenceSettingsFuryCutterFast,
	MoveSequenceSettingsFusionBolt,
	MoveSequenceSettingsFusionFlare,
	MoveSequenceSettingsFuturesight,
	MoveSequenceSettingsGeomancyFast,
	MoveSequenceSettingsGigaDrain,
	MoveSequenceSettingsGigaImpact,
	MoveSequenceSettingsGigatonHammer,
	MoveSequenceSettingsGlaciate,
	MoveSequenceSettingsGrassKnot,
	MoveSequenceSettingsGunkShot,
	MoveSequenceSettingsGustFast,
	MoveSequenceSettingsGyroBall,
	MoveSequenceSettingsHeartStamp,
	MoveSequenceSettingsHeatWave,
	MoveSequenceSettingsHeavySlam,
	MoveSequenceSettingsHexFast,
	MoveSequenceSettingsHiddenPowerFast,
	MoveSequenceSettingsHighHorsepower,
	MoveSequenceSettingsHighJumpKick,
	MoveSequenceSettingsHornAttack,
	MoveSequenceSettingsHornDrill,
	MoveSequenceSettingsHurricane,
	MoveSequenceSettingsHydroCannon,
	MoveSequenceSettingsHydroPump,
	MoveSequenceSettingsHydroPumpBlastoise,
	MoveSequenceSettingsHyperBeam,
	MoveSequenceSettingsHyperFang,
	MoveSequenceSettingsIceBeam,
	MoveSequenceSettingsIceBurn,
	MoveSequenceSettingsIceFangFast,
	MoveSequenceSettingsIcePunch,
	MoveSequenceSettingsIceShardFast,
	MoveSequenceSettingsIcicleSpear,
	MoveSequenceSettingsIcyWind,
	MoveSequenceSettingsIncinerateFast,
	MoveSequenceSettingsInfestationFast,
	MoveSequenceSettingsIronHead,
	MoveSequenceSettingsIronTailFast,
	MoveSequenceSettingsKarateChopFast,
	MoveSequenceSettingsLastResort,
	MoveSequenceSettingsLeafBlade,
	MoveSequenceSettingsLeafStorm,
	MoveSequenceSettingsLeafTornado,
	MoveSequenceSettingsLeafageFast,
	MoveSequenceSettingsLeechLife,
	MoveSequenceSettingsLickFast,
	MoveSequenceSettingsLiquidation,
	MoveSequenceSettingsLockOnFast,
	MoveSequenceSettingsLowKickFast,
	MoveSequenceSettingsLowSweep,
	MoveSequenceSettingsLunge,
	MoveSequenceSettingsLusterPurge,
	MoveSequenceSettingsMagicalLeafFast,
	MoveSequenceSettingsMagmaStorm,
	MoveSequenceSettingsMagnetBomb,
	MoveSequenceSettingsMegaDrain,
	MoveSequenceSettingsMegahorn,
	MoveSequenceSettingsMetalClawFast,
	MoveSequenceSettingsMetalSound,
	MoveSequenceSettingsMeteorBeam,
	MoveSequenceSettingsMeteorMash,
	MoveSequenceSettingsMindBlown,
	MoveSequenceSettingsMirrorCoat,
	MoveSequenceSettingsMirrorShot,
	MoveSequenceSettingsMistBall,
	MoveSequenceSettingsMoonblast,
	MoveSequenceSettingsMoongeistBeam,
	MoveSequenceSettingsMudBomb,
	MoveSequenceSettingsMudShotFast,
	MoveSequenceSettingsMudSlapFast,
	MoveSequenceSettingsMuddyWater,
	MoveSequenceSettingsMystFire,
	MoveSequenceSettingsNaturesMadness,
	MoveSequenceSettingsNightShade,
	MoveSequenceSettingsNightSlash,
	MoveSequenceSettingsOblivionWing,
	MoveSequenceSettingsObstruct,
	MoveSequenceSettingsOctazooka,
	MoveSequenceSettingsOminousWind,
	MoveSequenceSettingsOriginPulse,
	MoveSequenceSettingsOutrage,
	MoveSequenceSettingsOverheat,
	MoveSequenceSettingsParabolicCharge,
	MoveSequenceSettingsPayback,
	MoveSequenceSettingsPeckFast,
	MoveSequenceSettingsPetalBlizzard,
	MoveSequenceSettingsPlayRough,
	MoveSequenceSettingsPoisonFang,
	MoveSequenceSettingsPoisonJabFast,
	MoveSequenceSettingsPoisonStingFast,
	MoveSequenceSettingsPoltergeist,
	MoveSequenceSettingsPoundFast,
	MoveSequenceSettingsPowderSnowFast,
	MoveSequenceSettingsPowerGem,
	MoveSequenceSettingsPowerUpPunch,
	MoveSequenceSettingsPowerWhip,
	MoveSequenceSettingsPrecipiceBlades,
	MoveSequenceSettingsPresentFast,
	MoveSequenceSettingsPsybeam,
	MoveSequenceSettingsPsychic,
	MoveSequenceSettingsPsychicFangs,
	MoveSequenceSettingsPsychoBoost,
	MoveSequenceSettingsPsychoCutFast,
	MoveSequenceSettingsPsyshock,
	MoveSequenceSettingsPsystrike,
	MoveSequenceSettingsPsywave,
	MoveSequenceSettingsPyroball,
	MoveSequenceSettingsQuickAttackFast,
	MoveSequenceSettingsRageFist,
	MoveSequenceSettingsRazorLeafFast,
	MoveSequenceSettingsRazorShell,
	MoveSequenceSettingsRest,
	MoveSequenceSettingsReturn,
	MoveSequenceSettingsRoarOfTime,
	MoveSequenceSettingsRockBlast,
	MoveSequenceSettingsRockSlide,
	MoveSequenceSettingsRockSmashFast,
	MoveSequenceSettingsRockThrowFast,
	MoveSequenceSettingsRockTomb,
	MoveSequenceSettingsRockWrecker,
	MoveSequenceSettingsRolloutFast,
	MoveSequenceSettingsSacredFire,
	MoveSequenceSettingsSacredSword,
	MoveSequenceSettingsSandAttack,
	MoveSequenceSettingsSandTomb,
	MoveSequenceSettingsSandsearStorm,
	MoveSequenceSettingsScald,
	MoveSequenceSettingsScaldBlastoise,
	MoveSequenceSettingsScorchingSands,
	MoveSequenceSettingsScratchFast,
	MoveSequenceSettingsSecretSword,
	MoveSequenceSettingsSeedBomb,
	MoveSequenceSettingsSeedFlare,
	MoveSequenceSettingsSeqCombatFaint,
	MoveSequenceSettingsSeqCombatFaintEnding,
	MoveSequenceSettingsSeqCombatReturn,
	MoveSequenceSettingsSeqDing,
	MoveSequenceSettingsSeqDramaticFaint,
	MoveSequenceSettingsSeqFaint,
	MoveSequenceSettingsSeqFortFaint,
	MoveSequenceSettingsSeqIntro,
	MoveSequenceSettingsSeqOutro,
	MoveSequenceSettingsSeqReturn,
	MoveSequenceSettingsSeqTransform,
	MoveSequenceSettingsSeqTransformDark,
	MoveSequenceSettingsSeqTransformFast,
	MoveSequenceSettingsShadowBall,
	MoveSequenceSettingsShadowBone,
	MoveSequenceSettingsShadowClawFast,
	MoveSequenceSettingsShadowForce,
	MoveSequenceSettingsShadowPunch,
	MoveSequenceSettingsShadowSneak,
	MoveSequenceSettingsSignalBeam,
	MoveSequenceSettingsSilverWind,
	MoveSequenceSettingsSkullBash,
	MoveSequenceSettingsSkyAttack,
	MoveSequenceSettingsSludge,
	MoveSequenceSettingsSludgeBomb,
	MoveSequenceSettingsSludgeWave,
	MoveSequenceSettingsSmackDown,
	MoveSequenceSettingsSmackDownFast,
	MoveSequenceSettingsSnarlFast,
	MoveSequenceSettingsSolarBeam,
	MoveSequenceSettingsSpacialRend,
	MoveSequenceSettingsSparkFast,
	MoveSequenceSettingsSparklingAria,
	MoveSequenceSettingsSpiritShackle,
	MoveSequenceSettingsSplashFast,
	MoveSequenceSettingsSteelWingFast,
	MoveSequenceSettingsStomp,
	MoveSequenceSettingsStoneEdge,
	MoveSequenceSettingsStruggle,
	MoveSequenceSettingsStruggleBugFast,
	MoveSequenceSettingsSubmission,
	MoveSequenceSettingsSuckerPunchFast,
	MoveSequenceSettingsSunsteelStrike,
	MoveSequenceSettingsSuperPower,
	MoveSequenceSettingsSurf,
	MoveSequenceSettingsSwift,
	MoveSequenceSettingsSynchronoise,
	MoveSequenceSettingsTackleFast,
	MoveSequenceSettingsTakeDownFast,
	MoveSequenceSettingsTechnoBlastBurn,
	MoveSequenceSettingsTechnoBlastChill,
	MoveSequenceSettingsTechnoBlastNormal,
	MoveSequenceSettingsTechnoBlastShock,
	MoveSequenceSettingsTechnoBlastWater,
	MoveSequenceSettingsThunder,
	MoveSequenceSettingsThunderCage,
	MoveSequenceSettingsThunderFangFast,
	MoveSequenceSettingsThunderPunch,
	MoveSequenceSettingsThunderShockFast,
	MoveSequenceSettingsThunderbolt,
	MoveSequenceSettingsTorchSong,
	MoveSequenceSettingsTrailblaze,
	MoveSequenceSettingsTriAttack,
	MoveSequenceSettingsTripleAxel,
	MoveSequenceSettingsTwister,
	MoveSequenceSettingsUpperHand,
	MoveSequenceSettingsVCreate,
	MoveSequenceSettingsViceGrip,
	MoveSequenceSettingsVineWhipFast,
	MoveSequenceSettingsVoltSwitchFast,
	MoveSequenceSettingsVoltTackle,
	MoveSequenceSettingsWaterGunFast,
	MoveSequenceSettingsWaterGunFastBlastoise,
	MoveSequenceSettingsWaterPulse,
	MoveSequenceSettingsWaterShurikenFast,
	MoveSequenceSettingsWaterfallFast,
	MoveSequenceSettingsWeatherBallFire,
	MoveSequenceSettingsWeatherBallIce,
	MoveSequenceSettingsWeatherBallNormal,
	MoveSequenceSettingsWeatherBallRock,
	MoveSequenceSettingsWeatherBallWater,
	MoveSequenceSettingsWildCharge,
	MoveSequenceSettingsWildboltStorm,
	MoveSequenceSettingsWingAttackFast,
	MoveSequenceSettingsWrap,
	MoveSequenceSettingsWrapGreen,
	MoveSequenceSettingsWrapPink,
	MoveSequenceSettingsXScissor,
	MoveSequenceSettingsYawnFast,
	MoveSequenceSettingsZapCannon,
	MoveSequenceSettingsZenHeadbuttFast,
} from "pogo-masterfile-types/entries";

export interface MoveSequenceSettingsLookup {
	sequence_acid_fast: MoveSequenceSettingsAcidFast;
	sequence_acid_spray: MoveSequenceSettingsAcidSpray;
	sequence_acrobatics: MoveSequenceSettingsAcrobatics;
	sequence_aerial_ace: MoveSequenceSettingsAerialAce;
	sequence_aeroblast: MoveSequenceSettingsAeroblast;
	sequence_air_cutter: MoveSequenceSettingsAirCutter;
	sequence_air_slash_fast: MoveSequenceSettingsAirSlashFast;
	sequence_ancient_power: MoveSequenceSettingsAncientPower;
	sequence_aqua_jet: MoveSequenceSettingsAquaJet;
	sequence_aqua_step: MoveSequenceSettingsAquaStep;
	sequence_aqua_tail: MoveSequenceSettingsAquaTail;
	sequence_astonish_fast: MoveSequenceSettingsAstonishFast;
	sequence_aura_sphere: MoveSequenceSettingsAuraSphere;
	sequence_aura_wheel_dark: MoveSequenceSettingsAuraWheelDark;
	sequence_aura_wheel_electric: MoveSequenceSettingsAuraWheelElectric;
	sequence_aurora_beam: MoveSequenceSettingsAuroraBeam;
	sequence_avalanche: MoveSequenceSettingsAvalanche;
	sequence_beak_blast: MoveSequenceSettingsBeakBlast;
	sequence_behemoth_bash: MoveSequenceSettingsBehemothBash;
	sequence_behemoth_blade: MoveSequenceSettingsBehemothBlade;
	sequence_bite_fast: MoveSequenceSettingsBiteFast;
	sequence_blast_burn: MoveSequenceSettingsBlastBurn;
	sequence_blaze_kick: MoveSequenceSettingsBlazeKick;
	sequence_bleakwind_storm: MoveSequenceSettingsBleakwindStorm;
	sequence_blizzard: MoveSequenceSettingsBlizzard;
	sequence_body_slam: MoveSequenceSettingsBodySlam;
	sequence_bone_club: MoveSequenceSettingsBoneClub;
	sequence_boomburst: MoveSequenceSettingsBoomburst;
	sequence_brave_bird: MoveSequenceSettingsBraveBird;
	sequence_breaking_swipe: MoveSequenceSettingsBreakingSwipe;
	sequence_brick_break: MoveSequenceSettingsBrickBreak;
	sequence_brine: MoveSequenceSettingsBrine;
	sequence_brutal_swing: MoveSequenceSettingsBrutalSwing;
	sequence_bubble_beam: MoveSequenceSettingsBubbleBeam;
	sequence_bubble_fast: MoveSequenceSettingsBubbleFast;
	sequence_bug_bite_fast: MoveSequenceSettingsBugBiteFast;
	sequence_bug_buzz: MoveSequenceSettingsBugBuzz;
	sequence_bulldoze: MoveSequenceSettingsBulldoze;
	sequence_bullet_punch_fast: MoveSequenceSettingsBulletPunchFast;
	sequence_bullet_seed_fast: MoveSequenceSettingsBulletSeedFast;
	sequence_charge_beam_fast: MoveSequenceSettingsChargeBeamFast;
	sequence_charm_fast: MoveSequenceSettingsCharmFast;
	sequence_chilling_water: MoveSequenceSettingsChillingWater;
	sequence_clanging_scales: MoveSequenceSettingsClangingScales;
	sequence_close_combat: MoveSequenceSettingsCloseCombat;
	sequence_confusion_fast: MoveSequenceSettingsConfusionFast;
	sequence_counter_fast: MoveSequenceSettingsCounterFast;
	sequence_crabhammer: MoveSequenceSettingsCrabhammer;
	sequence_cross_chop: MoveSequenceSettingsCrossChop;
	sequence_cross_poison: MoveSequenceSettingsCrossPoison;
	sequence_crunch: MoveSequenceSettingsCrunch;
	sequence_crush_claw: MoveSequenceSettingsCrushClaw;
	sequence_crush_grip: MoveSequenceSettingsCrushGrip;
	sequence_cut_fast: MoveSequenceSettingsCutFast;
	sequence_dark_pulse: MoveSequenceSettingsDarkPulse;
	sequence_darkest_lariat: MoveSequenceSettingsDarkestLariat;
	sequence_dazzling_gleam: MoveSequenceSettingsDazzlingGleam;
	sequence_default: MoveSequenceSettingsDefault;
	sequence_dig: MoveSequenceSettingsDig;
	sequence_disarming_voice: MoveSequenceSettingsDisarmingVoice;
	sequence_discharge: MoveSequenceSettingsDischarge;
	sequence_doom_desire: MoveSequenceSettingsDoomDesire;
	sequence_double_iron_bash: MoveSequenceSettingsDoubleIronBash;
	sequence_double_kick_fast: MoveSequenceSettingsDoubleKickFast;
	sequence_draco_meteor: MoveSequenceSettingsDracoMeteor;
	sequence_dragon_ascent: MoveSequenceSettingsDragonAscent;
	sequence_dragon_breath_fast: MoveSequenceSettingsDragonBreathFast;
	sequence_dragon_claw: MoveSequenceSettingsDragonClaw;
	sequence_dragon_energy: MoveSequenceSettingsDragonEnergy;
	sequence_dragon_pulse: MoveSequenceSettingsDragonPulse;
	sequence_dragon_tail_fast: MoveSequenceSettingsDragonTailFast;
	sequence_drain_punch: MoveSequenceSettingsDrainPunch;
	sequence_draining_kiss: MoveSequenceSettingsDrainingKiss;
	sequence_drill_peck: MoveSequenceSettingsDrillPeck;
	sequence_drill_run: MoveSequenceSettingsDrillRun;
	sequence_drum_beating: MoveSequenceSettingsDrumBeating;
	sequence_dynamax_cannon: MoveSequenceSettingsDynamaxCannon;
	sequence_dynamic_punch: MoveSequenceSettingsDynamicPunch;
	sequence_earth_power: MoveSequenceSettingsEarthPower;
	sequence_earthquake: MoveSequenceSettingsEarthquake;
	sequence_ember_fast: MoveSequenceSettingsEmberFast;
	sequence_energy_ball: MoveSequenceSettingsEnergyBall;
	sequence_extrasensory_fast: MoveSequenceSettingsExtrasensoryFast;
	sequence_fairy_wind_fast: MoveSequenceSettingsFairyWindFast;
	sequence_feather_dance: MoveSequenceSettingsFeatherDance;
	sequence_feint_attack_fast: MoveSequenceSettingsFeintAttackFast;
	sequence_fell_stinger: MoveSequenceSettingsFellStinger;
	sequence_fire_blast: MoveSequenceSettingsFireBlast;
	sequence_fire_fang_fast: MoveSequenceSettingsFireFangFast;
	sequence_fire_punch: MoveSequenceSettingsFirePunch;
	sequence_fire_spin_fast: MoveSequenceSettingsFireSpinFast;
	sequence_fissure: MoveSequenceSettingsFissure;
	sequence_flame_burst: MoveSequenceSettingsFlameBurst;
	sequence_flame_charge: MoveSequenceSettingsFlameCharge;
	sequence_flame_wheel: MoveSequenceSettingsFlameWheel;
	sequence_flamethrower: MoveSequenceSettingsFlamethrower;
	sequence_flash_cannon: MoveSequenceSettingsFlashCannon;
	sequence_flower_trick: MoveSequenceSettingsFlowerTrick;
	sequence_fly: MoveSequenceSettingsFly;
	sequence_focus_blast: MoveSequenceSettingsFocusBlast;
	sequence_force_palm_fast: MoveSequenceSettingsForcePalmFast;
	sequence_foul_play: MoveSequenceSettingsFoulPlay;
	sequence_freeze_shock: MoveSequenceSettingsFreezeShock;
	sequence_frenzy_plant: MoveSequenceSettingsFrenzyPlant;
	sequence_frost_breath_fast: MoveSequenceSettingsFrostBreathFast;
	sequence_frustration: MoveSequenceSettingsFrustration;
	sequence_fury_cutter_fast: MoveSequenceSettingsFuryCutterFast;
	sequence_fusion_bolt: MoveSequenceSettingsFusionBolt;
	sequence_fusion_flare: MoveSequenceSettingsFusionFlare;
	sequence_futuresight: MoveSequenceSettingsFuturesight;
	sequence_geomancy_fast: MoveSequenceSettingsGeomancyFast;
	sequence_giga_drain: MoveSequenceSettingsGigaDrain;
	sequence_giga_impact: MoveSequenceSettingsGigaImpact;
	sequence_gigaton_hammer: MoveSequenceSettingsGigatonHammer;
	sequence_glaciate: MoveSequenceSettingsGlaciate;
	sequence_grass_knot: MoveSequenceSettingsGrassKnot;
	sequence_gunk_shot: MoveSequenceSettingsGunkShot;
	sequence_gust_fast: MoveSequenceSettingsGustFast;
	sequence_gyro_ball: MoveSequenceSettingsGyroBall;
	sequence_heart_stamp: MoveSequenceSettingsHeartStamp;
	sequence_heat_wave: MoveSequenceSettingsHeatWave;
	sequence_heavy_slam: MoveSequenceSettingsHeavySlam;
	sequence_hex_fast: MoveSequenceSettingsHexFast;
	sequence_hidden_power_fast: MoveSequenceSettingsHiddenPowerFast;
	sequence_high_horsepower: MoveSequenceSettingsHighHorsepower;
	sequence_high_jump_kick: MoveSequenceSettingsHighJumpKick;
	sequence_horn_attack: MoveSequenceSettingsHornAttack;
	sequence_horn_drill: MoveSequenceSettingsHornDrill;
	sequence_hurricane: MoveSequenceSettingsHurricane;
	sequence_hydro_cannon: MoveSequenceSettingsHydroCannon;
	sequence_hydro_pump: MoveSequenceSettingsHydroPump;
	sequence_hydro_pump_blastoise: MoveSequenceSettingsHydroPumpBlastoise;
	sequence_hyper_beam: MoveSequenceSettingsHyperBeam;
	sequence_hyper_fang: MoveSequenceSettingsHyperFang;
	sequence_ice_beam: MoveSequenceSettingsIceBeam;
	sequence_ice_burn: MoveSequenceSettingsIceBurn;
	sequence_ice_fang_fast: MoveSequenceSettingsIceFangFast;
	sequence_ice_punch: MoveSequenceSettingsIcePunch;
	sequence_ice_shard_fast: MoveSequenceSettingsIceShardFast;
	sequence_icicle_spear: MoveSequenceSettingsIcicleSpear;
	sequence_icy_wind: MoveSequenceSettingsIcyWind;
	sequence_incinerate_fast: MoveSequenceSettingsIncinerateFast;
	sequence_infestation_fast: MoveSequenceSettingsInfestationFast;
	sequence_iron_head: MoveSequenceSettingsIronHead;
	sequence_iron_tail_fast: MoveSequenceSettingsIronTailFast;
	sequence_karate_chop_fast: MoveSequenceSettingsKarateChopFast;
	sequence_last_resort: MoveSequenceSettingsLastResort;
	sequence_leaf_blade: MoveSequenceSettingsLeafBlade;
	sequence_leaf_storm: MoveSequenceSettingsLeafStorm;
	sequence_leaf_tornado: MoveSequenceSettingsLeafTornado;
	sequence_leafage_fast: MoveSequenceSettingsLeafageFast;
	sequence_leech_life: MoveSequenceSettingsLeechLife;
	sequence_lick_fast: MoveSequenceSettingsLickFast;
	sequence_liquidation: MoveSequenceSettingsLiquidation;
	sequence_lock_on_fast: MoveSequenceSettingsLockOnFast;
	sequence_low_kick_fast: MoveSequenceSettingsLowKickFast;
	sequence_low_sweep: MoveSequenceSettingsLowSweep;
	sequence_lunge: MoveSequenceSettingsLunge;
	sequence_luster_purge: MoveSequenceSettingsLusterPurge;
	sequence_magical_leaf_fast: MoveSequenceSettingsMagicalLeafFast;
	sequence_magma_storm: MoveSequenceSettingsMagmaStorm;
	sequence_magnet_bomb: MoveSequenceSettingsMagnetBomb;
	sequence_mega_drain: MoveSequenceSettingsMegaDrain;
	sequence_megahorn: MoveSequenceSettingsMegahorn;
	sequence_metal_claw_fast: MoveSequenceSettingsMetalClawFast;
	sequence_metal_sound: MoveSequenceSettingsMetalSound;
	sequence_meteor_beam: MoveSequenceSettingsMeteorBeam;
	sequence_meteor_mash: MoveSequenceSettingsMeteorMash;
	sequence_mind_blown: MoveSequenceSettingsMindBlown;
	sequence_mirror_coat: MoveSequenceSettingsMirrorCoat;
	sequence_mirror_shot: MoveSequenceSettingsMirrorShot;
	sequence_mist_ball: MoveSequenceSettingsMistBall;
	sequence_moonblast: MoveSequenceSettingsMoonblast;
	sequence_moongeist_beam: MoveSequenceSettingsMoongeistBeam;
	sequence_mud_bomb: MoveSequenceSettingsMudBomb;
	sequence_mud_shot_fast: MoveSequenceSettingsMudShotFast;
	sequence_mud_slap_fast: MoveSequenceSettingsMudSlapFast;
	sequence_muddy_water: MoveSequenceSettingsMuddyWater;
	sequence_myst_fire: MoveSequenceSettingsMystFire;
	sequence_natures_madness: MoveSequenceSettingsNaturesMadness;
	sequence_night_shade: MoveSequenceSettingsNightShade;
	sequence_night_slash: MoveSequenceSettingsNightSlash;
	sequence_oblivion_wing: MoveSequenceSettingsOblivionWing;
	sequence_obstruct: MoveSequenceSettingsObstruct;
	sequence_octazooka: MoveSequenceSettingsOctazooka;
	sequence_ominous_wind: MoveSequenceSettingsOminousWind;
	sequence_origin_pulse: MoveSequenceSettingsOriginPulse;
	sequence_outrage: MoveSequenceSettingsOutrage;
	sequence_overheat: MoveSequenceSettingsOverheat;
	sequence_parabolic_charge: MoveSequenceSettingsParabolicCharge;
	sequence_payback: MoveSequenceSettingsPayback;
	sequence_peck_fast: MoveSequenceSettingsPeckFast;
	sequence_petal_blizzard: MoveSequenceSettingsPetalBlizzard;
	sequence_play_rough: MoveSequenceSettingsPlayRough;
	sequence_poison_fang: MoveSequenceSettingsPoisonFang;
	sequence_poison_jab_fast: MoveSequenceSettingsPoisonJabFast;
	sequence_poison_sting_fast: MoveSequenceSettingsPoisonStingFast;
	sequence_poltergeist: MoveSequenceSettingsPoltergeist;
	sequence_pound_fast: MoveSequenceSettingsPoundFast;
	sequence_powder_snow_fast: MoveSequenceSettingsPowderSnowFast;
	sequence_power_gem: MoveSequenceSettingsPowerGem;
	sequence_power_up_punch: MoveSequenceSettingsPowerUpPunch;
	sequence_power_whip: MoveSequenceSettingsPowerWhip;
	sequence_precipice_blades: MoveSequenceSettingsPrecipiceBlades;
	sequence_present_fast: MoveSequenceSettingsPresentFast;
	sequence_psybeam: MoveSequenceSettingsPsybeam;
	sequence_psychic: MoveSequenceSettingsPsychic;
	sequence_psychic_fangs: MoveSequenceSettingsPsychicFangs;
	sequence_psycho_boost: MoveSequenceSettingsPsychoBoost;
	sequence_psycho_cut_fast: MoveSequenceSettingsPsychoCutFast;
	sequence_psyshock: MoveSequenceSettingsPsyshock;
	sequence_psystrike: MoveSequenceSettingsPsystrike;
	sequence_psywave: MoveSequenceSettingsPsywave;
	sequence_pyroball: MoveSequenceSettingsPyroball;
	sequence_quick_attack_fast: MoveSequenceSettingsQuickAttackFast;
	sequence_rage_fist: MoveSequenceSettingsRageFist;
	sequence_razor_leaf_fast: MoveSequenceSettingsRazorLeafFast;
	sequence_razor_shell: MoveSequenceSettingsRazorShell;
	sequence_rest: MoveSequenceSettingsRest;
	sequence_return: MoveSequenceSettingsReturn;
	sequence_roar_of_time: MoveSequenceSettingsRoarOfTime;
	sequence_rock_blast: MoveSequenceSettingsRockBlast;
	sequence_rock_slide: MoveSequenceSettingsRockSlide;
	sequence_rock_smash_fast: MoveSequenceSettingsRockSmashFast;
	sequence_rock_throw_fast: MoveSequenceSettingsRockThrowFast;
	sequence_rock_tomb: MoveSequenceSettingsRockTomb;
	sequence_rock_wrecker: MoveSequenceSettingsRockWrecker;
	sequence_rollout_fast: MoveSequenceSettingsRolloutFast;
	sequence_sacred_fire: MoveSequenceSettingsSacredFire;
	sequence_sacred_sword: MoveSequenceSettingsSacredSword;
	sequence_sand_attack: MoveSequenceSettingsSandAttack;
	sequence_sand_tomb: MoveSequenceSettingsSandTomb;
	sequence_sandsear_storm: MoveSequenceSettingsSandsearStorm;
	sequence_scald: MoveSequenceSettingsScald;
	sequence_scald_blastoise: MoveSequenceSettingsScaldBlastoise;
	sequence_scorching_sands: MoveSequenceSettingsScorchingSands;
	sequence_scratch_fast: MoveSequenceSettingsScratchFast;
	sequence_secret_sword: MoveSequenceSettingsSecretSword;
	sequence_seed_bomb: MoveSequenceSettingsSeedBomb;
	sequence_seed_flare: MoveSequenceSettingsSeedFlare;
	sequence_seq_combat_faint: MoveSequenceSettingsSeqCombatFaint;
	sequence_seq_combat_faint_ending: MoveSequenceSettingsSeqCombatFaintEnding;
	sequence_seq_combat_return: MoveSequenceSettingsSeqCombatReturn;
	sequence_seq_ding: MoveSequenceSettingsSeqDing;
	sequence_seq_dramatic_faint: MoveSequenceSettingsSeqDramaticFaint;
	sequence_seq_faint: MoveSequenceSettingsSeqFaint;
	sequence_seq_fort_faint: MoveSequenceSettingsSeqFortFaint;
	sequence_seq_intro: MoveSequenceSettingsSeqIntro;
	sequence_seq_outro: MoveSequenceSettingsSeqOutro;
	sequence_seq_return: MoveSequenceSettingsSeqReturn;
	sequence_seq_transform: MoveSequenceSettingsSeqTransform;
	sequence_seq_transform_dark: MoveSequenceSettingsSeqTransformDark;
	sequence_seq_transform_fast: MoveSequenceSettingsSeqTransformFast;
	sequence_shadow_ball: MoveSequenceSettingsShadowBall;
	sequence_shadow_bone: MoveSequenceSettingsShadowBone;
	sequence_shadow_claw_fast: MoveSequenceSettingsShadowClawFast;
	sequence_shadow_force: MoveSequenceSettingsShadowForce;
	sequence_shadow_punch: MoveSequenceSettingsShadowPunch;
	sequence_shadow_sneak: MoveSequenceSettingsShadowSneak;
	sequence_signal_beam: MoveSequenceSettingsSignalBeam;
	sequence_silver_wind: MoveSequenceSettingsSilverWind;
	sequence_skull_bash: MoveSequenceSettingsSkullBash;
	sequence_sky_attack: MoveSequenceSettingsSkyAttack;
	sequence_sludge: MoveSequenceSettingsSludge;
	sequence_sludge_bomb: MoveSequenceSettingsSludgeBomb;
	sequence_sludge_wave: MoveSequenceSettingsSludgeWave;
	sequence_smack_down: MoveSequenceSettingsSmackDown;
	sequence_smack_down_fast: MoveSequenceSettingsSmackDownFast;
	sequence_snarl_fast: MoveSequenceSettingsSnarlFast;
	sequence_solar_beam: MoveSequenceSettingsSolarBeam;
	sequence_spacial_rend: MoveSequenceSettingsSpacialRend;
	sequence_spark_fast: MoveSequenceSettingsSparkFast;
	sequence_sparkling_aria: MoveSequenceSettingsSparklingAria;
	sequence_spirit_shackle: MoveSequenceSettingsSpiritShackle;
	sequence_splash_fast: MoveSequenceSettingsSplashFast;
	sequence_steel_wing_fast: MoveSequenceSettingsSteelWingFast;
	sequence_stomp: MoveSequenceSettingsStomp;
	sequence_stone_edge: MoveSequenceSettingsStoneEdge;
	sequence_struggle: MoveSequenceSettingsStruggle;
	sequence_struggle_bug_fast: MoveSequenceSettingsStruggleBugFast;
	sequence_submission: MoveSequenceSettingsSubmission;
	sequence_sucker_punch_fast: MoveSequenceSettingsSuckerPunchFast;
	sequence_sunsteel_strike: MoveSequenceSettingsSunsteelStrike;
	sequence_super_power: MoveSequenceSettingsSuperPower;
	sequence_surf: MoveSequenceSettingsSurf;
	sequence_swift: MoveSequenceSettingsSwift;
	sequence_synchronoise: MoveSequenceSettingsSynchronoise;
	sequence_tackle_fast: MoveSequenceSettingsTackleFast;
	sequence_take_down_fast: MoveSequenceSettingsTakeDownFast;
	sequence_techno_blast_burn: MoveSequenceSettingsTechnoBlastBurn;
	sequence_techno_blast_chill: MoveSequenceSettingsTechnoBlastChill;
	sequence_techno_blast_normal: MoveSequenceSettingsTechnoBlastNormal;
	sequence_techno_blast_shock: MoveSequenceSettingsTechnoBlastShock;
	sequence_techno_blast_water: MoveSequenceSettingsTechnoBlastWater;
	sequence_thunder: MoveSequenceSettingsThunder;
	sequence_thunder_cage: MoveSequenceSettingsThunderCage;
	sequence_thunder_fang_fast: MoveSequenceSettingsThunderFangFast;
	sequence_thunder_punch: MoveSequenceSettingsThunderPunch;
	sequence_thunder_shock_fast: MoveSequenceSettingsThunderShockFast;
	sequence_thunderbolt: MoveSequenceSettingsThunderbolt;
	sequence_torch_song: MoveSequenceSettingsTorchSong;
	sequence_trailblaze: MoveSequenceSettingsTrailblaze;
	sequence_tri_attack: MoveSequenceSettingsTriAttack;
	sequence_triple_axel: MoveSequenceSettingsTripleAxel;
	sequence_twister: MoveSequenceSettingsTwister;
	sequence_upper_hand: MoveSequenceSettingsUpperHand;
	sequence_v_create: MoveSequenceSettingsVCreate;
	sequence_vice_grip: MoveSequenceSettingsViceGrip;
	sequence_vine_whip_fast: MoveSequenceSettingsVineWhipFast;
	sequence_volt_switch_fast: MoveSequenceSettingsVoltSwitchFast;
	sequence_volt_tackle: MoveSequenceSettingsVoltTackle;
	sequence_water_gun_fast: MoveSequenceSettingsWaterGunFast;
	sequence_water_gun_fast_blastoise: MoveSequenceSettingsWaterGunFastBlastoise;
	sequence_water_pulse: MoveSequenceSettingsWaterPulse;
	sequence_water_shuriken_fast: MoveSequenceSettingsWaterShurikenFast;
	sequence_waterfall_fast: MoveSequenceSettingsWaterfallFast;
	sequence_weather_ball_fire: MoveSequenceSettingsWeatherBallFire;
	sequence_weather_ball_ice: MoveSequenceSettingsWeatherBallIce;
	sequence_weather_ball_normal: MoveSequenceSettingsWeatherBallNormal;
	sequence_weather_ball_rock: MoveSequenceSettingsWeatherBallRock;
	sequence_weather_ball_water: MoveSequenceSettingsWeatherBallWater;
	sequence_wild_charge: MoveSequenceSettingsWildCharge;
	sequence_wildbolt_storm: MoveSequenceSettingsWildboltStorm;
	sequence_wing_attack_fast: MoveSequenceSettingsWingAttackFast;
	sequence_wrap: MoveSequenceSettingsWrap;
	sequence_wrap_green: MoveSequenceSettingsWrapGreen;
	sequence_wrap_pink: MoveSequenceSettingsWrapPink;
	sequence_x_scissor: MoveSequenceSettingsXScissor;
	sequence_yawn_fast: MoveSequenceSettingsYawnFast;
	sequence_zap_cannon: MoveSequenceSettingsZapCannon;
	sequence_zen_headbutt_fast: MoveSequenceSettingsZenHeadbuttFast;
}
