// Generated from Pokémon GO masterfile — "pokemonHomeFormReversions" lookup table.

import type {
	PokemonHomeFormReversionsV0351PokemonCastformHomeFormReversion,
	PokemonHomeFormReversionsV0421CherrimHomeFormReversion,
	PokemonHomeFormReversionsV0487PokemonGiratinaHomeReversion,
	PokemonHomeFormReversionsV0555PokemonDarmanitanHomeFormReversion,
	PokemonHomeFormReversionsV0647PokemonKeldeoHomeFormReversion,
	PokemonHomeFormReversionsV0648PokemonMeloettaHomeFormReversion,
	PokemonHomeFormReversionsV0649PokemonGenesectHomeFormReversion,
} from "pogo-masterfile-types/entries";

export interface PokemonHomeFormReversionsLookup {
	V0351_POKEMON_CASTFORM_HOME_FORM_REVERSION: PokemonHomeFormReversionsV0351PokemonCastformHomeFormReversion;
	V0421_CHERRIM_HOME_FORM_REVERSION: PokemonHomeFormReversionsV0421CherrimHomeFormReversion;
	V0487_POKEMON_GIRATINA_HOME_REVERSION: PokemonHomeFormReversionsV0487PokemonGiratinaHomeReversion;
	V0555_POKEMON_DARMANITAN_HOME_FORM_REVERSION: PokemonHomeFormReversionsV0555PokemonDarmanitanHomeFormReversion;
	V0647_POKEMON_KELDEO_HOME_FORM_REVERSION: PokemonHomeFormReversionsV0647PokemonKeldeoHomeFormReversion;
	V0648_POKEMON_MELOETTA_HOME_FORM_REVERSION: PokemonHomeFormReversionsV0648PokemonMeloettaHomeFormReversion;
	V0649_POKEMON_GENESECT_HOME_FORM_REVERSION: PokemonHomeFormReversionsV0649PokemonGenesectHomeFormReversion;
}
