// Generated from Pokémon GO masterfile — "recommendedSearchSettings" lookup table.

import type {
	RecommendedSearchSettingsAppraisalIvHigh,
	RecommendedSearchSettingsAppraisalIvLow,
	RecommendedSearchSettingsAppraisalLabelEvolveMega,
	RecommendedSearchSettingsBadgeKantoRegion,
	RecommendedSearchSettingsFilterLabelEvolvable,
	RecommendedSearchSettingsFilterLabelHatched,
	RecommendedSearchSettingsFilterLabelLegendary,
	RecommendedSearchSettingsFilterLabelShiny,
	RecommendedSearchSettingsFilterLabelTraded,
	RecommendedSearchSettingsPokemonTypeNormal,
} from "pogo-masterfile-types/entries";

export interface RecommendedSearchSettingsLookup {
	RECOMMENDED_SEARCH_APPRAISAL_IV_HIGH: RecommendedSearchSettingsAppraisalIvHigh;
	RECOMMENDED_SEARCH_APPRAISAL_IV_LOW: RecommendedSearchSettingsAppraisalIvLow;
	RECOMMENDED_SEARCH_APPRAISAL_LABEL_EVOLVE_MEGA: RecommendedSearchSettingsAppraisalLabelEvolveMega;
	RECOMMENDED_SEARCH_BADGE_KANTO_REGION: RecommendedSearchSettingsBadgeKantoRegion;
	RECOMMENDED_SEARCH_FILTER_LABEL_EVOLVABLE: RecommendedSearchSettingsFilterLabelEvolvable;
	RECOMMENDED_SEARCH_FILTER_LABEL_HATCHED: RecommendedSearchSettingsFilterLabelHatched;
	RECOMMENDED_SEARCH_FILTER_LABEL_LEGENDARY: RecommendedSearchSettingsFilterLabelLegendary;
	RECOMMENDED_SEARCH_FILTER_LABEL_SHINY: RecommendedSearchSettingsFilterLabelShiny;
	RECOMMENDED_SEARCH_FILTER_LABEL_TRADED: RecommendedSearchSettingsFilterLabelTraded;
	RECOMMENDED_SEARCH_POKEMON_TYPE_NORMAL: RecommendedSearchSettingsPokemonTypeNormal;
}
