export function emitSingletonsAccessor(): string {
	return `// Code generated. DO NOT EDIT — regenerated by \`bun run generate\`.

package accessor

import (
	masterfile "github.com/Hazels-Lab/pogo-masterfile-types/packages/go"
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/singletons"
)

// SingletonsAccessor provides lookups across the "singletons" group. Singleton
// entries are heterogeneous — each one is its own concrete *Entry struct in
// the upstream singletons package — so Get returns the wide MasterfileEntry
// interface and the caller type-asserts to the concrete type.
type SingletonsAccessor struct {
	entries []masterfile.MasterfileEntry
	ids     []singletons.SingletonsTemplateID
	index   map[singletons.SingletonsTemplateID]int
}

// NewSingletonsAccessor builds a SingletonsAccessor from a slice of singleton
// entries paired with their resolved templateIDs (since the entries are
// heterogeneous, the caller passes the IDs alongside).
func NewSingletonsAccessor(entries []masterfile.MasterfileEntry, ids []singletons.SingletonsTemplateID) *SingletonsAccessor {
	idx := make(map[singletons.SingletonsTemplateID]int, len(entries))
	for i, id := range ids {
		idx[id] = i
	}
	return &SingletonsAccessor{entries: entries, ids: ids, index: idx}
}

// Get returns the singleton entry registered under id (wide interface — caller
// type-asserts to the concrete singleton struct).
func (a *SingletonsAccessor) Get(id singletons.SingletonsTemplateID) (masterfile.MasterfileEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		return nil, false
	}
	return a.entries[i], true
}

// Has reports whether a singleton with id exists.
func (a *SingletonsAccessor) Has(id singletons.SingletonsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *SingletonsAccessor) All() []masterfile.MasterfileEntry {
	return a.entries
}

// TemplateIDs returns every singleton id in source order (zero-copy view; do not mutate).
func (a *SingletonsAccessor) TemplateIDs() []singletons.SingletonsTemplateID {
	return a.ids
}

// Len returns the number of singleton entries.
func (a *SingletonsAccessor) Len() int {
	return len(a.entries)
}
`;
}
