import type { Group } from "../group.ts";
import { pascalCase, snakeCase } from "../naming.ts";

export function emitMasterfileGen(groups: Map<string, Group>): string {
	const multiEntry = [...groups.values()].filter((g) => g.entries.length > 1);
	const groupNames = multiEntry.map((g) => g.discriminator);

	// Imports — one per multi-entry group, plus singletons + masterfile + accessor.
	const importLines: string[] = [
		'\tmasterfile "github.com/PLACEHOLDER/pogo-masterfile-types/packages/go"',
		'\t"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go-api/accessor"',
		'\t"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/singletons"',
	];
	for (const g of multiEntry) {
		importLines.push(`\t"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/${snakeCase(g.discriminator)}"`);
	}

	// Struct fields — one per multi-entry group, plus Singletons.
	const fieldLines: string[] = [];
	for (const g of multiEntry) {
		fieldLines.push(`\t${pascalCase(g.discriminator)} *accessor.${pascalCase(g.discriminator)}Accessor`);
	}
	fieldLines.push("\tSingletons *accessor.SingletonsAccessor");

	// Bucket declarations — one typed slice per multi-entry group, plus singleton bookkeeping.
	// Variable names use the discriminator directly (already camelCase from JSON keys),
	// which is idiomatic Go.
	const bucketDecls: string[] = [];
	for (const g of multiEntry) {
		const pkg = snakeCase(g.discriminator);
		const eName = `${pascalCase(g.discriminator)}Entry`;
		bucketDecls.push(`\t${g.discriminator}Bucket := []${pkg}.${eName}{}`);
	}
	bucketDecls.push("\tsingletonEntries := []masterfile.MasterfileEntry{}");
	bucketDecls.push("\tsingletonIDs := []singletons.SingletonsTemplateID{}");

	// Switch arms — one per multi-entry group + a wildcard for singletons.
	const switchArms: string[] = [];
	for (const g of multiEntry) {
		const pkg = snakeCase(g.discriminator);
		const eName = `${pascalCase(g.discriminator)}Entry`;
		switchArms.push(`\t\tcase ${pkg}.${eName}:`, `\t\t\tm.byID[v.TemplateID] = i`, `\t\t\t${g.discriminator}Bucket = append(${g.discriminator}Bucket, v)`);
	}
	// Default arm: singletons + anything else falls through into the singletons bucket.
	switchArms.push(
		"\t\tdefault:",
		"\t\t\ttid := singletonTemplateID(v)",
		'\t\t\tif tid != "" {',
		"\t\t\t\tm.byID[tid] = i",
		"\t\t\t\tsingletonEntries = append(singletonEntries, v)",
		"\t\t\t\tsingletonIDs = append(singletonIDs, singletons.SingletonsTemplateID(tid))",
		"\t\t\t}",
	);

	// Accessor wiring at the end of newMasterfile.
	const wiring: string[] = [];
	for (const g of multiEntry) {
		const aName = `${pascalCase(g.discriminator)}Accessor`;
		wiring.push(`\tm.${pascalCase(g.discriminator)} = accessor.New${aName}(${g.discriminator}Bucket)`);
	}
	wiring.push("\tm.Singletons = accessor.NewSingletonsAccessor(singletonEntries, singletonIDs)");

	return `// Code generated. DO NOT EDIT — regenerated by \`bun run generate\`.

package masterfileapi

import (
	"reflect"

${importLines.join("\n")}
)

// Masterfile is the indexed runtime view of a parsed masterfile. Construct via
// FromEntries, Load, or LoadRemote; treat as read-only thereafter.
type Masterfile struct {
	entries []masterfile.MasterfileEntry
	byID    map[string]int

${fieldLines.join("\n")}
}

// GroupNames lists every multi-entry group discriminator in canonical order.
// Singletons are not included — they share a single accessor on Masterfile.
var GroupNames = []string{
${groupNames.map((n) => `\t"${n}",`).join("\n")}
}

func newMasterfile(entries []masterfile.MasterfileEntry) *Masterfile {
	m := &Masterfile{
		entries: entries,
		byID:    make(map[string]int, len(entries)),
	}

${bucketDecls.join("\n")}

	for i, e := range entries {
		switch v := e.(type) {
${switchArms.join("\n")}
		}
	}

${wiring.join("\n")}

	return m
}

// singletonTemplateID extracts the TemplateID field via reflection from a
// singleton entry. Singletons are heterogeneous so we cannot enumerate them
// in the type switch above without producing thousands of arms; reflection is
// used only here, only on the singleton-load slow path.
func singletonTemplateID(e masterfile.MasterfileEntry) string {
	rv := reflect.ValueOf(e)
	if rv.Kind() != reflect.Struct {
		return ""
	}
	f := rv.FieldByName("TemplateID")
	if f.IsValid() && f.Kind() == reflect.String {
		return f.String()
	}
	return ""
}
`;
}
