import type { Group } from "../group.ts";
import { pascalCase, snakeCase } from "../naming.ts";

export function emitAccessor(group: Group): string {
	const disc = group.discriminator; // e.g. "moveSettings"
	const pkg = snakeCase(disc); // "move_settings"
	const tName = `${pascalCase(disc)}TemplateID`; // "MoveSettingsTemplateID"
	const eName = `${pascalCase(disc)}Entry`; // "MoveSettingsEntry"
	const aName = `${pascalCase(disc)}Accessor`; // "MoveSettingsAccessor"

	return `// Code generated. DO NOT EDIT — regenerated by \`bun run generate\`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/${pkg}"
)

// ${aName} provides typed lookups for the "${disc}" group.
type ${aName} struct {
	entries []${pkg}.${eName}
	index   map[${pkg}.${tName}]int
}

// New${aName} builds a ${aName} from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func New${aName}(entries []${pkg}.${eName}) *${aName} {
	idx := make(map[${pkg}.${tName}]int, len(entries))
	for i, e := range entries {
		idx[${pkg}.${tName}(e.TemplateID)] = i
	}
	return &${aName}{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *${aName}) Get(id ${pkg}.${tName}) (${pkg}.${eName}, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero ${pkg}.${eName}
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *${aName}) Has(id ${pkg}.${tName}) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *${aName}) All() []${pkg}.${eName} {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *${aName}) TemplateIDs() []${pkg}.${tName} {
	ids := make([]${pkg}.${tName}, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, ${pkg}.${tName}(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *${aName}) Len() int {
	return len(a.entries)
}
`;
}
