// Generated from Pokémon GO masterfile — group "badgeSettings", 868 entries (structural types).

export type * from "./variants";

export interface BadgeSettings<TemplateID extends string = string, TData extends BadgeSettingsData = BadgeSettingsData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		badgeSettings: TData;
	};
}

export interface BadgeSettingsData {
	badgeRank: number;
	badgeType: number | string;
	captureReward?: [
		object,
		object,
		object,
		object,
		{
			rewardTypes?: ["POKEMON_ENCOUNTER"];
		},
	];
	eventBadge?: boolean;
	eventBadgeSettings?: {
		obEventBadgeSettingsNumber6: number;
	};
	targets: Array<number>;
}

export type BadgeSettingsMasterfileEntry =
	| BadgeSettings7DayStreaks
	| BadgeSettingsAa2023JejuDay00
	| BadgeSettingsAa2023JejuDay01
	| BadgeSettingsAa2023JejuDay02
	| BadgeSettingsAa2023JejuDay03
	| BadgeSettingsAa2024BaliDay00
	| BadgeSettingsAa2024BaliDay01
	| BadgeSettingsAa2024BaliDay02
	| BadgeSettingsAa2024SurabayaDay00
	| BadgeSettingsAa2024SurabayaDay01
	| BadgeSettingsAa2024SurabayaDay02
	| BadgeSettingsAa2024YogyakartaDay00
	| BadgeSettingsAa2024YogyakartaDay01
	| BadgeSettingsAa2024YogyakartaDay02
	| BadgeSettingsApacPartnerJuly20181
	| BadgeSettingsApacPartnerJuly20182
	| BadgeSettingsApacPartnerJuly20183
	| BadgeSettingsApacPartnerJuly20184
	| BadgeSettingsApacPartnerJuly20185
	| BadgeSettingsApacPartnerJuly20186
	| BadgeSettingsApacPartnerJuly20187
	| BadgeSettingsBattleAttackWon
	| BadgeSettingsBattleTrainingWon
	| BadgeSettingsBerriesFed
	| BadgeSettingsBestFriendsPlusEligible
	| BadgeSettingsBigMagikarp
	| BadgeSettingsBuddyBest
	| BadgeSettingsButterflyCollector
	| BadgeSettingsCaptureLargePokemon
	| BadgeSettingsCaptureSmallPokemon
	| BadgeSettingsCaptureTotal
	| BadgeSettingsChallengeQuests
	| BadgeSettingsCheckIns
	| BadgeSettingsChicagoFestJuly2017
	| BadgeSettingsChicagoFestJuly2018SatNorth
	| BadgeSettingsChicagoFestJuly2018SatSouth
	| BadgeSettingsChicagoFestJuly2018SunNorth
	| BadgeSettingsChicagoFestJuly2018SunSouth
	| BadgeSettingsCityExplorerPass00
	| BadgeSettingsCityExplorerPass01
	| BadgeSettingsCityExplorerPass02
	| BadgeSettingsCityExplorerPass03
	| BadgeSettingsEvent0001
	| BadgeSettingsEvent0002
	| BadgeSettingsEvent0003
	| BadgeSettingsEvent0004
	| BadgeSettingsEvent0005
	| BadgeSettingsEvent0006
	| BadgeSettingsEvent0007
	| BadgeSettingsEvent0009
	| BadgeSettingsEvent0010
	| BadgeSettingsEvent0011
	| BadgeSettingsEvent0012
	| BadgeSettingsEvent0013
	| BadgeSettingsEvent0014
	| BadgeSettingsEvent0015
	| BadgeSettingsEvent0016
	| BadgeSettingsEvent0017
	| BadgeSettingsEvent0018
	| BadgeSettingsEvent0019
	| BadgeSettingsEvent0020
	| BadgeSettingsEvent0022
	| BadgeSettingsEvent0023
	| BadgeSettingsEvent0024
	| BadgeSettingsEvent0025
	| BadgeSettingsEvent0026
	| BadgeSettingsEvent0027
	| BadgeSettingsEvent0028
	| BadgeSettingsEvent0029
	| BadgeSettingsEvent0031
	| BadgeSettingsEvent0032
	| BadgeSettingsEvent0033
	| BadgeSettingsEvent0034
	| BadgeSettingsEvent0035
	| BadgeSettingsEvent0036
	| BadgeSettingsEvent0037
	| BadgeSettingsEvent0038
	| BadgeSettingsEvent0039
	| BadgeSettingsEvent0040
	| BadgeSettingsEvent0041
	| BadgeSettingsEvent0043
	| BadgeSettingsEvent0044
	| BadgeSettingsEvent0045
	| BadgeSettingsEvent0046
	| BadgeSettingsEvent0047
	| BadgeSettingsEvent0048
	| BadgeSettingsEvent0049
	| BadgeSettingsEvent0050
	| BadgeSettingsEvent0051
	| BadgeSettingsEvent0052
	| BadgeSettingsEvent0053
	| BadgeSettingsEvent0054
	| BadgeSettingsEvent0055
	| BadgeSettingsEvent0057
	| BadgeSettingsEvent0080
	| BadgeSettingsEvent0103
	| BadgeSettingsEvent0105
	| BadgeSettingsEvent0106
	| BadgeSettingsEvent0107
	| BadgeSettingsEvent0112
	| BadgeSettingsEvent0113
	| BadgeSettingsEvent0114
	| BadgeSettingsEvent0115
	| BadgeSettingsEvent0116
	| BadgeSettingsEvent0117
	| BadgeSettingsEvent0118
	| BadgeSettingsEvent0119
	| BadgeSettingsEvent0120
	| BadgeSettingsEvent0128
	| BadgeSettingsEvent0129
	| BadgeSettingsEvent0130
	| BadgeSettingsEvent0133
	| BadgeSettingsEvent0134
	| BadgeSettingsEvent0135
	| BadgeSettingsEvent0137
	| BadgeSettingsEvent0138
	| BadgeSettingsEvent0139
	| BadgeSettingsEvent0140
	| BadgeSettingsEvent0141
	| BadgeSettingsEvent0142
	| BadgeSettingsEvent0144
	| BadgeSettingsEvent0145
	| BadgeSettingsEvent0146
	| BadgeSettingsEvent0148
	| BadgeSettingsEvent0149
	| BadgeSettingsEvent0151
	| BadgeSettingsEvent0152
	| BadgeSettingsEvent0153
	| BadgeSettingsEvent0154
	| BadgeSettingsEvent0170
	| BadgeSettingsEvent0171
	| BadgeSettingsEvent0172
	| BadgeSettingsEvent0173
	| BadgeSettingsEvent0174
	| BadgeSettingsEvent0175
	| BadgeSettingsEvent0176
	| BadgeSettingsEvent0177
	| BadgeSettingsEvent0178
	| BadgeSettingsEvent0179
	| BadgeSettingsEvent0183
	| BadgeSettingsEvent0184
	| BadgeSettingsEvent0185
	| BadgeSettingsEvent0186
	| BadgeSettingsEvent0187
	| BadgeSettingsEvent0188
	| BadgeSettingsEvent0189
	| BadgeSettingsEvent0194
	| BadgeSettingsEvent0196
	| BadgeSettingsEvent0200
	| BadgeSettingsEvent0280
	| BadgeSettingsEvolvedTotal
	| BadgeSettingsGlobalTicketedEvent
	| BadgeSettingsGofest2019AmericasDay00NorthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay00NorthGeneral
	| BadgeSettingsGofest2019AmericasDay00SouthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay00SouthGeneral
	| BadgeSettingsGofest2019AmericasDay01NorthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay01NorthGeneral
	| BadgeSettingsGofest2019AmericasDay01SouthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay01SouthGeneral
	| BadgeSettingsGofest2019AmericasDay02NorthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay02NorthGeneral
	| BadgeSettingsGofest2019AmericasDay02SouthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay02SouthGeneral
	| BadgeSettingsGofest2019AmericasDay03NorthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay03NorthGeneral
	| BadgeSettingsGofest2019AmericasDay03SouthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay03SouthGeneral
	| BadgeSettingsGofest2019AmericasDay04NorthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay04NorthGeneral
	| BadgeSettingsGofest2019AmericasDay04SouthEarlyaccess
	| BadgeSettingsGofest2019AmericasDay04SouthGeneral
	| BadgeSettingsGofest2019ApacDay00General
	| BadgeSettingsGofest2019ApacDay01General
	| BadgeSettingsGofest2019ApacDay02General
	| BadgeSettingsGofest2019ApacDay03General
	| BadgeSettingsGofest2019ApacDay04General
	| BadgeSettingsGofest2019ApacDay05General
	| BadgeSettingsGofest2019ApacDay06General
	| BadgeSettingsGofest2019ApacDay07General
	| BadgeSettingsGofest2019EmeaDay00Earlyaccess
	| BadgeSettingsGofest2019EmeaDay00General
	| BadgeSettingsGofest2019EmeaDay01Earlyaccess
	| BadgeSettingsGofest2019EmeaDay01General
	| BadgeSettingsGofest2019EmeaDay02Earlyaccess
	| BadgeSettingsGofest2019EmeaDay02General
	| BadgeSettingsGofest2019EmeaDay03Earlyaccess
	| BadgeSettingsGofest2019EmeaDay03General
	| BadgeSettingsGofest2019EmeaDay04Earlyaccess
	| BadgeSettingsGofest2019EmeaDay04General
	| BadgeSettingsGofest2020Global
	| BadgeSettingsGofest2020Test
	| BadgeSettingsGofest2021Global
	| BadgeSettingsGofest2021Test
	| BadgeSettingsGofest2022BerlinAddonHatch
	| BadgeSettingsGofest2022BerlinAddonHatchTest
	| BadgeSettingsGofest2022BerlinAddonRaid
	| BadgeSettingsGofest2022BerlinAddonRaidTest
	| BadgeSettingsGofest2022BerlinDay01Earlyaccess
	| BadgeSettingsGofest2022BerlinDay01General
	| BadgeSettingsGofest2022BerlinDay02Earlyaccess
	| BadgeSettingsGofest2022BerlinDay02General
	| BadgeSettingsGofest2022BerlinDay03Earlyaccess
	| BadgeSettingsGofest2022BerlinDay03General
	| BadgeSettingsGofest2022BerlinTestEarlyaccess
	| BadgeSettingsGofest2022BerlinTestGeneral
	| BadgeSettingsGofest2022Global
	| BadgeSettingsGofest2022SapporoAddonHatch
	| BadgeSettingsGofest2022SapporoAddonHatchTest
	| BadgeSettingsGofest2022SapporoAddonRaid
	| BadgeSettingsGofest2022SapporoAddonRaidTest
	| BadgeSettingsGofest2022SapporoDay01CityAfternoon
	| BadgeSettingsGofest2022SapporoDay01CityMorning
	| BadgeSettingsGofest2022SapporoDay01ParkAfternoon
	| BadgeSettingsGofest2022SapporoDay01ParkMorning
	| BadgeSettingsGofest2022SapporoDay02CityAfternoon
	| BadgeSettingsGofest2022SapporoDay02CityMorning
	| BadgeSettingsGofest2022SapporoDay02ParkAfternoon
	| BadgeSettingsGofest2022SapporoDay02ParkMorning
	| BadgeSettingsGofest2022SapporoDay03CityAfternoon
	| BadgeSettingsGofest2022SapporoDay03CityMorning
	| BadgeSettingsGofest2022SapporoDay03ParkAfternoon
	| BadgeSettingsGofest2022SapporoDay03ParkMorning
	| BadgeSettingsGofest2022SapporoTestCityAfternoon
	| BadgeSettingsGofest2022SapporoTestCityMorning
	| BadgeSettingsGofest2022SapporoTestParkAfternoon
	| BadgeSettingsGofest2022SapporoTestParkMorning
	| BadgeSettingsGofest2022SeattleAddonHatch
	| BadgeSettingsGofest2022SeattleAddonHatchTest
	| BadgeSettingsGofest2022SeattleAddonRaid
	| BadgeSettingsGofest2022SeattleAddonRaidTest
	| BadgeSettingsGofest2022SeattleDay01CityAfternoon
	| BadgeSettingsGofest2022SeattleDay01CityMorning
	| BadgeSettingsGofest2022SeattleDay01ParkAfternoon
	| BadgeSettingsGofest2022SeattleDay01ParkMorning
	| BadgeSettingsGofest2022SeattleDay02CityAfternoon
	| BadgeSettingsGofest2022SeattleDay02CityMorning
	| BadgeSettingsGofest2022SeattleDay02ParkAfternoon
	| BadgeSettingsGofest2022SeattleDay02ParkMorning
	| BadgeSettingsGofest2022SeattleDay03CityAfternoon
	| BadgeSettingsGofest2022SeattleDay03CityMorning
	| BadgeSettingsGofest2022SeattleDay03ParkAfternoon
	| BadgeSettingsGofest2022SeattleDay03ParkMorning
	| BadgeSettingsGofest2022SeattleTestCityAfternoon
	| BadgeSettingsGofest2022SeattleTestCityMorning
	| BadgeSettingsGofest2022SeattleTestParkAfternoon
	| BadgeSettingsGofest2022SeattleTestParkMorning
	| BadgeSettingsGofest2022Test
	| BadgeSettingsGofest2023Global
	| BadgeSettingsGofest2023LondonAddonHatch
	| BadgeSettingsGofest2023LondonAddonHatchTest
	| BadgeSettingsGofest2023LondonAddonRaid
	| BadgeSettingsGofest2023LondonAddonRaidTest
	| BadgeSettingsGofest2023LondonCity2Test
	| BadgeSettingsGofest2023LondonCityTest
	| BadgeSettingsGofest2023LondonDay1City
	| BadgeSettingsGofest2023LondonDay1ParkAfternoon
	| BadgeSettingsGofest2023LondonDay1ParkMorning
	| BadgeSettingsGofest2023LondonDay2City
	| BadgeSettingsGofest2023LondonDay2ParkAfternoon
	| BadgeSettingsGofest2023LondonDay2ParkMorning
	| BadgeSettingsGofest2023LondonDay3City
	| BadgeSettingsGofest2023LondonDay3ParkAfternoon
	| BadgeSettingsGofest2023LondonDay3ParkMorning
	| BadgeSettingsGofest2023LondonPark2Test
	| BadgeSettingsGofest2023LondonParkTest
	| BadgeSettingsGofest2023LondonVip
	| BadgeSettingsGofest2023NewyorkAddonHatch
	| BadgeSettingsGofest2023NewyorkAddonHatchTest
	| BadgeSettingsGofest2023NewyorkAddonRaid
	| BadgeSettingsGofest2023NewyorkAddonRaidTest
	| BadgeSettingsGofest2023NewyorkCity2Test
	| BadgeSettingsGofest2023NewyorkCityTest
	| BadgeSettingsGofest2023NewyorkDay1City
	| BadgeSettingsGofest2023NewyorkDay1ParkAfternoon
	| BadgeSettingsGofest2023NewyorkDay1ParkMorning
	| BadgeSettingsGofest2023NewyorkDay2City
	| BadgeSettingsGofest2023NewyorkDay2ParkAfternoon
	| BadgeSettingsGofest2023NewyorkDay2ParkMorning
	| BadgeSettingsGofest2023NewyorkDay3City
	| BadgeSettingsGofest2023NewyorkDay3ParkAfternoon
	| BadgeSettingsGofest2023NewyorkDay3ParkMorning
	| BadgeSettingsGofest2023NewyorkPark2Test
	| BadgeSettingsGofest2023NewyorkParkTest
	| BadgeSettingsGofest2023NewyorkVip
	| BadgeSettingsGofest2023OsakaAddonHatch
	| BadgeSettingsGofest2023OsakaAddonHatchTest
	| BadgeSettingsGofest2023OsakaAddonRaid
	| BadgeSettingsGofest2023OsakaAddonRaidTest
	| BadgeSettingsGofest2023OsakaCity2Test
	| BadgeSettingsGofest2023OsakaCityTest
	| BadgeSettingsGofest2023OsakaDay1City
	| BadgeSettingsGofest2023OsakaDay1ParkAfternoon
	| BadgeSettingsGofest2023OsakaDay1ParkMorning
	| BadgeSettingsGofest2023OsakaDay2City
	| BadgeSettingsGofest2023OsakaDay2ParkAfternoon
	| BadgeSettingsGofest2023OsakaDay2ParkMorning
	| BadgeSettingsGofest2023OsakaDay3City
	| BadgeSettingsGofest2023OsakaDay3ParkAfternoon
	| BadgeSettingsGofest2023OsakaDay3ParkMorning
	| BadgeSettingsGofest2023OsakaPark2Test
	| BadgeSettingsGofest2023OsakaParkTest
	| BadgeSettingsGofest2023OsakaVip
	| BadgeSettingsGofest2023Test
	| BadgeSettingsGofest2024Global
	| BadgeSettingsGofest2024GlobalTest
	| BadgeSettingsGofest2024MadridAddonHatch
	| BadgeSettingsGofest2024MadridAddonHatchTest
	| BadgeSettingsGofest2024MadridAddonRaid
	| BadgeSettingsGofest2024MadridAddonRaidTest
	| BadgeSettingsGofest2024MadridCity2Test
	| BadgeSettingsGofest2024MadridCityTest
	| BadgeSettingsGofest2024MadridDay1City
	| BadgeSettingsGofest2024MadridDay1ParkAfternoon
	| BadgeSettingsGofest2024MadridDay1ParkMorning
	| BadgeSettingsGofest2024MadridDay2City
	| BadgeSettingsGofest2024MadridDay2ParkAfternoon
	| BadgeSettingsGofest2024MadridDay2ParkMorning
	| BadgeSettingsGofest2024MadridDay3City
	| BadgeSettingsGofest2024MadridDay3ParkAfternoon
	| BadgeSettingsGofest2024MadridDay3ParkMorning
	| BadgeSettingsGofest2024MadridPark2Test
	| BadgeSettingsGofest2024MadridParkTest
	| BadgeSettingsGofest2024MadridVip
	| BadgeSettingsGofest2024NewyorkAddonHatch
	| BadgeSettingsGofest2024NewyorkAddonHatchTest
	| BadgeSettingsGofest2024NewyorkAddonRaid
	| BadgeSettingsGofest2024NewyorkAddonRaidTest
	| BadgeSettingsGofest2024NewyorkCity2Test
	| BadgeSettingsGofest2024NewyorkCityTest
	| BadgeSettingsGofest2024NewyorkDay1City
	| BadgeSettingsGofest2024NewyorkDay1ParkAfternoon
	| BadgeSettingsGofest2024NewyorkDay1ParkMorning
	| BadgeSettingsGofest2024NewyorkDay2City
	| BadgeSettingsGofest2024NewyorkDay2ParkAfternoon
	| BadgeSettingsGofest2024NewyorkDay2ParkMorning
	| BadgeSettingsGofest2024NewyorkDay3City
	| BadgeSettingsGofest2024NewyorkDay3ParkAfternoon
	| BadgeSettingsGofest2024NewyorkDay3ParkMorning
	| BadgeSettingsGofest2024NewyorkPark2Test
	| BadgeSettingsGofest2024NewyorkParkTest
	| BadgeSettingsGofest2024NewyorkVip
	| BadgeSettingsGofest2024PjcsCity
	| BadgeSettingsGofest2024PjcsTest
	| BadgeSettingsGofest2024SendaiAddonHatch
	| BadgeSettingsGofest2024SendaiAddonHatchTest
	| BadgeSettingsGofest2024SendaiAddonRaid
	| BadgeSettingsGofest2024SendaiAddonRaidTest
	| BadgeSettingsGofest2024SendaiCity2Test
	| BadgeSettingsGofest2024SendaiCityTest
	| BadgeSettingsGofest2024SendaiDay0City
	| BadgeSettingsGofest2024SendaiDay0ParkAfternoon
	| BadgeSettingsGofest2024SendaiDay0ParkMorning
	| BadgeSettingsGofest2024SendaiDay1City
	| BadgeSettingsGofest2024SendaiDay1ParkAfternoon
	| BadgeSettingsGofest2024SendaiDay1ParkMorning
	| BadgeSettingsGofest2024SendaiDay2City
	| BadgeSettingsGofest2024SendaiDay2ParkAfternoon
	| BadgeSettingsGofest2024SendaiDay2ParkMorning
	| BadgeSettingsGofest2024SendaiDay3City
	| BadgeSettingsGofest2024SendaiDay3ParkAfternoon
	| BadgeSettingsGofest2024SendaiDay3ParkMorning
	| BadgeSettingsGofest2024SendaiPark2Test
	| BadgeSettingsGofest2024SendaiParkTest
	| BadgeSettingsGofest2024SendaiVip
	| BadgeSettingsGofest2025EventPassDeluxe
	| BadgeSettingsGofest2025Global
	| BadgeSettingsGofest2025GlobalTest
	| BadgeSettingsGofest2025JerseycityAddonHatch
	| BadgeSettingsGofest2025JerseycityAddonRaid
	| BadgeSettingsGofest2025JerseycityFridayCity
	| BadgeSettingsGofest2025JerseycityFridayEssential
	| BadgeSettingsGofest2025JerseycityFridayParkAfternoon
	| BadgeSettingsGofest2025JerseycityFridayParkMorning
	| BadgeSettingsGofest2025JerseycitySaturdayCity
	| BadgeSettingsGofest2025JerseycitySaturdayEssential
	| BadgeSettingsGofest2025JerseycitySaturdayParkAfternoon
	| BadgeSettingsGofest2025JerseycitySaturdayParkMorning
	| BadgeSettingsGofest2025JerseycitySundayCity
	| BadgeSettingsGofest2025JerseycitySundayEssential
	| BadgeSettingsGofest2025JerseycitySundayParkAfternoon
	| BadgeSettingsGofest2025JerseycitySundayParkMorning
	| BadgeSettingsGofest2025JerseycityTestAddonHatch
	| BadgeSettingsGofest2025JerseycityTestAddonRaid
	| BadgeSettingsGofest2025JerseycityTestCity
	| BadgeSettingsGofest2025JerseycityTestEssential
	| BadgeSettingsGofest2025JerseycityTestParkAfternoon
	| BadgeSettingsGofest2025JerseycityTestParkMorning
	| BadgeSettingsGofest2025JerseycityThursdayCity
	| BadgeSettingsGofest2025JerseycityThursdayEssential
	| BadgeSettingsGofest2025JerseycityThursdayParkAfternoon
	| BadgeSettingsGofest2025JerseycityThursdayParkMorning
	| BadgeSettingsGofest2025JerseycityVip
	| BadgeSettingsGofest2025OsakaAddonHatch
	| BadgeSettingsGofest2025OsakaAddonRaid
	| BadgeSettingsGofest2025OsakaFridayCity
	| BadgeSettingsGofest2025OsakaFridayEssential
	| BadgeSettingsGofest2025OsakaFridayParkAfternoon
	| BadgeSettingsGofest2025OsakaFridayParkMorning
	| BadgeSettingsGofest2025OsakaSaturdayCity
	| BadgeSettingsGofest2025OsakaSaturdayEssential
	| BadgeSettingsGofest2025OsakaSaturdayParkAfternoon
	| BadgeSettingsGofest2025OsakaSaturdayParkMorning
	| BadgeSettingsGofest2025OsakaSundayCity
	| BadgeSettingsGofest2025OsakaSundayEssential
	| BadgeSettingsGofest2025OsakaSundayParkAfternoon
	| BadgeSettingsGofest2025OsakaSundayParkMorning
	| BadgeSettingsGofest2025OsakaTestAddonHatch
	| BadgeSettingsGofest2025OsakaTestAddonRaid
	| BadgeSettingsGofest2025OsakaTestCity
	| BadgeSettingsGofest2025OsakaTestEssential
	| BadgeSettingsGofest2025OsakaTestParkAfternoon
	| BadgeSettingsGofest2025OsakaTestParkMorning
	| BadgeSettingsGofest2025OsakaThursdayCity
	| BadgeSettingsGofest2025OsakaThursdayEssential
	| BadgeSettingsGofest2025OsakaThursdayParkAfternoon
	| BadgeSettingsGofest2025OsakaThursdayParkMorning
	| BadgeSettingsGofest2025OsakaVip
	| BadgeSettingsGofest2025ParisAddonHatch
	| BadgeSettingsGofest2025ParisAddonRaid
	| BadgeSettingsGofest2025ParisFridayCity
	| BadgeSettingsGofest2025ParisFridayEssential
	| BadgeSettingsGofest2025ParisFridayParkAfternoon
	| BadgeSettingsGofest2025ParisFridayParkMorning
	| BadgeSettingsGofest2025ParisSaturdayCity
	| BadgeSettingsGofest2025ParisSaturdayEssential
	| BadgeSettingsGofest2025ParisSaturdayParkAfternoon
	| BadgeSettingsGofest2025ParisSaturdayParkMorning
	| BadgeSettingsGofest2025ParisSundayCity
	| BadgeSettingsGofest2025ParisSundayEssential
	| BadgeSettingsGofest2025ParisSundayParkAfternoon
	| BadgeSettingsGofest2025ParisSundayParkMorning
	| BadgeSettingsGofest2025ParisTestAddonHatch
	| BadgeSettingsGofest2025ParisTestAddonRaid
	| BadgeSettingsGofest2025ParisTestCity
	| BadgeSettingsGofest2025ParisTestEssential
	| BadgeSettingsGofest2025ParisTestParkAfternoon
	| BadgeSettingsGofest2025ParisTestParkMorning
	| BadgeSettingsGofest2025ParisThursdayCity
	| BadgeSettingsGofest2025ParisThursdayEssential
	| BadgeSettingsGofest2025ParisThursdayParkAfternoon
	| BadgeSettingsGofest2025ParisThursdayParkMorning
	| BadgeSettingsGofest2025ParisVip
	| BadgeSettingsGofest2026EventPassDeluxe
	| BadgeSettingsGofest2026Global
	| BadgeSettingsGofest2026GlobalTest
	| BadgeSettingsGotour2021GreenGlobal
	| BadgeSettingsGotour2021GreenTest
	| BadgeSettingsGotour2021RedGlobal
	| BadgeSettingsGotour2021RedTest
	| BadgeSettingsGotour2022GoldGlobal
	| BadgeSettingsGotour2022GoldTest
	| BadgeSettingsGotour2022LiveAGlobal
	| BadgeSettingsGotour2022LiveATest
	| BadgeSettingsGotour2022LiveBGlobal
	| BadgeSettingsGotour2022LiveBTest
	| BadgeSettingsGotour2022SilverGlobal
	| BadgeSettingsGotour2022SilverTest
	| BadgeSettingsGotour2023HatchAddon
	| BadgeSettingsGotour2023HatchAddonTest
	| BadgeSettingsGotour2023RaidAddon
	| BadgeSettingsGotour2023RaidAddonTest
	| BadgeSettingsGotour2023RubyGlobal
	| BadgeSettingsGotour2023RubyTest
	| BadgeSettingsGotour2023SapphireGlobal
	| BadgeSettingsGotour2023SapphireTest
	| BadgeSettingsGotour2024Diamond
	| BadgeSettingsGotour2024DiamondTest
	| BadgeSettingsGotour2024Pearl
	| BadgeSettingsGotour2024PearlTest
	| BadgeSettingsGotour2024Secret00
	| BadgeSettingsGotour2024Secret01
	| BadgeSettingsGotour2024Secret02
	| BadgeSettingsGotour2024Secret03
	| BadgeSettingsGotourLive2023Day00
	| BadgeSettingsGotourLive2023Day01
	| BadgeSettingsGotourLive2023Day02
	| BadgeSettingsGotourLive2024AddonHatch
	| BadgeSettingsGotourLive2024AddonRaid
	| BadgeSettingsGotourLive2024Day01City
	| BadgeSettingsGotourLive2024Day01Park
	| BadgeSettingsGotourLive2024Day02City
	| BadgeSettingsGotourLive2024Day02Park
	| BadgeSettingsGotourLive2024DayPreview
	| BadgeSettingsGotourLive2024TestAddonHatch
	| BadgeSettingsGotourLive2024TestAddonRaid
	| BadgeSettingsGotourLive2024TestCity
	| BadgeSettingsGotourLive2024TestPark
	| BadgeSettingsGotourLive2024Vip
	| BadgeSettingsGowa2024Global
	| BadgeSettingsGowa2024IrlAddonHatch
	| BadgeSettingsGowa2024IrlAddonHatchTest
	| BadgeSettingsGowa2024IrlAddonRaid
	| BadgeSettingsGowa2024IrlAddonRaidTest
	| BadgeSettingsGowa2024IrlFulltest
	| BadgeSettingsGowa2024IrlSaturdayCity
	| BadgeSettingsGowa2024IrlSaturdayParkAfternoon
	| BadgeSettingsGowa2024IrlSaturdayParkMorning
	| BadgeSettingsGowa2024IrlSundayCity
	| BadgeSettingsGowa2024IrlSundayParkAfternoon
	| BadgeSettingsGowa2024IrlSundayParkMorning
	| BadgeSettingsGowa2024IrlTestCity
	| BadgeSettingsGowa2024IrlTestParkAfternoon
	| BadgeSettingsGowa2024IrlTestParkMorning
	| BadgeSettingsGowa2024SpecialResearchA
	| BadgeSettingsGowa2024SpecialResearchB
	| BadgeSettingsGowa2024Test
	| BadgeSettingsGowa2025Global
	| BadgeSettingsGowa2025GlobalTest
	| BadgeSettingsGowa2025IrlAddonBattle
	| BadgeSettingsGowa2025IrlAddonBattleTest
	| BadgeSettingsGowa2025IrlAddonExtraDayTest
	| BadgeSettingsGowa2025IrlAddonHatch
	| BadgeSettingsGowa2025IrlAddonHatchTest
	| BadgeSettingsGowa2025IrlFridayCityAddon
	| BadgeSettingsGowa2025IrlFridayTicketedCity
	| BadgeSettingsGowa2025IrlFulltest
	| BadgeSettingsGowa2025IrlSaturdayCityAddon
	| BadgeSettingsGowa2025IrlSaturdayTicketedCity
	| BadgeSettingsGowa2025IrlSundayCityAddon
	| BadgeSettingsGowa2025IrlSundayTicketedCity
	| BadgeSettingsGowa2025SpecialResearchA
	| BadgeSettingsGowa2025SpecialResearchB
	| BadgeSettingsGoTour2025GlobalBlackVersion
	| BadgeSettingsGoTour2025GlobalWhiteVersion
	| BadgeSettingsGoTour2025LosAngelesAddOnHatch
	| BadgeSettingsGoTour2025LosAngelesAddOnHatchTest
	| BadgeSettingsGoTour2025LosAngelesAddOnRaid
	| BadgeSettingsGoTour2025LosAngelesAddOnRaidTest
	| BadgeSettingsGoTour2025LosAngelesFridayCity
	| BadgeSettingsGoTour2025LosAngelesFridayPark
	| BadgeSettingsGoTour2025LosAngelesSaturdayCity
	| BadgeSettingsGoTour2025LosAngelesSaturdayPark
	| BadgeSettingsGoTour2025LosAngelesSundayCity
	| BadgeSettingsGoTour2025LosAngelesSundayPark
	| BadgeSettingsGoTour2025LosAngelesTestCity
	| BadgeSettingsGoTour2025LosAngelesTestPark
	| BadgeSettingsGoTour2025LosAngelesVip
	| BadgeSettingsGoTour2025NewTaipeiCityAddOnHatch
	| BadgeSettingsGoTour2025NewTaipeiCityAddOnHatchTest
	| BadgeSettingsGoTour2025NewTaipeiCityAddOnRaid
	| BadgeSettingsGoTour2025NewTaipeiCityAddOnRaidTest
	| BadgeSettingsGoTour2025NewTaipeiCityFridayCity
	| BadgeSettingsGoTour2025NewTaipeiCityFridayPark
	| BadgeSettingsGoTour2025NewTaipeiCitySaturdayCity
	| BadgeSettingsGoTour2025NewTaipeiCitySaturdayPark
	| BadgeSettingsGoTour2025NewTaipeiCitySundayCity
	| BadgeSettingsGoTour2025NewTaipeiCitySundayPark
	| BadgeSettingsGoTour2025NewTaipeiCityTestCity
	| BadgeSettingsGoTour2025NewTaipeiCityTestPark
	| BadgeSettingsGoTour2025NewTaipeiCityVip
	| BadgeSettingsGoTour2026DeluxePass
	| BadgeSettingsGoTour2026Global
	| BadgeSettingsGoTour2026GlobalSecret01
	| BadgeSettingsGoTour2026GlobalTest
	| BadgeSettingsGoTour2026GlobalXVersion
	| BadgeSettingsGoTour2026GlobalYVersion
	| BadgeSettingsGoTour2026LosAngelesAddOnHatch
	| BadgeSettingsGoTour2026LosAngelesAddOnHatchTest
	| BadgeSettingsGoTour2026LosAngelesAddOnRaid
	| BadgeSettingsGoTour2026LosAngelesAddOnRaidTest
	| BadgeSettingsGoTour2026LosAngelesFridayCity
	| BadgeSettingsGoTour2026LosAngelesFridayMegaNight
	| BadgeSettingsGoTour2026LosAngelesFridayPark
	| BadgeSettingsGoTour2026LosAngelesMegaNightTest
	| BadgeSettingsGoTour2026LosAngelesSaturdayCity
	| BadgeSettingsGoTour2026LosAngelesSaturdayMegaNight
	| BadgeSettingsGoTour2026LosAngelesSaturdayPark
	| BadgeSettingsGoTour2026LosAngelesSundayCity
	| BadgeSettingsGoTour2026LosAngelesSundayMegaNight
	| BadgeSettingsGoTour2026LosAngelesSundayPark
	| BadgeSettingsGoTour2026LosAngelesTestCity
	| BadgeSettingsGoTour2026LosAngelesTestPark
	| BadgeSettingsGoTour2026LosAngelesVip
	| BadgeSettingsGoTour2026TainanAddOnHatch
	| BadgeSettingsGoTour2026TainanAddOnHatchTest
	| BadgeSettingsGoTour2026TainanAddOnRaid
	| BadgeSettingsGoTour2026TainanAddOnRaidTest
	| BadgeSettingsGoTour2026TainanFridayCity
	| BadgeSettingsGoTour2026TainanFridayMegaNight
	| BadgeSettingsGoTour2026TainanFridayPark
	| BadgeSettingsGoTour2026TainanMegaNightTest
	| BadgeSettingsGoTour2026TainanSaturdayCity
	| BadgeSettingsGoTour2026TainanSaturdayMegaNight
	| BadgeSettingsGoTour2026TainanSaturdayPark
	| BadgeSettingsGoTour2026TainanSundayCity
	| BadgeSettingsGoTour2026TainanSundayMegaNight
	| BadgeSettingsGoTour2026TainanSundayPark
	| BadgeSettingsGoTour2026TainanTestCity
	| BadgeSettingsGoTour2026TainanTestPark
	| BadgeSettingsGoTour2026TainanVip
	| BadgeSettingsGreatLeague
	| BadgeSettingsHatchedTotal
	| BadgeSettingsHoursDefended
	| BadgeSettingsLegendaryBattleWon
	| BadgeSettingsLevel40
	| BadgeSettingsMasterLeague
	| BadgeSettingsMaxLevelFriends
	| BadgeSettingsMaxSizeFirstPlaceWin
	| BadgeSettingsMiniCollection
	| BadgeSettingsPartnerEvent20190
	| BadgeSettingsPartnerEvent20191
	| BadgeSettingsPartyChallengesCompleted
	| BadgeSettingsPhotobomb
	| BadgeSettingsPikachu
	| BadgeSettingsPikachuOutbreakYokohama2017
	| BadgeSettingsPokedexEntries
	| BadgeSettingsPokedexEntriesGen2
	| BadgeSettingsPokedexEntriesGen3
	| BadgeSettingsPokedexEntriesGen4
	| BadgeSettingsPokedexEntriesGen5
	| BadgeSettingsPokedexEntriesGen6
	| BadgeSettingsPokedexEntriesGen7
	| BadgeSettingsPokedexEntriesGen8
	| BadgeSettingsPokedexEntriesGen8a
	| BadgeSettingsPokedexEntriesGen9
	| BadgeSettingsPokemonCaughtAtYourLures
	| BadgeSettingsPokemonPurified
	| BadgeSettingsPokestopsVisited
	| BadgeSettingsQuestDialogueInboxControl
	| BadgeSettingsQuestDialogueInboxRollout
	| BadgeSettingsRaidsWithFriends
	| BadgeSettingsRaidBattleStat
	| BadgeSettingsRaidBattleWon
	| BadgeSettingsRocketGiovanniDefeated
	| BadgeSettingsRocketGruntsDefeated
	| BadgeSettingsSafarizone2019MontrealDay00Earlyaccess
	| BadgeSettingsSafarizone2019MontrealDay00General
	| BadgeSettingsSafarizone2019MontrealDay01Earlyaccess
	| BadgeSettingsSafarizone2019MontrealDay01General
	| BadgeSettingsSafarizone2019MontrealDay02Earlyaccess
	| BadgeSettingsSafarizone2019MontrealDay02General
	| BadgeSettingsSafarizone2019MontrealDay03Earlyaccess
	| BadgeSettingsSafarizone2019MontrealDay03General
	| BadgeSettingsSafarizone2020LiverpoolDay00Earlyaccess
	| BadgeSettingsSafarizone2020LiverpoolDay00General
	| BadgeSettingsSafarizone2020LiverpoolDay01Earlyaccess
	| BadgeSettingsSafarizone2020LiverpoolDay01General
	| BadgeSettingsSafarizone2020LiverpoolDay02Earlyaccess
	| BadgeSettingsSafarizone2020LiverpoolDay02General
	| BadgeSettingsSafarizone2020LiverpoolDay03Earlyaccess
	| BadgeSettingsSafarizone2020LiverpoolDay03General
	| BadgeSettingsSafarizone2020PhiladelphiaDay00Earlyaccess
	| BadgeSettingsSafarizone2020PhiladelphiaDay00General
	| BadgeSettingsSafarizone2020PhiladelphiaDay01Earlyaccess
	| BadgeSettingsSafarizone2020PhiladelphiaDay01General
	| BadgeSettingsSafarizone2020PhiladelphiaDay02Earlyaccess
	| BadgeSettingsSafarizone2020PhiladelphiaDay02General
	| BadgeSettingsSafarizone2020PhiladelphiaDay03Earlyaccess
	| BadgeSettingsSafarizone2020PhiladelphiaDay03General
	| BadgeSettingsSafarizone2020StlouisDay00Earlyaccess
	| BadgeSettingsSafarizone2020StlouisDay00General
	| BadgeSettingsSafarizone2020StlouisDay01Earlyaccess
	| BadgeSettingsSafarizone2020StlouisDay01General
	| BadgeSettingsSafarizone2020StlouisDay02Earlyaccess
	| BadgeSettingsSafarizone2020StlouisDay02General
	| BadgeSettingsSafarizone2020StlouisDay03Earlyaccess
	| BadgeSettingsSafarizone2020StlouisDay03General
	| BadgeSettingsSafarizone2022SevilleDay00Earlyaccess
	| BadgeSettingsSafarizone2022SevilleDay00General
	| BadgeSettingsSafarizone2022SevilleDay01Earlyaccess
	| BadgeSettingsSafarizone2022SevilleDay01General
	| BadgeSettingsSafarizone2022SevilleDay02Earlyaccess
	| BadgeSettingsSafarizone2022SevilleDay02General
	| BadgeSettingsSafarizone2022SevilleDay03Earlyaccess
	| BadgeSettingsSafarizone2022SevilleDay03General
	| BadgeSettingsSafarizone2022SingaporeDay00EarlyaccessTest
	| BadgeSettingsSafarizone2022SingaporeDay00GeneralTest
	| BadgeSettingsSafarizone2022SingaporeDay01EarlyaccessTest
	| BadgeSettingsSafarizone2022SingaporeDay01GeneralTest
	| BadgeSettingsSafarizone2022SingaporeDay02EarlyaccessTest
	| BadgeSettingsSafarizone2022SingaporeDay02GeneralTest
	| BadgeSettingsSafarizone2022SingaporeDay03EarlyaccessTest
	| BadgeSettingsSafarizone2022SingaporeDay03GeneralTest
	| BadgeSettingsSafarizone2022TaipeiDay00Earlyaccess
	| BadgeSettingsSafarizone2022TaipeiDay00General
	| BadgeSettingsSafarizone2022TaipeiDay01Earlyaccess
	| BadgeSettingsSafarizone2022TaipeiDay01General
	| BadgeSettingsSafarizone2022TaipeiDay02Earlyaccess
	| BadgeSettingsSafarizone2022TaipeiDay02General
	| BadgeSettingsSafarizone2022TaipeiDay03Earlyaccess
	| BadgeSettingsSafarizone2022TaipeiDay03General
	| BadgeSettingsSafari2023BarcelonaAddOnHatch
	| BadgeSettingsSafari2023BarcelonaAddOnRaid
	| BadgeSettingsSafari2023BarcelonaDay00
	| BadgeSettingsSafari2023BarcelonaDay01
	| BadgeSettingsSafari2023BarcelonaDay02
	| BadgeSettingsSafari2023MexcityAddOnHatch
	| BadgeSettingsSafari2023MexcityAddOnRaid
	| BadgeSettingsSafari2023MexcityDay00
	| BadgeSettingsSafari2023MexcityDay01
	| BadgeSettingsSafari2023MexcityDay02
	| BadgeSettingsSafari2023SeoulAddOnHatch
	| BadgeSettingsSafari2023SeoulAddOnRaid
	| BadgeSettingsSafari2023SeoulDay00
	| BadgeSettingsSafari2023SeoulDay01
	| BadgeSettingsSafari2023SeoulDay02
	| BadgeSettingsSafari2024HongKongAddOnHatch
	| BadgeSettingsSafari2024HongKongAddOnHatchTest
	| BadgeSettingsSafari2024HongKongAddOnRaid
	| BadgeSettingsSafari2024HongKongAddOnRaidTest
	| BadgeSettingsSafari2024HongKongDay01
	| BadgeSettingsSafari2024HongKongDay02
	| BadgeSettingsSafari2024HongKongTest
	| BadgeSettingsSafari2024IncheonDay00
	| BadgeSettingsSafari2024IncheonDay00Citywide
	| BadgeSettingsSafari2024IncheonDay01
	| BadgeSettingsSafari2024IncheonDay01Citywide
	| BadgeSettingsSafari2024IncheonDay02
	| BadgeSettingsSafari2024IncheonDay02Citywide
	| BadgeSettingsSafari2024IncheonDay03
	| BadgeSettingsSafari2024IncheonDay03Citywide
	| BadgeSettingsSafari2024JakartaAddOnHatch
	| BadgeSettingsSafari2024JakartaAddOnHatchTest
	| BadgeSettingsSafari2024JakartaAddOnRaid
	| BadgeSettingsSafari2024JakartaAddOnRaidTest
	| BadgeSettingsSafari2024JakartaDay00
	| BadgeSettingsSafari2024JakartaDay01
	| BadgeSettingsSafari2024JakartaDay02
	| BadgeSettingsSafari2024SaoPauloAddOnHatch
	| BadgeSettingsSafari2024SaoPauloAddOnHatchTest
	| BadgeSettingsSafari2024SaoPauloAddOnRaid
	| BadgeSettingsSafari2024SaoPauloAddOnRaidTest
	| BadgeSettingsSafari2024SaoPauloDay01
	| BadgeSettingsSafari2024SaoPauloDay02
	| BadgeSettingsSafari2024SaoPauloTest
	| BadgeSettingsSafari2024TainanAddOnHatch
	| BadgeSettingsSafari2024TainanAddOnHatchTest
	| BadgeSettingsSafari2024TainanAddOnRaid
	| BadgeSettingsSafari2024TainanAddOnRaidTest
	| BadgeSettingsSafari2024TainanDay00
	| BadgeSettingsSafari2024TainanDay01
	| BadgeSettingsSafari2024TainanDay02
	| BadgeSettingsSafari2025AmsterdamAddOnHatch
	| BadgeSettingsSafari2025AmsterdamAddOnHatchTest
	| BadgeSettingsSafari2025AmsterdamAddOnRaid
	| BadgeSettingsSafari2025AmsterdamAddOnRaidTest
	| BadgeSettingsSafari2025AmsterdamSaturday
	| BadgeSettingsSafari2025AmsterdamSunday
	| BadgeSettingsSafari2025AmsterdamTest
	| BadgeSettingsSafari2025BangkokAddOnHatch
	| BadgeSettingsSafari2025BangkokAddOnHatchTest
	| BadgeSettingsSafari2025BangkokAddOnRaid
	| BadgeSettingsSafari2025BangkokAddOnRaidTest
	| BadgeSettingsSafari2025BangkokSaturday
	| BadgeSettingsSafari2025BangkokSunday
	| BadgeSettingsSafari2025BangkokTest
	| BadgeSettingsSafari2025BuenosAiresAddOnHatch
	| BadgeSettingsSafari2025BuenosAiresAddOnHatchTest
	| BadgeSettingsSafari2025BuenosAiresAddOnRaid
	| BadgeSettingsSafari2025BuenosAiresAddOnRaidTest
	| BadgeSettingsSafari2025BuenosAiresSaturday
	| BadgeSettingsSafari2025BuenosAiresSunday
	| BadgeSettingsSafari2025BuenosAiresTest
	| BadgeSettingsSafari2025CancunAddOnHatch
	| BadgeSettingsSafari2025CancunAddOnHatchTest
	| BadgeSettingsSafari2025CancunAddOnRaid
	| BadgeSettingsSafari2025CancunAddOnRaidTest
	| BadgeSettingsSafari2025CancunSaturday
	| BadgeSettingsSafari2025CancunSunday
	| BadgeSettingsSafari2025CancunTest
	| BadgeSettingsSafari2025MiamiAddOnHatch
	| BadgeSettingsSafari2025MiamiAddOnHatchTest
	| BadgeSettingsSafari2025MiamiAddOnRaid
	| BadgeSettingsSafari2025MiamiAddOnRaidTest
	| BadgeSettingsSafari2025MiamiSaturday
	| BadgeSettingsSafari2025MiamiSunday
	| BadgeSettingsSafari2025MiamiTest
	| BadgeSettingsSafari2025MilanAddOnHatch
	| BadgeSettingsSafari2025MilanAddOnHatchTest
	| BadgeSettingsSafari2025MilanAddOnRaid
	| BadgeSettingsSafari2025MilanAddOnRaidTest
	| BadgeSettingsSafari2025MilanDay01
	| BadgeSettingsSafari2025MilanDay02
	| BadgeSettingsSafari2025MilanTest
	| BadgeSettingsSafari2025MumbaiAddOnHatch
	| BadgeSettingsSafari2025MumbaiAddOnHatchTest
	| BadgeSettingsSafari2025MumbaiAddOnRaid
	| BadgeSettingsSafari2025MumbaiAddOnRaidTest
	| BadgeSettingsSafari2025MumbaiDay01
	| BadgeSettingsSafari2025MumbaiDay02
	| BadgeSettingsSafari2025MumbaiTest
	| BadgeSettingsSafari2025SantiagoAddOnHatch
	| BadgeSettingsSafari2025SantiagoAddOnHatchTest
	| BadgeSettingsSafari2025SantiagoAddOnRaid
	| BadgeSettingsSafari2025SantiagoAddOnRaidTest
	| BadgeSettingsSafari2025SantiagoDay01
	| BadgeSettingsSafari2025SantiagoDay02
	| BadgeSettingsSafari2025SantiagoTest
	| BadgeSettingsSafari2025SingaporeAddOnHatch
	| BadgeSettingsSafari2025SingaporeAddOnHatchTest
	| BadgeSettingsSafari2025SingaporeAddOnRaid
	| BadgeSettingsSafari2025SingaporeAddOnRaidTest
	| BadgeSettingsSafari2025SingaporeDay01
	| BadgeSettingsSafari2025SingaporeDay02
	| BadgeSettingsSafari2025SingaporeTest
	| BadgeSettingsSafari2025SydneyAddOnHatch
	| BadgeSettingsSafari2025SydneyAddOnHatchTest
	| BadgeSettingsSafari2025SydneyAddOnRaid
	| BadgeSettingsSafari2025SydneyAddOnRaidTest
	| BadgeSettingsSafari2025SydneySaturday
	| BadgeSettingsSafari2025SydneySunday
	| BadgeSettingsSafari2025SydneyTest
	| BadgeSettingsSafari2025ValenciaAddOnHatch
	| BadgeSettingsSafari2025ValenciaAddOnHatchTest
	| BadgeSettingsSafari2025ValenciaAddOnRaid
	| BadgeSettingsSafari2025ValenciaAddOnRaidTest
	| BadgeSettingsSafari2025ValenciaSaturday
	| BadgeSettingsSafari2025ValenciaSunday
	| BadgeSettingsSafari2025ValenciaTest
	| BadgeSettingsSafari2025VancouverAddOnHatch
	| BadgeSettingsSafari2025VancouverAddOnHatchTest
	| BadgeSettingsSafari2025VancouverAddOnRaid
	| BadgeSettingsSafari2025VancouverAddOnRaidTest
	| BadgeSettingsSafari2025VancouverSaturday
	| BadgeSettingsSafari2025VancouverSunday
	| BadgeSettingsSafari2025VancouverTest
	| BadgeSettingsSafariZoneEurope2017
	| BadgeSettingsSafariZoneEurope20171007
	| BadgeSettingsSafariZoneEurope20171014
	| BadgeSettingsSentosa18Apr2019
	| BadgeSettingsSentosa19Apr2019
	| BadgeSettingsSentosa20Apr2019
	| BadgeSettingsSentosa21Apr2019
	| BadgeSettingsSentosa22Apr2019
	| BadgeSettingsSmallRattata
	| BadgeSettingsSmores00
	| BadgeSettingsSmores01
	| BadgeSettingsTopBanana1
	| BadgeSettingsTopBanana2
	| BadgeSettingsTopBanana3
	| BadgeSettingsTotalMegaEvos
	| BadgeSettingsTotalRoutePlay
	| BadgeSettingsTrading
	| BadgeSettingsTradingCard0001
	| BadgeSettingsTradingDistance
	| BadgeSettingsTrainersReferred
	| BadgeSettingsTravelKm
	| BadgeSettingsTypeBug
	| BadgeSettingsTypeDark
	| BadgeSettingsTypeDragon
	| BadgeSettingsTypeElectric
	| BadgeSettingsTypeFairy
	| BadgeSettingsTypeFighting
	| BadgeSettingsTypeFire
	| BadgeSettingsTypeFlying
	| BadgeSettingsTypeGhost
	| BadgeSettingsTypeGrass
	| BadgeSettingsTypeGround
	| BadgeSettingsTypeIce
	| BadgeSettingsTypeNormal
	| BadgeSettingsTypePoison
	| BadgeSettingsTypePsychic
	| BadgeSettingsTypeRock
	| BadgeSettingsTypeSteel
	| BadgeSettingsTypeWater
	| BadgeSettingsUltraLeague
	| BadgeSettingsUniqueMegaEvos
	| BadgeSettingsUniquePokestops
	| BadgeSettingsUniqueRaidBossesDefeated
	| BadgeSettingsUnown
	| BadgeSettingsWayfarer
	| BadgeSettingsWeeklyChallengeEligible
	| BadgeSettingsYokosuka1Sep2018Verny
	| BadgeSettingsYokosuka29Aug2018Verny
	| BadgeSettingsYokosuka2Sep2018Verny
	| BadgeSettingsYokosuka30Aug2018Verny
	| BadgeSettingsYokosuka31Aug2018Verny;

export type BadgeSettingsTemplateID = BadgeSettingsMasterfileEntry["templateId"];
