// Generated from Pokémon GO masterfile — group "vsSeekerLoot", 48 entries (structural types).

import type { W } from "../_utils";

export interface VsSeekerLoot<TemplateID extends string = string, TData extends VsSeekerLootData = VsSeekerLootData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		vsSeekerLoot: TData;
	};
}
export type VsSeekerLootType = W<VsSeekerLoot>;

export interface VsSeekerLootData {
	rankLevel: number;
	reward: [
		{
			item?: {
				count: number;
				item?: "ITEM_RARE_CANDY";
				stardust?: boolean;
			};
			itemRankingLootTableCount?: number;
			pokemonReward?: boolean;
		},
		{
			item?: {
				count: number;
				item?: "ITEM_RARE_CANDY";
				stardust?: boolean;
			};
			itemRankingLootTableCount?: number;
			pokemonReward?: boolean;
		},
		{
			item?: {
				count: number;
				item?: "ITEM_RARE_CANDY";
				stardust?: boolean;
			};
			itemRankingLootTableCount?: number;
			pokemonReward?: boolean;
		},
		{
			item?: {
				count: number;
				item?: "ITEM_RARE_CANDY";
				stardust?: boolean;
			};
			itemRankingLootTableCount?: number;
			pokemonReward?: boolean;
		},
		{
			item?: {
				count: number;
				item?: "ITEM_RARE_CANDY";
				stardust?: boolean;
			};
			itemRankingLootTableCount?: number;
			pokemonReward?: boolean;
		},
	];
	rewardTrack?: "PREMIUM";
}

export type VsSeekerLootPerWinSettingsRank =
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_1_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_1_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_10_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_10_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_11_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_11_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_12_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_12_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_13_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_13_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_14_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_14_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_15_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_15_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_16_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_16_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_17_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_17_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_18_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_18_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_19_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_19_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_2_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_2_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_20_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_20_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_21_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_21_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_22_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_22_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_23_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_23_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_24_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_24_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_3_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_3_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_4_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_4_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_5_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_5_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_6_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_6_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_7_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_7_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_8_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_8_PREMIUM"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_9_FREE"
	| "VS_SEEKER_LOOT_PER_WIN_SETTINGS_RANK_9_PREMIUM";
