// Code generated. DO NOT EDIT — regenerated by `bun run generate`.
// During Phase 2 of the implementation plan this is a hand-written bootstrap stub:
// it uses reflection to populate byID and leaves all per-group accessor fields nil.
// Codegen replaces it with a typed switch and full accessor wiring.

package masterfileapi

import (
	"reflect"

	masterfile "github.com/PLACEHOLDER/pogo-masterfile-types/packages/go"
)

type Masterfile struct {
	entries []masterfile.MasterfileEntry
	byID    map[string]int
}

// GroupNames lists every group discriminator. The stub returns an empty slice;
// codegen replaces this with the full ordered list.
var GroupNames = []string{}

func newMasterfile(entries []masterfile.MasterfileEntry) *Masterfile {
	m := &Masterfile{
		entries: entries,
		byID:    make(map[string]int, len(entries)),
	}
	for i, e := range entries {
		rv := reflect.ValueOf(e)
		if rv.Kind() != reflect.Struct {
			continue
		}
		f := rv.FieldByName("TemplateID")
		if f.IsValid() && f.Kind() == reflect.String {
			m.byID[f.String()] = i
		}
	}
	return m
}
