// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package masterfileapi

import (
	"reflect"

	masterfile "github.com/Hazels-Lab/pogo-masterfile/packages/go"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go-api/accessor"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/avatar_customization"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/avatar_group_order_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/avatar_item_display"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/badge_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/bread_move_level_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/buddy_activity_category_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/buddy_emotion_level_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/buddy_level_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/client_quest_template"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/code_gate_proto"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_league"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_move"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_npc_personality"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_npc_trainer"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_ranking_proto_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_type"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/event_pass_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/event_pass_tier_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/evolution_chain_display_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/evolution_quest_template"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/feature_gate"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/form_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/fort_power_up_level_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/friendship_milestone_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/gender_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/iap_category_display"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/iap_item_display"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/invasion_npc_display_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/item_expiration_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/item_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/language_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/level_up_rewards"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/limited_purchase_sku_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/location_card_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/mega_evo_level_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/move_sequence_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/move_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/non_combat_move_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/party_play_general_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/photo_sets_settings_proto"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_extended_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_family"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_home_energy_costs"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_home_form_reversions"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_scale_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_upgrades"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokestop_invasion_availability_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/quest_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/recommended_search_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/roll_back"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/settings_override_rule"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/singletons"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/sticker_metadata"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/tappable_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/temporary_evolution_settings"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/type_effective"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/vs_seeker_loot"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/vs_seeker_pokemon_rewards"
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/weather_affinities"
)

// Masterfile is the indexed runtime view of a parsed masterfile. Construct via
// FromEntries, Load, or LoadRemote; treat as read-only thereafter.
type Masterfile struct {
	entries []masterfile.MasterfileEntry
	byID    map[string]int

	FeatureGate                          *accessor.FeatureGateAccessor
	RollBack                             *accessor.RollBackAccessor
	EvolutionQuestTemplate               *accessor.EvolutionQuestTemplateAccessor
	IapItemDisplay                       *accessor.IapItemDisplayAccessor
	AvatarGroupOrderSettings             *accessor.AvatarGroupOrderSettingsAccessor
	AvatarCustomization                  *accessor.AvatarCustomizationAccessor
	LevelUpRewards                       *accessor.LevelUpRewardsAccessor
	BadgeSettings                        *accessor.BadgeSettingsAccessor
	CodeGateProto                        *accessor.CodeGateProtoAccessor
	BreadMoveLevelSettings               *accessor.BreadMoveLevelSettingsAccessor
	BuddyActivityCategorySettings        *accessor.BuddyActivityCategorySettingsAccessor
	BuddyEmotionLevelSettings            *accessor.BuddyEmotionLevelSettingsAccessor
	BuddyLevelSettings                   *accessor.BuddyLevelSettingsAccessor
	InvasionNpcDisplaySettings           *accessor.InvasionNpcDisplaySettingsAccessor
	CombatLeague                         *accessor.CombatLeagueAccessor
	CombatType                           *accessor.CombatTypeAccessor
	CombatRankingProtoSettings           *accessor.CombatRankingProtoSettingsAccessor
	CombatMove                           *accessor.CombatMoveAccessor
	PokemonHomeEnergyCosts               *accessor.PokemonHomeEnergyCostsAccessor
	EventPassSettings                    *accessor.EventPassSettingsAccessor
	EventPassTierSettings                *accessor.EventPassTierSettingsAccessor
	EvolutionChainDisplaySettings        *accessor.EvolutionChainDisplaySettingsAccessor
	PokemonExtendedSettings              *accessor.PokemonExtendedSettingsAccessor
	FormSettings                         *accessor.FormSettingsAccessor
	FortPowerUpLevelSettings             *accessor.FortPowerUpLevelSettingsAccessor
	FriendshipMilestoneSettings          *accessor.FriendshipMilestoneSettingsAccessor
	ItemSettings                         *accessor.ItemSettingsAccessor
	LanguageSettings                     *accessor.LanguageSettingsAccessor
	IapCategoryDisplay                   *accessor.IapCategoryDisplayAccessor
	PokestopInvasionAvailabilitySettings *accessor.PokestopInvasionAvailabilitySettingsAccessor
	ItemExpirationSettings               *accessor.ItemExpirationSettingsAccessor
	LocationCardSettings                 *accessor.LocationCardSettingsAccessor
	ClientQuestTemplate                  *accessor.ClientQuestTemplateAccessor
	LimitedPurchaseSkuSettings           *accessor.LimitedPurchaseSkuSettingsAccessor
	MegaEvoLevelSettings                 *accessor.MegaEvoLevelSettingsAccessor
	NonCombatMoveSettings                *accessor.NonCombatMoveSettingsAccessor
	AvatarItemDisplay                    *accessor.AvatarItemDisplayAccessor
	PartyPlayGeneralSettings             *accessor.PartyPlayGeneralSettingsAccessor
	PhotoSetsSettingsProto               *accessor.PhotoSetsSettingsProtoAccessor
	PokemonScaleSettings                 *accessor.PokemonScaleSettingsAccessor
	TypeEffective                        *accessor.TypeEffectiveAccessor
	PokemonUpgrades                      *accessor.PokemonUpgradesAccessor
	QuestSettings                        *accessor.QuestSettingsAccessor
	RecommendedSearchSettings            *accessor.RecommendedSearchSettingsAccessor
	SettingsOverrideRule                 *accessor.SettingsOverrideRuleAccessor
	GenderSettings                       *accessor.GenderSettingsAccessor
	StickerMetadata                      *accessor.StickerMetadataAccessor
	TappableSettings                     *accessor.TappableSettingsAccessor
	TemporaryEvolutionSettings           *accessor.TemporaryEvolutionSettingsAccessor
	CombatNpcTrainer                     *accessor.CombatNpcTrainerAccessor
	CombatNpcPersonality                 *accessor.CombatNpcPersonalityAccessor
	PokemonFamily                        *accessor.PokemonFamilyAccessor
	PokemonSettings                      *accessor.PokemonSettingsAccessor
	MoveSettings                         *accessor.MoveSettingsAccessor
	PokemonHomeFormReversions            *accessor.PokemonHomeFormReversionsAccessor
	VsSeekerLoot                         *accessor.VsSeekerLootAccessor
	VsSeekerPokemonRewards               *accessor.VsSeekerPokemonRewardsAccessor
	WeatherAffinities                    *accessor.WeatherAffinitiesAccessor
	MoveSequenceSettings                 *accessor.MoveSequenceSettingsAccessor
	Singletons                           *accessor.SingletonsAccessor
}

// GroupNames lists every multi-entry group discriminator in canonical order.
// Singletons are not included — they share a single accessor on Masterfile.
var GroupNames = []string{
	"featureGate",
	"rollBack",
	"evolutionQuestTemplate",
	"iapItemDisplay",
	"avatarGroupOrderSettings",
	"avatarCustomization",
	"levelUpRewards",
	"badgeSettings",
	"codeGateProto",
	"breadMoveLevelSettings",
	"buddyActivityCategorySettings",
	"buddyEmotionLevelSettings",
	"buddyLevelSettings",
	"invasionNpcDisplaySettings",
	"combatLeague",
	"combatType",
	"combatRankingProtoSettings",
	"combatMove",
	"pokemonHomeEnergyCosts",
	"eventPassSettings",
	"eventPassTierSettings",
	"evolutionChainDisplaySettings",
	"pokemonExtendedSettings",
	"formSettings",
	"fortPowerUpLevelSettings",
	"friendshipMilestoneSettings",
	"itemSettings",
	"languageSettings",
	"iapCategoryDisplay",
	"pokestopInvasionAvailabilitySettings",
	"itemExpirationSettings",
	"locationCardSettings",
	"clientQuestTemplate",
	"limitedPurchaseSkuSettings",
	"megaEvoLevelSettings",
	"nonCombatMoveSettings",
	"avatarItemDisplay",
	"partyPlayGeneralSettings",
	"photoSetsSettingsProto",
	"pokemonScaleSettings",
	"typeEffective",
	"pokemonUpgrades",
	"questSettings",
	"recommendedSearchSettings",
	"settingsOverrideRule",
	"genderSettings",
	"stickerMetadata",
	"tappableSettings",
	"temporaryEvolutionSettings",
	"combatNpcTrainer",
	"combatNpcPersonality",
	"pokemonFamily",
	"pokemonSettings",
	"moveSettings",
	"pokemonHomeFormReversions",
	"vsSeekerLoot",
	"vsSeekerPokemonRewards",
	"weatherAffinities",
	"moveSequenceSettings",
}

func newMasterfile(entries []masterfile.MasterfileEntry) *Masterfile {
	m := &Masterfile{
		entries: entries,
		byID:    make(map[string]int, len(entries)),
	}

	featureGateBucket := []feature_gate.FeatureGateEntry{}
	rollBackBucket := []roll_back.RollBackEntry{}
	evolutionQuestTemplateBucket := []evolution_quest_template.EvolutionQuestTemplateEntry{}
	iapItemDisplayBucket := []iap_item_display.IapItemDisplayEntry{}
	avatarGroupOrderSettingsBucket := []avatar_group_order_settings.AvatarGroupOrderSettingsEntry{}
	avatarCustomizationBucket := []avatar_customization.AvatarCustomizationEntry{}
	levelUpRewardsBucket := []level_up_rewards.LevelUpRewardsEntry{}
	badgeSettingsBucket := []badge_settings.BadgeSettingsEntry{}
	codeGateProtoBucket := []code_gate_proto.CodeGateProtoEntry{}
	breadMoveLevelSettingsBucket := []bread_move_level_settings.BreadMoveLevelSettingsEntry{}
	buddyActivityCategorySettingsBucket := []buddy_activity_category_settings.BuddyActivityCategorySettingsEntry{}
	buddyEmotionLevelSettingsBucket := []buddy_emotion_level_settings.BuddyEmotionLevelSettingsEntry{}
	buddyLevelSettingsBucket := []buddy_level_settings.BuddyLevelSettingsEntry{}
	invasionNpcDisplaySettingsBucket := []invasion_npc_display_settings.InvasionNpcDisplaySettingsEntry{}
	combatLeagueBucket := []combat_league.CombatLeagueEntry{}
	combatTypeBucket := []combat_type.CombatTypeEntry{}
	combatRankingProtoSettingsBucket := []combat_ranking_proto_settings.CombatRankingProtoSettingsEntry{}
	combatMoveBucket := []combat_move.CombatMoveEntry{}
	pokemonHomeEnergyCostsBucket := []pokemon_home_energy_costs.PokemonHomeEnergyCostsEntry{}
	eventPassSettingsBucket := []event_pass_settings.EventPassSettingsEntry{}
	eventPassTierSettingsBucket := []event_pass_tier_settings.EventPassTierSettingsEntry{}
	evolutionChainDisplaySettingsBucket := []evolution_chain_display_settings.EvolutionChainDisplaySettingsEntry{}
	pokemonExtendedSettingsBucket := []pokemon_extended_settings.PokemonExtendedSettingsEntry{}
	formSettingsBucket := []form_settings.FormSettingsEntry{}
	fortPowerUpLevelSettingsBucket := []fort_power_up_level_settings.FortPowerUpLevelSettingsEntry{}
	friendshipMilestoneSettingsBucket := []friendship_milestone_settings.FriendshipMilestoneSettingsEntry{}
	itemSettingsBucket := []item_settings.ItemSettingsEntry{}
	languageSettingsBucket := []language_settings.LanguageSettingsEntry{}
	iapCategoryDisplayBucket := []iap_category_display.IapCategoryDisplayEntry{}
	pokestopInvasionAvailabilitySettingsBucket := []pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsEntry{}
	itemExpirationSettingsBucket := []item_expiration_settings.ItemExpirationSettingsEntry{}
	locationCardSettingsBucket := []location_card_settings.LocationCardSettingsEntry{}
	clientQuestTemplateBucket := []client_quest_template.ClientQuestTemplateEntry{}
	limitedPurchaseSkuSettingsBucket := []limited_purchase_sku_settings.LimitedPurchaseSkuSettingsEntry{}
	megaEvoLevelSettingsBucket := []mega_evo_level_settings.MegaEvoLevelSettingsEntry{}
	nonCombatMoveSettingsBucket := []non_combat_move_settings.NonCombatMoveSettingsEntry{}
	avatarItemDisplayBucket := []avatar_item_display.AvatarItemDisplayEntry{}
	partyPlayGeneralSettingsBucket := []party_play_general_settings.PartyPlayGeneralSettingsEntry{}
	photoSetsSettingsProtoBucket := []photo_sets_settings_proto.PhotoSetsSettingsProtoEntry{}
	pokemonScaleSettingsBucket := []pokemon_scale_settings.PokemonScaleSettingsEntry{}
	typeEffectiveBucket := []type_effective.TypeEffectiveEntry{}
	pokemonUpgradesBucket := []pokemon_upgrades.PokemonUpgradesEntry{}
	questSettingsBucket := []quest_settings.QuestSettingsEntry{}
	recommendedSearchSettingsBucket := []recommended_search_settings.RecommendedSearchSettingsEntry{}
	settingsOverrideRuleBucket := []settings_override_rule.SettingsOverrideRuleEntry{}
	genderSettingsBucket := []gender_settings.GenderSettingsEntry{}
	stickerMetadataBucket := []sticker_metadata.StickerMetadataEntry{}
	tappableSettingsBucket := []tappable_settings.TappableSettingsEntry{}
	temporaryEvolutionSettingsBucket := []temporary_evolution_settings.TemporaryEvolutionSettingsEntry{}
	combatNpcTrainerBucket := []combat_npc_trainer.CombatNpcTrainerEntry{}
	combatNpcPersonalityBucket := []combat_npc_personality.CombatNpcPersonalityEntry{}
	pokemonFamilyBucket := []pokemon_family.PokemonFamilyEntry{}
	pokemonSettingsBucket := []pokemon_settings.PokemonSettingsEntry{}
	moveSettingsBucket := []move_settings.MoveSettingsEntry{}
	pokemonHomeFormReversionsBucket := []pokemon_home_form_reversions.PokemonHomeFormReversionsEntry{}
	vsSeekerLootBucket := []vs_seeker_loot.VsSeekerLootEntry{}
	vsSeekerPokemonRewardsBucket := []vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsEntry{}
	weatherAffinitiesBucket := []weather_affinities.WeatherAffinitiesEntry{}
	moveSequenceSettingsBucket := []move_sequence_settings.MoveSequenceSettingsEntry{}
	singletonEntries := []masterfile.MasterfileEntry{}
	singletonIDs := []singletons.SingletonsTemplateID{}

	for i, e := range entries {
		switch v := e.(type) {
		case feature_gate.FeatureGateEntry:
			m.byID[v.TemplateID] = i
			featureGateBucket = append(featureGateBucket, v)
		case roll_back.RollBackEntry:
			m.byID[v.TemplateID] = i
			rollBackBucket = append(rollBackBucket, v)
		case evolution_quest_template.EvolutionQuestTemplateEntry:
			m.byID[v.TemplateID] = i
			evolutionQuestTemplateBucket = append(evolutionQuestTemplateBucket, v)
		case iap_item_display.IapItemDisplayEntry:
			m.byID[v.TemplateID] = i
			iapItemDisplayBucket = append(iapItemDisplayBucket, v)
		case avatar_group_order_settings.AvatarGroupOrderSettingsEntry:
			m.byID[v.TemplateID] = i
			avatarGroupOrderSettingsBucket = append(avatarGroupOrderSettingsBucket, v)
		case avatar_customization.AvatarCustomizationEntry:
			m.byID[v.TemplateID] = i
			avatarCustomizationBucket = append(avatarCustomizationBucket, v)
		case level_up_rewards.LevelUpRewardsEntry:
			m.byID[v.TemplateID] = i
			levelUpRewardsBucket = append(levelUpRewardsBucket, v)
		case badge_settings.BadgeSettingsEntry:
			m.byID[v.TemplateID] = i
			badgeSettingsBucket = append(badgeSettingsBucket, v)
		case code_gate_proto.CodeGateProtoEntry:
			m.byID[v.TemplateID] = i
			codeGateProtoBucket = append(codeGateProtoBucket, v)
		case bread_move_level_settings.BreadMoveLevelSettingsEntry:
			m.byID[v.TemplateID] = i
			breadMoveLevelSettingsBucket = append(breadMoveLevelSettingsBucket, v)
		case buddy_activity_category_settings.BuddyActivityCategorySettingsEntry:
			m.byID[v.TemplateID] = i
			buddyActivityCategorySettingsBucket = append(buddyActivityCategorySettingsBucket, v)
		case buddy_emotion_level_settings.BuddyEmotionLevelSettingsEntry:
			m.byID[v.TemplateID] = i
			buddyEmotionLevelSettingsBucket = append(buddyEmotionLevelSettingsBucket, v)
		case buddy_level_settings.BuddyLevelSettingsEntry:
			m.byID[v.TemplateID] = i
			buddyLevelSettingsBucket = append(buddyLevelSettingsBucket, v)
		case invasion_npc_display_settings.InvasionNpcDisplaySettingsEntry:
			m.byID[v.TemplateID] = i
			invasionNpcDisplaySettingsBucket = append(invasionNpcDisplaySettingsBucket, v)
		case combat_league.CombatLeagueEntry:
			m.byID[v.TemplateID] = i
			combatLeagueBucket = append(combatLeagueBucket, v)
		case combat_type.CombatTypeEntry:
			m.byID[v.TemplateID] = i
			combatTypeBucket = append(combatTypeBucket, v)
		case combat_ranking_proto_settings.CombatRankingProtoSettingsEntry:
			m.byID[v.TemplateID] = i
			combatRankingProtoSettingsBucket = append(combatRankingProtoSettingsBucket, v)
		case combat_move.CombatMoveEntry:
			m.byID[v.TemplateID] = i
			combatMoveBucket = append(combatMoveBucket, v)
		case pokemon_home_energy_costs.PokemonHomeEnergyCostsEntry:
			m.byID[v.TemplateID] = i
			pokemonHomeEnergyCostsBucket = append(pokemonHomeEnergyCostsBucket, v)
		case event_pass_settings.EventPassSettingsEntry:
			m.byID[v.TemplateID] = i
			eventPassSettingsBucket = append(eventPassSettingsBucket, v)
		case event_pass_tier_settings.EventPassTierSettingsEntry:
			m.byID[v.TemplateID] = i
			eventPassTierSettingsBucket = append(eventPassTierSettingsBucket, v)
		case evolution_chain_display_settings.EvolutionChainDisplaySettingsEntry:
			m.byID[v.TemplateID] = i
			evolutionChainDisplaySettingsBucket = append(evolutionChainDisplaySettingsBucket, v)
		case pokemon_extended_settings.PokemonExtendedSettingsEntry:
			m.byID[v.TemplateID] = i
			pokemonExtendedSettingsBucket = append(pokemonExtendedSettingsBucket, v)
		case form_settings.FormSettingsEntry:
			m.byID[v.TemplateID] = i
			formSettingsBucket = append(formSettingsBucket, v)
		case fort_power_up_level_settings.FortPowerUpLevelSettingsEntry:
			m.byID[v.TemplateID] = i
			fortPowerUpLevelSettingsBucket = append(fortPowerUpLevelSettingsBucket, v)
		case friendship_milestone_settings.FriendshipMilestoneSettingsEntry:
			m.byID[v.TemplateID] = i
			friendshipMilestoneSettingsBucket = append(friendshipMilestoneSettingsBucket, v)
		case item_settings.ItemSettingsEntry:
			m.byID[v.TemplateID] = i
			itemSettingsBucket = append(itemSettingsBucket, v)
		case language_settings.LanguageSettingsEntry:
			m.byID[v.TemplateID] = i
			languageSettingsBucket = append(languageSettingsBucket, v)
		case iap_category_display.IapCategoryDisplayEntry:
			m.byID[v.TemplateID] = i
			iapCategoryDisplayBucket = append(iapCategoryDisplayBucket, v)
		case pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsEntry:
			m.byID[v.TemplateID] = i
			pokestopInvasionAvailabilitySettingsBucket = append(pokestopInvasionAvailabilitySettingsBucket, v)
		case item_expiration_settings.ItemExpirationSettingsEntry:
			m.byID[v.TemplateID] = i
			itemExpirationSettingsBucket = append(itemExpirationSettingsBucket, v)
		case location_card_settings.LocationCardSettingsEntry:
			m.byID[v.TemplateID] = i
			locationCardSettingsBucket = append(locationCardSettingsBucket, v)
		case client_quest_template.ClientQuestTemplateEntry:
			m.byID[v.TemplateID] = i
			clientQuestTemplateBucket = append(clientQuestTemplateBucket, v)
		case limited_purchase_sku_settings.LimitedPurchaseSkuSettingsEntry:
			m.byID[v.TemplateID] = i
			limitedPurchaseSkuSettingsBucket = append(limitedPurchaseSkuSettingsBucket, v)
		case mega_evo_level_settings.MegaEvoLevelSettingsEntry:
			m.byID[v.TemplateID] = i
			megaEvoLevelSettingsBucket = append(megaEvoLevelSettingsBucket, v)
		case non_combat_move_settings.NonCombatMoveSettingsEntry:
			m.byID[v.TemplateID] = i
			nonCombatMoveSettingsBucket = append(nonCombatMoveSettingsBucket, v)
		case avatar_item_display.AvatarItemDisplayEntry:
			m.byID[v.TemplateID] = i
			avatarItemDisplayBucket = append(avatarItemDisplayBucket, v)
		case party_play_general_settings.PartyPlayGeneralSettingsEntry:
			m.byID[v.TemplateID] = i
			partyPlayGeneralSettingsBucket = append(partyPlayGeneralSettingsBucket, v)
		case photo_sets_settings_proto.PhotoSetsSettingsProtoEntry:
			m.byID[v.TemplateID] = i
			photoSetsSettingsProtoBucket = append(photoSetsSettingsProtoBucket, v)
		case pokemon_scale_settings.PokemonScaleSettingsEntry:
			m.byID[v.TemplateID] = i
			pokemonScaleSettingsBucket = append(pokemonScaleSettingsBucket, v)
		case type_effective.TypeEffectiveEntry:
			m.byID[v.TemplateID] = i
			typeEffectiveBucket = append(typeEffectiveBucket, v)
		case pokemon_upgrades.PokemonUpgradesEntry:
			m.byID[v.TemplateID] = i
			pokemonUpgradesBucket = append(pokemonUpgradesBucket, v)
		case quest_settings.QuestSettingsEntry:
			m.byID[v.TemplateID] = i
			questSettingsBucket = append(questSettingsBucket, v)
		case recommended_search_settings.RecommendedSearchSettingsEntry:
			m.byID[v.TemplateID] = i
			recommendedSearchSettingsBucket = append(recommendedSearchSettingsBucket, v)
		case settings_override_rule.SettingsOverrideRuleEntry:
			m.byID[v.TemplateID] = i
			settingsOverrideRuleBucket = append(settingsOverrideRuleBucket, v)
		case gender_settings.GenderSettingsEntry:
			m.byID[v.TemplateID] = i
			genderSettingsBucket = append(genderSettingsBucket, v)
		case sticker_metadata.StickerMetadataEntry:
			m.byID[v.TemplateID] = i
			stickerMetadataBucket = append(stickerMetadataBucket, v)
		case tappable_settings.TappableSettingsEntry:
			m.byID[v.TemplateID] = i
			tappableSettingsBucket = append(tappableSettingsBucket, v)
		case temporary_evolution_settings.TemporaryEvolutionSettingsEntry:
			m.byID[v.TemplateID] = i
			temporaryEvolutionSettingsBucket = append(temporaryEvolutionSettingsBucket, v)
		case combat_npc_trainer.CombatNpcTrainerEntry:
			m.byID[v.TemplateID] = i
			combatNpcTrainerBucket = append(combatNpcTrainerBucket, v)
		case combat_npc_personality.CombatNpcPersonalityEntry:
			m.byID[v.TemplateID] = i
			combatNpcPersonalityBucket = append(combatNpcPersonalityBucket, v)
		case pokemon_family.PokemonFamilyEntry:
			m.byID[v.TemplateID] = i
			pokemonFamilyBucket = append(pokemonFamilyBucket, v)
		case pokemon_settings.PokemonSettingsEntry:
			m.byID[v.TemplateID] = i
			pokemonSettingsBucket = append(pokemonSettingsBucket, v)
		case move_settings.MoveSettingsEntry:
			m.byID[v.TemplateID] = i
			moveSettingsBucket = append(moveSettingsBucket, v)
		case pokemon_home_form_reversions.PokemonHomeFormReversionsEntry:
			m.byID[v.TemplateID] = i
			pokemonHomeFormReversionsBucket = append(pokemonHomeFormReversionsBucket, v)
		case vs_seeker_loot.VsSeekerLootEntry:
			m.byID[v.TemplateID] = i
			vsSeekerLootBucket = append(vsSeekerLootBucket, v)
		case vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsEntry:
			m.byID[v.TemplateID] = i
			vsSeekerPokemonRewardsBucket = append(vsSeekerPokemonRewardsBucket, v)
		case weather_affinities.WeatherAffinitiesEntry:
			m.byID[v.TemplateID] = i
			weatherAffinitiesBucket = append(weatherAffinitiesBucket, v)
		case move_sequence_settings.MoveSequenceSettingsEntry:
			m.byID[v.TemplateID] = i
			moveSequenceSettingsBucket = append(moveSequenceSettingsBucket, v)
		default:
			tid := singletonTemplateID(v)
			if tid != "" {
				m.byID[tid] = i
				singletonEntries = append(singletonEntries, v)
				singletonIDs = append(singletonIDs, singletons.SingletonsTemplateID(tid))
			}
		}
	}

	m.FeatureGate = accessor.NewFeatureGateAccessor(featureGateBucket)
	m.RollBack = accessor.NewRollBackAccessor(rollBackBucket)
	m.EvolutionQuestTemplate = accessor.NewEvolutionQuestTemplateAccessor(evolutionQuestTemplateBucket)
	m.IapItemDisplay = accessor.NewIapItemDisplayAccessor(iapItemDisplayBucket)
	m.AvatarGroupOrderSettings = accessor.NewAvatarGroupOrderSettingsAccessor(avatarGroupOrderSettingsBucket)
	m.AvatarCustomization = accessor.NewAvatarCustomizationAccessor(avatarCustomizationBucket)
	m.LevelUpRewards = accessor.NewLevelUpRewardsAccessor(levelUpRewardsBucket)
	m.BadgeSettings = accessor.NewBadgeSettingsAccessor(badgeSettingsBucket)
	m.CodeGateProto = accessor.NewCodeGateProtoAccessor(codeGateProtoBucket)
	m.BreadMoveLevelSettings = accessor.NewBreadMoveLevelSettingsAccessor(breadMoveLevelSettingsBucket)
	m.BuddyActivityCategorySettings = accessor.NewBuddyActivityCategorySettingsAccessor(buddyActivityCategorySettingsBucket)
	m.BuddyEmotionLevelSettings = accessor.NewBuddyEmotionLevelSettingsAccessor(buddyEmotionLevelSettingsBucket)
	m.BuddyLevelSettings = accessor.NewBuddyLevelSettingsAccessor(buddyLevelSettingsBucket)
	m.InvasionNpcDisplaySettings = accessor.NewInvasionNpcDisplaySettingsAccessor(invasionNpcDisplaySettingsBucket)
	m.CombatLeague = accessor.NewCombatLeagueAccessor(combatLeagueBucket)
	m.CombatType = accessor.NewCombatTypeAccessor(combatTypeBucket)
	m.CombatRankingProtoSettings = accessor.NewCombatRankingProtoSettingsAccessor(combatRankingProtoSettingsBucket)
	m.CombatMove = accessor.NewCombatMoveAccessor(combatMoveBucket)
	m.PokemonHomeEnergyCosts = accessor.NewPokemonHomeEnergyCostsAccessor(pokemonHomeEnergyCostsBucket)
	m.EventPassSettings = accessor.NewEventPassSettingsAccessor(eventPassSettingsBucket)
	m.EventPassTierSettings = accessor.NewEventPassTierSettingsAccessor(eventPassTierSettingsBucket)
	m.EvolutionChainDisplaySettings = accessor.NewEvolutionChainDisplaySettingsAccessor(evolutionChainDisplaySettingsBucket)
	m.PokemonExtendedSettings = accessor.NewPokemonExtendedSettingsAccessor(pokemonExtendedSettingsBucket)
	m.FormSettings = accessor.NewFormSettingsAccessor(formSettingsBucket)
	m.FortPowerUpLevelSettings = accessor.NewFortPowerUpLevelSettingsAccessor(fortPowerUpLevelSettingsBucket)
	m.FriendshipMilestoneSettings = accessor.NewFriendshipMilestoneSettingsAccessor(friendshipMilestoneSettingsBucket)
	m.ItemSettings = accessor.NewItemSettingsAccessor(itemSettingsBucket)
	m.LanguageSettings = accessor.NewLanguageSettingsAccessor(languageSettingsBucket)
	m.IapCategoryDisplay = accessor.NewIapCategoryDisplayAccessor(iapCategoryDisplayBucket)
	m.PokestopInvasionAvailabilitySettings = accessor.NewPokestopInvasionAvailabilitySettingsAccessor(pokestopInvasionAvailabilitySettingsBucket)
	m.ItemExpirationSettings = accessor.NewItemExpirationSettingsAccessor(itemExpirationSettingsBucket)
	m.LocationCardSettings = accessor.NewLocationCardSettingsAccessor(locationCardSettingsBucket)
	m.ClientQuestTemplate = accessor.NewClientQuestTemplateAccessor(clientQuestTemplateBucket)
	m.LimitedPurchaseSkuSettings = accessor.NewLimitedPurchaseSkuSettingsAccessor(limitedPurchaseSkuSettingsBucket)
	m.MegaEvoLevelSettings = accessor.NewMegaEvoLevelSettingsAccessor(megaEvoLevelSettingsBucket)
	m.NonCombatMoveSettings = accessor.NewNonCombatMoveSettingsAccessor(nonCombatMoveSettingsBucket)
	m.AvatarItemDisplay = accessor.NewAvatarItemDisplayAccessor(avatarItemDisplayBucket)
	m.PartyPlayGeneralSettings = accessor.NewPartyPlayGeneralSettingsAccessor(partyPlayGeneralSettingsBucket)
	m.PhotoSetsSettingsProto = accessor.NewPhotoSetsSettingsProtoAccessor(photoSetsSettingsProtoBucket)
	m.PokemonScaleSettings = accessor.NewPokemonScaleSettingsAccessor(pokemonScaleSettingsBucket)
	m.TypeEffective = accessor.NewTypeEffectiveAccessor(typeEffectiveBucket)
	m.PokemonUpgrades = accessor.NewPokemonUpgradesAccessor(pokemonUpgradesBucket)
	m.QuestSettings = accessor.NewQuestSettingsAccessor(questSettingsBucket)
	m.RecommendedSearchSettings = accessor.NewRecommendedSearchSettingsAccessor(recommendedSearchSettingsBucket)
	m.SettingsOverrideRule = accessor.NewSettingsOverrideRuleAccessor(settingsOverrideRuleBucket)
	m.GenderSettings = accessor.NewGenderSettingsAccessor(genderSettingsBucket)
	m.StickerMetadata = accessor.NewStickerMetadataAccessor(stickerMetadataBucket)
	m.TappableSettings = accessor.NewTappableSettingsAccessor(tappableSettingsBucket)
	m.TemporaryEvolutionSettings = accessor.NewTemporaryEvolutionSettingsAccessor(temporaryEvolutionSettingsBucket)
	m.CombatNpcTrainer = accessor.NewCombatNpcTrainerAccessor(combatNpcTrainerBucket)
	m.CombatNpcPersonality = accessor.NewCombatNpcPersonalityAccessor(combatNpcPersonalityBucket)
	m.PokemonFamily = accessor.NewPokemonFamilyAccessor(pokemonFamilyBucket)
	m.PokemonSettings = accessor.NewPokemonSettingsAccessor(pokemonSettingsBucket)
	m.MoveSettings = accessor.NewMoveSettingsAccessor(moveSettingsBucket)
	m.PokemonHomeFormReversions = accessor.NewPokemonHomeFormReversionsAccessor(pokemonHomeFormReversionsBucket)
	m.VsSeekerLoot = accessor.NewVsSeekerLootAccessor(vsSeekerLootBucket)
	m.VsSeekerPokemonRewards = accessor.NewVsSeekerPokemonRewardsAccessor(vsSeekerPokemonRewardsBucket)
	m.WeatherAffinities = accessor.NewWeatherAffinitiesAccessor(weatherAffinitiesBucket)
	m.MoveSequenceSettings = accessor.NewMoveSequenceSettingsAccessor(moveSequenceSettingsBucket)
	m.Singletons = accessor.NewSingletonsAccessor(singletonEntries, singletonIDs)

	return m
}

// singletonTemplateID extracts the TemplateID field via reflection from a
// singleton entry. Singletons are heterogeneous so we cannot enumerate them
// in the type switch above without producing thousands of arms; reflection is
// used only here, only on the singleton-load slow path.
func singletonTemplateID(e masterfile.MasterfileEntry) string {
	rv := reflect.ValueOf(e)
	if rv.Kind() != reflect.Struct {
		return ""
	}
	f := rv.FieldByName("TemplateID")
	if f.IsValid() && f.Kind() == reflect.String {
		return f.String()
	}
	return ""
}
