// Generated from Pokémon GO masterfile — group "temporaryEvolutionSettings", 50 entries (structural types).

import type { W } from "../_utils";

export interface TemporaryEvolutionSettings<TemplateID extends string = string, TData extends TemporaryEvolutionSettingsData = TemporaryEvolutionSettingsData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		temporaryEvolutionSettings: TData;
	};
}
export type TemporaryEvolutionSettingsType = W<TemporaryEvolutionSettings>;

export interface TemporaryEvolutionSettingsData {
	pokemonId:
		| "ABOMASNOW"
		| "ABSOL"
		| "AERODACTYL"
		| "AGGRON"
		| "ALAKAZAM"
		| "ALTARIA"
		| "AMPHAROS"
		| "AUDINO"
		| "BANETTE"
		| "BEEDRILL"
		| "BLASTOISE"
		| "BLAZIKEN"
		| "CAMERUPT"
		| "CHARIZARD"
		| "DIANCIE"
		| "DRAGONITE"
		| "GALLADE"
		| "GARCHOMP"
		| "GARDEVOIR"
		| "GENGAR"
		| "GLALIE"
		| "GROUDON"
		| "GYARADOS"
		| "HERACROSS"
		| "HOUNDOOM"
		| "KANGASKHAN"
		| "KYOGRE"
		| "LATIAS"
		| "LATIOS"
		| "LOPUNNY"
		| "LUCARIO"
		| "MALAMAR"
		| "MANECTRIC"
		| "MAWILE"
		| "MEDICHAM"
		| "METAGROSS"
		| "PIDGEOT"
		| "PINSIR"
		| "RAYQUAZA"
		| "SABLEYE"
		| "SALAMENCE"
		| "SCEPTILE"
		| "SCIZOR"
		| "SHARPEDO"
		| "SLOWBRO"
		| "STEELIX"
		| "SWAMPERT"
		| "TYRANITAR"
		| "VENUSAUR"
		| "VICTREEBEL";
	temporaryEvolutions: Array<{
		assetBundleValue: number;
		temporaryEvolutionId: "TEMP_EVOLUTION_MEGA" | "TEMP_EVOLUTION_MEGA_X" | "TEMP_EVOLUTION_MEGA_Y" | "TEMP_EVOLUTION_PRIMAL";
	}>;
}

export type TemporaryEvolution =
	| "TEMPORARY_EVOLUTION_V0003_POKEMON_VENUSAUR"
	| "TEMPORARY_EVOLUTION_V0006_POKEMON_CHARIZARD"
	| "TEMPORARY_EVOLUTION_V0009_POKEMON_BLASTOISE"
	| "TEMPORARY_EVOLUTION_V0015_POKEMON_BEEDRILL"
	| "TEMPORARY_EVOLUTION_V0018_POKEMON_PIDGEOT"
	| "TEMPORARY_EVOLUTION_V0065_POKEMON_ALAKAZAM"
	| "TEMPORARY_EVOLUTION_V0071_POKEMON_VICTREEBEL"
	| "TEMPORARY_EVOLUTION_V0080_POKEMON_SLOWBRO"
	| "TEMPORARY_EVOLUTION_V0094_POKEMON_GENGAR"
	| "TEMPORARY_EVOLUTION_V0115_POKEMON_KANGASKHAN"
	| "TEMPORARY_EVOLUTION_V0127_POKEMON_PINSIR"
	| "TEMPORARY_EVOLUTION_V0130_POKEMON_GYARADOS"
	| "TEMPORARY_EVOLUTION_V0142_POKEMON_AERODACTYL"
	| "TEMPORARY_EVOLUTION_V0149_POKEMON_DRAGONITE"
	| "TEMPORARY_EVOLUTION_V0181_POKEMON_AMPHAROS"
	| "TEMPORARY_EVOLUTION_V0208_POKEMON_STEELIX"
	| "TEMPORARY_EVOLUTION_V0212_POKEMON_SCIZOR"
	| "TEMPORARY_EVOLUTION_V0214_POKEMON_HERACROSS"
	| "TEMPORARY_EVOLUTION_V0229_POKEMON_HOUNDOOM"
	| "TEMPORARY_EVOLUTION_V0248_POKEMON_TYRANITAR"
	| "TEMPORARY_EVOLUTION_V0254_POKEMON_SCEPTILE"
	| "TEMPORARY_EVOLUTION_V0257_POKEMON_BLAZIKEN"
	| "TEMPORARY_EVOLUTION_V0260_POKEMON_SWAMPERT"
	| "TEMPORARY_EVOLUTION_V0282_POKEMON_GARDEVOIR"
	| "TEMPORARY_EVOLUTION_V0302_POKEMON_SABLEYE"
	| "TEMPORARY_EVOLUTION_V0303_POKEMON_MAWILE"
	| "TEMPORARY_EVOLUTION_V0306_POKEMON_AGGRON"
	| "TEMPORARY_EVOLUTION_V0308_POKEMON_MEDICHAM"
	| "TEMPORARY_EVOLUTION_V0310_POKEMON_MANECTRIC"
	| "TEMPORARY_EVOLUTION_V0319_POKEMON_SHARPEDO"
	| "TEMPORARY_EVOLUTION_V0323_POKEMON_CAMERUPT"
	| "TEMPORARY_EVOLUTION_V0334_POKEMON_ALTARIA"
	| "TEMPORARY_EVOLUTION_V0354_POKEMON_BANETTE"
	| "TEMPORARY_EVOLUTION_V0359_POKEMON_ABSOL"
	| "TEMPORARY_EVOLUTION_V0362_POKEMON_GLALIE"
	| "TEMPORARY_EVOLUTION_V0373_POKEMON_SALAMENCE"
	| "TEMPORARY_EVOLUTION_V0376_POKEMON_METAGROSS"
	| "TEMPORARY_EVOLUTION_V0380_POKEMON_LATIAS"
	| "TEMPORARY_EVOLUTION_V0381_POKEMON_LATIOS"
	| "TEMPORARY_EVOLUTION_V0382_POKEMON_KYOGRE"
	| "TEMPORARY_EVOLUTION_V0383_POKEMON_GROUDON"
	| "TEMPORARY_EVOLUTION_V0384_POKEMON_RAYQUAZA"
	| "TEMPORARY_EVOLUTION_V0428_POKEMON_GARCHOMP"
	| "TEMPORARY_EVOLUTION_V0428_POKEMON_LOPUNNY"
	| "TEMPORARY_EVOLUTION_V0448_POKEMON_LUCARIO"
	| "TEMPORARY_EVOLUTION_V0460_POKEMON_ABOMASNOW"
	| "TEMPORARY_EVOLUTION_V0475_POKEMON_GALLADE"
	| "TEMPORARY_EVOLUTION_V0531_POKEMON_AUDINO"
	| "TEMPORARY_EVOLUTION_V0687_POKEMON_MALAMAR"
	| "TEMPORARY_EVOLUTION_V0719_POKEMON_DIANCIE";
