// Generated from Pokémon GO masterfile — group "megaEvoLevelSettings" templateIds.

package mega_evo_level_settings

type MegaEvoLevelSettingsTemplateID string

const (
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0                       MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0015PokemonBeedrill   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0015_POKEMON_BEEDRILL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0018PokemonPidgeot    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0018_POKEMON_PIDGEOT"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0026PokemonRaichu     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0026_POKEMON_RAICHU"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0071PokemonVictreebel MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0071_POKEMON_VICTREEBEL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0080PokemonSlowbro    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0080_POKEMON_SLOWBRO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0130PokemonGyarados   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0130_POKEMON_GYARADOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0149PokemonDragonite  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0149_POKEMON_DRAGONITE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0150PokemonMewtwo     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0150_POKEMON_MEWTWO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0227PokemonSkarmory   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0227_POKEMON_SKARMORY"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0229PokemonHoundoom   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0229_POKEMON_HOUNDOOM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0248PokemonTyranitar  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0248_POKEMON_TYRANITAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0302PokemonSableye    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0302_POKEMON_SABLEYE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0308PokemonMedicham   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0308_POKEMON_MEDICHAM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0310PokemonManectric  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0310_POKEMON_MANECTRIC"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0334PokemonAltaria    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0334_POKEMON_ALTARIA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0354PokemonBanette    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0354_POKEMON_BANETTE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0373PokemonSalamence  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0373_POKEMON_SALAMENCE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0376PokemonMetagross  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0376_POKEMON_METAGROSS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0380PokemonLatias     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0380_POKEMON_LATIAS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0381PokemonLatios     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0381_POKEMON_LATIOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0382PokemonKyogre     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0382_POKEMON_KYOGRE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0383PokemonGroudon    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0383_POKEMON_GROUDON"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0384PokemonRayquaza   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0384_POKEMON_RAYQUAZA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0445PokemonGarchomp   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0445_POKEMON_GARCHOMP"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0687PokemonMalamar    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0687_POKEMON_MALAMAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0719PokemonDiancie    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0719_POKEMON_DIANCIE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0870PokemonFalinks    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_0_V0870_POKEMON_FALINKS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1                       MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0015PokemonBeedrill   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0015_POKEMON_BEEDRILL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0018PokemonPidgeot    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0018_POKEMON_PIDGEOT"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0026PokemonRaichu     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0026_POKEMON_RAICHU"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0071PokemonVictreebel MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0071_POKEMON_VICTREEBEL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0080PokemonSlowbro    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0080_POKEMON_SLOWBRO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0130PokemonGyarados   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0130_POKEMON_GYARADOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0149PokemonDragonite  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0149_POKEMON_DRAGONITE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0150PokemonMewtwo     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0150_POKEMON_MEWTWO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0227PokemonSkarmory   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0227_POKEMON_SKARMORY"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0229PokemonHoundoom   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0229_POKEMON_HOUNDOOM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0248PokemonTyranitar  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0248_POKEMON_TYRANITAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0302PokemonSableye    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0302_POKEMON_SABLEYE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0308PokemonMedicham   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0308_POKEMON_MEDICHAM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0310PokemonManectric  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0310_POKEMON_MANECTRIC"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0334PokemonAltaria    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0334_POKEMON_ALTARIA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0354PokemonBanette    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0354_POKEMON_BANETTE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0373PokemonSalamence  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0373_POKEMON_SALAMENCE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0376PokemonMetagross  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0376_POKEMON_METAGROSS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0380PokemonLatias     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0380_POKEMON_LATIAS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0381PokemonLatios     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0381_POKEMON_LATIOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0382PokemonKyogre     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0382_POKEMON_KYOGRE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0383PokemonGroudon    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0383_POKEMON_GROUDON"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0384PokemonRayquaza   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0384_POKEMON_RAYQUAZA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0445PokemonGarchomp   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0445_POKEMON_GARCHOMP"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0687PokemonMalamar    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0687_POKEMON_MALAMAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0719PokemonDiancie    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0719_POKEMON_DIANCIE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0870PokemonFalinks    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_1_V0870_POKEMON_FALINKS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2                       MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0015PokemonBeedrill   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0015_POKEMON_BEEDRILL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0018PokemonPidgeot    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0018_POKEMON_PIDGEOT"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0026PokemonRaichu     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0026_POKEMON_RAICHU"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0071PokemonVictreebel MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0071_POKEMON_VICTREEBEL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0080PokemonSlowbro    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0080_POKEMON_SLOWBRO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0130PokemonGyarados   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0130_POKEMON_GYARADOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0149PokemonDragonite  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0149_POKEMON_DRAGONITE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0150PokemonMewtwo     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0150_POKEMON_MEWTWO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0227PokemonSkarmory   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0227_POKEMON_SKARMORY"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0229PokemonHoundoom   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0229_POKEMON_HOUNDOOM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0248PokemonTyranitar  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0248_POKEMON_TYRANITAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0302PokemonSableye    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0302_POKEMON_SABLEYE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0308PokemonMedicham   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0308_POKEMON_MEDICHAM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0310PokemonManectric  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0310_POKEMON_MANECTRIC"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0334PokemonAltaria    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0334_POKEMON_ALTARIA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0354PokemonBanette    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0354_POKEMON_BANETTE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0373PokemonSalamence  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0373_POKEMON_SALAMENCE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0376PokemonMetagross  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0376_POKEMON_METAGROSS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0380PokemonLatias     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0380_POKEMON_LATIAS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0381PokemonLatios     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0381_POKEMON_LATIOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0382PokemonKyogre     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0382_POKEMON_KYOGRE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0383PokemonGroudon    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0383_POKEMON_GROUDON"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0384PokemonRayquaza   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0384_POKEMON_RAYQUAZA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0445PokemonGarchomp   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0445_POKEMON_GARCHOMP"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0687PokemonMalamar    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0687_POKEMON_MALAMAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0719PokemonDiancie    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0719_POKEMON_DIANCIE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0870PokemonFalinks    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_2_V0870_POKEMON_FALINKS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3                       MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0015PokemonBeedrill   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0015_POKEMON_BEEDRILL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0018PokemonPidgeot    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0018_POKEMON_PIDGEOT"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0026PokemonRaichu     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0026_POKEMON_RAICHU"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0071PokemonVictreebel MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0071_POKEMON_VICTREEBEL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0080PokemonSlowbro    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0080_POKEMON_SLOWBRO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0130PokemonGyarados   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0130_POKEMON_GYARADOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0149PokemonDragonite  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0149_POKEMON_DRAGONITE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0150PokemonMewtwo     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0150_POKEMON_MEWTWO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0227PokemonSkarmory   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0227_POKEMON_SKARMORY"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0229PokemonHoundoom   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0229_POKEMON_HOUNDOOM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0248PokemonTyranitar  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0248_POKEMON_TYRANITAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0302PokemonSableye    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0302_POKEMON_SABLEYE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0308PokemonMedicham   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0308_POKEMON_MEDICHAM"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0310PokemonManectric  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0310_POKEMON_MANECTRIC"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0334PokemonAltaria    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0334_POKEMON_ALTARIA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0354PokemonBanette    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0354_POKEMON_BANETTE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0373PokemonSalamence  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0373_POKEMON_SALAMENCE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0376PokemonMetagross  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0376_POKEMON_METAGROSS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0380PokemonLatias     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0380_POKEMON_LATIAS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0381PokemonLatios     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0381_POKEMON_LATIOS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0382PokemonKyogre     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0382_POKEMON_KYOGRE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0383PokemonGroudon    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0383_POKEMON_GROUDON"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0384PokemonRayquaza   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0384_POKEMON_RAYQUAZA"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0445PokemonGarchomp   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0445_POKEMON_GARCHOMP"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0687PokemonMalamar    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0687_POKEMON_MALAMAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0719PokemonDiancie    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0719_POKEMON_DIANCIE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0870PokemonFalinks    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_3_V0870_POKEMON_FALINKS"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0026PokemonRaichu     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_4_V0026_POKEMON_RAICHU"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0071PokemonVictreebel MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_4_V0071_POKEMON_VICTREEBEL"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0149PokemonDragonite  MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_4_V0149_POKEMON_DRAGONITE"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0150PokemonMewtwo     MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_4_V0150_POKEMON_MEWTWO"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0227PokemonSkarmory   MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_4_V0227_POKEMON_SKARMORY"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0687PokemonMalamar    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_4_V0687_POKEMON_MALAMAR"
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0870PokemonFalinks    MegaEvoLevelSettingsTemplateID = "MEGA_EVOLUTION_LEVEL_4_V0870_POKEMON_FALINKS"
)

var MegaEvoLevelSettingsTemplateIDValues = [...]MegaEvoLevelSettingsTemplateID{
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0015PokemonBeedrill,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0018PokemonPidgeot,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0026PokemonRaichu,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0071PokemonVictreebel,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0080PokemonSlowbro,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0130PokemonGyarados,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0149PokemonDragonite,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0150PokemonMewtwo,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0227PokemonSkarmory,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0229PokemonHoundoom,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0248PokemonTyranitar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0302PokemonSableye,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0308PokemonMedicham,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0310PokemonManectric,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0334PokemonAltaria,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0354PokemonBanette,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0373PokemonSalamence,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0376PokemonMetagross,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0380PokemonLatias,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0381PokemonLatios,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0382PokemonKyogre,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0383PokemonGroudon,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0384PokemonRayquaza,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0445PokemonGarchomp,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0687PokemonMalamar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0719PokemonDiancie,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel0V0870PokemonFalinks,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0015PokemonBeedrill,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0018PokemonPidgeot,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0026PokemonRaichu,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0071PokemonVictreebel,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0080PokemonSlowbro,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0130PokemonGyarados,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0149PokemonDragonite,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0150PokemonMewtwo,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0227PokemonSkarmory,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0229PokemonHoundoom,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0248PokemonTyranitar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0302PokemonSableye,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0308PokemonMedicham,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0310PokemonManectric,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0334PokemonAltaria,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0354PokemonBanette,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0373PokemonSalamence,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0376PokemonMetagross,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0380PokemonLatias,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0381PokemonLatios,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0382PokemonKyogre,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0383PokemonGroudon,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0384PokemonRayquaza,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0445PokemonGarchomp,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0687PokemonMalamar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0719PokemonDiancie,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel1V0870PokemonFalinks,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0015PokemonBeedrill,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0018PokemonPidgeot,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0026PokemonRaichu,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0071PokemonVictreebel,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0080PokemonSlowbro,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0130PokemonGyarados,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0149PokemonDragonite,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0150PokemonMewtwo,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0227PokemonSkarmory,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0229PokemonHoundoom,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0248PokemonTyranitar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0302PokemonSableye,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0308PokemonMedicham,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0310PokemonManectric,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0334PokemonAltaria,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0354PokemonBanette,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0373PokemonSalamence,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0376PokemonMetagross,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0380PokemonLatias,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0381PokemonLatios,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0382PokemonKyogre,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0383PokemonGroudon,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0384PokemonRayquaza,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0445PokemonGarchomp,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0687PokemonMalamar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0719PokemonDiancie,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel2V0870PokemonFalinks,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0015PokemonBeedrill,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0018PokemonPidgeot,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0026PokemonRaichu,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0071PokemonVictreebel,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0080PokemonSlowbro,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0130PokemonGyarados,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0149PokemonDragonite,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0150PokemonMewtwo,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0227PokemonSkarmory,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0229PokemonHoundoom,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0248PokemonTyranitar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0302PokemonSableye,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0308PokemonMedicham,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0310PokemonManectric,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0334PokemonAltaria,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0354PokemonBanette,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0373PokemonSalamence,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0376PokemonMetagross,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0380PokemonLatias,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0381PokemonLatios,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0382PokemonKyogre,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0383PokemonGroudon,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0384PokemonRayquaza,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0445PokemonGarchomp,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0687PokemonMalamar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0719PokemonDiancie,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel3V0870PokemonFalinks,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0026PokemonRaichu,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0071PokemonVictreebel,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0149PokemonDragonite,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0150PokemonMewtwo,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0227PokemonSkarmory,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0687PokemonMalamar,
	MegaEvoLevelSettingsTemplateIDMegaEvolutionLevel4V0870PokemonFalinks,
}
