// Generated from Pokémon GO masterfile — group "stickerMetadata", 600 entries (structural types).

export type * from "./variants";

export interface StickerMetadata<TemplateID extends string = string, TData extends StickerMetadataData = StickerMetadataData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		stickerMetadata: TData & {
			maxCount: 25;
			stickerId: TemplateID;
		};
	};
}

export interface StickerMetadataData {
	category: Array<"24_7" | "Characters" | "Decoration" | "Messages" | "Misc" | "Pokemon">;
	pokemonId?: string;
	regionId?: number;
	releaseDate?: number;
	stickerUrl?: string;
}

export type StickerMetadataMasterfileEntry =
	| StickerMetadata2023collab1
	| StickerMetadata2023collab2
	| StickerMetadata2023collab3
	| StickerMetadata2023collab4
	| StickerMetadata6anniv1
	| StickerMetadata6anniv2
	| StickerMetadata6anniv3
	| StickerMetadata6anniv4
	| StickerMetadata6anniv5
	| StickerMetadata6anniv6
	| StickerMetadata7anniv1
	| StickerMetadata7anniv2
	| StickerMetadata7anniv3
	| StickerMetadata7anniv4
	| StickerMetadata7anniv5
	| StickerMetadata8anniv1
	| StickerMetadata8anniv2
	| StickerMetadata8anniv3
	| StickerMetadata8anniv4
	| StickerMetadata9anniv1
	| StickerMetadata9anniv2
	| StickerMetadata9anniv3
	| StickerMetadataAlolaishi1
	| StickerMetadataAlolaishi2
	| StickerMetadataAlolaishi3
	| StickerMetadataAlolaishi4
	| StickerMetadataAprilfool20231
	| StickerMetadataAprilfool20232
	| StickerMetadataAudino
	| StickerMetadataBellsproutcd1
	| StickerMetadataBellsproutcd2
	| StickerMetadataBellsproutcd3
	| StickerMetadataBellsproutcd4
	| StickerMetadataBidoofday1
	| StickerMetadataBidoofday2
	| StickerMetadataBidoofday3
	| StickerMetadataBounsweetcd20241
	| StickerMetadataBounsweetcd20242
	| StickerMetadataBounsweetcd20243
	| StickerMetadataBounsweetcd20244
	| StickerMetadataBreadkorea001
	| StickerMetadataBreadkorea002
	| StickerMetadataBreadkorea003
	| StickerMetadataBreadkorea004
	| StickerMetadataBreadkorea005
	| StickerMetadataBreadkorea006
	| StickerMetadataChanseycd1
	| StickerMetadataChanseycd2
	| StickerMetadataChanseycd3
	| StickerMetadataChanseycd4
	| StickerMetadataCharizard1
	| StickerMetadataCharizard2
	| StickerMetadataCharizard3
	| StickerMetadataChespin1
	| StickerMetadataChespin2
	| StickerMetadataChespin3
	| StickerMetadataChespin4
	| StickerMetadataCityspotlight
	| StickerMetadataConciergeEevee
	| StickerMetadataConciergePsyduck
	| StickerMetadataConciergeSealeo
	| StickerMetadataConciergeShinx
	| StickerMetadataDeino1
	| StickerMetadataDeino2
	| StickerMetadataDeino3
	| StickerMetadataDeino4
	| StickerMetadataDiademuertos20231
	| StickerMetadataDiademuertos20232
	| StickerMetadataDiademuertos20233
	| StickerMetadataDiademuertos20234
	| StickerMetadataDiamondpearlchimchar
	| StickerMetadataDiamondpearldialga
	| StickerMetadataDiamondpearllucario
	| StickerMetadataDiamondpearlpalkia
	| StickerMetadataDiamondpearlpiplup
	| StickerMetadataDiamondpearlturtwig
	| StickerMetadataDitto1
	| StickerMetadataDitto2
	| StickerMetadataDitto3
	| StickerMetadataDitto4
	| StickerMetadataDitto5
	| StickerMetadataDitto6
	| StickerMetadataEeveefriends1
	| StickerMetadataEeveefriends2
	| StickerMetadataEeveefriends3
	| StickerMetadataEeveefriends4
	| StickerMetadataEeveefriends5
	| StickerMetadataEeveefriends6
	| StickerMetadataEeveefriends7
	| StickerMetadataEeveefriends8
	| StickerMetadataEeveefriends9
	| StickerMetadataEternatus
	| StickerMetadataFall20231
	| StickerMetadataFall20232
	| StickerMetadataFall20233
	| StickerMetadataFall20234
	| StickerMetadataFall20235
	| StickerMetadataFall20236
	| StickerMetadataFall20241
	| StickerMetadataFall20242
	| StickerMetadataFall20243
	| StickerMetadataFall20244
	| StickerMetadataFall20245
	| StickerMetadataFall20246
	| StickerMetadataFall20251
	| StickerMetadataFall20252
	| StickerMetadataFall20253
	| StickerMetadataFall20254
	| StickerMetadataFallSawsbuck
	| StickerMetadataFallShroomish
	| StickerMetadataFallSkwovet
	| StickerMetadataFallTeddiursa
	| StickerMetadataFallTrevenant
	| StickerMetadataFallVulpix
	| StickerMetadataFennekin1
	| StickerMetadataFennekin2
	| StickerMetadataFennekin3
	| StickerMetadataFennekin4
	| StickerMetadataFestivaloflightMorelull
	| StickerMetadataFestivaloflightShiinotic
	| StickerMetadataFestivalofthelights21V1
	| StickerMetadataFestivalofthelights21V2
	| StickerMetadataFestivalofthelights21V3
	| StickerMetadataFestivalofthelights21V4
	| StickerMetadataFlabebe1
	| StickerMetadataFlabebe2
	| StickerMetadataFlairHeart1
	| StickerMetadataFlairHeart2
	| StickerMetadataFlairHeart3
	| StickerMetadataFlairHeart4
	| StickerMetadataFlairHeart5
	| StickerMetadataFlairStar1
	| StickerMetadataFlairStar2
	| StickerMetadataFlairStar3
	| StickerMetadataFlairStar4
	| StickerMetadataFlairStar5
	| StickerMetadataFlairStar6
	| StickerMetadataFlairStar7
	| StickerMetadataFormulaekoreaPikachu
	| StickerMetadataFossilmuseum1
	| StickerMetadataFossilmuseum2
	| StickerMetadataFroakie1
	| StickerMetadataFroakie2
	| StickerMetadataFroakie3
	| StickerMetadataFroakie4
	| StickerMetadataFunawari04312
	| StickerMetadataFunawari05312
	| StickerMetadataFunawari06312
	| StickerMetadataFunawari22312
	| StickerMetadataFunwari020608
	| StickerMetadataFunwari10
	| StickerMetadataFunwari11Thanku
	| StickerMetadataFunwari1202
	| StickerMetadataFunwari18
	| StickerMetadataFunwari20
	| StickerMetadataFunwari35
	| StickerMetadataFunwariPidgey18
	| StickerMetadataFurfrouheart1
	| StickerMetadataFurfrouheart2
	| StickerMetadataGalarianzigzagoon1
	| StickerMetadataGalarianzigzagoon2
	| StickerMetadataGalarianzigzagoon3
	| StickerMetadataGalarianzigzagoon4
	| StickerMetadataGiftthankyou
	| StickerMetadataGimmighoul1
	| StickerMetadataGimmighoul2
	| StickerMetadataGimmighoul3
	| StickerMetadataGimmighoul4
	| StickerMetadataGimmighoul5
	| StickerMetadataGoomycd1
	| StickerMetadataGoomycd2
	| StickerMetadataGoomycd3
	| StickerMetadataGoomycd4
	| StickerMetadataGotour2021
	| StickerMetadataGotour20221
	| StickerMetadataGotour20222
	| StickerMetadataGotour20223
	| StickerMetadataGotour20224
	| StickerMetadataGotour2022Chikorita
	| StickerMetadataGotour2022Cyndaquil
	| StickerMetadataGotour2022Hooh
	| StickerMetadataGotour2022Lugia
	| StickerMetadataGotour2022Togepi
	| StickerMetadataGotour2022Totodile
	| StickerMetadataGotour2025Badge
	| StickerMetadataGotour2025Kyuremblack
	| StickerMetadataGotour2025Kyuremwhite
	| StickerMetadataGotour2025Reshiram
	| StickerMetadataGotour2025Rz
	| StickerMetadataGotour2025Zekrom
	| StickerMetadataGotourhoenn1
	| StickerMetadataGotourhoenn2
	| StickerMetadataGotourhoenn3
	| StickerMetadataGotourhoenn4
	| StickerMetadataGotourhoenn5
	| StickerMetadataGotourhoenn6
	| StickerMetadataGowa202501
	| StickerMetadataGowa202502
	| StickerMetadataGowa202503
	| StickerMetadataGowa202504
	| StickerMetadataGowa202505
	| StickerMetadataGrubbin1
	| StickerMetadataGrubbin2
	| StickerMetadataGrubbin3
	| StickerMetadataGrubbin4
	| StickerMetadataHalloween2022Gengar
	| StickerMetadataHalloween2022Pumpkaboo
	| StickerMetadataHalloween2022Vulpix
	| StickerMetadataHalloween2025Noibat
	| StickerMetadataHalloween2025Teddiursa
	| StickerMetadataHalloween21Fuwaraid
	| StickerMetadataHalloween21Ghostpika
	| StickerMetadataHalloween21Pikachu
	| StickerMetadataHalloween21Pochama
	| StickerMetadataHalloween23Gengar
	| StickerMetadataHalloween23Greavard
	| StickerMetadataHalloween23Misdreavus
	| StickerMetadataHalloween23Phantump
	| StickerMetadataHalloween24Froakie
	| StickerMetadataHalloween24Rowlet
	| StickerMetadataHalloweenBulb
	| StickerMetadataHalloweenCharm
	| StickerMetadataHalloweenGengarmd
	| StickerMetadataHalloweenPika
	| StickerMetadataHalloweenSableyemd
	| StickerMetadataHalloweenSqu
	| StickerMetadataHaruCherrim
	| StickerMetadataHaruDredearpika
	| StickerMetadataHaruKireihana
	| StickerMetadataHaruLalantes
	| StickerMetadataHaruMebukishikijik
	| StickerMetadataHaruMitsuhoney
	| StickerMetadataHawlucha01
	| StickerMetadataHisuidiscoArcanine
	| StickerMetadataHisuidiscoBraviary
	| StickerMetadataHisuidiscoGrowlithe
	| StickerMetadataHolidayevent211
	| StickerMetadataHolidayevent212
	| StickerMetadataHolidayevent213
	| StickerMetadataHolidayevent214
	| StickerMetadataHolidayevent22Cubchoo
	| StickerMetadataHolidayevent22Scatterbug
	| StickerMetadataHolidayevent22Snowpika
	| StickerMetadataHolidayevent22Vulpix
	| StickerMetadataHolidayevent23Cetoddle
	| StickerMetadataHolidayevent23Cryogonal
	| StickerMetadataHolidayevent23Psyduck
	| StickerMetadataHolidayevent23Seel
	| StickerMetadataHolidayevent23Vanillish
	| StickerMetadataHolographicChancey
	| StickerMetadataHolographicCharmeleon
	| StickerMetadataHolographicIvysaur
	| StickerMetadataHolographicMeltan
	| StickerMetadataHolographicPikachu
	| StickerMetadataHolographicWartortle
	| StickerMetadataHoppip1
	| StickerMetadataHoppip2
	| StickerMetadataHoppip3
	| StickerMetadataHoppip4
	| StickerMetadataIndonesiajourney1
	| StickerMetadataIndonesiajourney2
	| StickerMetadataIplpartnership1
	| StickerMetadataIplpartnership2
	| StickerMetadataJunecd2023Axew1
	| StickerMetadataJunecd2023Axew2
	| StickerMetadataJunecd2023Axew3
	| StickerMetadataJunecd2023Axew4
	| StickerMetadataKoreatown1
	| StickerMetadataKoreatown2
	| StickerMetadataKoreatown3
	| StickerMetadataKrDitto
	| StickerMetadataKurtasaree1
	| StickerMetadataKurtasaree2
	| StickerMetadataKurtasaree3
	| StickerMetadataKurtasaree4
	| StickerMetadataKurtasaree5
	| StickerMetadataKurtasaree6
	| StickerMetadataLentillaunchCamera
	| StickerMetadataLittencd1
	| StickerMetadataLittencd2
	| StickerMetadataLittencd3
	| StickerMetadataLittencd4
	| StickerMetadataLitwick1
	| StickerMetadataLitwick2
	| StickerMetadataLitwick3
	| StickerMetadataLitwick4
	| StickerMetadataLuvdisc
	| StickerMetadataMankey1
	| StickerMetadataMankey2
	| StickerMetadataMankey3
	| StickerMetadataMankey4
	| StickerMetadataMegaevolutionParis1
	| StickerMetadataMegaevolutionParis2
	| StickerMetadataMegaevolutionParis3
	| StickerMetadataMewtwo
	| StickerMetadataMewLaugh
	| StickerMetadataMukkuruCd1
	| StickerMetadataMukkuruCd2
	| StickerMetadataMukkuruCd3
	| StickerMetadataMukkuruCd4
	| StickerMetadataNagano06312
	| StickerMetadataNagano08
	| StickerMetadataNagano11
	| StickerMetadataNagano15
	| StickerMetadataNagano15312
	| StickerMetadataNaganoBath
	| StickerMetadataNaganoMarill
	| StickerMetadataNaganoYadon
	| StickerMetadataNewpokemon21
	| StickerMetadataNewpokemon215
	| StickerMetadataNewpokemon233
	| StickerMetadataNewpokemon04
	| StickerMetadataNewpokemon20
	| StickerMetadataNewpokemon37
	| StickerMetadataNewteamrascal
	| StickerMetadataNewteamrascalpikachu26
	| StickerMetadataNewyears221
	| StickerMetadataNewyears222
	| StickerMetadataNewyears223
	| StickerMetadataNewyears224
	| StickerMetadataNewyears231
	| StickerMetadataNewyears232
	| StickerMetadataNewyears233
	| StickerMetadataNewyears234
	| StickerMetadataNiaLogo
	| StickerMetadataNigiyaka080508312
	| StickerMetadataNigiyaka160508312
	| StickerMetadataNoibatCd1
	| StickerMetadataNoibatCd2
	| StickerMetadataNoibatCd3
	| StickerMetadataNoibatCd4
	| StickerMetadataNyarth38
	| StickerMetadataObservatory01
	| StickerMetadataObservatory02
	| StickerMetadataPapelpicadotgr1
	| StickerMetadataPapelpicadotgr2
	| StickerMetadataPapelpicadotgr3
	| StickerMetadataPapelpicadotgr4
	| StickerMetadataPapelpicadotgr5
	| StickerMetadataPgofest2021Galarianzigzagoon
	| StickerMetadataPgofest2021Logo
	| StickerMetadataPgofest2021Meloetta1
	| StickerMetadataPgofest2021Meloetta2
	| StickerMetadataPgofest2021Ponyta
	| StickerMetadataPgofest2021Shirticon
	| StickerMetadataPgofest2022Denjyumoku
	| StickerMetadataPgofest2022Groudon
	| StickerMetadataPgofest2022Kibago
	| StickerMetadataPgofest2022Kyogre
	| StickerMetadataPgofest2022Massivoon
	| StickerMetadataPgofest2022Pheroache
	| StickerMetadataPgofest2022Pikachu
	| StickerMetadataPgofest2022Pochama
	| StickerMetadataPgofest2022Shaymin
	| StickerMetadataPgofest2022Shayminsky
	| StickerMetadataPgofest2022Uturoid
	| StickerMetadataPgoFest2017
	| StickerMetadataPgoFest2018
	| StickerMetadataPgoFest2019
	| StickerMetadataPgoFest2020
	| StickerMetadataPgoFest2020Logo
	| StickerMetadataPgoFest2022
	| StickerMetadataPgoFest2022Logo
	| StickerMetadataPgoFest2023
	| StickerMetadataPgoFest20231
	| StickerMetadataPgoFest20232
	| StickerMetadataPgoFest20233
	| StickerMetadataPgoFest20234
	| StickerMetadataPgoFest20235
	| StickerMetadataPgoFest20236
	| StickerMetadataPgoFest2023Logo
	| StickerMetadataPgoFest2024
	| StickerMetadataPgoFest20241
	| StickerMetadataPgoFest20242
	| StickerMetadataPgoFest20243
	| StickerMetadataPgoFest20244
	| StickerMetadataPgoFest20245
	| StickerMetadataPgoFest20246
	| StickerMetadataPgoFest2024Logo
	| StickerMetadataPgoFest2025
	| StickerMetadataPgoFest20251
	| StickerMetadataPgoFest20252
	| StickerMetadataPgoFest20253
	| StickerMetadataPgoFest2025Logo
	| StickerMetadataPgoFestVictini05
	| StickerMetadataPgoTour2024
	| StickerMetadataPgoTour20241
	| StickerMetadataPgoTour20242
	| StickerMetadataPgoTour20243
	| StickerMetadataPgoTour20244
	| StickerMetadataPgoTour20245
	| StickerMetadataPgoTour2024Logo
	| StickerMetadataPgoTour2026
	| StickerMetadataPgoTour20261
	| StickerMetadataPgoTour20262
	| StickerMetadataPgoTour20263
	| StickerMetadataPgoTour2026Logo
	| StickerMetadataPgoWildarea2024
	| StickerMetadataPgoWildarea20241
	| StickerMetadataPgoWildarea20242
	| StickerMetadataPgoWildarea20243
	| StickerMetadataPgoWildarea20244
	| StickerMetadataPgoWildarea2024Logo
	| StickerMetadataPikaairadventure1
	| StickerMetadataPikaairadventure2
	| StickerMetadataPikaairadventure3
	| StickerMetadataPikaairjejuPikachu
	| StickerMetadataPikaairsingaporeLapras
	| StickerMetadataPikaairsingaporePikachu
	| StickerMetadataPikaairtaiwanPikachu
	| StickerMetadataPikaairtaiwanSnorlax
	| StickerMetadataPikachuJol
	| StickerMetadataPika14Thankyou
	| StickerMetadataPokemonchatpals204
	| StickerMetadataPokemonchatpals240
	| StickerMetadataPokopiaBulbasaur
	| StickerMetadataPokopiaPikachu
	| StickerMetadataPokopiaSnorlax
	| StickerMetadataPokopiaTangrowth
	| StickerMetadataPoliwag1
	| StickerMetadataPoliwag2
	| StickerMetadataPoliwag3
	| StickerMetadataPoliwag4
	| StickerMetadataPonyta1
	| StickerMetadataPonyta2
	| StickerMetadataPonyta3
	| StickerMetadataPonyta4
	| StickerMetadataPoppliocd1
	| StickerMetadataPoppliocd2
	| StickerMetadataPoppliocd3
	| StickerMetadataPoppliocd4
	| StickerMetadataProjectguitar04
	| StickerMetadataProjectguitar07
	| StickerMetadataProjectguitar13
	| StickerMetadataProjectguitar25
	| StickerMetadataProjectguitarFroakie
	| StickerMetadataPsychicspec21Inkay
	| StickerMetadataPsychicspec21Inkay2
	| StickerMetadataRoggenrolaCd1
	| StickerMetadataRoggenrolaCd2
	| StickerMetadataRoggenrolaCd3
	| StickerMetadataRoggenrolaCd4
	| StickerMetadataRowletcd1
	| StickerMetadataRowletcd2
	| StickerMetadataRowletcd3
	| StickerMetadataRowletcd4
	| StickerMetadataSandshrew1
	| StickerMetadataSandshrew2
	| StickerMetadataSandshrew3
	| StickerMetadataSandshrew4
	| StickerMetadataSecretsofthejungle1
	| StickerMetadataSecretsofthejungle4
	| StickerMetadataSecretsofthejungle5
	| StickerMetadataSecretsofthejungle6
	| StickerMetadataSecretsofthejungle7
	| StickerMetadataSecretsofthejungle8
	| StickerMetadataSecretsofthejungle9
	| StickerMetadataSewaddlecd1
	| StickerMetadataSewaddlecd2
	| StickerMetadataSewaddlecd3
	| StickerMetadataSewaddlecd4
	| StickerMetadataShelmetKarrablast1
	| StickerMetadataShelmetKarrablast2
	| StickerMetadataShelmetKarrablast3
	| StickerMetadataSleep1
	| StickerMetadataSleep2
	| StickerMetadataSleep3
	| StickerMetadataSleep4
	| StickerMetadataSleep5
	| StickerMetadataSleep6
	| StickerMetadataSleep7
	| StickerMetadataSlowpoke1
	| StickerMetadataSlowpoke2
	| StickerMetadataSlowpoke3
	| StickerMetadataSlowpoke4
	| StickerMetadataSpheal1
	| StickerMetadataSpheal2
	| StickerMetadataSpheal3
	| StickerMetadataSpheal4
	| StickerMetadataSprigatito1
	| StickerMetadataSprigatito2
	| StickerMetadataSprigatito3
	| StickerMetadataSprigatito4
	| StickerMetadataSpring20241
	| StickerMetadataSpring20242
	| StickerMetadataSpring20243
	| StickerMetadataSpring20244
	| StickerMetadataSpring20245
	| StickerMetadataSpring20246
	| StickerMetadataSpring20251
	| StickerMetadataSpring20252
	| StickerMetadataSpring20253
	| StickerMetadataSpring20254
	| StickerMetadataSpring20261
	| StickerMetadataSpring20262
	| StickerMetadataSpring20263
	| StickerMetadataSpring20264
	| StickerMetadataSpringEievui
	| StickerMetadataSpringHapinas
	| StickerMetadataSpringMimirol
	| StickerMetadataSpringNimphia
	| StickerMetadataSpringPikachu
	| StickerMetadataSpringPipito
	| StickerMetadataStufful1
	| StickerMetadataStufful2
	| StickerMetadataStufful3
	| StickerMetadataStufful4
	| StickerMetadataSummer1
	| StickerMetadataSummer2
	| StickerMetadataSummer2023Blastoise
	| StickerMetadataSummer2023Butterfree
	| StickerMetadataSummer2023Clamperl
	| StickerMetadataSummer2023Ledian
	| StickerMetadataSummer2023Sawsbuck
	| StickerMetadataSummer2023Squirtle
	| StickerMetadataSummer20241
	| StickerMetadataSummer20242
	| StickerMetadataSummer20243
	| StickerMetadataSummer20244
	| StickerMetadataSummer20245
	| StickerMetadataSummer20246
	| StickerMetadataSummer20251
	| StickerMetadataSummer20252
	| StickerMetadataSummer20253
	| StickerMetadataSummer20254
	| StickerMetadataSummer3
	| StickerMetadataSummer4
	| StickerMetadataSummer5
	| StickerMetadataSummer6
	| StickerMetadataSwordshield211
	| StickerMetadataSwordshield212
	| StickerMetadataSwordshield213
	| StickerMetadataSwordshield214
	| StickerMetadataSwordshield215
	| StickerMetadataTeddiursa1
	| StickerMetadataTeddiursa2
	| StickerMetadataTeddiursa3
	| StickerMetadataTeddiursa4
	| StickerMetadataTimburr1
	| StickerMetadataTimburr2
	| StickerMetadataTimburr3
	| StickerMetadataTimburr4
	| StickerMetadataTlBlanche
	| StickerMetadataTlCandela
	| StickerMetadataTlSpark
	| StickerMetadataTogeticcd20231
	| StickerMetadataTogeticcd20232
	| StickerMetadataTogeticcd20233
	| StickerMetadataTogeticcd20234
	| StickerMetadataTrArlo
	| StickerMetadataTrCliff
	| StickerMetadataTrSierra
	| StickerMetadataTynamocd1
	| StickerMetadataTynamocd2
	| StickerMetadataTynamocd3
	| StickerMetadataTynamocd4
	| StickerMetadataValentine20231
	| StickerMetadataValentine20232
	| StickerMetadataValentine20233
	| StickerMetadataWcs2025CarGroup
	| StickerMetadataWcs2025Jigglypuff
	| StickerMetadataWcs2025Murkrow
	| StickerMetadataWcs2025Pikachu
	| StickerMetadataWcsPlay
	| StickerMetadataWillowBronze
	| StickerMetadataWillowGold
	| StickerMetadataWillowSilver
	| StickerMetadataWinter20231
	| StickerMetadataWinter20232
	| StickerMetadataWinter20233
	| StickerMetadataWinter20234
	| StickerMetadataWinter20235
	| StickerMetadataWinter20236
	| StickerMetadataWinter20251
	| StickerMetadataWinter20252
	| StickerMetadataWinter20253
	| StickerMetadataWinter20254
	| StickerMetadataWinter20241
	| StickerMetadataWinter20242
	| StickerMetadataWinter20243
	| StickerMetadataWinter20244
	| StickerMetadataWinter20245
	| StickerMetadataWinter20246
	| StickerMetadataWinterAmaura
	| StickerMetadataWinterDarumaka
	| StickerMetadataWinterGlaceon
	| StickerMetadataWinterPikachu
	| StickerMetadataWinterSawsbuck
	| StickerMetadataWinterSnorunt
	| StickerMetadataWoopercd20231
	| StickerMetadataWoopercd20232
	| StickerMetadataWoopercd20233
	| StickerMetadataWoopercd20234
	| StickerMetadataYadon
	| StickerMetadataYurutto12
	| StickerMetadataYurutto24
	| StickerMetadataYurutto26
	| StickerMetadataYurutto33
	| StickerMetadataYurutto36
	| StickerMetadataYurutto37;

export type StickerMetadataTemplateID = StickerMetadataMasterfileEntry["templateId"];
