// Generated from Pokémon GO masterfile — group "settingsOverrideRule", 250 entries (structural types).

export type * from "./variants";

export interface SettingsOverrideRule<TemplateID extends string = string, TData extends SettingsOverrideRuleData = SettingsOverrideRuleData> {
	templateId: TemplateID;
	data: {
		templateId: TemplateID;
		settingsOverrideRule: TData;
	};
}

export interface SettingsOverrideRuleData {
	fusedDepthEnabled?: "TRUE";
	meshingEnabled?: "FALSE" | "TRUE";
	occlusionDefaultOn?: "FALSE";
	occlusionEnabled: "FALSE" | "TRUE";
	ruleType: number | "ALL" | "DEVICE_MODEL" | "DEVICE_MODEL_CONTAINS" | "PLATFORM";
	ruleValue?: string;
	semanticsEnabled: "FALSE" | "TRUE";
	sortOrder: number;
	vpsEnabled?: "FALSE" | "TRUE";
}

export type SettingsOverrideRuleMasterfileEntry =
	| SettingsOverrideRuleAllowAsusasusI006d
	| SettingsOverrideRuleAllowGooglepixel6
	| SettingsOverrideRuleAllowGooglepixel6a
	| SettingsOverrideRuleAllowGooglepixel6pro
	| SettingsOverrideRuleAllowGooglepixel7
	| SettingsOverrideRuleAllowGooglepixel7a
	| SettingsOverrideRuleAllowGooglepixel7pro
	| SettingsOverrideRuleAllowGooglepixel8
	| SettingsOverrideRuleAllowGooglepixel8pro
	| SettingsOverrideRuleAllowGooglepixel9
	| SettingsOverrideRuleAllowGooglepixel9pro
	| SettingsOverrideRuleAllowGooglepixelprofold
	| SettingsOverrideRuleAllowGooglepixelproxl
	| SettingsOverrideRuleAllowLgelmV600
	| SettingsOverrideRuleAllowMotorolamotorolaedge40
	| SettingsOverrideRuleAllowOnepluscph2399
	| SettingsOverrideRuleAllowOnepluscph2449
	| SettingsOverrideRuleAllowOneplusdn2103
	| SettingsOverrideRuleAllowOnepluskb2003
	| SettingsOverrideRuleAllowOneplusle2113
	| SettingsOverrideRuleAllowOneplusle2123
	| SettingsOverrideRuleAllowOneplusne2213
	| SettingsOverrideRuleAllowOneplusCph2413
	| SettingsOverrideRuleAllowOneplusCph2415
	| SettingsOverrideRuleAllowOneplusCph2417
	| SettingsOverrideRuleAllowOneplusCph2447
	| SettingsOverrideRuleAllowOneplusCph2451
	| SettingsOverrideRuleAllowOneplusCph2573
	| SettingsOverrideRuleAllowOneplusCph2581
	| SettingsOverrideRuleAllowOneplusCph2583
	| SettingsOverrideRuleAllowOneplusCph2585
	| SettingsOverrideRuleAllowOneplusCph2609
	| SettingsOverrideRuleAllowOneplusLe2115
	| SettingsOverrideRuleAllowOneplusLe2120
	| SettingsOverrideRuleAllowOneplusLe2121
	| SettingsOverrideRuleAllowOneplusLe2123
	| SettingsOverrideRuleAllowOneplusLe2125
	| SettingsOverrideRuleAllowOneplusLe2127
	| SettingsOverrideRuleAllowOneplusNe2210
	| SettingsOverrideRuleAllowOneplusNe2211
	| SettingsOverrideRuleAllowOneplusNe2213
	| SettingsOverrideRuleAllowOneplusNe2215
	| SettingsOverrideRuleAllowOneplusNe2217
	| SettingsOverrideRuleAllowOneplusPhb110
	| SettingsOverrideRuleAllowOneplusPjd110
	| SettingsOverrideRuleAllowOppocph2359
	| SettingsOverrideRuleAllowSamsungscg09
	| SettingsOverrideRuleAllowSamsungscg13
	| SettingsOverrideRuleAllowSamsungsc51a
	| SettingsOverrideRuleAllowSamsungsc51b
	| SettingsOverrideRuleAllowSamsungsc51c
	| SettingsOverrideRuleAllowSamsungsc51d
	| SettingsOverrideRuleAllowSamsungsc52c
	| SettingsOverrideRuleAllowSamsungsc52d
	| SettingsOverrideRuleAllowSamsungscA528b
	| SettingsOverrideRuleAllowSamsungsmF711b
	| SettingsOverrideRuleAllowSamsungsmF711n
	| SettingsOverrideRuleAllowSamsungsmF711u
	| SettingsOverrideRuleAllowSamsungsmF721b
	| SettingsOverrideRuleAllowSamsungsmF721n
	| SettingsOverrideRuleAllowSamsungsmF721u
	| SettingsOverrideRuleAllowSamsungsmF731b
	| SettingsOverrideRuleAllowSamsungsmF731n
	| SettingsOverrideRuleAllowSamsungsmF731u
	| SettingsOverrideRuleAllowSamsungsmF926b
	| SettingsOverrideRuleAllowSamsungsmF926n
	| SettingsOverrideRuleAllowSamsungsmF926u
	| SettingsOverrideRuleAllowSamsungsmF936b
	| SettingsOverrideRuleAllowSamsungsmF936n
	| SettingsOverrideRuleAllowSamsungsmF936u
	| SettingsOverrideRuleAllowSamsungsmF946b
	| SettingsOverrideRuleAllowSamsungsmF946n
	| SettingsOverrideRuleAllowSamsungsmF946u
	| SettingsOverrideRuleAllowSamsungsmG780f
	| SettingsOverrideRuleAllowSamsungsmG780g
	| SettingsOverrideRuleAllowSamsungsmG781b
	| SettingsOverrideRuleAllowSamsungsmG781n
	| SettingsOverrideRuleAllowSamsungsmG781u
	| SettingsOverrideRuleAllowSamsungsmG781u1
	| SettingsOverrideRuleAllowSamsungsmG781v
	| SettingsOverrideRuleAllowSamsungsmG781w
	| SettingsOverrideRuleAllowSamsungsmG980f
	| SettingsOverrideRuleAllowSamsungsmG981b
	| SettingsOverrideRuleAllowSamsungsmG981n
	| SettingsOverrideRuleAllowSamsungsmG981u
	| SettingsOverrideRuleAllowSamsungsmG981u1
	| SettingsOverrideRuleAllowSamsungsmG985f
	| SettingsOverrideRuleAllowSamsungsmG986b
	| SettingsOverrideRuleAllowSamsungsmG986n
	| SettingsOverrideRuleAllowSamsungsmG986u
	| SettingsOverrideRuleAllowSamsungsmG986u1
	| SettingsOverrideRuleAllowSamsungsmG988b
	| SettingsOverrideRuleAllowSamsungsmG988n
	| SettingsOverrideRuleAllowSamsungsmG988u
	| SettingsOverrideRuleAllowSamsungsmG990b
	| SettingsOverrideRuleAllowSamsungsmG990b2
	| SettingsOverrideRuleAllowSamsungsmG990e
	| SettingsOverrideRuleAllowSamsungsmG990u
	| SettingsOverrideRuleAllowSamsungsmG990u2
	| SettingsOverrideRuleAllowSamsungsmG990w2
	| SettingsOverrideRuleAllowSamsungsmG9910
	| SettingsOverrideRuleAllowSamsungsmG991b
	| SettingsOverrideRuleAllowSamsungsmG991n
	| SettingsOverrideRuleAllowSamsungsmG991u
	| SettingsOverrideRuleAllowSamsungsmG991u1
	| SettingsOverrideRuleAllowSamsungsmG991w
	| SettingsOverrideRuleAllowSamsungsmG996b
	| SettingsOverrideRuleAllowSamsungsmG996n
	| SettingsOverrideRuleAllowSamsungsmG996u
	| SettingsOverrideRuleAllowSamsungsmG996u1
	| SettingsOverrideRuleAllowSamsungsmG998b
	| SettingsOverrideRuleAllowSamsungsmG998n
	| SettingsOverrideRuleAllowSamsungsmG998u
	| SettingsOverrideRuleAllowSamsungsmG998u1
	| SettingsOverrideRuleAllowSamsungsmN970u
	| SettingsOverrideRuleAllowSamsungsmN980f
	| SettingsOverrideRuleAllowSamsungsmN981b
	| SettingsOverrideRuleAllowSamsungsmN981n
	| SettingsOverrideRuleAllowSamsungsmN981u
	| SettingsOverrideRuleAllowSamsungsmN9860
	| SettingsOverrideRuleAllowSamsungsmN986b
	| SettingsOverrideRuleAllowSamsungsmN986n
	| SettingsOverrideRuleAllowSamsungsmN986u
	| SettingsOverrideRuleAllowSamsungsmN986u1
	| SettingsOverrideRuleAllowSamsungsmS711b
	| SettingsOverrideRuleAllowSamsungsmS711n
	| SettingsOverrideRuleAllowSamsungsmS711u
	| SettingsOverrideRuleAllowSamsungsmS711w
	| SettingsOverrideRuleAllowSamsungsmS901b
	| SettingsOverrideRuleAllowSamsungsmS901e
	| SettingsOverrideRuleAllowSamsungsmS901n
	| SettingsOverrideRuleAllowSamsungsmS901u
	| SettingsOverrideRuleAllowSamsungsmS901u1
	| SettingsOverrideRuleAllowSamsungsmS901w
	| SettingsOverrideRuleAllowSamsungsmS9060
	| SettingsOverrideRuleAllowSamsungsmS906b
	| SettingsOverrideRuleAllowSamsungsmS906e
	| SettingsOverrideRuleAllowSamsungsmS906n
	| SettingsOverrideRuleAllowSamsungsmS906u
	| SettingsOverrideRuleAllowSamsungsmS906u1
	| SettingsOverrideRuleAllowSamsungsmS9080
	| SettingsOverrideRuleAllowSamsungsmS908b
	| SettingsOverrideRuleAllowSamsungsmS908e
	| SettingsOverrideRuleAllowSamsungsmS908n
	| SettingsOverrideRuleAllowSamsungsmS908u
	| SettingsOverrideRuleAllowSamsungsmS908u1
	| SettingsOverrideRuleAllowSamsungsmS908w
	| SettingsOverrideRuleAllowSamsungsmS911b
	| SettingsOverrideRuleAllowSamsungsmS911n
	| SettingsOverrideRuleAllowSamsungsmS911u
	| SettingsOverrideRuleAllowSamsungsmS911u1
	| SettingsOverrideRuleAllowSamsungsmS911w
	| SettingsOverrideRuleAllowSamsungsmS9160
	| SettingsOverrideRuleAllowSamsungsmS916b
	| SettingsOverrideRuleAllowSamsungsmS916n
	| SettingsOverrideRuleAllowSamsungsmS916u
	| SettingsOverrideRuleAllowSamsungsmS916u1
	| SettingsOverrideRuleAllowSamsungsmS9180
	| SettingsOverrideRuleAllowSamsungsmS918b
	| SettingsOverrideRuleAllowSamsungsmS918n
	| SettingsOverrideRuleAllowSamsungsmS918u
	| SettingsOverrideRuleAllowSamsungsmS918u1
	| SettingsOverrideRuleAllowSamsungsmS918w
	| SettingsOverrideRuleAllowSamsungsmS921b
	| SettingsOverrideRuleAllowSamsungsmS921n
	| SettingsOverrideRuleAllowSamsungsmS9260
	| SettingsOverrideRuleAllowSamsungsmS926u
	| SettingsOverrideRuleAllowSamsungsmS9280
	| SettingsOverrideRuleAllowSamsungsmS928b
	| SettingsOverrideRuleAllowSamsungsmS928n
	| SettingsOverrideRuleAllowSamsungsmS928u
	| SettingsOverrideRuleAllowSamsungsmS928u1
	| SettingsOverrideRuleAllowSharpsh51b
	| SettingsOverrideRuleAllowSonysog02
	| SettingsOverrideRuleAllowSonysog05
	| SettingsOverrideRuleAllowSonysog06
	| SettingsOverrideRuleAllowSonyso51a
	| SettingsOverrideRuleAllowSonyso51b
	| SettingsOverrideRuleAllowSonyso51c
	| SettingsOverrideRuleAllowSonyso52a
	| SettingsOverrideRuleAllowSonyso53b
	| SettingsOverrideRuleAllowSonyso54c
	| SettingsOverrideRuleAllowSonyA002so
	| SettingsOverrideRuleAllowSonyA101so
	| SettingsOverrideRuleAllowSonyA103so
	| SettingsOverrideRuleAllowSonyA201so
	| SettingsOverrideRuleAllowSonySo53b
	| SettingsOverrideRuleAllowSonySog01
	| SettingsOverrideRuleAllowSonySog03
	| SettingsOverrideRuleAllowSonyXperia1Ii
	| SettingsOverrideRuleAllowSonyXperia1Iii
	| SettingsOverrideRuleAllowSonyXperia1Iv
	| SettingsOverrideRuleAllowSonyXperia1V
	| SettingsOverrideRuleAllowSonyXperia5Ii
	| SettingsOverrideRuleAllowSonyXperia5Iii
	| SettingsOverrideRuleAllowSonyXperia5V
	| SettingsOverrideRuleAllowSonyXperiaPro
	| SettingsOverrideRuleAllowSonyXperiaProi
	| SettingsOverrideRuleAllowSonyXqaq52
	| SettingsOverrideRuleAllowSonyXqaq62
	| SettingsOverrideRuleAllowSonyXqas42
	| SettingsOverrideRuleAllowSonyXqas52
	| SettingsOverrideRuleAllowSonyXqas62
	| SettingsOverrideRuleAllowSonyXqas72
	| SettingsOverrideRuleAllowSonyXqat42
	| SettingsOverrideRuleAllowSonyXqat51
	| SettingsOverrideRuleAllowSonyXqat52
	| SettingsOverrideRuleAllowSonyXqat72
	| SettingsOverrideRuleAllowSonyXqbc42
	| SettingsOverrideRuleAllowSonyXqbc52
	| SettingsOverrideRuleAllowSonyXqbc62
	| SettingsOverrideRuleAllowSonyXqbc72
	| SettingsOverrideRuleAllowSonyXqbe52
	| SettingsOverrideRuleAllowSonyXqbe62
	| SettingsOverrideRuleAllowSonyXqbe72
	| SettingsOverrideRuleAllowSonyXqbq42
	| SettingsOverrideRuleAllowSonyXqbq52
	| SettingsOverrideRuleAllowSonyXqbq62
	| SettingsOverrideRuleAllowSonyXqbq72
	| SettingsOverrideRuleAllowSonyXqct54
	| SettingsOverrideRuleAllowSonyXqct62
	| SettingsOverrideRuleAllowSonyXqct72
	| SettingsOverrideRuleAllowSonyXqDe44
	| SettingsOverrideRuleAllowSonyXqDq44
	| SettingsOverrideRuleAllowXiaomi21061110ag
	| SettingsOverrideRuleAllowXiaomi2107113sg
	| SettingsOverrideRuleAllowXiaomi21081111rg
	| SettingsOverrideRuleAllowXiaomi21121210g
	| SettingsOverrideRuleAllowXiaomi2201123g
	| SettingsOverrideRuleAllowXiaomi22021211rg
	| SettingsOverrideRuleAllowXiaomi22041216g
	| SettingsOverrideRuleAllowXiaomi22081212ug
	| SettingsOverrideRuleAllowXiaomi23049pcd8g
	| SettingsOverrideRuleAllowXiaomim2007j3sg
	| SettingsOverrideRuleAllowXiaomim2007j3sy
	| SettingsOverrideRuleAllowXiaomim2012k11ag
	| SettingsOverrideRuleAllowXiaomim2102k1ac
	| SettingsOverrideRuleAndroid
	| SettingsOverrideRuleAndroid14Onward
	| SettingsOverrideRuleBase
	| SettingsOverrideRuleDenyGooglepixel10
	| SettingsOverrideRuleDenyGooglepixel10pro
	| SettingsOverrideRuleDenyGooglepixel10profold
	| SettingsOverrideRuleDenyGooglepixel10proxl
	| SettingsOverrideRuleDenyIpad4
	| SettingsOverrideRuleDenyIpad5
	| SettingsOverrideRuleDenyIpad6
	| SettingsOverrideRuleDenyIphone6
	| SettingsOverrideRuleDenyIphone7
	| SettingsOverrideRuleDenyIphonese;

export type SettingsOverrideRuleTemplateID = SettingsOverrideRuleMasterfileEntry["templateId"];
