// Generated from Pokémon GO masterfile — group "pokestopInvasionAvailabilitySettings" templateIds.

package pokestop_invasion_availability_settings

type PokestopInvasionAvailabilitySettingsTemplateID string

const (
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsFriday    PokestopInvasionAvailabilitySettingsTemplateID = "INVASION_AVAILABILITY_SETTINGS_FRIDAY"
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsMonday    PokestopInvasionAvailabilitySettingsTemplateID = "INVASION_AVAILABILITY_SETTINGS_MONDAY"
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsSaturday  PokestopInvasionAvailabilitySettingsTemplateID = "INVASION_AVAILABILITY_SETTINGS_SATURDAY"
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsSunday    PokestopInvasionAvailabilitySettingsTemplateID = "INVASION_AVAILABILITY_SETTINGS_SUNDAY"
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsThursday  PokestopInvasionAvailabilitySettingsTemplateID = "INVASION_AVAILABILITY_SETTINGS_THURSDAY"
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsTuesday   PokestopInvasionAvailabilitySettingsTemplateID = "INVASION_AVAILABILITY_SETTINGS_TUESDAY"
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsWednesday PokestopInvasionAvailabilitySettingsTemplateID = "INVASION_AVAILABILITY_SETTINGS_WEDNESDAY"
)

var PokestopInvasionAvailabilitySettingsTemplateIDValues = [...]PokestopInvasionAvailabilitySettingsTemplateID{
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsFriday,
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsMonday,
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsSaturday,
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsSunday,
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsThursday,
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsTuesday,
	PokestopInvasionAvailabilitySettingsTemplateIDInvasionAvailabilitySettingsWednesday,
}
