// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/avatar_item_display"
)

// AvatarItemDisplayAccessor provides typed lookups for the "avatarItemDisplay" group.
type AvatarItemDisplayAccessor struct {
	entries []avatar_item_display.AvatarItemDisplayEntry
	index   map[avatar_item_display.AvatarItemDisplayTemplateID]int
}

// NewAvatarItemDisplayAccessor builds a AvatarItemDisplayAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewAvatarItemDisplayAccessor(entries []avatar_item_display.AvatarItemDisplayEntry) *AvatarItemDisplayAccessor {
	idx := make(map[avatar_item_display.AvatarItemDisplayTemplateID]int, len(entries))
	for i, e := range entries {
		idx[avatar_item_display.AvatarItemDisplayTemplateID(e.TemplateID)] = i
	}
	return &AvatarItemDisplayAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *AvatarItemDisplayAccessor) Get(id avatar_item_display.AvatarItemDisplayTemplateID) (avatar_item_display.AvatarItemDisplayEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero avatar_item_display.AvatarItemDisplayEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *AvatarItemDisplayAccessor) Has(id avatar_item_display.AvatarItemDisplayTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *AvatarItemDisplayAccessor) All() []avatar_item_display.AvatarItemDisplayEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *AvatarItemDisplayAccessor) TemplateIDs() []avatar_item_display.AvatarItemDisplayTemplateID {
	ids := make([]avatar_item_display.AvatarItemDisplayTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, avatar_item_display.AvatarItemDisplayTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *AvatarItemDisplayAccessor) Len() int {
	return len(a.entries)
}
