// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/avatar_group_order_settings"
)

// AvatarGroupOrderSettingsAccessor provides typed lookups for the "avatarGroupOrderSettings" group.
type AvatarGroupOrderSettingsAccessor struct {
	entries []avatar_group_order_settings.AvatarGroupOrderSettingsEntry
	index   map[avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID]int
}

// NewAvatarGroupOrderSettingsAccessor builds a AvatarGroupOrderSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewAvatarGroupOrderSettingsAccessor(entries []avatar_group_order_settings.AvatarGroupOrderSettingsEntry) *AvatarGroupOrderSettingsAccessor {
	idx := make(map[avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID(e.TemplateID)] = i
	}
	return &AvatarGroupOrderSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *AvatarGroupOrderSettingsAccessor) Get(id avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID) (avatar_group_order_settings.AvatarGroupOrderSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero avatar_group_order_settings.AvatarGroupOrderSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *AvatarGroupOrderSettingsAccessor) Has(id avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *AvatarGroupOrderSettingsAccessor) All() []avatar_group_order_settings.AvatarGroupOrderSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *AvatarGroupOrderSettingsAccessor) TemplateIDs() []avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID {
	ids := make([]avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, avatar_group_order_settings.AvatarGroupOrderSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *AvatarGroupOrderSettingsAccessor) Len() int {
	return len(a.entries)
}
