// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/avatar_customization"
)

// AvatarCustomizationAccessor provides typed lookups for the "avatarCustomization" group.
type AvatarCustomizationAccessor struct {
	entries []avatar_customization.AvatarCustomizationEntry
	index   map[avatar_customization.AvatarCustomizationTemplateID]int
}

// NewAvatarCustomizationAccessor builds a AvatarCustomizationAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewAvatarCustomizationAccessor(entries []avatar_customization.AvatarCustomizationEntry) *AvatarCustomizationAccessor {
	idx := make(map[avatar_customization.AvatarCustomizationTemplateID]int, len(entries))
	for i, e := range entries {
		idx[avatar_customization.AvatarCustomizationTemplateID(e.TemplateID)] = i
	}
	return &AvatarCustomizationAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *AvatarCustomizationAccessor) Get(id avatar_customization.AvatarCustomizationTemplateID) (avatar_customization.AvatarCustomizationEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero avatar_customization.AvatarCustomizationEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *AvatarCustomizationAccessor) Has(id avatar_customization.AvatarCustomizationTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *AvatarCustomizationAccessor) All() []avatar_customization.AvatarCustomizationEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *AvatarCustomizationAccessor) TemplateIDs() []avatar_customization.AvatarCustomizationTemplateID {
	ids := make([]avatar_customization.AvatarCustomizationTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, avatar_customization.AvatarCustomizationTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *AvatarCustomizationAccessor) Len() int {
	return len(a.entries)
}
