// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/badge_settings"
)

// BadgeSettingsAccessor provides typed lookups for the "badgeSettings" group.
type BadgeSettingsAccessor struct {
	entries []badge_settings.BadgeSettingsEntry
	index   map[badge_settings.BadgeSettingsTemplateID]int
}

// NewBadgeSettingsAccessor builds a BadgeSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewBadgeSettingsAccessor(entries []badge_settings.BadgeSettingsEntry) *BadgeSettingsAccessor {
	idx := make(map[badge_settings.BadgeSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[badge_settings.BadgeSettingsTemplateID(e.TemplateID)] = i
	}
	return &BadgeSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *BadgeSettingsAccessor) Get(id badge_settings.BadgeSettingsTemplateID) (badge_settings.BadgeSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero badge_settings.BadgeSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *BadgeSettingsAccessor) Has(id badge_settings.BadgeSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *BadgeSettingsAccessor) All() []badge_settings.BadgeSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *BadgeSettingsAccessor) TemplateIDs() []badge_settings.BadgeSettingsTemplateID {
	ids := make([]badge_settings.BadgeSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, badge_settings.BadgeSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *BadgeSettingsAccessor) Len() int {
	return len(a.entries)
}
