// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/bread_move_level_settings"
)

// BreadMoveLevelSettingsAccessor provides typed lookups for the "breadMoveLevelSettings" group.
type BreadMoveLevelSettingsAccessor struct {
	entries []bread_move_level_settings.BreadMoveLevelSettingsEntry
	index   map[bread_move_level_settings.BreadMoveLevelSettingsTemplateID]int
}

// NewBreadMoveLevelSettingsAccessor builds a BreadMoveLevelSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewBreadMoveLevelSettingsAccessor(entries []bread_move_level_settings.BreadMoveLevelSettingsEntry) *BreadMoveLevelSettingsAccessor {
	idx := make(map[bread_move_level_settings.BreadMoveLevelSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[bread_move_level_settings.BreadMoveLevelSettingsTemplateID(e.TemplateID)] = i
	}
	return &BreadMoveLevelSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *BreadMoveLevelSettingsAccessor) Get(id bread_move_level_settings.BreadMoveLevelSettingsTemplateID) (bread_move_level_settings.BreadMoveLevelSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero bread_move_level_settings.BreadMoveLevelSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *BreadMoveLevelSettingsAccessor) Has(id bread_move_level_settings.BreadMoveLevelSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *BreadMoveLevelSettingsAccessor) All() []bread_move_level_settings.BreadMoveLevelSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *BreadMoveLevelSettingsAccessor) TemplateIDs() []bread_move_level_settings.BreadMoveLevelSettingsTemplateID {
	ids := make([]bread_move_level_settings.BreadMoveLevelSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, bread_move_level_settings.BreadMoveLevelSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *BreadMoveLevelSettingsAccessor) Len() int {
	return len(a.entries)
}
