// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/buddy_emotion_level_settings"
)

// BuddyEmotionLevelSettingsAccessor provides typed lookups for the "buddyEmotionLevelSettings" group.
type BuddyEmotionLevelSettingsAccessor struct {
	entries []buddy_emotion_level_settings.BuddyEmotionLevelSettingsEntry
	index   map[buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID]int
}

// NewBuddyEmotionLevelSettingsAccessor builds a BuddyEmotionLevelSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewBuddyEmotionLevelSettingsAccessor(entries []buddy_emotion_level_settings.BuddyEmotionLevelSettingsEntry) *BuddyEmotionLevelSettingsAccessor {
	idx := make(map[buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID(e.TemplateID)] = i
	}
	return &BuddyEmotionLevelSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *BuddyEmotionLevelSettingsAccessor) Get(id buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID) (buddy_emotion_level_settings.BuddyEmotionLevelSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero buddy_emotion_level_settings.BuddyEmotionLevelSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *BuddyEmotionLevelSettingsAccessor) Has(id buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *BuddyEmotionLevelSettingsAccessor) All() []buddy_emotion_level_settings.BuddyEmotionLevelSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *BuddyEmotionLevelSettingsAccessor) TemplateIDs() []buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID {
	ids := make([]buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, buddy_emotion_level_settings.BuddyEmotionLevelSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *BuddyEmotionLevelSettingsAccessor) Len() int {
	return len(a.entries)
}
