// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/buddy_activity_category_settings"
)

// BuddyActivityCategorySettingsAccessor provides typed lookups for the "buddyActivityCategorySettings" group.
type BuddyActivityCategorySettingsAccessor struct {
	entries []buddy_activity_category_settings.BuddyActivityCategorySettingsEntry
	index   map[buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID]int
}

// NewBuddyActivityCategorySettingsAccessor builds a BuddyActivityCategorySettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewBuddyActivityCategorySettingsAccessor(entries []buddy_activity_category_settings.BuddyActivityCategorySettingsEntry) *BuddyActivityCategorySettingsAccessor {
	idx := make(map[buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID(e.TemplateID)] = i
	}
	return &BuddyActivityCategorySettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *BuddyActivityCategorySettingsAccessor) Get(id buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID) (buddy_activity_category_settings.BuddyActivityCategorySettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero buddy_activity_category_settings.BuddyActivityCategorySettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *BuddyActivityCategorySettingsAccessor) Has(id buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *BuddyActivityCategorySettingsAccessor) All() []buddy_activity_category_settings.BuddyActivityCategorySettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *BuddyActivityCategorySettingsAccessor) TemplateIDs() []buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID {
	ids := make([]buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, buddy_activity_category_settings.BuddyActivityCategorySettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *BuddyActivityCategorySettingsAccessor) Len() int {
	return len(a.entries)
}
