// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/buddy_level_settings"
)

// BuddyLevelSettingsAccessor provides typed lookups for the "buddyLevelSettings" group.
type BuddyLevelSettingsAccessor struct {
	entries []buddy_level_settings.BuddyLevelSettingsEntry
	index   map[buddy_level_settings.BuddyLevelSettingsTemplateID]int
}

// NewBuddyLevelSettingsAccessor builds a BuddyLevelSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewBuddyLevelSettingsAccessor(entries []buddy_level_settings.BuddyLevelSettingsEntry) *BuddyLevelSettingsAccessor {
	idx := make(map[buddy_level_settings.BuddyLevelSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[buddy_level_settings.BuddyLevelSettingsTemplateID(e.TemplateID)] = i
	}
	return &BuddyLevelSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *BuddyLevelSettingsAccessor) Get(id buddy_level_settings.BuddyLevelSettingsTemplateID) (buddy_level_settings.BuddyLevelSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero buddy_level_settings.BuddyLevelSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *BuddyLevelSettingsAccessor) Has(id buddy_level_settings.BuddyLevelSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *BuddyLevelSettingsAccessor) All() []buddy_level_settings.BuddyLevelSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *BuddyLevelSettingsAccessor) TemplateIDs() []buddy_level_settings.BuddyLevelSettingsTemplateID {
	ids := make([]buddy_level_settings.BuddyLevelSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, buddy_level_settings.BuddyLevelSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *BuddyLevelSettingsAccessor) Len() int {
	return len(a.entries)
}
