// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/client_quest_template"
)

// ClientQuestTemplateAccessor provides typed lookups for the "clientQuestTemplate" group.
type ClientQuestTemplateAccessor struct {
	entries []client_quest_template.ClientQuestTemplateEntry
	index   map[client_quest_template.ClientQuestTemplateTemplateID]int
}

// NewClientQuestTemplateAccessor builds a ClientQuestTemplateAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewClientQuestTemplateAccessor(entries []client_quest_template.ClientQuestTemplateEntry) *ClientQuestTemplateAccessor {
	idx := make(map[client_quest_template.ClientQuestTemplateTemplateID]int, len(entries))
	for i, e := range entries {
		idx[client_quest_template.ClientQuestTemplateTemplateID(e.TemplateID)] = i
	}
	return &ClientQuestTemplateAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *ClientQuestTemplateAccessor) Get(id client_quest_template.ClientQuestTemplateTemplateID) (client_quest_template.ClientQuestTemplateEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero client_quest_template.ClientQuestTemplateEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *ClientQuestTemplateAccessor) Has(id client_quest_template.ClientQuestTemplateTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *ClientQuestTemplateAccessor) All() []client_quest_template.ClientQuestTemplateEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *ClientQuestTemplateAccessor) TemplateIDs() []client_quest_template.ClientQuestTemplateTemplateID {
	ids := make([]client_quest_template.ClientQuestTemplateTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, client_quest_template.ClientQuestTemplateTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *ClientQuestTemplateAccessor) Len() int {
	return len(a.entries)
}
