// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/code_gate_proto"
)

// CodeGateProtoAccessor provides typed lookups for the "codeGateProto" group.
type CodeGateProtoAccessor struct {
	entries []code_gate_proto.CodeGateProtoEntry
	index   map[code_gate_proto.CodeGateProtoTemplateID]int
}

// NewCodeGateProtoAccessor builds a CodeGateProtoAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewCodeGateProtoAccessor(entries []code_gate_proto.CodeGateProtoEntry) *CodeGateProtoAccessor {
	idx := make(map[code_gate_proto.CodeGateProtoTemplateID]int, len(entries))
	for i, e := range entries {
		idx[code_gate_proto.CodeGateProtoTemplateID(e.TemplateID)] = i
	}
	return &CodeGateProtoAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *CodeGateProtoAccessor) Get(id code_gate_proto.CodeGateProtoTemplateID) (code_gate_proto.CodeGateProtoEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero code_gate_proto.CodeGateProtoEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *CodeGateProtoAccessor) Has(id code_gate_proto.CodeGateProtoTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *CodeGateProtoAccessor) All() []code_gate_proto.CodeGateProtoEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *CodeGateProtoAccessor) TemplateIDs() []code_gate_proto.CodeGateProtoTemplateID {
	ids := make([]code_gate_proto.CodeGateProtoTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, code_gate_proto.CodeGateProtoTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *CodeGateProtoAccessor) Len() int {
	return len(a.entries)
}
