// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_move"
)

// CombatMoveAccessor provides typed lookups for the "combatMove" group.
type CombatMoveAccessor struct {
	entries []combat_move.CombatMoveEntry
	index   map[combat_move.CombatMoveTemplateID]int
}

// NewCombatMoveAccessor builds a CombatMoveAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewCombatMoveAccessor(entries []combat_move.CombatMoveEntry) *CombatMoveAccessor {
	idx := make(map[combat_move.CombatMoveTemplateID]int, len(entries))
	for i, e := range entries {
		idx[combat_move.CombatMoveTemplateID(e.TemplateID)] = i
	}
	return &CombatMoveAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *CombatMoveAccessor) Get(id combat_move.CombatMoveTemplateID) (combat_move.CombatMoveEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero combat_move.CombatMoveEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *CombatMoveAccessor) Has(id combat_move.CombatMoveTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *CombatMoveAccessor) All() []combat_move.CombatMoveEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *CombatMoveAccessor) TemplateIDs() []combat_move.CombatMoveTemplateID {
	ids := make([]combat_move.CombatMoveTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, combat_move.CombatMoveTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *CombatMoveAccessor) Len() int {
	return len(a.entries)
}
