// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_league"
)

// CombatLeagueAccessor provides typed lookups for the "combatLeague" group.
type CombatLeagueAccessor struct {
	entries []combat_league.CombatLeagueEntry
	index   map[combat_league.CombatLeagueTemplateID]int
}

// NewCombatLeagueAccessor builds a CombatLeagueAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewCombatLeagueAccessor(entries []combat_league.CombatLeagueEntry) *CombatLeagueAccessor {
	idx := make(map[combat_league.CombatLeagueTemplateID]int, len(entries))
	for i, e := range entries {
		idx[combat_league.CombatLeagueTemplateID(e.TemplateID)] = i
	}
	return &CombatLeagueAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *CombatLeagueAccessor) Get(id combat_league.CombatLeagueTemplateID) (combat_league.CombatLeagueEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero combat_league.CombatLeagueEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *CombatLeagueAccessor) Has(id combat_league.CombatLeagueTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *CombatLeagueAccessor) All() []combat_league.CombatLeagueEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *CombatLeagueAccessor) TemplateIDs() []combat_league.CombatLeagueTemplateID {
	ids := make([]combat_league.CombatLeagueTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, combat_league.CombatLeagueTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *CombatLeagueAccessor) Len() int {
	return len(a.entries)
}
