// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/combat_type"
)

// CombatTypeAccessor provides typed lookups for the "combatType" group.
type CombatTypeAccessor struct {
	entries []combat_type.CombatTypeEntry
	index   map[combat_type.CombatTypeTemplateID]int
}

// NewCombatTypeAccessor builds a CombatTypeAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewCombatTypeAccessor(entries []combat_type.CombatTypeEntry) *CombatTypeAccessor {
	idx := make(map[combat_type.CombatTypeTemplateID]int, len(entries))
	for i, e := range entries {
		idx[combat_type.CombatTypeTemplateID(e.TemplateID)] = i
	}
	return &CombatTypeAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *CombatTypeAccessor) Get(id combat_type.CombatTypeTemplateID) (combat_type.CombatTypeEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero combat_type.CombatTypeEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *CombatTypeAccessor) Has(id combat_type.CombatTypeTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *CombatTypeAccessor) All() []combat_type.CombatTypeEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *CombatTypeAccessor) TemplateIDs() []combat_type.CombatTypeTemplateID {
	ids := make([]combat_type.CombatTypeTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, combat_type.CombatTypeTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *CombatTypeAccessor) Len() int {
	return len(a.entries)
}
