// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/combat_npc_trainer"
)

// CombatNpcTrainerAccessor provides typed lookups for the "combatNpcTrainer" group.
type CombatNpcTrainerAccessor struct {
	entries []combat_npc_trainer.CombatNpcTrainerEntry
	index   map[combat_npc_trainer.CombatNpcTrainerTemplateID]int
}

// NewCombatNpcTrainerAccessor builds a CombatNpcTrainerAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewCombatNpcTrainerAccessor(entries []combat_npc_trainer.CombatNpcTrainerEntry) *CombatNpcTrainerAccessor {
	idx := make(map[combat_npc_trainer.CombatNpcTrainerTemplateID]int, len(entries))
	for i, e := range entries {
		idx[combat_npc_trainer.CombatNpcTrainerTemplateID(e.TemplateID)] = i
	}
	return &CombatNpcTrainerAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *CombatNpcTrainerAccessor) Get(id combat_npc_trainer.CombatNpcTrainerTemplateID) (combat_npc_trainer.CombatNpcTrainerEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero combat_npc_trainer.CombatNpcTrainerEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *CombatNpcTrainerAccessor) Has(id combat_npc_trainer.CombatNpcTrainerTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *CombatNpcTrainerAccessor) All() []combat_npc_trainer.CombatNpcTrainerEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *CombatNpcTrainerAccessor) TemplateIDs() []combat_npc_trainer.CombatNpcTrainerTemplateID {
	ids := make([]combat_npc_trainer.CombatNpcTrainerTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, combat_npc_trainer.CombatNpcTrainerTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *CombatNpcTrainerAccessor) Len() int {
	return len(a.entries)
}
