// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/combat_npc_personality"
)

// CombatNpcPersonalityAccessor provides typed lookups for the "combatNpcPersonality" group.
type CombatNpcPersonalityAccessor struct {
	entries []combat_npc_personality.CombatNpcPersonalityEntry
	index   map[combat_npc_personality.CombatNpcPersonalityTemplateID]int
}

// NewCombatNpcPersonalityAccessor builds a CombatNpcPersonalityAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewCombatNpcPersonalityAccessor(entries []combat_npc_personality.CombatNpcPersonalityEntry) *CombatNpcPersonalityAccessor {
	idx := make(map[combat_npc_personality.CombatNpcPersonalityTemplateID]int, len(entries))
	for i, e := range entries {
		idx[combat_npc_personality.CombatNpcPersonalityTemplateID(e.TemplateID)] = i
	}
	return &CombatNpcPersonalityAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *CombatNpcPersonalityAccessor) Get(id combat_npc_personality.CombatNpcPersonalityTemplateID) (combat_npc_personality.CombatNpcPersonalityEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero combat_npc_personality.CombatNpcPersonalityEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *CombatNpcPersonalityAccessor) Has(id combat_npc_personality.CombatNpcPersonalityTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *CombatNpcPersonalityAccessor) All() []combat_npc_personality.CombatNpcPersonalityEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *CombatNpcPersonalityAccessor) TemplateIDs() []combat_npc_personality.CombatNpcPersonalityTemplateID {
	ids := make([]combat_npc_personality.CombatNpcPersonalityTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, combat_npc_personality.CombatNpcPersonalityTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *CombatNpcPersonalityAccessor) Len() int {
	return len(a.entries)
}
