// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/combat_ranking_proto_settings"
)

// CombatRankingProtoSettingsAccessor provides typed lookups for the "combatRankingProtoSettings" group.
type CombatRankingProtoSettingsAccessor struct {
	entries []combat_ranking_proto_settings.CombatRankingProtoSettingsEntry
	index   map[combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID]int
}

// NewCombatRankingProtoSettingsAccessor builds a CombatRankingProtoSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewCombatRankingProtoSettingsAccessor(entries []combat_ranking_proto_settings.CombatRankingProtoSettingsEntry) *CombatRankingProtoSettingsAccessor {
	idx := make(map[combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID(e.TemplateID)] = i
	}
	return &CombatRankingProtoSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *CombatRankingProtoSettingsAccessor) Get(id combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID) (combat_ranking_proto_settings.CombatRankingProtoSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero combat_ranking_proto_settings.CombatRankingProtoSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *CombatRankingProtoSettingsAccessor) Has(id combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *CombatRankingProtoSettingsAccessor) All() []combat_ranking_proto_settings.CombatRankingProtoSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *CombatRankingProtoSettingsAccessor) TemplateIDs() []combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID {
	ids := make([]combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, combat_ranking_proto_settings.CombatRankingProtoSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *CombatRankingProtoSettingsAccessor) Len() int {
	return len(a.entries)
}
