// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/event_pass_tier_settings"
)

// EventPassTierSettingsAccessor provides typed lookups for the "eventPassTierSettings" group.
type EventPassTierSettingsAccessor struct {
	entries []event_pass_tier_settings.EventPassTierSettingsEntry
	index   map[event_pass_tier_settings.EventPassTierSettingsTemplateID]int
}

// NewEventPassTierSettingsAccessor builds a EventPassTierSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewEventPassTierSettingsAccessor(entries []event_pass_tier_settings.EventPassTierSettingsEntry) *EventPassTierSettingsAccessor {
	idx := make(map[event_pass_tier_settings.EventPassTierSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[event_pass_tier_settings.EventPassTierSettingsTemplateID(e.TemplateID)] = i
	}
	return &EventPassTierSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *EventPassTierSettingsAccessor) Get(id event_pass_tier_settings.EventPassTierSettingsTemplateID) (event_pass_tier_settings.EventPassTierSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero event_pass_tier_settings.EventPassTierSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *EventPassTierSettingsAccessor) Has(id event_pass_tier_settings.EventPassTierSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *EventPassTierSettingsAccessor) All() []event_pass_tier_settings.EventPassTierSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *EventPassTierSettingsAccessor) TemplateIDs() []event_pass_tier_settings.EventPassTierSettingsTemplateID {
	ids := make([]event_pass_tier_settings.EventPassTierSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, event_pass_tier_settings.EventPassTierSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *EventPassTierSettingsAccessor) Len() int {
	return len(a.entries)
}
