// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/event_pass_settings"
)

// EventPassSettingsAccessor provides typed lookups for the "eventPassSettings" group.
type EventPassSettingsAccessor struct {
	entries []event_pass_settings.EventPassSettingsEntry
	index   map[event_pass_settings.EventPassSettingsTemplateID]int
}

// NewEventPassSettingsAccessor builds a EventPassSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewEventPassSettingsAccessor(entries []event_pass_settings.EventPassSettingsEntry) *EventPassSettingsAccessor {
	idx := make(map[event_pass_settings.EventPassSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[event_pass_settings.EventPassSettingsTemplateID(e.TemplateID)] = i
	}
	return &EventPassSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *EventPassSettingsAccessor) Get(id event_pass_settings.EventPassSettingsTemplateID) (event_pass_settings.EventPassSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero event_pass_settings.EventPassSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *EventPassSettingsAccessor) Has(id event_pass_settings.EventPassSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *EventPassSettingsAccessor) All() []event_pass_settings.EventPassSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *EventPassSettingsAccessor) TemplateIDs() []event_pass_settings.EventPassSettingsTemplateID {
	ids := make([]event_pass_settings.EventPassSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, event_pass_settings.EventPassSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *EventPassSettingsAccessor) Len() int {
	return len(a.entries)
}
