// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/evolution_quest_template"
)

// EvolutionQuestTemplateAccessor provides typed lookups for the "evolutionQuestTemplate" group.
type EvolutionQuestTemplateAccessor struct {
	entries []evolution_quest_template.EvolutionQuestTemplateEntry
	index   map[evolution_quest_template.EvolutionQuestTemplateTemplateID]int
}

// NewEvolutionQuestTemplateAccessor builds a EvolutionQuestTemplateAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewEvolutionQuestTemplateAccessor(entries []evolution_quest_template.EvolutionQuestTemplateEntry) *EvolutionQuestTemplateAccessor {
	idx := make(map[evolution_quest_template.EvolutionQuestTemplateTemplateID]int, len(entries))
	for i, e := range entries {
		idx[evolution_quest_template.EvolutionQuestTemplateTemplateID(e.TemplateID)] = i
	}
	return &EvolutionQuestTemplateAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *EvolutionQuestTemplateAccessor) Get(id evolution_quest_template.EvolutionQuestTemplateTemplateID) (evolution_quest_template.EvolutionQuestTemplateEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero evolution_quest_template.EvolutionQuestTemplateEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *EvolutionQuestTemplateAccessor) Has(id evolution_quest_template.EvolutionQuestTemplateTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *EvolutionQuestTemplateAccessor) All() []evolution_quest_template.EvolutionQuestTemplateEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *EvolutionQuestTemplateAccessor) TemplateIDs() []evolution_quest_template.EvolutionQuestTemplateTemplateID {
	ids := make([]evolution_quest_template.EvolutionQuestTemplateTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, evolution_quest_template.EvolutionQuestTemplateTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *EvolutionQuestTemplateAccessor) Len() int {
	return len(a.entries)
}
