// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/evolution_chain_display_settings"
)

// EvolutionChainDisplaySettingsAccessor provides typed lookups for the "evolutionChainDisplaySettings" group.
type EvolutionChainDisplaySettingsAccessor struct {
	entries []evolution_chain_display_settings.EvolutionChainDisplaySettingsEntry
	index   map[evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID]int
}

// NewEvolutionChainDisplaySettingsAccessor builds a EvolutionChainDisplaySettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewEvolutionChainDisplaySettingsAccessor(entries []evolution_chain_display_settings.EvolutionChainDisplaySettingsEntry) *EvolutionChainDisplaySettingsAccessor {
	idx := make(map[evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID(e.TemplateID)] = i
	}
	return &EvolutionChainDisplaySettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *EvolutionChainDisplaySettingsAccessor) Get(id evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID) (evolution_chain_display_settings.EvolutionChainDisplaySettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero evolution_chain_display_settings.EvolutionChainDisplaySettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *EvolutionChainDisplaySettingsAccessor) Has(id evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *EvolutionChainDisplaySettingsAccessor) All() []evolution_chain_display_settings.EvolutionChainDisplaySettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *EvolutionChainDisplaySettingsAccessor) TemplateIDs() []evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID {
	ids := make([]evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, evolution_chain_display_settings.EvolutionChainDisplaySettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *EvolutionChainDisplaySettingsAccessor) Len() int {
	return len(a.entries)
}
