// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/feature_gate"
)

// FeatureGateAccessor provides typed lookups for the "featureGate" group.
type FeatureGateAccessor struct {
	entries []feature_gate.FeatureGateEntry
	index   map[feature_gate.FeatureGateTemplateID]int
}

// NewFeatureGateAccessor builds a FeatureGateAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewFeatureGateAccessor(entries []feature_gate.FeatureGateEntry) *FeatureGateAccessor {
	idx := make(map[feature_gate.FeatureGateTemplateID]int, len(entries))
	for i, e := range entries {
		idx[feature_gate.FeatureGateTemplateID(e.TemplateID)] = i
	}
	return &FeatureGateAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *FeatureGateAccessor) Get(id feature_gate.FeatureGateTemplateID) (feature_gate.FeatureGateEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero feature_gate.FeatureGateEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *FeatureGateAccessor) Has(id feature_gate.FeatureGateTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *FeatureGateAccessor) All() []feature_gate.FeatureGateEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *FeatureGateAccessor) TemplateIDs() []feature_gate.FeatureGateTemplateID {
	ids := make([]feature_gate.FeatureGateTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, feature_gate.FeatureGateTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *FeatureGateAccessor) Len() int {
	return len(a.entries)
}
