// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/form_settings"
)

// FormSettingsAccessor provides typed lookups for the "formSettings" group.
type FormSettingsAccessor struct {
	entries []form_settings.FormSettingsEntry
	index   map[form_settings.FormSettingsTemplateID]int
}

// NewFormSettingsAccessor builds a FormSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewFormSettingsAccessor(entries []form_settings.FormSettingsEntry) *FormSettingsAccessor {
	idx := make(map[form_settings.FormSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[form_settings.FormSettingsTemplateID(e.TemplateID)] = i
	}
	return &FormSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *FormSettingsAccessor) Get(id form_settings.FormSettingsTemplateID) (form_settings.FormSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero form_settings.FormSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *FormSettingsAccessor) Has(id form_settings.FormSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *FormSettingsAccessor) All() []form_settings.FormSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *FormSettingsAccessor) TemplateIDs() []form_settings.FormSettingsTemplateID {
	ids := make([]form_settings.FormSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, form_settings.FormSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *FormSettingsAccessor) Len() int {
	return len(a.entries)
}
