// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/fort_power_up_level_settings"
)

// FortPowerUpLevelSettingsAccessor provides typed lookups for the "fortPowerUpLevelSettings" group.
type FortPowerUpLevelSettingsAccessor struct {
	entries []fort_power_up_level_settings.FortPowerUpLevelSettingsEntry
	index   map[fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID]int
}

// NewFortPowerUpLevelSettingsAccessor builds a FortPowerUpLevelSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewFortPowerUpLevelSettingsAccessor(entries []fort_power_up_level_settings.FortPowerUpLevelSettingsEntry) *FortPowerUpLevelSettingsAccessor {
	idx := make(map[fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID(e.TemplateID)] = i
	}
	return &FortPowerUpLevelSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *FortPowerUpLevelSettingsAccessor) Get(id fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID) (fort_power_up_level_settings.FortPowerUpLevelSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero fort_power_up_level_settings.FortPowerUpLevelSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *FortPowerUpLevelSettingsAccessor) Has(id fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *FortPowerUpLevelSettingsAccessor) All() []fort_power_up_level_settings.FortPowerUpLevelSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *FortPowerUpLevelSettingsAccessor) TemplateIDs() []fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID {
	ids := make([]fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, fort_power_up_level_settings.FortPowerUpLevelSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *FortPowerUpLevelSettingsAccessor) Len() int {
	return len(a.entries)
}
