// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/friendship_milestone_settings"
)

// FriendshipMilestoneSettingsAccessor provides typed lookups for the "friendshipMilestoneSettings" group.
type FriendshipMilestoneSettingsAccessor struct {
	entries []friendship_milestone_settings.FriendshipMilestoneSettingsEntry
	index   map[friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID]int
}

// NewFriendshipMilestoneSettingsAccessor builds a FriendshipMilestoneSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewFriendshipMilestoneSettingsAccessor(entries []friendship_milestone_settings.FriendshipMilestoneSettingsEntry) *FriendshipMilestoneSettingsAccessor {
	idx := make(map[friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID(e.TemplateID)] = i
	}
	return &FriendshipMilestoneSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *FriendshipMilestoneSettingsAccessor) Get(id friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID) (friendship_milestone_settings.FriendshipMilestoneSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero friendship_milestone_settings.FriendshipMilestoneSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *FriendshipMilestoneSettingsAccessor) Has(id friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *FriendshipMilestoneSettingsAccessor) All() []friendship_milestone_settings.FriendshipMilestoneSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *FriendshipMilestoneSettingsAccessor) TemplateIDs() []friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID {
	ids := make([]friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, friendship_milestone_settings.FriendshipMilestoneSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *FriendshipMilestoneSettingsAccessor) Len() int {
	return len(a.entries)
}
