// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/gender_settings"
)

// GenderSettingsAccessor provides typed lookups for the "genderSettings" group.
type GenderSettingsAccessor struct {
	entries []gender_settings.GenderSettingsEntry
	index   map[gender_settings.GenderSettingsTemplateID]int
}

// NewGenderSettingsAccessor builds a GenderSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewGenderSettingsAccessor(entries []gender_settings.GenderSettingsEntry) *GenderSettingsAccessor {
	idx := make(map[gender_settings.GenderSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[gender_settings.GenderSettingsTemplateID(e.TemplateID)] = i
	}
	return &GenderSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *GenderSettingsAccessor) Get(id gender_settings.GenderSettingsTemplateID) (gender_settings.GenderSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero gender_settings.GenderSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *GenderSettingsAccessor) Has(id gender_settings.GenderSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *GenderSettingsAccessor) All() []gender_settings.GenderSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *GenderSettingsAccessor) TemplateIDs() []gender_settings.GenderSettingsTemplateID {
	ids := make([]gender_settings.GenderSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, gender_settings.GenderSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *GenderSettingsAccessor) Len() int {
	return len(a.entries)
}
