// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/iap_item_display"
)

// IapItemDisplayAccessor provides typed lookups for the "iapItemDisplay" group.
type IapItemDisplayAccessor struct {
	entries []iap_item_display.IapItemDisplayEntry
	index   map[iap_item_display.IapItemDisplayTemplateID]int
}

// NewIapItemDisplayAccessor builds a IapItemDisplayAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewIapItemDisplayAccessor(entries []iap_item_display.IapItemDisplayEntry) *IapItemDisplayAccessor {
	idx := make(map[iap_item_display.IapItemDisplayTemplateID]int, len(entries))
	for i, e := range entries {
		idx[iap_item_display.IapItemDisplayTemplateID(e.TemplateID)] = i
	}
	return &IapItemDisplayAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *IapItemDisplayAccessor) Get(id iap_item_display.IapItemDisplayTemplateID) (iap_item_display.IapItemDisplayEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero iap_item_display.IapItemDisplayEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *IapItemDisplayAccessor) Has(id iap_item_display.IapItemDisplayTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *IapItemDisplayAccessor) All() []iap_item_display.IapItemDisplayEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *IapItemDisplayAccessor) TemplateIDs() []iap_item_display.IapItemDisplayTemplateID {
	ids := make([]iap_item_display.IapItemDisplayTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, iap_item_display.IapItemDisplayTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *IapItemDisplayAccessor) Len() int {
	return len(a.entries)
}
