// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/iap_category_display"
)

// IapCategoryDisplayAccessor provides typed lookups for the "iapCategoryDisplay" group.
type IapCategoryDisplayAccessor struct {
	entries []iap_category_display.IapCategoryDisplayEntry
	index   map[iap_category_display.IapCategoryDisplayTemplateID]int
}

// NewIapCategoryDisplayAccessor builds a IapCategoryDisplayAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewIapCategoryDisplayAccessor(entries []iap_category_display.IapCategoryDisplayEntry) *IapCategoryDisplayAccessor {
	idx := make(map[iap_category_display.IapCategoryDisplayTemplateID]int, len(entries))
	for i, e := range entries {
		idx[iap_category_display.IapCategoryDisplayTemplateID(e.TemplateID)] = i
	}
	return &IapCategoryDisplayAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *IapCategoryDisplayAccessor) Get(id iap_category_display.IapCategoryDisplayTemplateID) (iap_category_display.IapCategoryDisplayEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero iap_category_display.IapCategoryDisplayEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *IapCategoryDisplayAccessor) Has(id iap_category_display.IapCategoryDisplayTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *IapCategoryDisplayAccessor) All() []iap_category_display.IapCategoryDisplayEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *IapCategoryDisplayAccessor) TemplateIDs() []iap_category_display.IapCategoryDisplayTemplateID {
	ids := make([]iap_category_display.IapCategoryDisplayTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, iap_category_display.IapCategoryDisplayTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *IapCategoryDisplayAccessor) Len() int {
	return len(a.entries)
}
