// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/invasion_npc_display_settings"
)

// InvasionNpcDisplaySettingsAccessor provides typed lookups for the "invasionNpcDisplaySettings" group.
type InvasionNpcDisplaySettingsAccessor struct {
	entries []invasion_npc_display_settings.InvasionNpcDisplaySettingsEntry
	index   map[invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID]int
}

// NewInvasionNpcDisplaySettingsAccessor builds a InvasionNpcDisplaySettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewInvasionNpcDisplaySettingsAccessor(entries []invasion_npc_display_settings.InvasionNpcDisplaySettingsEntry) *InvasionNpcDisplaySettingsAccessor {
	idx := make(map[invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID(e.TemplateID)] = i
	}
	return &InvasionNpcDisplaySettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *InvasionNpcDisplaySettingsAccessor) Get(id invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID) (invasion_npc_display_settings.InvasionNpcDisplaySettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero invasion_npc_display_settings.InvasionNpcDisplaySettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *InvasionNpcDisplaySettingsAccessor) Has(id invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *InvasionNpcDisplaySettingsAccessor) All() []invasion_npc_display_settings.InvasionNpcDisplaySettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *InvasionNpcDisplaySettingsAccessor) TemplateIDs() []invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID {
	ids := make([]invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, invasion_npc_display_settings.InvasionNpcDisplaySettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *InvasionNpcDisplaySettingsAccessor) Len() int {
	return len(a.entries)
}
