// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/item_settings"
)

// ItemSettingsAccessor provides typed lookups for the "itemSettings" group.
type ItemSettingsAccessor struct {
	entries []item_settings.ItemSettingsEntry
	index   map[item_settings.ItemSettingsTemplateID]int
}

// NewItemSettingsAccessor builds a ItemSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewItemSettingsAccessor(entries []item_settings.ItemSettingsEntry) *ItemSettingsAccessor {
	idx := make(map[item_settings.ItemSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[item_settings.ItemSettingsTemplateID(e.TemplateID)] = i
	}
	return &ItemSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *ItemSettingsAccessor) Get(id item_settings.ItemSettingsTemplateID) (item_settings.ItemSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero item_settings.ItemSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *ItemSettingsAccessor) Has(id item_settings.ItemSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *ItemSettingsAccessor) All() []item_settings.ItemSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *ItemSettingsAccessor) TemplateIDs() []item_settings.ItemSettingsTemplateID {
	ids := make([]item_settings.ItemSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, item_settings.ItemSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *ItemSettingsAccessor) Len() int {
	return len(a.entries)
}
