// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/item_expiration_settings"
)

// ItemExpirationSettingsAccessor provides typed lookups for the "itemExpirationSettings" group.
type ItemExpirationSettingsAccessor struct {
	entries []item_expiration_settings.ItemExpirationSettingsEntry
	index   map[item_expiration_settings.ItemExpirationSettingsTemplateID]int
}

// NewItemExpirationSettingsAccessor builds a ItemExpirationSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewItemExpirationSettingsAccessor(entries []item_expiration_settings.ItemExpirationSettingsEntry) *ItemExpirationSettingsAccessor {
	idx := make(map[item_expiration_settings.ItemExpirationSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[item_expiration_settings.ItemExpirationSettingsTemplateID(e.TemplateID)] = i
	}
	return &ItemExpirationSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *ItemExpirationSettingsAccessor) Get(id item_expiration_settings.ItemExpirationSettingsTemplateID) (item_expiration_settings.ItemExpirationSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero item_expiration_settings.ItemExpirationSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *ItemExpirationSettingsAccessor) Has(id item_expiration_settings.ItemExpirationSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *ItemExpirationSettingsAccessor) All() []item_expiration_settings.ItemExpirationSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *ItemExpirationSettingsAccessor) TemplateIDs() []item_expiration_settings.ItemExpirationSettingsTemplateID {
	ids := make([]item_expiration_settings.ItemExpirationSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, item_expiration_settings.ItemExpirationSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *ItemExpirationSettingsAccessor) Len() int {
	return len(a.entries)
}
