// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/language_settings"
)

// LanguageSettingsAccessor provides typed lookups for the "languageSettings" group.
type LanguageSettingsAccessor struct {
	entries []language_settings.LanguageSettingsEntry
	index   map[language_settings.LanguageSettingsTemplateID]int
}

// NewLanguageSettingsAccessor builds a LanguageSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewLanguageSettingsAccessor(entries []language_settings.LanguageSettingsEntry) *LanguageSettingsAccessor {
	idx := make(map[language_settings.LanguageSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[language_settings.LanguageSettingsTemplateID(e.TemplateID)] = i
	}
	return &LanguageSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *LanguageSettingsAccessor) Get(id language_settings.LanguageSettingsTemplateID) (language_settings.LanguageSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero language_settings.LanguageSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *LanguageSettingsAccessor) Has(id language_settings.LanguageSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *LanguageSettingsAccessor) All() []language_settings.LanguageSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *LanguageSettingsAccessor) TemplateIDs() []language_settings.LanguageSettingsTemplateID {
	ids := make([]language_settings.LanguageSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, language_settings.LanguageSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *LanguageSettingsAccessor) Len() int {
	return len(a.entries)
}
