// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/level_up_rewards"
)

// LevelUpRewardsAccessor provides typed lookups for the "levelUpRewards" group.
type LevelUpRewardsAccessor struct {
	entries []level_up_rewards.LevelUpRewardsEntry
	index   map[level_up_rewards.LevelUpRewardsTemplateID]int
}

// NewLevelUpRewardsAccessor builds a LevelUpRewardsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewLevelUpRewardsAccessor(entries []level_up_rewards.LevelUpRewardsEntry) *LevelUpRewardsAccessor {
	idx := make(map[level_up_rewards.LevelUpRewardsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[level_up_rewards.LevelUpRewardsTemplateID(e.TemplateID)] = i
	}
	return &LevelUpRewardsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *LevelUpRewardsAccessor) Get(id level_up_rewards.LevelUpRewardsTemplateID) (level_up_rewards.LevelUpRewardsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero level_up_rewards.LevelUpRewardsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *LevelUpRewardsAccessor) Has(id level_up_rewards.LevelUpRewardsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *LevelUpRewardsAccessor) All() []level_up_rewards.LevelUpRewardsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *LevelUpRewardsAccessor) TemplateIDs() []level_up_rewards.LevelUpRewardsTemplateID {
	ids := make([]level_up_rewards.LevelUpRewardsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, level_up_rewards.LevelUpRewardsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *LevelUpRewardsAccessor) Len() int {
	return len(a.entries)
}
