// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/limited_purchase_sku_settings"
)

// LimitedPurchaseSkuSettingsAccessor provides typed lookups for the "limitedPurchaseSkuSettings" group.
type LimitedPurchaseSkuSettingsAccessor struct {
	entries []limited_purchase_sku_settings.LimitedPurchaseSkuSettingsEntry
	index   map[limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID]int
}

// NewLimitedPurchaseSkuSettingsAccessor builds a LimitedPurchaseSkuSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewLimitedPurchaseSkuSettingsAccessor(entries []limited_purchase_sku_settings.LimitedPurchaseSkuSettingsEntry) *LimitedPurchaseSkuSettingsAccessor {
	idx := make(map[limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID(e.TemplateID)] = i
	}
	return &LimitedPurchaseSkuSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *LimitedPurchaseSkuSettingsAccessor) Get(id limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID) (limited_purchase_sku_settings.LimitedPurchaseSkuSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero limited_purchase_sku_settings.LimitedPurchaseSkuSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *LimitedPurchaseSkuSettingsAccessor) Has(id limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *LimitedPurchaseSkuSettingsAccessor) All() []limited_purchase_sku_settings.LimitedPurchaseSkuSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *LimitedPurchaseSkuSettingsAccessor) TemplateIDs() []limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID {
	ids := make([]limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, limited_purchase_sku_settings.LimitedPurchaseSkuSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *LimitedPurchaseSkuSettingsAccessor) Len() int {
	return len(a.entries)
}
