// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/location_card_settings"
)

// LocationCardSettingsAccessor provides typed lookups for the "locationCardSettings" group.
type LocationCardSettingsAccessor struct {
	entries []location_card_settings.LocationCardSettingsEntry
	index   map[location_card_settings.LocationCardSettingsTemplateID]int
}

// NewLocationCardSettingsAccessor builds a LocationCardSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewLocationCardSettingsAccessor(entries []location_card_settings.LocationCardSettingsEntry) *LocationCardSettingsAccessor {
	idx := make(map[location_card_settings.LocationCardSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[location_card_settings.LocationCardSettingsTemplateID(e.TemplateID)] = i
	}
	return &LocationCardSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *LocationCardSettingsAccessor) Get(id location_card_settings.LocationCardSettingsTemplateID) (location_card_settings.LocationCardSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero location_card_settings.LocationCardSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *LocationCardSettingsAccessor) Has(id location_card_settings.LocationCardSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *LocationCardSettingsAccessor) All() []location_card_settings.LocationCardSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *LocationCardSettingsAccessor) TemplateIDs() []location_card_settings.LocationCardSettingsTemplateID {
	ids := make([]location_card_settings.LocationCardSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, location_card_settings.LocationCardSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *LocationCardSettingsAccessor) Len() int {
	return len(a.entries)
}
