// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/mega_evo_level_settings"
)

// MegaEvoLevelSettingsAccessor provides typed lookups for the "megaEvoLevelSettings" group.
type MegaEvoLevelSettingsAccessor struct {
	entries []mega_evo_level_settings.MegaEvoLevelSettingsEntry
	index   map[mega_evo_level_settings.MegaEvoLevelSettingsTemplateID]int
}

// NewMegaEvoLevelSettingsAccessor builds a MegaEvoLevelSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewMegaEvoLevelSettingsAccessor(entries []mega_evo_level_settings.MegaEvoLevelSettingsEntry) *MegaEvoLevelSettingsAccessor {
	idx := make(map[mega_evo_level_settings.MegaEvoLevelSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[mega_evo_level_settings.MegaEvoLevelSettingsTemplateID(e.TemplateID)] = i
	}
	return &MegaEvoLevelSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *MegaEvoLevelSettingsAccessor) Get(id mega_evo_level_settings.MegaEvoLevelSettingsTemplateID) (mega_evo_level_settings.MegaEvoLevelSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero mega_evo_level_settings.MegaEvoLevelSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *MegaEvoLevelSettingsAccessor) Has(id mega_evo_level_settings.MegaEvoLevelSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *MegaEvoLevelSettingsAccessor) All() []mega_evo_level_settings.MegaEvoLevelSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *MegaEvoLevelSettingsAccessor) TemplateIDs() []mega_evo_level_settings.MegaEvoLevelSettingsTemplateID {
	ids := make([]mega_evo_level_settings.MegaEvoLevelSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, mega_evo_level_settings.MegaEvoLevelSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *MegaEvoLevelSettingsAccessor) Len() int {
	return len(a.entries)
}
