// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/move_settings"
)

// MoveSettingsAccessor provides typed lookups for the "moveSettings" group.
type MoveSettingsAccessor struct {
	entries []move_settings.MoveSettingsEntry
	index   map[move_settings.MoveSettingsTemplateID]int
}

// NewMoveSettingsAccessor builds a MoveSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewMoveSettingsAccessor(entries []move_settings.MoveSettingsEntry) *MoveSettingsAccessor {
	idx := make(map[move_settings.MoveSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[move_settings.MoveSettingsTemplateID(e.TemplateID)] = i
	}
	return &MoveSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *MoveSettingsAccessor) Get(id move_settings.MoveSettingsTemplateID) (move_settings.MoveSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero move_settings.MoveSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *MoveSettingsAccessor) Has(id move_settings.MoveSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *MoveSettingsAccessor) All() []move_settings.MoveSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *MoveSettingsAccessor) TemplateIDs() []move_settings.MoveSettingsTemplateID {
	ids := make([]move_settings.MoveSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, move_settings.MoveSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *MoveSettingsAccessor) Len() int {
	return len(a.entries)
}
