// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/move_sequence_settings"
)

// MoveSequenceSettingsAccessor provides typed lookups for the "moveSequenceSettings" group.
type MoveSequenceSettingsAccessor struct {
	entries []move_sequence_settings.MoveSequenceSettingsEntry
	index   map[move_sequence_settings.MoveSequenceSettingsTemplateID]int
}

// NewMoveSequenceSettingsAccessor builds a MoveSequenceSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewMoveSequenceSettingsAccessor(entries []move_sequence_settings.MoveSequenceSettingsEntry) *MoveSequenceSettingsAccessor {
	idx := make(map[move_sequence_settings.MoveSequenceSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[move_sequence_settings.MoveSequenceSettingsTemplateID(e.TemplateID)] = i
	}
	return &MoveSequenceSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *MoveSequenceSettingsAccessor) Get(id move_sequence_settings.MoveSequenceSettingsTemplateID) (move_sequence_settings.MoveSequenceSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero move_sequence_settings.MoveSequenceSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *MoveSequenceSettingsAccessor) Has(id move_sequence_settings.MoveSequenceSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *MoveSequenceSettingsAccessor) All() []move_sequence_settings.MoveSequenceSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *MoveSequenceSettingsAccessor) TemplateIDs() []move_sequence_settings.MoveSequenceSettingsTemplateID {
	ids := make([]move_sequence_settings.MoveSequenceSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, move_sequence_settings.MoveSequenceSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *MoveSequenceSettingsAccessor) Len() int {
	return len(a.entries)
}
