// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/non_combat_move_settings"
)

// NonCombatMoveSettingsAccessor provides typed lookups for the "nonCombatMoveSettings" group.
type NonCombatMoveSettingsAccessor struct {
	entries []non_combat_move_settings.NonCombatMoveSettingsEntry
	index   map[non_combat_move_settings.NonCombatMoveSettingsTemplateID]int
}

// NewNonCombatMoveSettingsAccessor builds a NonCombatMoveSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewNonCombatMoveSettingsAccessor(entries []non_combat_move_settings.NonCombatMoveSettingsEntry) *NonCombatMoveSettingsAccessor {
	idx := make(map[non_combat_move_settings.NonCombatMoveSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[non_combat_move_settings.NonCombatMoveSettingsTemplateID(e.TemplateID)] = i
	}
	return &NonCombatMoveSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *NonCombatMoveSettingsAccessor) Get(id non_combat_move_settings.NonCombatMoveSettingsTemplateID) (non_combat_move_settings.NonCombatMoveSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero non_combat_move_settings.NonCombatMoveSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *NonCombatMoveSettingsAccessor) Has(id non_combat_move_settings.NonCombatMoveSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *NonCombatMoveSettingsAccessor) All() []non_combat_move_settings.NonCombatMoveSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *NonCombatMoveSettingsAccessor) TemplateIDs() []non_combat_move_settings.NonCombatMoveSettingsTemplateID {
	ids := make([]non_combat_move_settings.NonCombatMoveSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, non_combat_move_settings.NonCombatMoveSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *NonCombatMoveSettingsAccessor) Len() int {
	return len(a.entries)
}
