// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/party_play_general_settings"
)

// PartyPlayGeneralSettingsAccessor provides typed lookups for the "partyPlayGeneralSettings" group.
type PartyPlayGeneralSettingsAccessor struct {
	entries []party_play_general_settings.PartyPlayGeneralSettingsEntry
	index   map[party_play_general_settings.PartyPlayGeneralSettingsTemplateID]int
}

// NewPartyPlayGeneralSettingsAccessor builds a PartyPlayGeneralSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPartyPlayGeneralSettingsAccessor(entries []party_play_general_settings.PartyPlayGeneralSettingsEntry) *PartyPlayGeneralSettingsAccessor {
	idx := make(map[party_play_general_settings.PartyPlayGeneralSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[party_play_general_settings.PartyPlayGeneralSettingsTemplateID(e.TemplateID)] = i
	}
	return &PartyPlayGeneralSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PartyPlayGeneralSettingsAccessor) Get(id party_play_general_settings.PartyPlayGeneralSettingsTemplateID) (party_play_general_settings.PartyPlayGeneralSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero party_play_general_settings.PartyPlayGeneralSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PartyPlayGeneralSettingsAccessor) Has(id party_play_general_settings.PartyPlayGeneralSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PartyPlayGeneralSettingsAccessor) All() []party_play_general_settings.PartyPlayGeneralSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PartyPlayGeneralSettingsAccessor) TemplateIDs() []party_play_general_settings.PartyPlayGeneralSettingsTemplateID {
	ids := make([]party_play_general_settings.PartyPlayGeneralSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, party_play_general_settings.PartyPlayGeneralSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PartyPlayGeneralSettingsAccessor) Len() int {
	return len(a.entries)
}
