// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/photo_sets_settings_proto"
)

// PhotoSetsSettingsProtoAccessor provides typed lookups for the "photoSetsSettingsProto" group.
type PhotoSetsSettingsProtoAccessor struct {
	entries []photo_sets_settings_proto.PhotoSetsSettingsProtoEntry
	index   map[photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID]int
}

// NewPhotoSetsSettingsProtoAccessor builds a PhotoSetsSettingsProtoAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPhotoSetsSettingsProtoAccessor(entries []photo_sets_settings_proto.PhotoSetsSettingsProtoEntry) *PhotoSetsSettingsProtoAccessor {
	idx := make(map[photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID]int, len(entries))
	for i, e := range entries {
		idx[photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID(e.TemplateID)] = i
	}
	return &PhotoSetsSettingsProtoAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PhotoSetsSettingsProtoAccessor) Get(id photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID) (photo_sets_settings_proto.PhotoSetsSettingsProtoEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero photo_sets_settings_proto.PhotoSetsSettingsProtoEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PhotoSetsSettingsProtoAccessor) Has(id photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PhotoSetsSettingsProtoAccessor) All() []photo_sets_settings_proto.PhotoSetsSettingsProtoEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PhotoSetsSettingsProtoAccessor) TemplateIDs() []photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID {
	ids := make([]photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, photo_sets_settings_proto.PhotoSetsSettingsProtoTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PhotoSetsSettingsProtoAccessor) Len() int {
	return len(a.entries)
}
