// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/pokemon_settings"
)

// PokemonSettingsAccessor provides typed lookups for the "pokemonSettings" group.
type PokemonSettingsAccessor struct {
	entries []pokemon_settings.PokemonSettingsEntry
	index   map[pokemon_settings.PokemonSettingsTemplateID]int
}

// NewPokemonSettingsAccessor builds a PokemonSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokemonSettingsAccessor(entries []pokemon_settings.PokemonSettingsEntry) *PokemonSettingsAccessor {
	idx := make(map[pokemon_settings.PokemonSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokemon_settings.PokemonSettingsTemplateID(e.TemplateID)] = i
	}
	return &PokemonSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokemonSettingsAccessor) Get(id pokemon_settings.PokemonSettingsTemplateID) (pokemon_settings.PokemonSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokemon_settings.PokemonSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokemonSettingsAccessor) Has(id pokemon_settings.PokemonSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokemonSettingsAccessor) All() []pokemon_settings.PokemonSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokemonSettingsAccessor) TemplateIDs() []pokemon_settings.PokemonSettingsTemplateID {
	ids := make([]pokemon_settings.PokemonSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokemon_settings.PokemonSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokemonSettingsAccessor) Len() int {
	return len(a.entries)
}
