// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/pokemon_upgrades"
)

// PokemonUpgradesAccessor provides typed lookups for the "pokemonUpgrades" group.
type PokemonUpgradesAccessor struct {
	entries []pokemon_upgrades.PokemonUpgradesEntry
	index   map[pokemon_upgrades.PokemonUpgradesTemplateID]int
}

// NewPokemonUpgradesAccessor builds a PokemonUpgradesAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokemonUpgradesAccessor(entries []pokemon_upgrades.PokemonUpgradesEntry) *PokemonUpgradesAccessor {
	idx := make(map[pokemon_upgrades.PokemonUpgradesTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokemon_upgrades.PokemonUpgradesTemplateID(e.TemplateID)] = i
	}
	return &PokemonUpgradesAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokemonUpgradesAccessor) Get(id pokemon_upgrades.PokemonUpgradesTemplateID) (pokemon_upgrades.PokemonUpgradesEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokemon_upgrades.PokemonUpgradesEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokemonUpgradesAccessor) Has(id pokemon_upgrades.PokemonUpgradesTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokemonUpgradesAccessor) All() []pokemon_upgrades.PokemonUpgradesEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokemonUpgradesAccessor) TemplateIDs() []pokemon_upgrades.PokemonUpgradesTemplateID {
	ids := make([]pokemon_upgrades.PokemonUpgradesTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokemon_upgrades.PokemonUpgradesTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokemonUpgradesAccessor) Len() int {
	return len(a.entries)
}
