// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/pokestop_invasion_availability_settings"
)

// PokestopInvasionAvailabilitySettingsAccessor provides typed lookups for the "pokestopInvasionAvailabilitySettings" group.
type PokestopInvasionAvailabilitySettingsAccessor struct {
	entries []pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsEntry
	index   map[pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID]int
}

// NewPokestopInvasionAvailabilitySettingsAccessor builds a PokestopInvasionAvailabilitySettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokestopInvasionAvailabilitySettingsAccessor(entries []pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsEntry) *PokestopInvasionAvailabilitySettingsAccessor {
	idx := make(map[pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID(e.TemplateID)] = i
	}
	return &PokestopInvasionAvailabilitySettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokestopInvasionAvailabilitySettingsAccessor) Get(id pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID) (pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokestopInvasionAvailabilitySettingsAccessor) Has(id pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokestopInvasionAvailabilitySettingsAccessor) All() []pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokestopInvasionAvailabilitySettingsAccessor) TemplateIDs() []pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID {
	ids := make([]pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokestop_invasion_availability_settings.PokestopInvasionAvailabilitySettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokestopInvasionAvailabilitySettingsAccessor) Len() int {
	return len(a.entries)
}
