// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_home_form_reversions"
)

// PokemonHomeFormReversionsAccessor provides typed lookups for the "pokemonHomeFormReversions" group.
type PokemonHomeFormReversionsAccessor struct {
	entries []pokemon_home_form_reversions.PokemonHomeFormReversionsEntry
	index   map[pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID]int
}

// NewPokemonHomeFormReversionsAccessor builds a PokemonHomeFormReversionsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokemonHomeFormReversionsAccessor(entries []pokemon_home_form_reversions.PokemonHomeFormReversionsEntry) *PokemonHomeFormReversionsAccessor {
	idx := make(map[pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID(e.TemplateID)] = i
	}
	return &PokemonHomeFormReversionsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokemonHomeFormReversionsAccessor) Get(id pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID) (pokemon_home_form_reversions.PokemonHomeFormReversionsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokemon_home_form_reversions.PokemonHomeFormReversionsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokemonHomeFormReversionsAccessor) Has(id pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokemonHomeFormReversionsAccessor) All() []pokemon_home_form_reversions.PokemonHomeFormReversionsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokemonHomeFormReversionsAccessor) TemplateIDs() []pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID {
	ids := make([]pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokemon_home_form_reversions.PokemonHomeFormReversionsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokemonHomeFormReversionsAccessor) Len() int {
	return len(a.entries)
}
