// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/pokemon_home_energy_costs"
)

// PokemonHomeEnergyCostsAccessor provides typed lookups for the "pokemonHomeEnergyCosts" group.
type PokemonHomeEnergyCostsAccessor struct {
	entries []pokemon_home_energy_costs.PokemonHomeEnergyCostsEntry
	index   map[pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID]int
}

// NewPokemonHomeEnergyCostsAccessor builds a PokemonHomeEnergyCostsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokemonHomeEnergyCostsAccessor(entries []pokemon_home_energy_costs.PokemonHomeEnergyCostsEntry) *PokemonHomeEnergyCostsAccessor {
	idx := make(map[pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID(e.TemplateID)] = i
	}
	return &PokemonHomeEnergyCostsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokemonHomeEnergyCostsAccessor) Get(id pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID) (pokemon_home_energy_costs.PokemonHomeEnergyCostsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokemon_home_energy_costs.PokemonHomeEnergyCostsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokemonHomeEnergyCostsAccessor) Has(id pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokemonHomeEnergyCostsAccessor) All() []pokemon_home_energy_costs.PokemonHomeEnergyCostsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokemonHomeEnergyCostsAccessor) TemplateIDs() []pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID {
	ids := make([]pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokemon_home_energy_costs.PokemonHomeEnergyCostsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokemonHomeEnergyCostsAccessor) Len() int {
	return len(a.entries)
}
