// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_extended_settings"
)

// PokemonExtendedSettingsAccessor provides typed lookups for the "pokemonExtendedSettings" group.
type PokemonExtendedSettingsAccessor struct {
	entries []pokemon_extended_settings.PokemonExtendedSettingsEntry
	index   map[pokemon_extended_settings.PokemonExtendedSettingsTemplateID]int
}

// NewPokemonExtendedSettingsAccessor builds a PokemonExtendedSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokemonExtendedSettingsAccessor(entries []pokemon_extended_settings.PokemonExtendedSettingsEntry) *PokemonExtendedSettingsAccessor {
	idx := make(map[pokemon_extended_settings.PokemonExtendedSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokemon_extended_settings.PokemonExtendedSettingsTemplateID(e.TemplateID)] = i
	}
	return &PokemonExtendedSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokemonExtendedSettingsAccessor) Get(id pokemon_extended_settings.PokemonExtendedSettingsTemplateID) (pokemon_extended_settings.PokemonExtendedSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokemon_extended_settings.PokemonExtendedSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokemonExtendedSettingsAccessor) Has(id pokemon_extended_settings.PokemonExtendedSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokemonExtendedSettingsAccessor) All() []pokemon_extended_settings.PokemonExtendedSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokemonExtendedSettingsAccessor) TemplateIDs() []pokemon_extended_settings.PokemonExtendedSettingsTemplateID {
	ids := make([]pokemon_extended_settings.PokemonExtendedSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokemon_extended_settings.PokemonExtendedSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokemonExtendedSettingsAccessor) Len() int {
	return len(a.entries)
}
