// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/pokemon_family"
)

// PokemonFamilyAccessor provides typed lookups for the "pokemonFamily" group.
type PokemonFamilyAccessor struct {
	entries []pokemon_family.PokemonFamilyEntry
	index   map[pokemon_family.PokemonFamilyTemplateID]int
}

// NewPokemonFamilyAccessor builds a PokemonFamilyAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokemonFamilyAccessor(entries []pokemon_family.PokemonFamilyEntry) *PokemonFamilyAccessor {
	idx := make(map[pokemon_family.PokemonFamilyTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokemon_family.PokemonFamilyTemplateID(e.TemplateID)] = i
	}
	return &PokemonFamilyAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokemonFamilyAccessor) Get(id pokemon_family.PokemonFamilyTemplateID) (pokemon_family.PokemonFamilyEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokemon_family.PokemonFamilyEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokemonFamilyAccessor) Has(id pokemon_family.PokemonFamilyTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokemonFamilyAccessor) All() []pokemon_family.PokemonFamilyEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokemonFamilyAccessor) TemplateIDs() []pokemon_family.PokemonFamilyTemplateID {
	ids := make([]pokemon_family.PokemonFamilyTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokemon_family.PokemonFamilyTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokemonFamilyAccessor) Len() int {
	return len(a.entries)
}
