// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/pokemon_scale_settings"
)

// PokemonScaleSettingsAccessor provides typed lookups for the "pokemonScaleSettings" group.
type PokemonScaleSettingsAccessor struct {
	entries []pokemon_scale_settings.PokemonScaleSettingsEntry
	index   map[pokemon_scale_settings.PokemonScaleSettingsTemplateID]int
}

// NewPokemonScaleSettingsAccessor builds a PokemonScaleSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewPokemonScaleSettingsAccessor(entries []pokemon_scale_settings.PokemonScaleSettingsEntry) *PokemonScaleSettingsAccessor {
	idx := make(map[pokemon_scale_settings.PokemonScaleSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[pokemon_scale_settings.PokemonScaleSettingsTemplateID(e.TemplateID)] = i
	}
	return &PokemonScaleSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *PokemonScaleSettingsAccessor) Get(id pokemon_scale_settings.PokemonScaleSettingsTemplateID) (pokemon_scale_settings.PokemonScaleSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero pokemon_scale_settings.PokemonScaleSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *PokemonScaleSettingsAccessor) Has(id pokemon_scale_settings.PokemonScaleSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *PokemonScaleSettingsAccessor) All() []pokemon_scale_settings.PokemonScaleSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *PokemonScaleSettingsAccessor) TemplateIDs() []pokemon_scale_settings.PokemonScaleSettingsTemplateID {
	ids := make([]pokemon_scale_settings.PokemonScaleSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, pokemon_scale_settings.PokemonScaleSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *PokemonScaleSettingsAccessor) Len() int {
	return len(a.entries)
}
