// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/quest_settings"
)

// QuestSettingsAccessor provides typed lookups for the "questSettings" group.
type QuestSettingsAccessor struct {
	entries []quest_settings.QuestSettingsEntry
	index   map[quest_settings.QuestSettingsTemplateID]int
}

// NewQuestSettingsAccessor builds a QuestSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewQuestSettingsAccessor(entries []quest_settings.QuestSettingsEntry) *QuestSettingsAccessor {
	idx := make(map[quest_settings.QuestSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[quest_settings.QuestSettingsTemplateID(e.TemplateID)] = i
	}
	return &QuestSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *QuestSettingsAccessor) Get(id quest_settings.QuestSettingsTemplateID) (quest_settings.QuestSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero quest_settings.QuestSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *QuestSettingsAccessor) Has(id quest_settings.QuestSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *QuestSettingsAccessor) All() []quest_settings.QuestSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *QuestSettingsAccessor) TemplateIDs() []quest_settings.QuestSettingsTemplateID {
	ids := make([]quest_settings.QuestSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, quest_settings.QuestSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *QuestSettingsAccessor) Len() int {
	return len(a.entries)
}
