// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/quick_invite_settings"
)

// QuickInviteSettingsAccessor provides typed lookups for the "quickInviteSettings" group.
type QuickInviteSettingsAccessor struct {
	entries []quick_invite_settings.QuickInviteSettingsEntry
	index   map[quick_invite_settings.QuickInviteSettingsTemplateID]int
}

// NewQuickInviteSettingsAccessor builds a QuickInviteSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewQuickInviteSettingsAccessor(entries []quick_invite_settings.QuickInviteSettingsEntry) *QuickInviteSettingsAccessor {
	idx := make(map[quick_invite_settings.QuickInviteSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[quick_invite_settings.QuickInviteSettingsTemplateID(e.TemplateID)] = i
	}
	return &QuickInviteSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *QuickInviteSettingsAccessor) Get(id quick_invite_settings.QuickInviteSettingsTemplateID) (quick_invite_settings.QuickInviteSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero quick_invite_settings.QuickInviteSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *QuickInviteSettingsAccessor) Has(id quick_invite_settings.QuickInviteSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *QuickInviteSettingsAccessor) All() []quick_invite_settings.QuickInviteSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *QuickInviteSettingsAccessor) TemplateIDs() []quick_invite_settings.QuickInviteSettingsTemplateID {
	ids := make([]quick_invite_settings.QuickInviteSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, quick_invite_settings.QuickInviteSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *QuickInviteSettingsAccessor) Len() int {
	return len(a.entries)
}
