// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/recommended_search_settings"
)

// RecommendedSearchSettingsAccessor provides typed lookups for the "recommendedSearchSettings" group.
type RecommendedSearchSettingsAccessor struct {
	entries []recommended_search_settings.RecommendedSearchSettingsEntry
	index   map[recommended_search_settings.RecommendedSearchSettingsTemplateID]int
}

// NewRecommendedSearchSettingsAccessor builds a RecommendedSearchSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewRecommendedSearchSettingsAccessor(entries []recommended_search_settings.RecommendedSearchSettingsEntry) *RecommendedSearchSettingsAccessor {
	idx := make(map[recommended_search_settings.RecommendedSearchSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[recommended_search_settings.RecommendedSearchSettingsTemplateID(e.TemplateID)] = i
	}
	return &RecommendedSearchSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *RecommendedSearchSettingsAccessor) Get(id recommended_search_settings.RecommendedSearchSettingsTemplateID) (recommended_search_settings.RecommendedSearchSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero recommended_search_settings.RecommendedSearchSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *RecommendedSearchSettingsAccessor) Has(id recommended_search_settings.RecommendedSearchSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *RecommendedSearchSettingsAccessor) All() []recommended_search_settings.RecommendedSearchSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *RecommendedSearchSettingsAccessor) TemplateIDs() []recommended_search_settings.RecommendedSearchSettingsTemplateID {
	ids := make([]recommended_search_settings.RecommendedSearchSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, recommended_search_settings.RecommendedSearchSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *RecommendedSearchSettingsAccessor) Len() int {
	return len(a.entries)
}
