// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/PLACEHOLDER/pogo-masterfile-types/packages/go/roll_back"
)

// RollBackAccessor provides typed lookups for the "rollBack" group.
type RollBackAccessor struct {
	entries []roll_back.RollBackEntry
	index   map[roll_back.RollBackTemplateID]int
}

// NewRollBackAccessor builds a RollBackAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewRollBackAccessor(entries []roll_back.RollBackEntry) *RollBackAccessor {
	idx := make(map[roll_back.RollBackTemplateID]int, len(entries))
	for i, e := range entries {
		idx[roll_back.RollBackTemplateID(e.TemplateID)] = i
	}
	return &RollBackAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *RollBackAccessor) Get(id roll_back.RollBackTemplateID) (roll_back.RollBackEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero roll_back.RollBackEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *RollBackAccessor) Has(id roll_back.RollBackTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *RollBackAccessor) All() []roll_back.RollBackEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *RollBackAccessor) TemplateIDs() []roll_back.RollBackTemplateID {
	ids := make([]roll_back.RollBackTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, roll_back.RollBackTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *RollBackAccessor) Len() int {
	return len(a.entries)
}
