// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/settings_override_rule"
)

// SettingsOverrideRuleAccessor provides typed lookups for the "settingsOverrideRule" group.
type SettingsOverrideRuleAccessor struct {
	entries []settings_override_rule.SettingsOverrideRuleEntry
	index   map[settings_override_rule.SettingsOverrideRuleTemplateID]int
}

// NewSettingsOverrideRuleAccessor builds a SettingsOverrideRuleAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewSettingsOverrideRuleAccessor(entries []settings_override_rule.SettingsOverrideRuleEntry) *SettingsOverrideRuleAccessor {
	idx := make(map[settings_override_rule.SettingsOverrideRuleTemplateID]int, len(entries))
	for i, e := range entries {
		idx[settings_override_rule.SettingsOverrideRuleTemplateID(e.TemplateID)] = i
	}
	return &SettingsOverrideRuleAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *SettingsOverrideRuleAccessor) Get(id settings_override_rule.SettingsOverrideRuleTemplateID) (settings_override_rule.SettingsOverrideRuleEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero settings_override_rule.SettingsOverrideRuleEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *SettingsOverrideRuleAccessor) Has(id settings_override_rule.SettingsOverrideRuleTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *SettingsOverrideRuleAccessor) All() []settings_override_rule.SettingsOverrideRuleEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *SettingsOverrideRuleAccessor) TemplateIDs() []settings_override_rule.SettingsOverrideRuleTemplateID {
	ids := make([]settings_override_rule.SettingsOverrideRuleTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, settings_override_rule.SettingsOverrideRuleTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *SettingsOverrideRuleAccessor) Len() int {
	return len(a.entries)
}
