// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/sticker_metadata"
)

// StickerMetadataAccessor provides typed lookups for the "stickerMetadata" group.
type StickerMetadataAccessor struct {
	entries []sticker_metadata.StickerMetadataEntry
	index   map[sticker_metadata.StickerMetadataTemplateID]int
}

// NewStickerMetadataAccessor builds a StickerMetadataAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewStickerMetadataAccessor(entries []sticker_metadata.StickerMetadataEntry) *StickerMetadataAccessor {
	idx := make(map[sticker_metadata.StickerMetadataTemplateID]int, len(entries))
	for i, e := range entries {
		idx[sticker_metadata.StickerMetadataTemplateID(e.TemplateID)] = i
	}
	return &StickerMetadataAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *StickerMetadataAccessor) Get(id sticker_metadata.StickerMetadataTemplateID) (sticker_metadata.StickerMetadataEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero sticker_metadata.StickerMetadataEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *StickerMetadataAccessor) Has(id sticker_metadata.StickerMetadataTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *StickerMetadataAccessor) All() []sticker_metadata.StickerMetadataEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *StickerMetadataAccessor) TemplateIDs() []sticker_metadata.StickerMetadataTemplateID {
	ids := make([]sticker_metadata.StickerMetadataTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, sticker_metadata.StickerMetadataTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *StickerMetadataAccessor) Len() int {
	return len(a.entries)
}
