// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/tappable_settings"
)

// TappableSettingsAccessor provides typed lookups for the "tappableSettings" group.
type TappableSettingsAccessor struct {
	entries []tappable_settings.TappableSettingsEntry
	index   map[tappable_settings.TappableSettingsTemplateID]int
}

// NewTappableSettingsAccessor builds a TappableSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewTappableSettingsAccessor(entries []tappable_settings.TappableSettingsEntry) *TappableSettingsAccessor {
	idx := make(map[tappable_settings.TappableSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[tappable_settings.TappableSettingsTemplateID(e.TemplateID)] = i
	}
	return &TappableSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *TappableSettingsAccessor) Get(id tappable_settings.TappableSettingsTemplateID) (tappable_settings.TappableSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero tappable_settings.TappableSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *TappableSettingsAccessor) Has(id tappable_settings.TappableSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *TappableSettingsAccessor) All() []tappable_settings.TappableSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *TappableSettingsAccessor) TemplateIDs() []tappable_settings.TappableSettingsTemplateID {
	ids := make([]tappable_settings.TappableSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, tappable_settings.TappableSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *TappableSettingsAccessor) Len() int {
	return len(a.entries)
}
