// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/temporary_evolution_settings"
)

// TemporaryEvolutionSettingsAccessor provides typed lookups for the "temporaryEvolutionSettings" group.
type TemporaryEvolutionSettingsAccessor struct {
	entries []temporary_evolution_settings.TemporaryEvolutionSettingsEntry
	index   map[temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID]int
}

// NewTemporaryEvolutionSettingsAccessor builds a TemporaryEvolutionSettingsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewTemporaryEvolutionSettingsAccessor(entries []temporary_evolution_settings.TemporaryEvolutionSettingsEntry) *TemporaryEvolutionSettingsAccessor {
	idx := make(map[temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID(e.TemplateID)] = i
	}
	return &TemporaryEvolutionSettingsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *TemporaryEvolutionSettingsAccessor) Get(id temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID) (temporary_evolution_settings.TemporaryEvolutionSettingsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero temporary_evolution_settings.TemporaryEvolutionSettingsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *TemporaryEvolutionSettingsAccessor) Has(id temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *TemporaryEvolutionSettingsAccessor) All() []temporary_evolution_settings.TemporaryEvolutionSettingsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *TemporaryEvolutionSettingsAccessor) TemplateIDs() []temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID {
	ids := make([]temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, temporary_evolution_settings.TemporaryEvolutionSettingsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *TemporaryEvolutionSettingsAccessor) Len() int {
	return len(a.entries)
}
