// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile/packages/go/type_effective"
)

// TypeEffectiveAccessor provides typed lookups for the "typeEffective" group.
type TypeEffectiveAccessor struct {
	entries []type_effective.TypeEffectiveEntry
	index   map[type_effective.TypeEffectiveTemplateID]int
}

// NewTypeEffectiveAccessor builds a TypeEffectiveAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewTypeEffectiveAccessor(entries []type_effective.TypeEffectiveEntry) *TypeEffectiveAccessor {
	idx := make(map[type_effective.TypeEffectiveTemplateID]int, len(entries))
	for i, e := range entries {
		idx[type_effective.TypeEffectiveTemplateID(e.TemplateID)] = i
	}
	return &TypeEffectiveAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *TypeEffectiveAccessor) Get(id type_effective.TypeEffectiveTemplateID) (type_effective.TypeEffectiveEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero type_effective.TypeEffectiveEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *TypeEffectiveAccessor) Has(id type_effective.TypeEffectiveTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *TypeEffectiveAccessor) All() []type_effective.TypeEffectiveEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *TypeEffectiveAccessor) TemplateIDs() []type_effective.TypeEffectiveTemplateID {
	ids := make([]type_effective.TypeEffectiveTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, type_effective.TypeEffectiveTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *TypeEffectiveAccessor) Len() int {
	return len(a.entries)
}
