// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/vs_seeker_pokemon_rewards"
)

// VsSeekerPokemonRewardsAccessor provides typed lookups for the "vsSeekerPokemonRewards" group.
type VsSeekerPokemonRewardsAccessor struct {
	entries []vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsEntry
	index   map[vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID]int
}

// NewVsSeekerPokemonRewardsAccessor builds a VsSeekerPokemonRewardsAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewVsSeekerPokemonRewardsAccessor(entries []vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsEntry) *VsSeekerPokemonRewardsAccessor {
	idx := make(map[vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID]int, len(entries))
	for i, e := range entries {
		idx[vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID(e.TemplateID)] = i
	}
	return &VsSeekerPokemonRewardsAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *VsSeekerPokemonRewardsAccessor) Get(id vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID) (vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *VsSeekerPokemonRewardsAccessor) Has(id vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *VsSeekerPokemonRewardsAccessor) All() []vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *VsSeekerPokemonRewardsAccessor) TemplateIDs() []vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID {
	ids := make([]vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, vs_seeker_pokemon_rewards.VsSeekerPokemonRewardsTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *VsSeekerPokemonRewardsAccessor) Len() int {
	return len(a.entries)
}
