// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/vs_seeker_loot"
)

// VsSeekerLootAccessor provides typed lookups for the "vsSeekerLoot" group.
type VsSeekerLootAccessor struct {
	entries []vs_seeker_loot.VsSeekerLootEntry
	index   map[vs_seeker_loot.VsSeekerLootTemplateID]int
}

// NewVsSeekerLootAccessor builds a VsSeekerLootAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewVsSeekerLootAccessor(entries []vs_seeker_loot.VsSeekerLootEntry) *VsSeekerLootAccessor {
	idx := make(map[vs_seeker_loot.VsSeekerLootTemplateID]int, len(entries))
	for i, e := range entries {
		idx[vs_seeker_loot.VsSeekerLootTemplateID(e.TemplateID)] = i
	}
	return &VsSeekerLootAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *VsSeekerLootAccessor) Get(id vs_seeker_loot.VsSeekerLootTemplateID) (vs_seeker_loot.VsSeekerLootEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero vs_seeker_loot.VsSeekerLootEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *VsSeekerLootAccessor) Has(id vs_seeker_loot.VsSeekerLootTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *VsSeekerLootAccessor) All() []vs_seeker_loot.VsSeekerLootEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *VsSeekerLootAccessor) TemplateIDs() []vs_seeker_loot.VsSeekerLootTemplateID {
	ids := make([]vs_seeker_loot.VsSeekerLootTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, vs_seeker_loot.VsSeekerLootTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *VsSeekerLootAccessor) Len() int {
	return len(a.entries)
}
