// Code generated. DO NOT EDIT — regenerated by `bun run generate`.

package accessor

import (
	"github.com/Hazels-Lab/pogo-masterfile-types/packages/go/weather_affinities"
)

// WeatherAffinitiesAccessor provides typed lookups for the "weatherAffinities" group.
type WeatherAffinitiesAccessor struct {
	entries []weather_affinities.WeatherAffinitiesEntry
	index   map[weather_affinities.WeatherAffinitiesTemplateID]int
}

// NewWeatherAffinitiesAccessor builds a WeatherAffinitiesAccessor from a typed slice. The constructor
// must be exported because the buildAccessors helper in masterfile_gen.go
// instantiates it from a different package (masterfileapi).
func NewWeatherAffinitiesAccessor(entries []weather_affinities.WeatherAffinitiesEntry) *WeatherAffinitiesAccessor {
	idx := make(map[weather_affinities.WeatherAffinitiesTemplateID]int, len(entries))
	for i, e := range entries {
		idx[weather_affinities.WeatherAffinitiesTemplateID(e.TemplateID)] = i
	}
	return &WeatherAffinitiesAccessor{entries: entries, index: idx}
}

// Get returns the entry registered under id, or zero+false if missing.
func (a *WeatherAffinitiesAccessor) Get(id weather_affinities.WeatherAffinitiesTemplateID) (weather_affinities.WeatherAffinitiesEntry, bool) {
	i, ok := a.index[id]
	if !ok {
		var zero weather_affinities.WeatherAffinitiesEntry
		return zero, false
	}
	return a.entries[i], true
}

// Has reports whether an entry exists for id.
func (a *WeatherAffinitiesAccessor) Has(id weather_affinities.WeatherAffinitiesTemplateID) bool {
	_, ok := a.index[id]
	return ok
}

// All returns the underlying slice (zero-copy view; do not mutate).
func (a *WeatherAffinitiesAccessor) All() []weather_affinities.WeatherAffinitiesEntry {
	return a.entries
}

// TemplateIDs returns every id in source order.
func (a *WeatherAffinitiesAccessor) TemplateIDs() []weather_affinities.WeatherAffinitiesTemplateID {
	ids := make([]weather_affinities.WeatherAffinitiesTemplateID, 0, len(a.entries))
	for _, e := range a.entries {
		ids = append(ids, weather_affinities.WeatherAffinitiesTemplateID(e.TemplateID))
	}
	return ids
}

// Len returns the number of entries.
func (a *WeatherAffinitiesAccessor) Len() int {
	return len(a.entries)
}
